### ISSUE TITLE
Import error on Windows

### ISSUE THREAD

**Issue by LoSealL** [tensorflow/datasets#1]
ModuleNotFoundError: No module named 'cPickle'

**Comment by piyush-kgp** [comment]
Try this from https://stackoverflow.com/questions/43550407/pip-install-pickle-not-working-no-such-file-or-directory
import _pickle as cPickle

**Comment by LoSealL** [comment]
I know, i mean this should be included in source codes

**Comment by rsepassi** [comment]
Hi, we have yet to actually release, so please follow #5 to be notified when we do. Thanks!
