### ISSUE TITLE
XL dataset generation with Apache Beam

### ISSUE THREAD

**Issue by rsepassi** [tensorflow/datasets#10]
This is a tracking bug for extra-large dataset generation using Apache Beam (i.e. for datasets that cannot feasibly be generated within a day on a single machine). Follow it to be notified of updates on this support.

**Comment by rsepassi** [comment]
Some thoughts:

`BeamBasedBuilder` or `BeamWriter` that instead of `_generate_examples` yielding `dict`s, it would return a `PCollection`.

**Comment by dbieber** [comment]
For defining the splits, `BeamBasedBuilder`'s `_split_generators` could have the same signature as `tfds.core.GeneratorBasedBuilder` (dl_manager -> list of SplitGenerators). But importantly, some Beam calculation might have to run as part of setting up the feature connectors. E.g. in lm1b `_split_generators` calls `maybe_build_from_corpus` which does a full pass through the dataset. In a very large dataset `maybe_build_from_corpus` (or other functions serving similar purposes) may require running a Beam pipeline.

**Comment by rsepassi** [comment]
cc @adarob who also needs Beam support for the Wikipedia dumps dataset (in-flight with #146).

**Comment by SoumyadeepJana** [comment]
@rsepassi I would like to contribute to this issue,where do I start?

**Comment by rsepassi** [comment]
Thanks @SoumyadeepJana! @Conchylicultor is actively working on this, so maybe let's find you another issue to contribute on. If he needs the help, he can say so here.

**Comment by Conchylicultor** [comment]
Mostly fixed. Additional features may be tracked in independent feature requests.
