### ISSUE TITLE
can't download bigearthnet using tfds.load()

### ISSUE THREAD

**Issue by MOdusa** [tensorflow/datasets#1007]
when i try to download bigearthnet dataset using  
tfds.load('bigearthnet/all',data_dir="e:\data")

result:
Downloading and preparing dataset bigearthnet (?? GiB) to e:\data\bigearthnet\all\0.0.2...
---------------------------------------------------------------------------
**ModuleNotFoundError**                       Traceback (most recent call last)
D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\lazy_imports_lib.py in _try_import(module_name)
     29   try:
---> 30     mod = importlib.import_module(module_name)
     31     return mod

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

**ModuleNotFoundError: No module named 'apache_beam'

During handling of the above exception, another exception occurred:**

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-4bdcc8312cf8> in <module>
      5 splits = tfds.Split.TRAIN.subsplit(weighted=SPLIT_WEIGHTS)
      6 (raw_train, raw_validation, raw_test), metadata = tfds.load('bigearthnet/all',data_dir="e:\data",split=list(splits),
----> 7     with_info=True, as_supervised=True)

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\registered.py in load(name, split, data_dir, batch_size, in_memory, shuffle_files, download, as_supervised, decoders, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
    298   if download:
    299     download_and_prepare_kwargs = download_and_prepare_kwargs or {}
--> 300     dbuilder.download_and_prepare(**download_and_prepare_kwargs)
    301 
    302   if as_dataset_kwargs is None:

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in download_and_prepare(self, download_dir, download_config)
    285         self._download_and_prepare(
    286             dl_manager=dl_manager,
--> 287             download_config=download_config)
    288 
    289         # NOTE: If modifying the lines below to put additional information in

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in _download_and_prepare(self, dl_manager, download_config)
   1021   def _download_and_prepare(self, dl_manager, download_config):
   1022     # Create the Beam pipeline and forward it to _prepare_split
**-> 1023     beam = lazy_imports_lib.lazy_imports.apache_beam**
   1024 
   1025     if not download_config.beam_runner and not download_config.beam_options:

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\utils\py_utils.py in __get__(self, obj, objtype)
    100 
    101   def __get__(self, obj, objtype=None):
--> 102     return self.fget.__get__(None, objtype)()
    103 
    104 

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\lazy_imports_lib.py in apache_beam(cls)
     48   @classmethod
     49   def apache_beam(cls):
---> 50     return _try_import("apache_beam")
     51 
     52   @utils.classproperty

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\lazy_imports_lib.py in _try_import(module_name)
     34                "The dataset you are trying to use may have additional "
     35                "dependencies.")
---> 36     utils.reraise(suffix=err_msg)
     37 
     38 

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\utils\py_utils.py in reraise(prefix, suffix)
    318   suffix = "\n" + suffix if suffix else ""
    319   msg = prefix + str(exc_value) + suffix
--> 320   six.reraise(exc_type, exc_type(msg), exc_traceback)
    321 
    322 

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\lazy_imports_lib.py in _try_import(module_name)
     28   """Try importing a module, with an informative error message on failure."""
     29   try:
---> 30     mod = importlib.import_module(module_name)
     31     return mod
     32   except ImportError:

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib\__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

**ModuleNotFoundError: No module named 'apache_beam'**
Tried importing %s but failed. See setup.py extras_require. The dataset you are trying to use may have additional dependencies.

​
**I  found apache-beam** 
requires:python>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*

**Environment information**
(if applicable)
* Operating System:  Windows10
* Python version: 3.6.9
* `tensorflow-datasets` version: 1.2.0
* `tensorflow` version:  1.14.0

**Comment by Conchylicultor** [comment]
We package tfds only with the minimal set of dependencies to keep the install minimal.
As the error message explain, the dataset requires additional dependencies that you need to install manually (here `pip install apache-beam`)

**Comment by MOdusa** [comment]
> We package tfds only with the minimal set of dependencies to keep the install minimal.
> As the error message explain, the dataset requires additional dependencies that you need to install manually (here `pip install apache-beam`)

thanks.But when i installed apache-beam,another problem happened.
**result:**
Downloading and preparing dataset bigearthnet (?? GiB) to e:\data\bigearthnet\all\0.0.2...
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-d8f51a233104> in <module>
      2 splits = tfds.Split.TRAIN.subsplit(weighted=SPLIT_WEIGHTS)
      3 downConfig = tfds.download.DownloadConfig(beam_options=beam.options.pipeline_options.PipelineOptions())
----> 4 (raw_train, raw_validation, raw_test), metadata = tfds.load("bigearthnet/all",data_dir="e:\data",split=list(splits))

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\registered.py in load(name, split, data_dir, batch_size, in_memory, shuffle_files, download, as_supervised, decoders, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
    298   if download:
    299     download_and_prepare_kwargs = download_and_prepare_kwargs or {}
--> 300     dbuilder.download_and_prepare(**download_and_prepare_kwargs)
    301 
    302   if as_dataset_kwargs is None:

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     50     _check_no_positional(fn, args, ismethod, allowed=allowed)
     51     _check_required(fn, kwargs)
---> 52     return fn(*args, **kwargs)
     53 
     54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in download_and_prepare(self, download_dir, download_config)
    285         self._download_and_prepare(
    286             dl_manager=dl_manager,
--> 287             download_config=download_config)
    288 
    289         # NOTE: If modifying the lines below to put additional information in

D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in _download_and_prepare(self, dl_manager, download_config)
   1025     if not download_config.beam_runner and not download_config.beam_options:
   1026       raise ValueError(
-> 1027           "Trying to generate a dataset using Apache Beam, yet no Beam Runner "
   1028           "or PipelineOptions() has been provided. Please pass a "
   1029           "tfds.download.DownloadConfig(beam_runner=...) object to the "

**ValueError: Trying to generate a dataset using Apache Beam, yet no Beam Runner or PipelineOptions() has been provided. Please pass a tfds.download.DownloadConfig(beam_runner=...) object to the builder.download_and_prepare(download_config=...) method**

**Comment by MOdusa** [comment]
and when i set a downloadConfig,
```
SPLIT_WEIGHTS = (6, 2, 2)
splits = tfds.Split.TRAIN.subsplit(weighted=SPLIT_WEIGHTS)
downConfig=tfds.download.DownloadConfig(beam_options=beam.options.pipeline_options.PipelineOptions())
(raw_train, raw_validation, raw_test), metadata = tfds.load("bigearthnet/all",data_dir="e:\data",split=list(splits),download_and_prepare_kwargs={"download_config":downConfig})
```
i am having this issue when i run this code.
**Jupyter send a messege,**

> Kernel Restarting
> the kernel appears to have died,it will restart automatically

**Comment by leno86** [comment]
> We package tfds only with the minimal set of dependencies to keep the install minimal.
> As the error message explain, the dataset requires additional dependencies that you need to install manually (here `pip install apache-beam`)

I have installed beam and got following prompt for nearly 24 hours without any changes

Downloading and preparing dataset bigearthnet (?? GiB) to /root/tensorflow_datasets/bigearthnet/all/0.0.2...
Dl Completed...:   0%|                                                                                                                          | 0/1 [05:35<?, ? url/s]
Dl Size...:   0%|                                                                                                             | 2/66787 [05:35<3001:55:21, 161.82s/ MiB]
Extraction completed...: 0 file [05:35, ? file/s]

Is there something wrong?

**Comment by leno86** [comment]
> when i try to download bigearthnet dataset using
> tfds.load('bigearthnet/all',data_dir="e:\data")
> 
> ## result:
> Downloading and preparing dataset bigearthnet (?? GiB) to e:\data\bigearthnet\all\0.0.2...
> **ModuleNotFoundError** Traceback (most recent call last)
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\lazy_imports_lib.py in _try_import(module_name)
> 29 try:
> ---> 30 mod = importlib.import_module(module_name)
> 31 return mod
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib__init__.py in import_module(name, package)
> 125 level += 1
> --> 126 return _bootstrap._gcd_import(name[level:], package, level)
> 127
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib_bootstrap.py in _gcd_import(name, package, level)
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib_bootstrap.py in _find_and_load(name, import_)
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib_bootstrap.py in _find_and_load_unlocked(name, import_)
> 
> **ModuleNotFoundError: No module named 'apache_beam'
> 
> During handling of the above exception, another exception occurred:**
> 
> ModuleNotFoundError Traceback (most recent call last)
> in
> 5 splits = tfds.Split.TRAIN.subsplit(weighted=SPLIT_WEIGHTS)
> 6 (raw_train, raw_validation, raw_test), metadata = tfds.load('bigearthnet/all',data_dir="e:\data",split=list(splits),
> ----> 7 with_info=True, as_supervised=True)
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
> 50 _check_no_positional(fn, args, ismethod, allowed=allowed)
> 51 _check_required(fn, kwargs)
> ---> 52 return fn(*args, **kwargs)
> 53
> 54 return disallow_positional_args_dec(wrapped) # pylint: disable=no-value-for-parameter
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\registered.py in load(name, split, data_dir, batch_size, in_memory, shuffle_files, download, as_supervised, decoders, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
> 298 if download:
> 299 download_and_prepare_kwargs = download_and_prepare_kwargs or {}
> --> 300 dbuilder.download_and_prepare(**download_and_prepare_kwargs)
> 301
> 302 if as_dataset_kwargs is None:
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
> 50 _check_no_positional(fn, args, ismethod, allowed=allowed)
> 51 _check_required(fn, kwargs)
> ---> 52 return fn(*args, **kwargs)
> 53
> 54 return disallow_positional_args_dec(wrapped) # pylint: disable=no-value-for-parameter
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in download_and_prepare(self, download_dir, download_config)
> 285 self._download_and_prepare(
> 286 dl_manager=dl_manager,
> --> 287 download_config=download_config)
> 288
> 289 # NOTE: If modifying the lines below to put additional information in
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in _download_and_prepare(self, dl_manager, download_config)
> 1021 def _download_and_prepare(self, dl_manager, download_config):
> 1022 # Create the Beam pipeline and forward it to _prepare_split
> **-> 1023 beam = lazy_imports_lib.lazy_imports.apache_beam**
> 1024
> 1025 if not download_config.beam_runner and not download_config.beam_options:
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\utils\py_utils.py in **get**(self, obj, objtype)
> 100
> 101 def **get**(self, obj, objtype=None):
> --> 102 return self.fget.**get**(None, objtype)()
> 103
> 104
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\lazy_imports_lib.py in apache_beam(cls)
> 48 @classmethod
> 49 def apache_beam(cls):
> ---> 50 return _try_import("apache_beam")
> 51
> 52 @utils.classproperty
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\lazy_imports_lib.py in _try_import(module_name)
> 34 "The dataset you are trying to use may have additional "
> 35 "dependencies.")
> ---> 36 utils.reraise(suffix=err_msg)
> 37
> 38
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\utils\py_utils.py in reraise(prefix, suffix)
> 318 suffix = "\n" + suffix if suffix else ""
> 319 msg = prefix + str(exc_value) + suffix
> --> 320 six.reraise(exc_type, exc_type(msg), exc_traceback)
> 321
> 322
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\six.py in reraise(tp, value, tb)
> 690 value = tp()
> 691 if value.**traceback** is not tb:
> --> 692 raise value.with_traceback(tb)
> 693 raise value
> 694 finally:
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\lazy_imports_lib.py in _try_import(module_name)
> 28 """Try importing a module, with an informative error message on failure."""
> 29 try:
> ---> 30 mod = importlib.import_module(module_name)
> 31 return mod
> 32 except ImportError:
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib__init__.py in import_module(name, package)
> 124 break
> 125 level += 1
> --> 126 return _bootstrap._gcd_import(name[level:], package, level)
> 127
> 128
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib_bootstrap.py in _gcd_import(name, package, level)
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib_bootstrap.py in _find_and_load(name, import_)
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\importlib_bootstrap.py in _find_and_load_unlocked(name, import_)
> 
> **ModuleNotFoundError: No module named 'apache_beam'**
> Tried importing %s but failed. See setup.py extras_require. The dataset you are trying to use may have additional dependencies.
> 
> ​
> **I found apache-beam**
> requires:python>=2.7,!=3.0._,!=3.1._,!=3.2._,!=3.3._,!=3.4.*
> 
> **Environment information**
> (if applicable)
> 
> * Operating System:  Windows10
> * Python version: 3.6.9
> * `tensorflow-datasets` version: 1.2.0
> * `tensorflow` version:  1.14.0

BTW, Could you share how the problem was solved?

**Comment by Conchylicultor** [comment]
It seems you are running within an Anaconda environment, so make sure that apache_beam is installed within this environment.

**Comment by leno86** [comment]
> It seems you are running within an Anaconda environment, so make sure that apache_beam is installed within this environment.

apache_beam has been correctly installed and the dataset has been extracted. But there is another problem with beam.

Downloading and preparing dataset bigearthnet (?? GiB) to /root/tensorflow_datasets/bigearthnet/all/0.0.2...
Dl Completed...:   0%|                                                                                                                          | 0/1 [50:13<?, ? url/s]
Dl Size...: 0 MiB [50:13, ? MiB/s]
Extraction completed...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [50:13<00:00, 3013.48s/ file]

Traceback (most recent call last):
  File "download_data.py", line 7, in <module>
    (raw_train, raw_validation, raw_test), metadata = tfds.load("bigearthnet/all",split=list(splits),download_and_prepare_kwargs={'download_config':downConfig})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_datasets/core/registered.py", line 302, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 287, in download_and_prepare
    download_config=download_config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_datasets/core/dataset_builder.py", line 1031, in _download_and_prepare
    pipeline=pipeline,
  File "/usr/local/lib/python3.5/dist-packages/apache_beam/pipeline.py", line 427, in __exit__
    self.run().wait_until_finish()
  File "/usr/local/lib/python3.5/dist-packages/apache_beam/pipeline.py", line 407, in run
    self._options).run(False)
  File "/usr/local/lib/python3.5/dist-packages/apache_beam/pipeline.py", line 420, in run
    return self.runner.run_pipeline(self, self._options)
  File "/usr/local/lib/python3.5/dist-packages/apache_beam/runners/direct/direct_runner.py", line 129, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/usr/local/lib/python3.5/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 371, in run_pipeline
    default_environment=self._default_environment))
  File "/usr/local/lib/python3.5/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 378, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/usr/local/lib/python3.5/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 460, in run_stages
    stage_context.safe_coders)
  File "/usr/local/lib/python3.5/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 738, in _run_stage
    result, splits = bundle_manager.process_bundle(data_input, data_output)
  File "/usr/local/lib/python3.5/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 1709, in process_bundle
    for ix, part in enumerate(input.partition(self._num_workers)):
  File "/usr/local/lib/python3.5/dist-packages/apache_beam/runners/portability/fn_api_runner.py", line 249, in partition
    coder_impl.encode_to_stream(wkvs, output_stream_list[idx % n], True)
  File "apache_beam/coders/coder_impl.py", line 989, in apache_beam.coders.coder_impl.WindowedValueCoderImpl.encode_to_stream
  File "apache_beam/coders/coder_impl.py", line 1009, in apache_beam.coders.coder_impl.WindowedValueCoderImpl.encode_to_stream
  File "apache_beam/coders/coder_impl.py", line 635, in apache_beam.coders.coder_impl.AbstractComponentCoderImpl.encode_to_stream
  File "apache_beam/coders/coder_impl.py", line 791, in apache_beam.coders.coder_impl.SequenceCoderImpl.encode_to_stream
  File "apache_beam/coders/stream.pyx", line 47, in apache_beam.coders.stream.OutputStream.write
  File "apache_beam/coders/stream.pyx", line 109, in apache_beam.coders.stream.OutputStream.extend
AssertionError: OutputStream realloc failed.

**Comment by leno86** [comment]
This problem arised when the system memory was nearly full, in my case is about 500G. I guess the load() function will expand all the samples in datasat  into memory, so the system memory will be a bottleneck when using the fucntion. 

Is there any solution that can be used to fix this memory run-out-of problem? @Conchylicultor 
Thank you.

**Comment by gnthibault** [comment]
Currently facing the following issue:

> ValueError: The dataset you're trying to generate is using Apache Beam. Beamdatasets are usually very large and should be generated separately.Please have a look athttps://www.tensorflow.org/datasets/beam_datasets#generating_a_beam_datasetfor instructions.
