### ISSUE TITLE
using load() ,Extraction step interrupt

### ISSUE THREAD

**Issue by MOdusa** [tensorflow/datasets#1019]
**i try to download the bigearthnet datasets by load().**
```
import tensorflow as tf
import tensorflow_datasets as tfds
import apache_beam as beam
SPLIT_WEIGHTS = (6, 2, 2)
splits = tfds.Split.TRAIN.subsplit(weighted=SPLIT_WEIGHTS)
(raw_train, raw_validation, raw_test), metadata = tfds.load("bigearthnet/rgb",data_dir="e:\data",split=list(splits))
```

> Downloading and preparing dataset bigearthnet (?? GiB) to e:\data\bigearthnet\all\0.0.2...
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-3-d8f51a233104> in <module>
>       2 splits = tfds.Split.TRAIN.subsplit(weighted=SPLIT_WEIGHTS)
>       3 downConfig = tfds.download.DownloadConfig(beam_options=beam.options.pipeline_options.PipelineOptions())
> ----> 4 (raw_train, raw_validation, raw_test), metadata = tfds.load("bigearthnet/all",data_dir="e:\data",split=list(splits))
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
>      50     _check_no_positional(fn, args, ismethod, allowed=allowed)
>      51     _check_required(fn, kwargs)
> ---> 52     return fn(*args, **kwargs)
>      53 
>      54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\registered.py in load(name, split, data_dir, batch_size, in_memory, shuffle_files, download, as_supervised, decoders, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
>     298   if download:
>     299     download_and_prepare_kwargs = download_and_prepare_kwargs or {}
> --> 300     dbuilder.download_and_prepare(**download_and_prepare_kwargs)
>     301 
>     302   if as_dataset_kwargs is None:
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
>      50     _check_no_positional(fn, args, ismethod, allowed=allowed)
>      51     _check_required(fn, kwargs)
> ---> 52     return fn(*args, **kwargs)
>      53 
>      54   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in download_and_prepare(self, download_dir, download_config)
>     285         self._download_and_prepare(
>     286             dl_manager=dl_manager,
> --> 287             download_config=download_config)
>     288 
>     289         # NOTE: If modifying the lines below to put additional information in
> 
> D:\My_SoftWare\Anaconda\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in _download_and_prepare(self, dl_manager, download_config)
>    1025     if not download_config.beam_runner and not download_config.beam_options:
>    1026       raise ValueError(
> -> 1027           "Trying to generate a dataset using Apache Beam, yet no Beam Runner "
>    1028           "or PipelineOptions() has been provided. Please pass a "
>    1029           "tfds.download.DownloadConfig(beam_runner=...) object to the "
> 
> **ValueError: Trying to generate a dataset using Apache Beam, yet no Beam Runner or PipelineOptions() has been provided. Please pass a tfds.download.DownloadConfig(beam_runner=...) object to the builder.download_and_prepare(download_config=...) method** 

**What I've tried so far**
**then i set a beam-runner,**
```
downConfig = tfds.download.DownloadConfig(beam_options=beam.options.pipeline_options.PipelineOptions(),register_checksums=True)
(raw_train, raw_validation, raw_test), metadata = tfds.load("bigearthnet/rgb",data_dir="e:\data",split=list(splits),
download_and_prepare_kwargs={'download_config':downConfig})
```
**another problem happened,**
![image](https://user-images.githubusercontent.com/31296628/65401002-fc3c9480-ddf7-11e9-80e6-ecf7f81f4915.png)
**after Dl size and Dl Completed steps ,Extraction step interrupt without any error report,**
**in the download folder,only has one extraction folder. Extraction is not complete**
![image](https://user-images.githubusercontent.com/31296628/65401122-a5838a80-ddf8-11e9-9185-832ea24f6e40.png)
![image](https://user-images.githubusercontent.com/31296628/65401214-2e022b00-ddf9-11e9-89f7-68ee4b26e3ee.png)

![image](https://user-images.githubusercontent.com/31296628/65402327-327e1200-de00-11e9-8d57-6d56c59c0aa6.png)

**It would be nice if...**
is my download_config wrong? or another problem?

**Environment information**
(if applicable)
* Operating System:  Windows10
* Python version: 3.6.9
* `tensorflow-datasets` version: 1.2.0
* `tensorflow` version: 1.14.0

**Comment by diaoyingyu** [comment]
I also met this problem. Have you solved it?

**Comment by ucalyptus** [comment]
@diaoyingyu any ypdates?

**Comment by ucalyptus** [comment]
@diaoyingyu this solved all problems :
`#data, info = tfds.load("bigearthnet", with_info=True)`
`import tensorflow as tf`
`import tensorflow_datasets as tfds`
`import apache_beam as beam`
`SPLIT_WEIGHTS = (6, 2, 2)`
`splits = tfds.Split.TRAIN.subsplit(weighted=SPLIT_WEIGHTS)`
`downConfig =`
`tfds.download.DownloadConfig(beam_options=beam.options.pipeline_options.PipelineOptions(),reg```ister_checksums=True)`
`(raw_train, raw_validation, raw_test), metadata = ``tfds.load("bigearthnet/rgb",data_dir="e:\data",split=list(splits),`
`download_and_prepare_kwargs={'download_config':downConfig})`

**Comment by diaoyingyu** [comment]
> @diaoyingyu this solved all problems :
> `#data, info = tfds.load("bigearthnet", with_info=True)`
> `import tensorflow as tf`
> `import tensorflow_datasets as tfds`
> `import apache_beam as beam`
> `SPLIT_WEIGHTS = (6, 2, 2)`
> `splits = tfds.Split.TRAIN.subsplit(weighted=SPLIT_WEIGHTS)`
> `downConfig =`
> `tfds.download.DownloadConfig(beam_options=beam.options.pipeline_options.PipelineOptions(),register_checksums=True)`
> `(raw_train, raw_validation, raw_test), metadata = `
> `tfds.load("bigearthnet/rgb",data_dir="e:\data",split=list(splits),`
> `download_and_prepare_kwargs={'download_config':downConfig})`

Thanks!

**Comment by diaoyingyu** [comment]
@ucalyptus Thanks!
