### ISSUE TITLE
open_images_v5 

### ISSUE THREAD

**Issue by DeveloperRachit** [tensorflow/datasets#1042]
how could i load this data set and  how to use it to detect object. train also

**Comment by Conchylicultor** [comment]
Our catalog of dataset is available at https://www.tensorflow.org/datasets/catalog/overview

https://www.tensorflow.org/datasets/catalog/open_images_v4
Only Open image V4 is currently present, not V5.

**Comment by DeveloperRachit** [comment]
i mean how to  implement at the time of object detection.

**Comment by DeveloperRachit** [comment]
op._set_device_from_string(device_string)
AttributeError: '_TfDeviceCaptureOp' object has no attribute '_set_device_from_string'
this error i am getting now after maintaining data files structure

**Comment by cyfra** [comment]
Hey @DeveloperRachit 

The dataset request for V5 is in #906  - but it is not ready yet.

I didn't understand your most recent question about the device_from_string - this code doesn't seem to come from tensorflow_datasets library.

**Comment by Conchylicultor** [comment]
Closing this in favor of https://github.com/tensorflow/datasets/issues/906

**Comment by sonaliashish** [comment]
It would be nice, if someone tells me if any deep learning model (either in TensorFlow or PyTorch) available on Github, which is trained on OpenImages v4/v5/v6 visual relationships dataset for relation detection task or any similar task?
