### ISSUE TITLE
diabetic_retinopathy_detection (configuration: btgraham-300) uses tf.logging instead of logging from absl

### ISSUE THREAD

**Issue by mariodoebler** [tensorflow/datasets#1043]
**Short description**
The configuration btgraham-300 of the dataset diabetic_retinopathy_detection uses tf.logging (does not exist in TensorFlow 2.0) instead of logging from absl.

**Environment information**
* Operating System: Ubuntu 18.04
* Python version: 3.6.8
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets 1.2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow-gpu 2.0.0

**Reproduction instructions**

diabetic_retinopathy_detection.py -> line 277
```
tf.logging.info("Radius of image \"%s\" could not be determined.", filepath)
```

**Comment by mariodoebler** [comment]
Created pull request https://github.com/tensorflow/datasets/pull/1044

**Comment by Conchylicultor** [comment]
Thanks for fixing this. Merging now
