### ISSUE TITLE
Huggingface dataset supporting problem

### ISSUE THREAD

**Issue by Humairahmedofficial** [tensorflow/datasets#10504]
Short description
Unable to load huggingface datasets with the tfds.load() function.

Environment information

Operating System: Debian 6.1.99-1 (2024-07-15) x86_64

Python version: 3.11

tensorflow-datasets/tfds-nightly version: 4.9.7

tensorflow/tf-nightly version: 2.18.0

datasets version: 3.1.0

Does the issue still exists with the last tfds-nightly package (pip install --upgrade tfds-nightly) Yes

**Comment by chandarpalmaurya236** [comment]
Have you read this before: [https://github.com/tensorflow/datasets/issues/9014](https://github.com/tensorflow/datasets/issues/9014)
