### ISSUE TITLE
Loading diabetic_retinopathy_detection dataset throws error

### ISSUE THREAD

**Issue by sararob** [tensorflow/datasets#1051]
**Short description**
When I try to run:

```
train_data, test_data = tfds.load(
    name="diabetic_retinopathy_detection"
)
```
I get the following error:

`AssertionError: Manual directory /root/tensorflow_datasets/downloads/manual/diabetic_retinopathy_detection does not exist. Create it and download/extract dataset artifacts in there.`

Just to confirm this wasn't an environment or versioning issue I tried changing the dataset I was loading to `mnist` and it worked.

**Environment information**
* Operating System: Colab
* Python version: 3.6.8
* `tensorflow-datasets`/`tfds-nightly` version: tfds 1.2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: Tried with tf 1.14.0 and 2.0.0-rc2

**Reproduction instructions**
Run the code snippet above with both `diabetic_retinopathy_detection` and `mnist`. Loading the DR dataset should throw an error.

**Comment by Conchylicultor** [comment]
As the error message says, `diabetic_retinopathy_detection` do not supports automatic download, so you should manually download the file and put in in the requested location instead.

**Comment by sararob** [comment]
Is it possible to make the error message and / or docs clearer to explicitly say you need to download the data into a directory with that name? In the current error message it isn't clear that this specific dataset doesn't support automatic download.

On [this page](https://www.tensorflow.org/datasets/api_docs/python/tfds/load) it might be helpful to add something along the lines of "datasets that aren't in Google Cloud Storage don't support the `load` method. To use them with tfds, download them from the URL and place them in a directory in the following format (zip, raw files, etc.)..."

**Comment by Conchylicultor** [comment]
Yes, we should make a better job to document this. There is https://github.com/tensorflow/datasets/issues/936 for better surfacing this info on the doc

**Comment by vijayphoenix** [comment]
This issue can be closed
