### ISSUE TITLE
[data request] LVIS

### ISSUE THREAD

**Issue by netw0rkf10w** [tensorflow/datasets#1073]
* Name of dataset: LVIS
* URL of dataset: https://www.lvisdataset.org
* License of dataset:  Creative Commons Attribution 4.0 License
* Short description of dataset and use case(s): A new dataset for Large Vocabulary Instance Segmentation. There will be ∼2 million high-quality instance segmentation masks for over 1000 entry-level object categories in 164k images. 

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by Player0109** [comment]
I am a deep learning enthusiast, so I want to work on this dataset.
Can I do so? @netw0rkf10w

**Comment by Marvin182** [comment]
LVIS is now included in TFDS.
github.com/tensorflow/datasets/pull/2836

**Comment by Conchylicultor** [comment]
Thanks Marvin for your contribution! Closing this

**Comment by XinyueZ** [comment]
How to load this dataset, I still cannot see it in the tfds.....

**Comment by Conchylicultor** [comment]
What is the stacktrace ?

**Comment by XinyueZ** [comment]
> What is the stacktrace ?
@Conchylicultor 
DatasetNotFoundError: Dataset lvis not found. Available datasets:	- abstract_reasoning	- accentdb	- aeslc	- aflw2k3d	- ag_news_subset	- ai2_arc	- ai2_arc_with_ir	- amazon_us_reviews	- anli	- arc	- bair_robot_pushing_small	- bccd	- beans	- big_patent	- bigearthnet	- billsum	- binarized_mnist	- binary_alpha_digits	- blimp	- bool_q	- c4	- caltech101	- caltech_birds2010	- caltech_birds2011	- cars196	- cassava	- cats_vs_dogs	- celeb_a	- celeb_a_hq	- cfq	- chexpert	- cifar10	- cifar100	- cifar10_1	- cifar10_corrupted	- citrus_leaves	- cityscapes	- civil_comments	- clevr	- clic	- clinc_oos	- cmaterdb	- cnn_dailymail	- coco	- coco_captions	- coil100	- colorectal_histology	- colorectal_histology_large	- common_voice	- coqa	- cos_e	- cosmos_qa	- covid19sum	- crema_d	- curated_breast_imaging_ddsm	- cycle_gan	- deep_weeds	- definite_pronoun_resolution	- dementiabank	- diabetic_retinopathy_detection	- div2k	- dmlab	- downsampled_imagenet	- dsprites	- dtd	- duke_ultrasound	- emnist	- eraser_multi_rc	- esnli	- eurosat	- fashion_mnist	- flic	- flores	- food101	- forest_fires	- fuss	- gap	- geirhos_conflict_stimuli	- genomics_ood	- german_credit_numeric	- gigaword	- glue	- goemotions	- gpt3	- groove	- gtzan	- gtzan_music_speech	- hellaswag	- higgs	- horses_or_humans	- i_naturalist2017	- imagenet2012	- imagenet2012_corrupted	- imagenet2012_real	- imagenet2012_subset	- imagenet_a	- imagenet_r	- imagenet_resized	- imagenet_v2	- imagenette	- imagewang	- imdb_reviews	- irc_disentanglement	- iris	- kitti	- kmnist	- lfw	- librispeech	- librispeech_lm	- libritts	- ljspeech	- lm1b	- lost_and_found	- lsun	- malaria	- math_dataset	- mctaco	- mnist	- mnist_corrupted	- movie_lens	- movie_rationales	- movielens	- moving_mnist	- multi_news	- multi_nli	- multi_nli_mismatch	- natural_questions	- natural_questions_open	- newsroom	- nsynth	- nyu_depth_v2	- omniglot	- open_images_challenge2019_detection	- open_images_v4	- openbookqa	- opinion_abstracts	- opinosis	- opus	- oxford_flowers102	- oxford_iiit_pet	- para_crawl	- patch_camelyon	- paws_wiki	- paws_x_wiki	- pet_finder	- pg19	- places365_small	- plant_leaves	- plant_village	- plantae_k	- qa4mre	- qasc	- quickdraw_bitmap	- radon	- reddit	- reddit_disentanglement	- reddit_tifu	- resisc45	- robonet	- rock_paper_scissors	- rock_you	- salient_span_wikipedia	- samsum	- savee	- scan	- scene_parse150	- scicite	- scientific_papers	- sentiment140	- shapes3d	- smallnorb	- snli	- so2sat	- speech_commands	- spoken_digit	- squad	- stanford_dogs	- stanford_online_products	- starcraft_video	- stl10	- sun397	- super_glue	- svhn_cropped	- ted_hrlr_translate	- ted_multi_translate	- tedlium	- tf_flowers	- the300w_lp	- tiny_shakespeare	- titanic	- trec	- trivia_qa	- tydi_qa	- uc_merced	- ucf101	- vctk	- vgg_face2	- visual_domain_decathlon	- voc	- voxceleb	- voxforge	- waymo_open_dataset	- web_questions	- wider_face	- wiki40b	- wikihow	- wikipedia	- wikipedia_toxicity_subtypes	- wine_quality	- winogrande	- wmt14_translate	- wmt15_translate	- wmt16_translate	- wmt17_translate	- wmt18_translate	- wmt19_translate	- wmt_t2t_translate	- wmt_translate	- wordnet	- xnli	- xquad	- xsum	- yelp_polarity_reviews	- yes_noCheck that:    - if dataset was added recently, it may only be available      in `tfds-nightly`    - the dataset name is spelled correctly    - dataset class defines all base class abstract methods    - the module defining the dataset class is imported site:stackoverflow.com
