### ISSUE TITLE
Splits and slicing documentation errors

### ISSUE THREAD

**Issue by feapri** [tensorflow/datasets#1079]
**Short description** Please use keyword arguments and not positional arguments
Description of the bug.
following the documentation on this link https://github.com/tensorflow/datasets/blob/master/docs/splits.md
running this example generates the error below the code

```
# 10-fold cross-validation (see also next section on rounding behavior):
# The validation datasets are each going to be 10%:
# [0%:10%], [10%:20%], ..., [90%:100%].
# And the training datasets are each going to be the complementary 90%:
# [10%:100%] (for a corresponding validation set of [0%:10%]),
# [0%:10%] + [20%:100%] (for a validation set of [10%:20%]), ...,
# [0%:90%] (for a validation set of [90%:100%]).
vals_ds = tfds.load('mnist:3.*.*', ['train[{}%:{}%]'.format(k, k+10)
                                    for k in range(0, 100, 10)])
trains_ds = tfds.load('mnist:3.*.*', ['train[:{}%]+train[{}%:]'.format(k, k+10)
                                      for k in range(0, 100, 10)])
```

**`ValueError: Please use keyword arguments and not positional arguments. This enables more flexible API development. Thank you!
Positional arguments passed to fn load: ['name', 'split'].`**

**Environment information**
* Operating System: Google's Colab
* Python version: Python 3.6.8
* `tensorflow-datasets`/`tfds-nightly` version: tfds tfds.__version__: 1.2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tf.__version__: 2.0.0-rc2

**Reproduction instructions**
run the book (2 cells) on the link below in google's Colab
```
<put a code snippet or link to a gist here>
```

**Link to logs**
colab link to runt the book: https://drive.google.com/open?id=1Rrg9kdmDN2AzvM800rXEcvb6oRADO56u

or nbviewer link to the book:
https://nbviewer.jupyter.org/github/feapri/tensorflow_practice/blob/master/errors/tf_ValueError.ipynb

If applicable, <link to gist with logs, stack trace>

**Expected behavior**
Udate the Samples in the documentatation to align with the recomendations to avoid the 'ValueError'

**Additional context**

**Comment by Conchylicultor** [comment]
Sorry about that, you should explicitly pass split kwargs to tfds.load:

```
tfds.load('mnist:3.*.*', split=...)
```

**Comment by Conchylicultor** [comment]
Should be fixed with https://github.com/tensorflow/datasets/pull/1064
