### ISSUE TITLE
No-op `decode_example` affects iteration speed

### ISSUE THREAD

**Issue by 0x0badc0de** [tensorflow/datasets#1093]
**Short description**
Eventhough `decode_example` used for most features is no-op in sence it just returns its argument (see https://github.com/tensorflow/datasets/blob/v1.2.0/tensorflow_datasets/core/features/feature.py#L285-L301) it affects dataset iteration speed especially when dataset has sequence features. We use TFDS to make private datasets but the issue can be reproduced w/ public one as well.

**Environment information**
* Operating System: Debian GNU/Linux 10 (buster)
* Python version: 3.7.4
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets==1.2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow==1.14.0

**Reproduction instructions**

First, altered https://github.com/tensorflow/datasets/blob/v1.2.0/tensorflow_datasets/core/features/top_level_feature.py#L120 by putting following just after `sequence_rank == 1`:
```
    import os
    if os.environ.get('BYPASS') == 'yes':
      return example
```

Then tested in Jupyter notebook:
```
import os

import tensorflow as tf
import tensorflow_datasets as tfds

# tfds works in both Eager and Graph modes
tf.compat.v1.enable_eager_execution()
dataset_name = 'trivia_qa'
```

```
os.environ['BYPASS'] = 'no'
dataset = tfds.load(name=dataset_name, split=tfds.Split.TRAIN)
```
```
%timeit sum(1 for x in dataset)
```
```
os.environ['BYPASS'] = 'yes'
dataset = tfds.load(name=dataset_name, split=tfds.Split.TRAIN)
```
```
%timeit sum(1 for x in dataset)
```

**Link to logs**
Results:

Current implementation: 5min 14s ± 4.35 s per loop (mean ± std. dev. of 7 runs, 1 loop each)
Bypassing no-op sequence decoding: 4min 26s ± 2.94 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

For our dataset no-op decode bypassing gives 2x speed improvement.

**Expected behavior**
No-op operations shouldn't have noticeable effect.

**Additional context**

**Comment by Conchylicultor** [comment]
Thanks for reporting. Sending a PR which should fix those performance issues: https://github.com/tensorflow/datasets/pull/1096

**Comment by 0x0badc0de** [comment]
Thanks for picking this up. So once #1096 is merged - how exactly can we avoid no-op decoding overhead of sequences? If I got your changes right `tf.map_fn` will still be invoked. Should we override `decode_batch_example` or something like this?

**Comment by Conchylicultor** [comment]
If you're using only the official `tfds.features`, no change should be required.
* `tf.map_fn` shouldn't be invoked anymore for all features which inherit from `tfds.features.Tensor` (`Tensor`, `ClassLabel`, `BBoxes`,...).
* `tf.map_fn` will still be invoked for `tfds.features.Image` or other features which requires per-example decoding.
* If you are using your custom FeatureConnector, you may have to overwrite `decode_batch_example` for performance.

**Comment by 0x0badc0de** [comment]
Great, thanks!

**Comment by Conchylicultor** [comment]
Should be fixed now that the PR is merged. Let me know if you still encounter performances issues.
