### ISSUE TITLE
[data request] Omniglot

### ISSUE THREAD

**Issue by anandtrex** [tensorflow/datasets#11]
* Name of dataset: Omniglot
* URL of dataset: https://github.com/brendenlake/omniglot
* License of dataset: MIT
* Short description of dataset and use case(s): Image dataset for few-shot image classification and meta-learning

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by rsepassi** [comment]
[Added](https://github.com/tensorflow/datasets/blob/master/docs/datasets.md#omniglot)!

**Comment by slerman12** [comment]
Will there ever be standard training paradigms implemented as well? To the best of my knowlege, Omniglot is usually not used in its raw form, but rather I see results usually get reported for a k-way setup where a handful of classes are observed at a given time. It would be very useful to be able to use Datasets to reproduce those benchmarks. Would be much better than relying on open source reference implementations from random github users.

**Comment by rsepassi** [comment]
We have considered adding the concept of a `Task` or `ProblemStatement`, which might go along with some preprocessing on the datasets, but probably won't be adding that anytime soon. It's important we flesh out the core right now, which is to standardize base datasets, and allow users the flexibility to build any kind of pipeline they want.

You can easily get the class labels for the dataset and filter with `tf.data` [see `tf.data.Dataset.filter`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#filter)
