### ISSUE TITLE
Small Bug on Windows in Oxford_iiit_pet 

### ISSUE THREAD

**Issue by Nodice** [tensorflow/datasets#1100]
Tensorflow 2.0.0
Latest tensorflow_datasets from pip install tensorflow_datasets

Windows Anaconda environment.

Code is from Tensorflow tutorials.

import tensorflow as tf
from future import absolute_import, division, print_function, unicode_literals
from tensorflow_examples.models.pix2pix import pix2pix

import tensorflow_datasets as tfds
tfds.disable_progress_bar()

from IPython.display import clear_output
import matplotlib.pyplot as plt
dataset, info = tfds.load('oxford_iiit_pet:3.0.0', with_info=True)

Results in:

DownloadError: Failed to get url http://www.robots.ox.ac.uk/~vgg/data/pets/data\images.tar.gz. HTTP code: 404.

404 is due to the data\images.tar.gz instead of /images.tar.gz

Use of os.path.join is the cause. 

Just simply adding the base to the target will fix the issue.

dl_paths = dl_manager.download_and_extract({
        "images": tfds.download.Resource(
            url=_BASE_URL + "/images.tar.gz",
            extract_method=tfds.download.ExtractMethod.TAR),
        "annotations": tfds.download.Resource(
            url=_BASE_URL + "/annotations.tar.gz",
            extract_method=tfds.download.ExtractMethod.TAR)
    })

**Comment by Conchylicultor** [comment]
Sorry about that, sending a fix now.

**Comment by Conchylicultor** [comment]
Should be fixed with https://github.com/tensorflow/datasets/pull/1101

**Comment by Nodice** [comment]
Thanks. There were a few others in the main Tensorflow board having the same issue that no one addressed here. Good to get it resolved.

**Comment by chelvyn20** [comment]
> Tensorflow 2.0.0 Latest tensorflow_datasets from pip install tensorflow_datasets
> 
> Windows Anaconda environment.
> 
> Code is from Tensorflow tutorials.
> 
> import tensorflow as tf from future import absolute_import, division, print_function, unicode_literals from tensorflow_examples.models.pix2pix import pix2pix
> 
> import tensorflow_datasets as tfds tfds.disable_progress_bar()
> 
> from IPython.display import clear_output import matplotlib.pyplot as plt dataset, info = tfds.load('oxford_iiit_pet:3.0.0', with_info=True)
> 
> Results in:
> 
> DownloadError: Failed to get url [http://www.robots.ox.ac.uk/~vgg/data/pets/data\images.tar.gz](http://www.robots.ox.ac.uk/~vgg/data/pets/data%5Cimages.tar.gz). HTTP code: 404.
> 
> 404 is due to the data\images.tar.gz instead of /images.tar.gz
> 
> Use of os.path.join is the cause.
> 
> Just simply adding the base to the target will fix the issue.
> 
> dl_paths = dl_manager.download_and_extract({ "images": tfds.download.Resource( url=_BASE_URL + "/images.tar.gz", extract_method=tfds.download.ExtractMethod.TAR), "annotations": tfds.download.Resource( url=_BASE_URL + "/annotations.tar.gz", extract_method=tfds.download.ExtractMethod.TAR) })

nice, thx
