### ISSUE TITLE
Loading of stanford_dogs fails with ValueError(Trying to overwrite already defined ClassLabel names)

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/datasets#1124]
**Short description**
The call to `tfds.load(name='stanford_dogs',
                               with_info=True,
                               as_supervised=True,
                               shuffle_files=False)`
fails with a ValueError if the dataset does not exists in the tensorflow_datasets folder (case just after installing tensorflow_datasets

**Environment information**
* Operating System: Linux mint
* Python version: 3.7
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets 1.2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow 2.0.0

**Reproduction instructions**

```
import tensorflow_datasets as tfds
tfds.load(name='stanford_dogs',
                               with_info=True,
                               as_supervised=True,
                               shuffle_files=False)
```

**Expected behavior**
No error

**Additional context**
I traced the problem to the following:
- `DatasetBuilder.__init__` checks for `_data_dir`, which does not exist and hence `info.initialize_from_bucket()` is called which loads the labels from a file called `label.labels.txt` which was downloaded from GCS
- This file is read line-by-line and passed to the `names` property **unsorted**
- later `download_and_prepare` is called which uses the list of files to generate the **set** of labels: `label_names = set([element.split("/")[-2].lower() for element in train_mat_arr["file_list"]])`
- As this is a set, the order does not match the previously defined order read from the file and the error is thrown

Solution:
- Define the "correct" order
- Use either the label file OR the sorted set depending on which is correct

**Comment by Conchylicultor** [comment]
Thanks for reporting. https://github.com/tensorflow/datasets/pull/1126 should fix it.

**Comment by Conchylicultor** [comment]
Closing this as it has been merged. It should be available on the next release.

**Comment by byrdsmyth** [comment]
Not sure of the etiquette, but this problem appears to have resurfaced in v4.4.0. When I downgraded back to 4.2.0, was able to run without this issue surfacing.
