### ISSUE TITLE
Writing TFRecords without shuffling (i.e. in-order)

### ISSUE THREAD

**Issue by BenjinP** [tensorflow/datasets#113]
Hello. I'm now trying to create my own dataset of synthetic data. What I understand is that data is automatically converted to TFRecords in the disk. The thing is, I need the records to be written in order it is generated. However, I noticed that records are shuffled before writing them to the disk. The only place where I can set the shuffling to 'False' is inside the function 'def write_from_generator(self, generator_fn, output_files)'  from the class 'core.file_format_adapter.TFRecordExampleAdapter' .

I'm using tfds.core.GeneratorBasedBuilder as base class of my dataset.

Is there other way to do it?
Am I missing or misunderstanding something?

(I hope it's not a dumb question. I'm new with this API.)
Thanks in advance.

**Comment by rsepassi** [comment]
You're understanding correctly. Right now, we always round robin write across shards, and we shuffle.

In-order writes do seem very reasonable for naturally contiguous data.

Disabling shuffling should be easy. But we'll have to come up with how to replace round robin writing in a reasonable way given a context of multiple shards. The caller would have to specify either how many records should go into each shard (so the writer knows when to switch), or they would have to specify when to switch shards, or they could provide multiple generators (1 per shard) instead of just 1. Basically, this needs some API design work and prototype.

cc @Conchylicultor and @yovadia, what do you all think would be some reasonable ways of doing this?

**Comment by jackd** [comment]
Any progress on this? I'm looking at a similar problem where I have multiple representations corresponding to the same examples and would like to be able to create separate builders and use different subsets in `tf.data.Dataset.zip`.

**Comment by jneeven** [comment]
I also think this would be a really useful feature for video-based data.

**Comment by dwolfschlaeger** [comment]
I concord. This would be quite an enhancement for my work with image-sequences/ videos in a production metrology use case.

**Comment by lely475** [comment]
I'm also vouching for this enhancement as I am dealing with timeseries sensor data, where the correct order is crucial.

In the meantime:
Is there any workaround/ quick and dirty solution to change `tfrecords_writer.py` to disable shuffling?

**Comment by tchaye59** [comment]
The easiest way to disable shuffling with a custom data is to set `disable_shuffling=True` in the `DatasetInfo`

```
class Dataset(tfds.core.GeneratorBasedBuilder):
   
    def _split_generators(self, dl_manager):
       ...
    
    def _info(self):
        return tfds.core.DatasetInfo(
            builder=self,
            description=(""),
            disable_shuffling=True,
            features=tfds.features.FeaturesDict(...),
        )
    
    def _generate_examples(self,**args):
        ...
```

**Comment by YannisPap** [comment]
@tchaye59 No, using `disable_shuffling=True` still shuffles the dataset.

**Comment by RaphvK** [comment]
> @tchaye59 No, using `disable_shuffling=True` still shuffles the dataset.

That‘s not true, but you have to make sure that `key` in the following example is in in order of the time series:

```py
def _generate_examples(self, path) -> Iterator[Tuple[Key, Example]]:
    """Generator of examples for each split."""
    for key, img_path in enumerate(path.glob('*.jpeg')):
      yield key, {
          'image': img_path,
          'label': 'yes' if img_path.name.startswith('yes_') else 'no',
      }
```

**Comment by tchaye59** [comment]
> @tchaye59 No, using `disable_shuffling=True` still shuffles the dataset.

You're probably doing something wrong. Make sure _generate_examples is returning items in order
