### ISSUE TITLE
C4 Dataset Download Problem

### ISSUE THREAD

**Issue by impulsecorp** [tensorflow/datasets#1136]
I am trying to download the c4 cleaned dataset on my AWS Linux 16.04 server but am having some problems. The main issue is that I only want the 750GB cleaned version, but it seems to still require 6.96TiB of disk space.  So to deal with that, I set up a new AWS server with a 7.5TB drive, but when I try to do the download it says I don't have the 6.96TiB of space that is needed. Fdisk-i shows "Disk /dev/nvme1n1: 6.8 TiB, 7500000000000 bytes, 14648437500 sectors" and AWS does not offer larger than a 7.5TB drive.

I then switched to saving it on my AWS S3 bucket like:
data, info = tfds.load('c4', data_dir='s3://mybucketinfo/')
but then I get this error: 
ValueError: Trying to generate a dataset using Apache Beam, yet no Beam Runner or PipelineOptions() has been provided. Please pass a tfds.download.DownloadConfig(beam_runner=...) object to the builder.download_and_prepare(download_config=...) method

I am running Python 3.6, TF datasets 1.3, TF 2.0. I updated everything before I tried all of this.

I see a similar issue was reported at https://github.com/tensorflow/datasets/issues/1019
so I tried doing it like they did:
downConfig = tfds.download.DownloadConfig(beam_options=beam.options.pipeline_options.PipelineOptions(),register_checksums=True)
data, info = tfds.load("c4",data_dir="mybucketinfo",split=list(splits),
download_and_prepare_kwargs={'download_config':downConfig})

but then I get this error:   NameError: name 'beam' is not defined

Also, if I combine 2 hard drives on my AWS server to form a virtual drive with 15TB of space, would that still need Beam to work or is the Beam issue only related to using S3 for storage?

**Comment by Conchylicultor** [comment]
I do not have solution for the space issue.

What is the last error stacktrace ? make sure you have `pip install appache_beam`. From your code, it looks like you haven't imported `import appache_beam as beam`, so it's an undefined variable.
```
tfds.download.DownloadConfig(
    beam_options=beam.options.pipeline_options.PipelineOptions(),  # << `beam undefined`
)
```
Documentation: https://www.tensorflow.org/datasets/beam_datasets#run_your_pipeline

Note that you could just use the default download script:
```
python -m tensorflow_datasets.scripts.download_and_prepare --datasets=c4
```
which should run with the correct options.

Also note that you do not have to run with `register_checksum`. Only the dataset creator should run with this option.

**Comment by Conchylicultor** [comment]
Note that you can customize olders individually (have a look at: https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadConfig#__init__)

So generate the data in a different folder from where you download the data.

```
tfds.load(
    'c4/config_name', 
    data_dir='...', 
    download_and_prepare_kwargs={'download_config':DownloadConfig(...)}),
)
```

**Comment by adarob** [comment]
FYI, I'm working on ensuring this dataset is reproducible outside of Google's internal infrastructure. Once the data is downloaded, the real fun begins, as it requires some very large joins to do the cleaning.

I wrote some initial instructions for use on Cloud Dataflow here: https://www.tensorflow.org/datasets/beam_datasets#run_your_pipeline . However, I am finding that Beam's default shuffling is too slow for handling the size of these joins. It would take weeks to complete. I'm now trying using Dataflow's Shuffle Service and it's significantly faster (https://cloud.google.com/blog/products/gcp/introducing-cloud-dataflow-shuffle-for-up-to-5x-performance-improvement-in-data-analytic-pipelines). However, I am running in to quota issues with the shuffling service.

I'm now working on finding how much shuffle quota is needed to make this run. I'm also looking into a few modifications to the pipeline that will make the joins smaller without sacrificing too much quality.

**Comment by impulsecorp** [comment]
Thanks!  It works now (it is downloading) when I did what you suggested:
1. Add "import apache_beam as beam"
2. Remove the checksums part.

But, I still don't understand about the cleaning part. Aren't I able to download the cleaned version (750GB)?

**Comment by adarob** [comment]
Unfortunately Google cannot redistribute the Common Crawl dataset.

Our hope is that someone will reproduce the clean dataset and host it on GCS for others to access, since we cannot.

**Comment by Conchylicultor** [comment]
All data has to be downloaded (6TB), but after the data his generated, the final dataset-size should only be 750GB. As adarob said, if someone was hosting the clean data, users could directly download the pre-processed tf-record from there, and skip the entire download/processing phase.

Also just be careful to specify the config you want `c4/en`, `c4/en.noclean`, ... if you're using the `download_and_prepare` script, as otherwise it would generate all configs.

**Comment by impulsecorp** [comment]
That info is a huge help, but I am still a little confused.  Once I have the 6.96TB of data in my S3 bucket, why do I need to use Beam to clean it? I know Beam makes things faster, but it also seems to make it a lot more complicated.

Is the 6.96TB of data WET files? If so, what would I run to clean it?  The file at https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/c4.py seems to be mostly about downloading the WET files.

**Comment by adarob** [comment]
@impulsecorp were you able to create the cleaned dataset?

**Comment by impulsecorp** [comment]
No, I did not try. I was already in the process of creating my owned cleaned version when I heard about c4, so it is easier for me to just do it the way I was going to do it, and also add some of the methods you use that I had not though of.  Using Beam/Dataflow is far above my programming level.

**Comment by adarob** [comment]
Gotcha. The Beam part was especially important in globally deduplicating
repetitive and boilerplate text. Best of luck on your cleaning!

**Comment by sdliuyuzhi** [comment]
Do we have a script to run the downloading part with Dataflow? It takes forever to download even one month 6.96TB data.

**Comment by prashant-kikani** [comment]
@adarob and @Conchylicultor 
Do you guys come to know if someone had cleaned & hosted the cleaned C4 (750 GB) dataset somewhere to download?

Thank you.

**Comment by adarob** [comment]
It should do the downloading on DataFlow now. Download + clean is the only option unless someone else decides to host it.

**Comment by dirkgr** [comment]
We just released the pre-processed C4 datasets in TensorFlow and JSON format: https://github.com/allenai/allennlp/discussions/5056
