### ISSUE TITLE
APIs to read/access generated tensorflow datasets with out requiring Builder interface

### ISSUE THREAD

**Issue by ksachdeva** [tensorflow/datasets#1186]
**Is your feature request related to a problem? Please describe.**

I wrote some custom Builder classes i.e subclasses of tfds.core.GeneratorBasedBuilder to generate/build my datasets. These classes make use of various CSVs files, images etc. 

Now as long as I have access to my custom GeneratorBasedBuilder classes I have no problem as I create the instance of my builder class (do not call download_and_prepare) and get all the benefits of getting the DataSetInfo & usage of .as_dataset(split="train/test") api.

However, I would like to use the generated dataset (i.e. tfrecords & various json files tfds generates) in a setting where my  custom class that inherits from tfds.core.GeneratorBasedBuilder is not available. For e.g. I now uploaded the generated folder (i.e. tfrecords & various json files) to my google drive and would like to use google colab to do some experiments.  Since at the end we are working with an instance of tf.data.Dataset I should be able to do so.

As you can appreciate that to get access to DatasetInfo object and tf.data.Dataset it does not make sense to use a GeneratorBuilder class. Even in a regular usage (i.e. when I have access to my custom subclasses the interface is misleading as rarely you would want to download and prepare dynamically except for toy datasets)

**Describe the solution you'd like**

I would have liked that other than the GeneratorBUilder class there is another generic class let's say DatasetReader class to which you supply the path to tfds generated dataset (i.e. tfrecords and json file) and it now gives you the DatasetInfo and .as_dataset api. I believe you have the all information to do these two things because the info is stored in json files along side tfrecords.

**Describe alternatives you've considered**

At present I have to use my custom GeneratorBuilder class whenever I want to have access to tfds dataset. This means I copy paste that class in colab.

**Comment by rsepassi** [comment]
Good idea.

The first thing would probably be to think about the potential benefits and costs of moving to a design like this. Some benefits that come to mind:
* Limits the amount of code necessary at read time.
* May simplify `Features` and `DatasetBuilder`. Cleaner code base.
* Better-specified cross-language support; each language needs to implement only `DatasetReader` and the generation can always happen in Python.
* ...

A way to further investigate the costs is to sketch out a design for a system like this, paying special attention to the API, how it'd refactor the `Features` code, how it interacts with versioning, and how we might be able to maintain backwards compatibility for the current set of datasets.

One possibility for the high-level API is something like:
Separate our current `DatasetBuilder` into a `DatasetBuilder` that only generates data to disk (what `download_and_prepare` does currently), including something like a seralized `DatasetReaderConfig`, and a `DatasetReader` that consumes a `DatasetReaderConfig` and produces a `tf.data.Dataset` (what `as_dataset` does currently).

Some folks have mentioned things along these lines before and may be interested. @Conchylicultor @pierrot0

**Comment by Conchylicultor** [comment]
There benefit of being able to load any generated dataset without access to the original dataset.

Currently, not all information get saved in `dataset_info.json`. Feature can already save/resore their config through the `save/load_metadata`, but most of them don't do it. We would also need a mapping `str > FeatureConnector` to save restore the feature structure.

One drawback I can see is that if the dataset is entirely loaded from the config file, every minor updates (ex: fixing a typo in the description) would require to re-generate the entire dataset. 
We had this issue before, which leads to the decision that the code always overwrite the `json`. That may be less of an issue now that we have a more deterministic generation mechanism.
