### ISSUE TITLE
FailedPreconditionError :- when loading the summarization dataset 'aeslc'

### ISSUE THREAD

**Issue by praveenjune17** [tensorflow/datasets#1192]
**Short description**
Description of the bug.

Dataset not extracted after download

**Environment information**
Used google colab
* Operating System: linux
* Python version: 3
* `tensorflow-datasets`/`tfds-nightly` version:  1.3.0.dev201911120105
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 
tf-gpu :- 2.0.0b1

**Reproduction instructions**
examples, metadata = tfds.load('aeslc')

failed with the below error:-
FailedPreconditionError: /root/tensorflow_datasets/downloads/ryanzhumich_AESLC_archive_masterteov-4N8XPubAz1is5QKiiMwqetpvSo5qfVdtqI6QKQ.zip/AESLC-master/enron_subject_line/train; Not a directory

**Expected behavior**
no error

**Comment by cyfra** [comment]
Yes, I can reproduce this bug.

**Comment by captain-pool** [comment]
Hey @cyfra can I put this as a task for Google Code In?

**Comment by cyfra** [comment]
I debugged it a little bit - seems that github sends some strange headers when we download the zip files from it.

import requests
result = requests.get("https://github.com/ryanzhumich/AESLC/archive/master.zip")
print(result.url)
# 'https://codeload.github.com/ryanzhumich/AESLC/zip/master'
print(result.headers.get('content-disposition', None))
# attachment; filename=AESLC-master.zip

There are two issues here:
- The headers are missing the quotes (which cause our regexp expression from downloader.py to failback to detect the ending based on url).
- The url returned doesn't have the proper ending (it is missing "zip" file)

Both of these things are causing our system to not-recognize it as a zip file.

**Comment by cyfra** [comment]
Fixing in #1287
