### ISSUE TITLE
Plant village data set problem

### ISSUE THREAD

**Issue by carlosfloar** [tensorflow/datasets#1201]
I'm try to use the plant_village data set from tensorflow-datasets. first i run the builder 	plant_village.py hosted in https://github.com/tensorflow/datasets/tree/master/tensorflow_datasets/image in my colab notebook but when i execute

SPLIT_WEIGHTS = (7, 2, 1)
splits = tfds.Split.TRAIN.subsplit(weighted=SPLIT_WEIGHTS)

(raw_train, raw_validation, raw_test), metadata = tfds.load(
    'plant_village', split=list(splits),
    with_info=True, as_supervised=True) 
shows:
TypeError: __init__() got an unexpected keyword argument 'homepage'

I coment the line in the builder an execute again, and then this appear: 
NonMatchingChecksumError: Artifact https://data.mendeley.com/datasets/tywbtsjrjv/1/files/127d0761-7c63-46f0-b08e-d0d9f7cad9da/Plant_leaf_diseases_dataset_without_augmentation.zip, downloaded to /root/tensorflow_datasets/downloads/data.mend.com_data_tywb_1_file_127d-7c63-4LIjMNrfw8-ooQCHujhT2aQjTA8tWuc4domkVJgvV5bI.zip.tmp.ff9c51d26a464d96956d66840ac2798d/Plant_leaf_diseases_dataset_without_augmentation.zip, has wrong checksum.

anyone can help me?

**Environment information**
* Operating System: ubuntu 18.04 lts
* Python version: 3.6
* `tensorflow-datasets version: <bump version 1.3.0>
* `tensorflow  version: <1.15>

**Comment by Conchylicultor** [comment]
Could you re-try with `tfds-nightly` ? This dataset has been added in end of october, so may not be present in the `1.3.0` version

**Comment by carlosfloar** [comment]
thank you very much, I already downloaded it.

**Comment by AnandKishore21** [comment]
Tried with tfds-nightly but still gettning "NonMatchingChecksumError" .I have tried the following code 
 `ds = tfds.load('plant_village', split='train', shuffle_files=True)`
