### ISSUE TITLE
Use Tensorflow Dataset with other ML framework (Sklearn)

### ISSUE THREAD

**Issue by Sharathmk99** [tensorflow/datasets#1203]
**What I need help with / What I was wondering**
I wanted to use Tensorflow Dataset as one source for all the framework like sklearn. Is it possible to use this framework with Sklearn?

Any steps to host provate Tensorflow Dataset?

**What I've tried so far**
I have tried with Tensorflow, it works awesome. How can I try with Sklearn?

**Comment by Conchylicultor** [comment]
For use with other frameworks, you can convert any datasets into numpy array, using `tfds.as_numpy(ds)`.

```
ds = tfds.load('mnist', split='trainn')
for ex in tfds.as_numpy(ds):
  print(ex)
```
