### ISSUE TITLE
Wrong labels in "DeepWeeds" Dataset

### ISSUE THREAD

**Issue by hannesrichter** [tensorflow/datasets#1207]
The current implementation of the "DeepWeeds" dataset uses the wrong data as a class label.
The labels are parsed from the filename, but the original repository of the author states:
```
Images are assigned unique filenames that include the date/time the image was photographed and an ID number for the instrument which produced the image. The format is like so: YYYYMMDD-HHMMSS-ID, where the ID is simply an integer from 0 to 3. The unique filenames are strings of 17 characters, such as 20170320-093423-1.
```
link to the original repository: https://github.com/AlexOlsen/DeepWeeds

So what is expected to be the labels is an ID of the image acquisition device used when recording the images.

**Comment by Conchylicultor** [comment]
Sorry about that, please don't hesitate to send a PR to fix this.

**Comment by hannesrichter** [comment]
I made a PR and proposed a fix for this.
PR: #1209
