### ISSUE TITLE
There is only a train split in the food101 dataset.

### ISSUE THREAD

**Issue by sweaterr** [tensorflow/datasets#1215]
**Short description**

There is only a train split in the [food101 dataset](https://www.tensorflow.org/datasets/catalog/food101). In the [source data](https://www.vision.ee.ethz.ch/datasets_extra/food-101/), the dataset consists of the following configurations: 

```
  num_images = {
    'train': 75750,
    'validation': 25250,
  }
```

I think it should be fixed.
Thanks

**Comment by Conchylicultor** [comment]
Thanks for reporting.
Yes it would be nice to use the original dataset splits. Please don't hesitate to send a PR to fix this.

**Comment by captain-pool** [comment]
Hey @Conchylicultor, can I put this issue as a task for Google Code In?
