### ISSUE TITLE
NonMachtingChecksumError for Kitti dataset

### ISSUE THREAD

**Issue by jrabary** [tensorflow/datasets#1221]
The following code fails with `NonMatchingChecksumError`

Code:

```
import tensorflow_datasets as tfds
import tensorflow as tf

kitti_builder = tfds.builder('kitti', data_dir='/data')

# Download the dataset
kitti_builder.download_and_prepare()
```

Output error:

```
NonMatchingChecksumError: Artifact https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_object.zip, downloaded to /data/downloads/s3.eu-central-1_avg-kitti_devkit_objectLwMAO1uIjU-eBJEp605N-Wtd3-25ncIu5j-rD605uW0.zip.tmp.523afd5a748243559a2ccd57ba87102b/devkit_object.zip, has wrong checksum
```

**Comment by Conchylicultor** [comment]
Is the issue still here ? This might indicates that the file has been silently updated or is momentarily unavailable. If the issue persist, it means that we need to find a non-corrupted mirror of this file and update the url.
If it's the dataset which has been updated, the version should be increased with the new checksum (and should make sure the dataset still correctly generate).

**Comment by jrabary** [comment]
The workaround I found is to run the script `download_and_prepare` with `register_checksums=True` as follow 

```
python -m tensorflow_datasets.scripts.download_and_prepare --registrer_checksums=True --datasets=kitti
```

**Comment by cyfra** [comment]
This is a good workaround - but running with 'register_checksums=True' basically means that you 'ignore' the build-in checksum and simply download the file.

@jrabary - could you do us a favor and
a) verify that data is still correct and not corrupted (same number of elements etc)
b) send the pull request with the new checksum + version change?

Thanks!

**Comment by tmensink** [comment]
I get the same error and used a similar workaround.

The resulting checksum is: 
`https://s3.eu-central-1.amazonaws.com/avg-kitti/devkit_object.zip 63794 ce0b76b69c0c5f89690a0d65b7302bbbdb962a0c7e8aba6efc7050d1b04b4cf1`

**Comment by vijayphoenix** [comment]
Fixed by PR https://github.com/tensorflow/datasets/pull/1507
