### ISSUE TITLE
how to use manual_dir to load imagenet2012 dataset?

### ISSUE THREAD

**Issue by darcula1993** [tensorflow/datasets#1236]
From #1075 and #1121
Seems that we can manully download imagenet2012 dataset and use tfds to load it. Is there any clear documentation show how to do that?

I tried `tfds.load("imagenet2012",download = False, manual_dir = path/to/data )` but failed since no manual_dir for `load`

**Comment by Conchylicultor** [comment]
TFDS converts all datasets into `.tfrecord` files.
Even after manual downloading the archive files and placing them into the manual_dir, you still need to generate the tfrecord files by passing `download=True`, which will call `ImageNet2012().download_and_prepare()` which will generate the tfrecord files.
Hope this helps.

**Comment by darcula1993** [comment]
> TFDS converts all datasets into `.tfrecord` files.
> Even after manual downloading the archive files and placing them into the manual_dir, you still need to generate the tfrecord files by passing `download=True`, which will call `ImageNet2012().download_and_prepare()` which will generate the tfrecord files.
> Hope this helps.

so which function should I call to set manual_dir?
`ImageNet2012(manul_dir = path/to/data)`?

**Comment by Conchylicultor** [comment]
`manual_dir` is set in `tfds.download.DownloadConfig()`. See https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/scripts/download_and_prepare.py for an example of usage.

**Comment by darcula1993** [comment]
thank you very much!
I found I cannot set manual_dir is because the officially tfds 1.3.0 hasn't changed the code of imagenet builder. I guess pip install tfds-nightly can solve the problem.

I just hacked the code and manually insert the path which point to downloaded imagenet dataset(.tar file) and problem solved.

**Comment by sayakpaul** [comment]
@darcula1993 possible to enlist the steps that would need to be performed to successfully load `imagenet2012` now given the tars have been downloaded?
