### ISSUE TITLE
[data request] SCAN

### ISSUE THREAD

**Issue by dfurrer** [tensorflow/datasets#1246]
Name of dataset: scan
URL of dataset: https://github.com/brendenlake/SCAN
License of dataset: BSD License
Short description of dataset and use case(s): SCAN is a set of simple language-driven navigation tasks for studying compositional learning and zero-shot generalization.

Folks who would also like to see this dataset in tensorflow/datasets, please thumbs-up so the developers can know which requests to prioritize.

**Comment by dfurrer** [comment]
1. I noticed that I did not create this issue in the standard way and thus it's missing the proper label and IIUC I don't have the permissions to add it. Could someone help?

1. This is a pretty small dataset (20K examples) and the interesting thing is to look at how models perform on different train/test splits so there are many different splits of this same dataset. I'm wondering what would be the best way to implement that and make it easy to use given the datasets APIs. (https://www.tensorflow.org/datasets/add_dataset#dataset_configuration seems relevant)

**Comment by cyfra** [comment]
One option is to have custom names for the splits (tfds.core.SplitGenerator accepts string as name).

Another is to use separate datasets configs.

Reading quickly through this dataset description - it seems that separate configs might be a better choice (as normally we assume that splits don't have common objects).

**Comment by dfurrer** [comment]
Thanks Marcin. I discussed this with Etienne Pot as well and it seems to me that a config is the way to go so will look into that.

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as SCAN is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/scan.py and https://www.tensorflow.org/datasets/catalog/scan for more info.
Thank you for your contribution
