### ISSUE TITLE
[data request] <imdb>

### ISSUE THREAD

**Issue by HayekLynx** [tensorflow/datasets#1251]
* Name of dataset: <name>
* URL of dataset: <url>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by cyfra** [comment]
Hey @HayekLynx - your request is empty (you didn't provide the name or the url of the dataset).

We already have imdb_reviews - is that the one that you wanted ?

If not - please create a new request with the fields filled.
