### ISSUE TITLE
setup.py link returns error 404

### ISSUE THREAD

**Issue by WilliamHYZhang** [tensorflow/datasets#1257]
**Short description**
When clicking on the setup.py link in the guide to adding a dataset ("https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md"), returns error 404. I would like to submit a pull request to edit the guide so that the setup.py links instead to "https://github.com/tensorflow/datasets/blob/master/setup.py". Thanks so much!

**Environment information**
* Operating System: Kubuntu Linux with Firefox
* Python version: N/A
* `tensorflow-datasets`/`tfds-nightly` version: N/A
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: N/A

**Reproduction instructions**
Click the setup.py link in the guide to adding a dataset ("https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md")

**Expected behavior**
It should redirect the user to the setup.py file in the repo, "https://github.com/tensorflow/datasets/blob/master/setup.py"

**Comment by cyfra** [comment]
Thanks for the PR.
