### ISSUE TITLE
report UnicdeDecodeError when use tfds to load wmt14_translation/fr-en dataset

### ISSUE THREAD

**Issue by tracy-talent** [tensorflow/datasets#1270]
**Short description**
When I use tfds to load wmt14_translation/fr-en dataset, it meets UnicodeDecodeError.

**Environment information**
* Operating System: Ubuntu18.04
* Python version: 3.6.2
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets1.3.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tf-nightly2.0.0

**Reproduction instructions**

```
import tensorflow_datasets as tfds
import tensorflow as tf

datasets, metadata = tfds.load('wmt14_translate/fr-en', with_info=True,
                               as_supervised=True)
print(metadata)
train_examples, val_examples, test_examples = datasets['train'], datasets['validation'], datasets['test']
```

**Link to logs**
18316097 examples [45:40, 6843.25 examples/s]Traceback (most recent call last):
  File "/opt/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/util/compat.py", line 94, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Expected behavior**
If the encode of wmt14_translation/fr-en is not utf-8?

**Comment by cyfra** [comment]
Hey @tracy-talent 

Yes, we had a UTF-8 related bug there.  It should be fixed (but we didn't cut the new release since then).

Could you see if tfds-nightly works for you ?

**Comment by tracy-talent** [comment]
> Hey @tracy-talent
> 
> Yes, we had a UTF-8 related bug there. It should be fixed (but we didn't cut the new release since then).
> 
> Could you see if tfds-nightly works for you ?
Yes, tfds-nightly works well.
Thanks a lot!
