### ISSUE TITLE
Celeb A mirrors are down

### ISSUE THREAD

**Issue by nepet** [tensorflow/datasets#1271]
**Short description**
The following mirrors lead to a 404 page:
- https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pY0NSMzRuSXJEVkk 2836386 fc955bcb3ef8fbdf7d5640d9a8693a8431b5f2ee291a5c1449a1549e7e073fe7
- https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pblRyaVFSWGxPY0U 26721026 f0e5da289d5ccf75ffe8811132694922b60f2af59256ed362afa03fefba324d0
- https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pd0FJY3Blby1HUTQ 12156055 6c02a87569907f6db2ba99019085697596730e8129f67a3d61659f198c48d43b

The only other mirror
https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM 1443490838 46fb89443c578308acf364d7d379fe1b9efb793042c0af734b6112e4fd3a8c74

Leads to a page of google explaining, that the data was requested too often and can not be downloaded again.

**Reproduction instructions**

Use `wget` or call the download links from browser.

Cheers!

**Comment by Conchylicultor** [comment]
The links works for me, could you try again ?

**Comment by cyfra** [comment]
Hey,

AFAIK Google drive does have a download limit per file per day.
Unfortunately we don't have a control over that.
