### ISSUE TITLE
Fake data utility for audio files

### ISSUE THREAD

**Issue by captain-pool** [tensorflow/datasets#1277]
**Is your feature request related to a problem? Please describe.**
While writing tests for audio dataset downloader, the fake sample needs to be taken from the dataset itself since there's no fake data generator utility for audio. (Like `testing/fake_data_utils.py` is used for generating random images for fake samples)

**Describe the solution you'd like**
A couple of new functions in `fake_data_utils.py` which generates audio samples too.

**Describe alternatives you've considered**
For now samples from the dataset are being used as fake data samples.

**Are you willing to contribute?**
Yes

**Comment by cyfra** [comment]
Thanks @captain-pool  - yes, having such tooling for audio would be nice to have.

**Comment by ChanchalKumarMaji** [comment]
I think @us was working on some `fake_data` generator.

**Comment by Eshan-Agarwal** [comment]
Can I start working on this issue ?

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor please close this issue PR #1608 solves this
