### ISSUE TITLE
[data request] KDD Cup 1999 Data Set/Large structured-text dataset

### ISSUE THREAD

**Issue by gogasca** [tensorflow/datasets#128]
* Name of dataset: KDD Cup 1999 Data Data Set
Request is to have a large dataset for text based features to perform classification. Currently only Structured/Text based dataset is Titanic with only: 1,309, This dataset contains 4M records.
* URL of dataset: https://archive.ics.uci.edu/ml/datasets/KDD+Cup+1999+Data
* License of dataset: https://archive.ics.uci.edu/ml/citation_policy.html
* Short description of dataset and use case(s): This is the data set used for The Third International Knowledge Discovery and Data Mining Tools Competition, which was held in conjunction with KDD-99 The Fifth International Conference on Knowledge Discovery and Data Mining. The competition task was to build a network intrusion detector, a predictive model capable of distinguishing between ``bad'' connections, called intrusions or attacks, and ``good'' normal connections. This database contains a standard set of data to be audited, which includes a wide variety of intrusions simulated in a military network environment. 

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by Shashankjain12** [comment]
Hey @gogasca  can i work on this can you assign me this issue?

**Comment by cyfra** [comment]
@Shashankjain12 - please accept collaborator invite

**Comment by Shashankjain12** [comment]
sorry @cyfra ... but i did not got any invite!!

**Comment by cyfra** [comment]
Please check in https://github.com/tensorflow/datasets/settings/collaboration

**Comment by Shashankjain12** [comment]
@cyfra  i did not get collaborator invite for this!!

**Comment by eli-osherovich** [comment]
ping.

**Comment by eli-osherovich** [comment]
We can close this issue since the PR has been merged.
