### ISSUE TITLE
Checksums in DatasetBuilderTestCase non deterministic for str

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1285]
The example `checksum(example)` computed in https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/testing/dataset_builder_testing.py
is not deterministic for string arrays.

snippet to reproduce the issue:
```
import numpy as np
import tensorflow as tf

# STABLE = GOOD
for _ in range(5):
    obj = np.array([b"foo", b"bar"])
    print(bytes(obj))
print()

# UNSTABLE = BAD
for _ in range(5):
    obj = tf.constant([b"foo", b"bar"]).numpy()
    print(obj.tobytes())
print()
```

It seems the issue is that `tf.constant([b"foo", b"bar"]).numpy().dtype == object` while `np.array([b"foo", b"bar"]).dtype = 'S3'`.
In TF1, the issue is the same as `sess.run(tf.constant([b"foo", b"bar"])).dtype == object`

Thanks to @ageron for reporting this.

**Comment by gaurav-singh1998** [comment]
Hi, @Conchylicultor I want to take up this issue. Since this will be my first issue with TensorFlow datasets any help on how to move forward with this will be extremely helpful. Thanks.

**Comment by Conchylicultor** [comment]
Thanks for helping us. The goal of this issue is to update the `def checksum(example):` function in `dataset_builder_testing` such as it always produce the same value when the same input is provided:

```python
all_checksums = {checksum(tf.constant([b"foo", b"bar"]).numpy()) for _ in range(5)}
assert len(all_checksums) == 1
```

**Comment by gaurav-singh1998** [comment]
Hi, @Conchylicultor I would definitely like to help but since I am new to this repository it might take some time for me to solve it. Is it okay?

**Comment by Conchylicultor** [comment]
Sure, please note that the function is independent of the rest of the repository, so I would suggest to just experiment on a separate file/colab. Something like:

```py
import tensorflow.compat.v2 as tf
import numpy as tf

def checksum(example):
  """Computes the md5 for a given example."""

  def _bytes_flatten(element):
    """Recursively flatten an element to its byte representation."""
    ret = "".encode("utf-8")
    if isinstance(element, numbers.Number):
      # In python3, bytes(-3) is not allowed (or large numbers),
      # so convert to str to avoid problems.
      element = str(element)
    if isinstance(element, dict):
      for k, v in sorted(element.items()):
        ret += k.encode("utf-8")
        ret += _bytes_flatten(v)
    elif isinstance(element, str):
      if hasattr(element, "decode"):
        # Python2 considers bytes to be str, but are almost always latin-1
        # encoded bytes here. Extra step needed to avoid DecodeError.
        element = element.decode("latin-1")
      element = element.encode("utf-8")
      ret += element
    elif isinstance(element,
                    (tf.RaggedTensor, tf.compat.v1.ragged.RaggedTensorValue)):
      ret += str(element.to_list()).encode("utf-8")
    elif isinstance(element, np.ndarray):
      ret += element.tobytes()
    else:
      ret += bytes(element)
    return ret

  hash_ = hashlib.md5()
  hash_.update(_bytes_flatten(example))
  return hash_.hexdigest()

all_checksums = {checksum(tf.constant([b"foo", b"bar"]).numpy()) for _ in range(5)}
assert len(all_checksums) == 1
```

Then you can run this file and apply modifications until the `assert` pass.

**Comment by gaurav-singh1998** [comment]
@Conchylicultor Sure and thanks for the reply :)

**Comment by gaurav-singh1998** [comment]
Hey @Conchylicultor, so I added a line in between `elif isinstance(element, np.ndarray):` and `ret += element.tobytes()` to convert the *dtype* of the *numpy array* from **object** to **S3** i.e. `element = element.astype('S3')` and everything worked fine. So, I wanted to ask to apply these modifications and open a Pull Request.

**Comment by gaurav-singh1998** [comment]
Hey, @Conchylicultor I added a test between the lines `elif isinstance(element, np.ndarray):` and `ret += element.tobytes()` to check if the *type* of the *dtype* of the numpy array is *object* and if this true then I changed it to *S3* i.e.
```
if(element.dtype.type is np.object_):
   element = element.astype('S3')
```
I wanted to know if this correct and should I go ahead and apply the same modifications to the main repository and open a pull request?

**Comment by Conchylicultor** [comment]
@gaurav-singh1998 This won't works as `S3` correspond to fixed string of len 3 while this should handle arbitrary string. One way to solve this is to convert the np array into a list of str and compute the hash as a function of np_array.shape and flat_str_list.

**Comment by gaurav-singh1998** [comment]
@Conchylicultor Have a look at this,

```
def _bytes_flatten(element):
    """Recursively flatten an element to its byte representation."""
    ret = "".encode("utf-8")
    if isinstance(element, numbers.Number):
      # In python3, bytes(-3) is not allowed (or large numbers),
      # so convert to str to avoid problems.
      element = str(element)
    if isinstance(element, dict):
      for k, v in sorted(element.items()):
        ret += k.encode("utf-8")
        ret += _bytes_flatten(v)
    elif isinstance(element, str):
      if hasattr(element, "decode"):
        # Python2 considers bytes to be str, but are almost always latin-1
        # encoded bytes here. Extra step needed to avoid DecodeError.
        element = element.decode("latin-1")
      element = element.encode("utf-8")
      ret += element
    elif isinstance(element,
                    (tf.RaggedTensor, tf.compat.v1.ragged.RaggedTensorValue)):
      ret += str(element.to_list()).encode("utf-8")
    elif isinstance(element, np.ndarray):
      if(element.dtype.type is np.object_):
        element = element.ravel()
        i = element.shape[0]
        j = 0
        while j is not i:
          ret += _bytes_flatten(j)
          j += 1
      else:
        ret += element.tobytes()
    else:
      ret += bytes(element)
    return ret
```

**Comment by gaurav-singh1998** [comment]
@Conchylicultor what about this,
```
elif isinstance(element, np.ndarray):
   if(element.dtype.type is np.object_):
        element = element.ravel()
        i = element.shape[0]
        j = 0
        while j is not i:
          ret += _bytes_flatten(element[j])
          j += 1
   else:
         ret += element.tobytes()
```

**Comment by Conchylicultor** [comment]
Thank you for fixing this @gaurav-singh1998 !
