### ISSUE TITLE
Top requested datasets (ranking)

### ISSUE THREAD

**Issue by cyfra** [tensorflow/datasets#1291]
Here is the list of top-voted datasets (as of December 10 2019)

* #301 "Highway Drone Dataset" - 18 votes
* #27 "Pascal VOC" - 12 votes
* #299 "IBM Faces dataset" - 11 votes
* #18 "Youtube 8M" - 10 votes

**Comment by Conchylicultor** [comment]
Voc2012 is available in: https://www.tensorflow.org/datasets/catalog/voc

There is a PR to add the additional SDB extension, but it seems to add quite a lot of complexity, so I'm not sure about what is the right implementation: https://github.com/tensorflow/datasets/pull/1198

**Comment by vinayvr11** [comment]
Hello I would like to work on these datasets. This will be my first contribution so please guide me on this.
Thanks

**Comment by bhack** [comment]
This is the dynamic list https://github.com/tensorflow/datasets/issues?q=is%3Aissue+is%3Aopen+label%3A%22dataset+request%22+sort%3Areactions-%2B1-desc

**Comment by bhack** [comment]
It could be really nice if the Google Dataset team could start to programmatically contact the original datasets teams. 
Some of them could be interested to promote their datasets preparing a PR for this repo.
