### ISSUE TITLE
[data request] Moving MNIST

### ISSUE THREAD

**Issue by rsepassi** [tensorflow/datasets#13]
* Name of dataset: Moving MNIST
* URL of dataset: http://www.cs.toronto.edu/~nitish/unsupervised_video/
* License of dataset: unknown (same as MNIST probably)
* Short description of dataset and use case(s): A test set for evaluating sequence prediction/reconstruction. 10,000 sequences each of length 20 showing 2 digits moving in a 64 x 64 frame.

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by jackd** [comment]
[pull request](https://github.com/tensorflow/datasets/pull/28) made.

**Comment by cyfra** [comment]
Thanks @jackd
