### ISSUE TITLE
ImageNet_Resized not working

### ISSUE THREAD

**Issue by shun-lin** [tensorflow/datasets#1304]
**Short description**
The ImageNet_Resized unable to download using `tfds.load("imagenet_resize/8x8)` and all available options of sizes (`8x8`, `16x16`, `32x32`, `64x64`).

**Environment information**
* Operating System: gLinux, but reproducible on Colab
* Python version: 3.6.9
* `tensorflow-datasets`/`tfds-nightly` version: 1.3.2
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.1.0-rc1

**Reproduction instructions**

```Python
from tensorflow_datasets as tfds
tfds.load("imagenet_resized/8x8")
```

**Link to logs**
This colab has the error message:
https://colab.research.google.com/drive/1k_9zPXW8Yt8IUh0gyHx8sE8J30C1RrI5

The error message is:
`NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_datasets/image/imagenet_resized_labels.txt; No such file or directory`

**Expected behavior**
To load the dataset.

**Additional context**
N/A

**Comment by Conchylicultor** [comment]
Thanks for reporting. The `txt` file was missing from the `setup.py`. Sending a fix now, it should appear in the nightly version in the next few days.

In the meantime, building the dataset from the cloned repo should works.

**Comment by shun-lin** [comment]
@Conchylicultor thanks for the quick response!

**Comment by abhinavsp0730** [comment]
Hey, @shun-lin and @Conchylicultor I've checked, now It's not producing any error would you please close this issue.

**Comment by shun-lin** [comment]
it's resolved, closing the issue :) Thanks!

**Comment by lekanlanihun** [comment]
I also had this problem, but I have been to resolve it and I am loading the image_resized (32 x 32) datasets successfully. However, using the same datasets for classification based on pre-trained VGG16  CNN model. and using tf.keras.losses.sparse_categorical_crossentropy loss function,  it gives another error that has to do with NAN values. The error message starting from the first epoch is as shown below. 
Epoch 1/100
  424/20018 [..............................] - ETA: 35:04 - loss: nan - accuracy: 9.5814e-04
