### ISSUE TITLE
[data request] Image网, Imagewang

### ISSUE THREAD

**Issue by rickwierenga** [tensorflow/datasets#1325]
* Name of dataset: Image网, Imagewang
* URL of dataset: https://github.com/fastai/imagenette
* License of dataset: Apache 2.0
* Short description of dataset and use case(s): Image网 contains Imagenette and Imagewoof combined.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

Edit: I would like to add this dataset myself.

**Comment by ChanchalKumarMaji** [comment]
@Conchylicultor @cyfra this can be closed :+1: .
