### ISSUE TITLE
[GSoC] FileNotFoundError with BeamMetadataDict on Dataflow but not DirectRunner

### ISSUE THREAD

**Issue by carlthome** [tensorflow/datasets#1345]
**Short description**
I'm running my own `BeamBasedBuilder` implementation on Dataflow. It has worked fine until I added `BeamMetadataDict`. The pipeline works with the DirectRunner (metadata too). On Dataflow I get a `FileNotFoundError` however.

**Environment information**
* Debian 9.11
* Python 3.7
* TensorFlow 2.0.0
* tensorflow-datasets 1.3.0

**Reproduction instructions**
```py
import tensorflow_datasets as tfds


class MyDataset(tfds.core.BeamBasedBuilder):
    VERSION = tfds.core.Version("1.0.0")

    def _info(self):
        features = {"labels": tfds.features.ClassLabel(names=["A", "B"])}
        return tfds.core.DatasetInfo(
            builder=self,
            features=tfds.features.FeaturesDict(features),
            metadata=tfds.core.BeamMetadataDict(),
        )

    def _split_generators(self, dl_manager):
        return [tfds.core.SplitGenerator(name=tfds.Split.TRAIN)]

    def _build_pcollection(self, pipeline):
        beam = tfds.core.lazy_imports.apache_beam
        bq = beam.io.BigQuerySource(
            query="SELECT * FROM `my-project.data`", use_standard_sql=True
        )
        examples = pipeline | beam.io.Read(bq)
        self.info.metadata["counts"] = (
            examples | beam.combiners.Count.PerElement() | beam.combiners.ToDict()
        )
        return examples


if __name__ == "__main__":
    beam = tfds.core.lazy_imports.apache_beam

    beam_options = beam.options.pipeline_options.PipelineOptions(
        [
            "--project=my-project",
            "--region=europe-west1",
            "--runner=DataflowRunner",
            "--temp_location=gs://my-bucket/dataflow",
        ]
    )
    download_config = tfds.download.DownloadConfig(beam_options=beam_options)

    tfds.load(
        name="my_dataset",
        data_dir="gs://my-bucket",
        download_and_prepare_kwargs={"download_config": download_config},
    )
```

**Logs**
```
RuntimeError: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpkrcli8vttfds_beam_metadata/beam-temp-counts.json-9947cad2316411ea858a42010a840046/d8e5e354-c224-42b6-9883-eb56a5a52879.counts.json' [while running 'train/metadata_counts_write/Write/WriteImpl/WriteBundles/WriteBundles']
```

**Expected behavior**
I expect the pipeline to work on Dataflow since it works on the DirectRunner.

**Additional context**
https://github.com/tensorflow/datasets/blob/4ed180f915fdcf970a3affe14693f245429931f1/tensorflow_datasets/core/dataset_info.py#L665 looks like the culprit to me. Shouldn't it respect either `--temp_location` or `data_dir`?

**Comment by Conchylicultor** [comment]
Thanks for reporting. Yes, this is possibly the issue, the tmp location may not be accessible from all workers.

Don't hesitate to send a fix if you can solve the issue. One way would be to forward the temporary location from `BeamBasedBuilder._download_and_prepare`. Something like

```
if isinstance(self.info.metadata, BeamMetadataDict):
  self.info.metadata.set_tmp_dir(...)
```

Please note that when using `tfds-nightly`, you shouldn't use `, experiments={tfds.core.Experiment.S3: False}` which is deprecated and is going to be removed soon.
With the new writer, each example must have a unique identification key.

**Comment by carlthome** [comment]
Same error happens on Dataflow with TFDS 2.0.0

Probably still https://github.com/tensorflow/datasets/blob/v2.0.0/tensorflow_datasets/core/dataset_info.py#L665 if I were to guess.

**Comment by Conchylicultor** [comment]
Yes, this is likely the issue. Have you tried the bug fix I suggested in my previous message ? Forward a directory to `BeamMetadataDict` which would be accessed from all workers. Updating `BeamBasedBuilder._download_and_prepare` with something like:

```
  if isinstance(self.info.metadata, BeamMetadataDict):
    self.info.metadata.set_tmp_dir(self._data_dir)
```

If this works, please open a PR.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  Can you please help me please in solving this issue. Is above script is used to create own dataset using `BeamBasedBuilder` ?. If so then for running above code we can use below script ?
`python -m tensorflow_datasets.scripts.download_and_prepare \
  --register_checksums \
  --datasets=my_new_dataset`

Also I have to add data (which I want to add) in my bucket ? Is there is some guide which explains more clearly how to add data using beam I found [this](https://www.tensorflow.org/datasets/beam_datasets), but not getting much from it.

**Comment by Conchylicultor** [comment]
Thank you for looking into this. Can you be more specific about what issue you are encountering ?

The goal is to modify:
`BeamBasedBuilder. _download_and_prepare` defined in `dataset_builder.py`.
`BeamMetadataDict` defined in `dataset_info.py`

using the instructions above. Currently, if you look at `BeamMetadataDict` code, you'll see it write to some tmp dir. The goal is to replace this tmp dir by the `BeamBasedBuilder._data_dir` value, forwarded using the instructions above.

To generate a beam dataset, see instructions in: https://www.tensorflow.org/datasets/beam_datasets#on_google_cloud_dataflow

To implement a beam dataset, see instructions in: https://www.tensorflow.org/datasets/beam_datasets#implementing_a_beam_dataset

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  I am trying to generate above error.  So in above script I am confused in`data_dir`. So for `data_dir` should I store my data in bucket first so that it take it from there ?

okay I will update them, but confused in above code : Above code which we use to update `BeamBasedBuilder._download_and_prepare` is set temp directory of metadata info to `_data_dir` of `BeamBasedBuilder` using `set_tmp_dir` , So I have to create `set_tmp_dir` or it is defined. Also for Forward a directory to `BeamMetadataDict` just replace `self._tempdir` to `BeamBasedBuilder._data_dir` ?

**Comment by Conchylicultor** [comment]
I'm sorry, but I'm not sure I understood what you're saying. Could you try to rephrase using simpler sentences.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor thanks for your response, In above code that you given 
```py
if isinstance(self.info.metadata, BeamMetadataDict):
    self.info.metadata.set_tmp_dir(self._data_dir)
```
What is `Set_temp_dir` function. Is it already defined or I have to define it ?

I am not getting what exactly forwarding mean, is it mean like updating above code in `BeamBasedBuilder. _download_and_prepare` and replace temp_dir by `BeamBasedBuilder._data_dir` which not seems correct , can you please help me understanding it.

**Comment by Conchylicultor** [comment]
By looking at the code, you can see that `set_tmp_dir` does not exists already. This is a new function you have to defined.

`BeamMetadataDict` need to write in a directory accessible by all flume workers. Currently it is writing to a local `/tmp/` file. The goal is to replace this temp_dir by `BeamBasedBuilder._data_dir`. So `BeamMetadataDict` would write in `_data_dir` instead of `/tmp/...`.

You should look at the `BeamMetadataDict` code. I think you'll understand better.

**Comment by carlthome** [comment]
Closing because getting pretty stale with unified Beam/Generator classes etc.
