### ISSUE TITLE
The labels in test set of glue/sst2 are -1.

### ISSUE THREAD

**Issue by ForeverZyh** [tensorflow/datasets#1356]
**Short description**
The test set of glue/sst2 has wrong labels. All labels are -1.

**Environment information**
* Operating System: <os>
* Python version: <version>
* `tensorflow-datasets`/`tfds-nightly` version: <package and version>
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version>
ubuntu 18.04
python 3.6.9
tensorflow-gpu==1.13.1
tensorflow-datasets=1.3.2
**Reproduction instructions**

```
<put a code snippet or link to a gist here>
```

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
The label show be 0-1

**Additional context**
The dataset_info.json:

"sizeInBytes": "7439277",
  "splits": [
    {
      "name": "test",
      "numShards": "1",
      "statistics": {
        "features": [
          {
            "name": "idx",
            "numStats": {
              "commonStats": {
                "numNonMissing": "1821"
              },
              "max": 1820.0
            }
          },
          {
            "name": "label",
            "numStats": {
              "commonStats": {
                "numNonMissing": "1821"
              },
              "max": -1.0,
              "min": -1.0
            }
          },
          {
            "bytesStats": {
              "commonStats": {
                "numNonMissing": "1821"
              }
            },
            "name": "sentence",
            "type": "BYTES"
          }
        ],
        "numExamples": "1821"
      }
    },

**Comment by ForeverZyh** [comment]
It seems that it is the expected behavior?

**Comment by Conchylicultor** [comment]
This probably indicates that the labels are not public, or are not present in the original dataset. Probably nothing we can do

**Comment by ForeverZyh** [comment]
Thanks!
