### ISSUE TITLE
NonMatchingChecksumError for datasets "flores"

### ISSUE THREAD

**Issue by dojipkim** [tensorflow/datasets#1366]
**Short description**
Description of the bug.
tfds.load for "flores" fails due to NonMatchingChecksumError.

**Environment information**
* Operating System: Windows 10
* Python version: 3.7
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets 1.2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow 2.0.0

**Reproduction instructions**

```
import tensorflow_datasets as tfds
datasets = tfds.load("flores", as_supervised=True)
```

**Link to logs**
```
NonMatchingChecksumError: Artifact https://github.com/facebookresearch/flores/raw/master/data/wikipedia_en_ne_si_test_sets.tgz, downloaded to C:\Users\dojip.kim\tensorflow_datasets\downloads\face_flor_raw_mast_wiki_en_ne_si_test_setsWS4PloHuIrs36CVNe1RvVy-NYIvZxGWik2ZmKbQjoUY.tgz.tmp.b8ce407eda6647d9a1129504da3c70c0\wikipedia_en_ne_si_test_sets.tgz, has wrong checksum.
```

**Expected behavior**
The datasets should be loaded without any issues

**Additional context**

**Comment by Conchylicultor** [comment]
Do you still encounter this ? We do not host the data and sometimes the server hosting the data is down or reject the query if too many people try to download at the same time.
If you still get the issue, you can try to regenerate the checksums by running

This might indicates that the data has changed. In which case, we might want to regenerate the checksums with:

```
python -m tensorflow_datasets.scripts.download_and_prepare --registrer_checksums=True --datasets='flores'
```

**Comment by dhirensr** [comment]
@Conchylicultor : even I am able to reproduce this on ubuntu!
```
import tensorflow_datasets as tfds
datasets = tfds.load("flores", as_supervised=True)
``` 
is not working.
however 
```
python -m tensorflow_datasets.scripts.download_and_prepare --registrer_checksums=True --datasets='flores'
``` 
with this it's working
can you describe how could we solve this? I would like to contribute to this issue

**Comment by Conchylicultor** [comment]
Thanks for confirming. It seems the data has bee updated in https://github.com/facebookresearch/flores/commit/2f4a0e60bd7744304e87e456995fee5c61e87147, so the checksum has changed.

`--registrer_checksums=True` should have updated the `tensorflow_datasets/url_checksums/flores.txt` file. Could you send a PR with the updated checksum file ?

**Comment by dhirensr** [comment]
@Conchylicultor : https://github.com/tensorflow/datasets/pull/1494 please review and let me know if any changes are required.
I changed the MINOR IN patch because data got increased and also let me know if I have implemented the check correctly.

**Comment by vijayphoenix** [comment]
@dojipkim Please close the issue if your problem is solved

**Comment by dojipkim** [comment]
I've verified with tfds-nightly. All works as expected. Thanks all!
