### ISSUE TITLE
PR Templates for Dataset Additions

### ISSUE THREAD

**Issue by WilliamHYZhang** [tensorflow/datasets#1382]
**Is your feature request related to a problem? Please describe.**
No template = increase in PR review times.

**Describe the solution you'd like**
Implement a simple PR template for dataset additions, i.e. checkpoints such as "GitHub Gist:", "Lint Code: yes/no", "Add import: yes/no", etc. based on the instructions on adding a dataset. Provides helpful reminder.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

If approved, I'd like to work on this. Thanks!

**Comment by Conchylicultor** [comment]
I'm not familiar with github PR template but this sounds nice :) (as long as people can still submit non-dataset PR).
I assigned it to you if you want to work on this.
