### ISSUE TITLE
"max_examples_per_split" DownloadConfig option not working in COCO dataset

### ISSUE THREAD

**Issue by bilalsoomro** [tensorflow/datasets#1391]
**Short description**
Downloading COCO dataset with small max_examples_per_split in DownloadConfig still tries to download entire (37.5 GB) dataset in Colab and causes Colab to run out of storage space.

**Environment information**
* Operating System: Google Colab
* Python version: 3.7
* `tensorflow-datasets`/`tfds-nightly` version: 1.3.2
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.1.0-rc1

**Reproduction instructions**

```
coco_builder = tfds.builder("coco")
coco_config = tfds.download.DownloadConfig(max_examples_per_split=500)
coco_builder.download_and_prepare(download_dir='coco_dataset', download_config=coco_config)
train_dataset = coco_builder.as_dataset(split='train')
```

**Link to logs**
Here is colab link to reproduce the issue.  [link](https://colab.research.google.com/drive/1xwoHT4tfhy8jju3dvc6hJilI2uRg9N9n)

**Expected behavior**
It should only download the max number of samples set in the DownloadConfig

**Comment by Conchylicultor** [comment]
I'm sorry, but this is the intended behavior. TFDS cannot download partially the archive containing the images. This is a technical limitation.
The `max_examples_per_split` will only stop the generation, after the download.

If the dataset is too big, you may have to preprocess it on GCS. See instructions: https://www.tensorflow.org/datasets/gcs

**Comment by Ericodencoder** [comment]
Hi, I got the solution:
downgrade the tensorflow_datasets version and give the data_dir of tfds.load as data_dir="gs://gresearch/robotics" 

!pip install rlds[tensorflow]
!pip uninstall tensorflow_datasets
!pip install tensorflow_datasets==4.9.3

!pip install tfds-nightly
import tensorflow_datasets as tfds
print(tfds.__version__)

dataset_name = 'berkeley_autolab_ur5'  # @param { isTemplate: true}
num_episodes_to_load = 2  # @param { isTemplate: true}

dataset = tfds.load(dataset_name, split=f'train[:{num_episodes_to_load}]', data_dir="gs://gresearch/robotics")
