### ISSUE TITLE
Test that new dataset has correctly set the checksums

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1397]
When adding new datasets in our repository, it is possible for developer to forgot the checksums.

We cannot test the actual checksums values in the unittest, but we should at least check the presence or not of the requested urls.

In `dataset_builder_testing.py`, should modify the mocking of the `dl_manager.download` and `dl_manager.download_and_prepare` to validate the checksum urls presence.
https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/testing/dataset_builder_testing.py#L218
Also add a constant `DatasetBuilderTestCase.SKIP_CHECKSUMS = False`, if external tests want to opt-out of checksum testing.

**Comment by dhirensr** [comment]
@Conchylicultor : I would like to work on this one. could you assign the ticket to me?
also in this should we just check that if os.listdir(current_dir) has the url_checksums file or not?

**Comment by Conchylicultor** [comment]
Thank you for looking into this. When the test execute the training pipeline there are multiple call to `dl_manager.download` during the `_generate_examples` call.

The goal of this bug is to ensure that after the generation is complete, the urls from `checksums/**.txt` and the urls passed in `dl_manager.download(url)` matches (all urls called inside `dl_manager.download`) are already present in `**.txt`.

For this, have a look at our `dataset_builder_testing.py` class. You need to replace the mocked `download()` method by a new one which track the urls passed to this function (recorded in some `called_urls`).
At the end of the test, you should add an assert to ensure that `called_urls` and `checksums/**.txt` match.

**Comment by Conchylicultor** [comment]
Hey @dhirensr , any update on this ? Let me know if you want to pass over the issue to someone else.

**Comment by dhirensr** [comment]
@Conchylicultor : Yes I unassigned from this ticket. I am working on some other ticket :smile:

**Comment by gaurav-singh1998** [comment]
@Conchylicultor: Can I take up this issue?

**Comment by vijayphoenix** [comment]
Working on it!

**Comment by vijayphoenix** [comment]
@Conchylicultor how to get the path to the `url_checksums` file in `dataset_builder_testing.py` ?
