### ISSUE TITLE
Is there a way to pass a custom dict of feature connectors to pre-existing datasets?

### ISSUE THREAD

**Issue by Naio** [tensorflow/datasets#140]
For instance, there's already a COCO dataset implementation integrated to the Dataset API, and I would like to use a different representation for the 'category' feature of the dataset. Can I somehow specify what feature connectors should be used to encode and decode the data, passing them as arguments to some function? 

Thanks in advance.

**Comment by Conchylicultor** [comment]
Currently, the only way to customize the decoding is to do do this in your output pipeline:

```
ds = tfds.load(...)
ds = ds.map(process_fn)
```

There is no way to customize the encoding/generation except by creating a new dataset.

Can you tell more about your use case. What format are you expecting for the label ?

**Comment by Naio** [comment]
One-hot representation. If I'm not mistaken, ClassLabel only maps categories  to scalars. But as you say, it can easily be done using 'map()'. I forgot about that. Thank you.

**Comment by Conchylicultor** [comment]
Thanks for explaining. Yes, in this case, using `tf.one_hot` either with `ds.map` or after iterating on the dataset element is the correct way to do.
Closing this but feel free to re-open if this didn't answer your question
