### ISSUE TITLE
Creating custom dataset in tfds format

### ISSUE THREAD

**Issue by ghost** [tensorflow/datasets#1402]
**What I need help with / What I was wondering**
I am trying to create a sequence to sequence dataset in the exact format as the `ted_hrlr_translate/pt_to_en` data used in the [transformer example](https://www.tensorflow.org/tutorials/text/transformer). How can I do this?

**What I've tried so far**
I tried to create my own dataset but I am unable to feed my data into the transformer model as the dataset format does not match. I basically want to use the existing transformer model code on my custom data which is in text format. Each line is a sample. Each sample has the input sequence and output sequence separated by a tab.

**It would be nice if...**
there was a standalone script to convert text data to tfds format.

**Comment by Conchylicultor** [comment]
To create your dataset, have a look at our guide: https://www.tensorflow.org/datasets/add_dataset

For text data, you just have to load your file and yield the examples that you want:
```
class MyDataset(tfds.core.GeneratorBasedBuilder):

  def _generate_examples(self, path):
    with tf.io.gfile.GFile(path) as f:  # path to custom data
      for i, line in enumerate(f):
        source, target = line.split('\t')
        yield i, {
            'source': source,
            'target': target,
        }

```

**Comment by Conchylicultor** [comment]
Closing this as I think the question was answered. We might add a new util class in the future to simplify this use-case.

**Comment by 8904591612** [comment]
> Closing this as I think the question was answered. We might add a new util class in the future to simplify this use-case.

can you please help in solving ,  as per the documentation in tensorflow I followed  https://www.tensorflow.org/datasets/api_docs/python/tfds/folder_dataset/TranslateFolder    , followed the instructions but does not allow  to set  "supervised=True",      can we use  [tensorflow_datasets/core/custom_dataset/translate_dataset.py]
I have the same problem tto create custom data set from parallel corpus for training language model. Please help
