### ISSUE TITLE
Comment here to be added to the collaborators list

### ISSUE THREAD

**Issue by cyfra** [tensorflow/datasets#142]
Please comment here to be added to the collaborators list.

You must be in this list in order to get an issue assigned to you.

After being added - you must go to:
https://github.com/tensorflow/datasets/settings/collaboration

and accept the invite.

**Comment by Shashankjain12** [comment]
Yes sir @cyfra  please add me to the list

**Comment by cyfra** [comment]
@Shashankjain12 - already done.

**Comment by aayu04** [comment]
add me.

**Comment by cyfra** [comment]
@aayu04  - done

**Comment by KumarArindam** [comment]
Yes sir add me.

**Comment by cyfra** [comment]
@KumarArindam - done.

**Comment by ctiijima** [comment]
Add me please.

**Comment by SoumyadeepJana** [comment]
Please consider adding me.

**Comment by cyfra** [comment]
@ctiijima - done.
@SoumyadeepJana - done.

**Comment by prasadgujar** [comment]
@cyfra Hello Sir, please Added me to List as well.

**Comment by kaustumbh7** [comment]
@cyfra Please add me to the list. I am working on https://github.com/tensorflow/datasets/issues/25.

**Comment by kaustumbh7** [comment]
@cyfra Thanks! 😊

**Comment by kyscg** [comment]
@cyfra Add me

**Comment by jackd** [comment]
@cyra sure :)

**Comment by us** [comment]
@cyfra Heyyop 🐳

**Comment by amitness** [comment]
@cyfra Hi. I would like to submit some datasets I have created. Please add me as a collaborator.

**Comment by cyfra** [comment]
@kyscg @jackd  @amitness - done.

**Comment by amitness** [comment]
Thanks @cyfra

**Comment by iswariyam** [comment]
Please add to the collaborator list  @cyfra

**Comment by deemedkage** [comment]
Do add me as well.

**Comment by pmkalshetti** [comment]
Hi @cyfra, I would like to collaborate to #204. Thanks

**Comment by suvarnak** [comment]
Hi @cyfra, I would like to collaborate. 

Thanks

**Comment by suvarnak** [comment]
Hi @cyfra, I would like to collaborate. 
I currently working on MiniImagenet
Thanks.

**Comment by Nimishkhurana** [comment]
Please add me to the list @cyfra

**Comment by cyfra** [comment]
@iswariyam @deemedkage @pmkalshetti @suvarnak @Nimishkhurana 
Done - welcome to tfds.

(please remember to accept the invite)

**Comment by pmkalshetti** [comment]
Invitation accepted. Thanks @cyfra.

**Comment by iswariyam** [comment]
Thanks @cyfra

**Comment by us** [comment]
@cyfra add me please?

**Comment by cyfra** [comment]
@us - done. (you already were a collabolator)

**Comment by us** [comment]
Sorry! I thought there was a problem when the website didn't open.

**Comment by jsaurabh** [comment]
Add me as well

**Comment by mandroid6** [comment]
@cyfra please add me to the list

**Comment by Shashi456** [comment]
@cyfra please add me as well.

**Comment by gshashank84** [comment]
Please add me to list @cyfra

**Comment by amanp592** [comment]
Add me in this list please @cyfra  @Conchylicultor

**Comment by Conchylicultor** [comment]
Everyone before this message should have received an invite. You can accept it at: https://github.com/tensorflow/datasets/invitations

**Comment by mr-ubik** [comment]
Could anyone please add me? Thanks :heart:

**Comment by rsepassi** [comment]
Sorry for the change here. Please comment in the issue you'd like to be
assigned to and we'll add you as a collaborator then. And please accept the
collaborator invite when we send it to you.

**Comment by InduManimaran** [comment]
Please add me to the list @cyfra

**Comment by prabhuomkar** [comment]
Please add me to the list @cyfra @rsepassi :)

**Comment by praveenjune17** [comment]
I have collected 370,000 lines of english_tamil parallel text for training Machine translation models,  I would like to contribute this to tfds. Please add me to the list @rsepassi @cyfra . Please find the attachement explaining the dataset splits (train, validation and test)
[dataset_info.txt](https://github.com/tensorflow/datasets/files/3389650/dataset_info.txt)

**Comment by alejandrods** [comment]
Please add me as collaborator @cyfra

**Comment by sparkingdark** [comment]
add me as collaborator @cyfra @rsepassi
