### ISSUE TITLE
Better integration with tf.data autosharding

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1426]
Currently, if a user want to train on multiple workers, he/she needs to manually shard the data using the split API (https://www.tensorflow.org/datasets/splits).

Distribution Strategy [tries to auto-shard](https://www.tensorflow.org/api_docs/python/tf/data/experimental/DistributeOptions#auto_shard_policy) the `tf.data` pipeline. Because we are using `ds.interleave`, this is likely not going to works as expected.
We should:
 * Test our pipeline to make sure that datasets are correctly sharded by default
 * Add documentation about distributed pipeline with TFDS
 * If autoshard not possible, we could add a `input_context` argument to `tfds.ReadConfig`, which auto-shard tfds for better compatibility with distribution strategy: https://www.tensorflow.org/api_docs/python/tf/distribute/Strategy?version=nightly#experimental_distribute_datasets_from_function

```
def input_fn(context):
  return tfds.load(..., read_config=tfds.ReadConfig(input_context=context))

strategy.experimental_distribute_datasets_from_function(input_context)
```
 * Alternatively, there is some `ds.shard()` that we may use to helps with sharding, https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#shard
 * Make sure that sharding works with `shuffle_files=True` (no data overlap between workers)

**Comment by mathemakitten** [comment]
Hi! Thanks for flagging this. Would you be able to expand the issues with `ds.interleave` and autosharding? I'm using a TFDS dataset with a TPU pod but having data pipeline issues which results in extremely slow step times and non-convergence. I was using `experimental_distribute_dataset` but the docs seem to say that TPU pods require `experimental_distribute_datasets_from_function` instead, so I flipped it over to use that but there's no difference in performance.

I have a hypothesis that is something going wrong with the sharding and wondering if you could expand on the issues / expected behaviour / provide an example of how one should currently be using `experimental_distribute_datasets_from_function` with TFDS today. Thanks!

**Comment by Conchylicultor** [comment]
To debug you pipeline you should first try on a single machine. What is the performance when you're loading the full dataset in imgs/sec ? That would give you an idea of the performances. Also, when benchmarking, you should skip first batch as the initial set-up is not representative of the true performance (buffers are loading & cie).

Have a look at the guide for some tips on performances: https://www.tensorflow.org/guide/data_performance

Here is also some code snippet that you can use to benchmark the dataset:

```python
for split in [tfds.Split.TRAIN]:
  builder = tfds.builder('imagenet2012')
  data = builder.as_dataset(split='train')
  data = data.repeat()
  data = data.shuffle(10000)
  # data = data.apply(tf.data.experimental.map_and_batch(
  #     map_func=_preprocessing,
  #     batch_size=batch_size,
  #     drop_remainder=True,
  #     num_parallel_calls=400))
  data = data.prefetch(1)
  data = data.make_one_shot_iterator().get_next()

  num_iter = 1000
  with tf.Session() as sess:
    batch = sess.run(data)  # warmup batch
    tic = time.time()
    for i in range(num_iter):
      batch = sess.run(data)
    toc = time.time()
  print("Images per second: {}".format((num_iter * batch_size) / (toc - tic)))
```

Once you get good performances, you can switch the split to use the subsplit API (`train[:10%]`) inside `experimental_distribute_datasets_from_function` such as each worker read a subsplit of the data.
