### ISSUE TITLE
copyright and permissions for celebA dataset

### ISSUE THREAD

**Issue by makeyourownneuralnetwork** [tensorflow/datasets#1432]
I have tried quite hard but have not been able to find answers to the following questions about the celebA dataset.

1. I know the dataset is for "non-commercial use" as per the source website. It is not clear if this means we can't redistribute the website, but can commercialise instructions for working with the dataset. (In my own specific case, a member of the HK university replied to give me permission to use it in a book).

2. Have the celebrities, the subjects of the photos, given permission for their images to be used in ways they didn't initially expect or indeed give permission for when the photos were published online. Remember, the photos are scraped from the public web.

3. Have photography agencies / photographers given permission for their photos to be used in this way?

I'd love for there to be a good answer to all these questions.

**Comment by Conchylicultor** [comment]
We are not the author of the dataset, so unfortunately we cannot provide legal advice. TFDS is only a TF interface but we are not hosting the data our-self.

You should contact the dataset authors directly: http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html

Closing this as TFDS cannot help for those issues unfortunately.

**Comment by makeyourownneuralnetwork** [comment]
I don't believe this issue should be closed without considering the question of a TF interface that allows data to be downloaded and transformed

**Comment by brianzhang01** [comment]
I second @makeyourownneuralnetwork 's questions.
