### ISSUE TITLE
Is it possible to add the Kaggle dataset?

### ISSUE THREAD

**Issue by Leslie-Fang** [tensorflow/datasets#1434]
**What I need help with / What I was wondering**
Hi, I just wondering if is it possible to add the kaggle competition dataset into this project?
Do we have any legal concerns?

**What I've tried so far**
A description of what you've tried so far to solve your problem.

**It would be nice if...**
Could we have done anything to make things better (documentation, etc.)?

**Environment information**
(if applicable)
* Operating System: <os>
* Python version: <version>
* `tensorflow-datasets`/`tfds-nightly` version: <package and version>
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version>

**Comment by Conchylicultor** [comment]
Kaggle has a lot of dataset. Which dataset do you want exactly ? To add a dataset, see our contribution guide: https://www.tensorflow.org/datasets/add_dataset 
Also note TFDS has a Kaggle helper to gather the data: https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadManager#download_kaggle_data

**Comment by Leslie-Fang** [comment]
Thanks, I will check the help APIs: https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadManager#download_kaggle_data
