### ISSUE TITLE
copyright and permissions for celebA dataset - again

### ISSUE THREAD

**Issue by makeyourownneuralnetwork** [tensorflow/datasets#1437]
I don't believe the previous issue should have been closed because the questions remain valid and unanswered. Let me elaborate:

- TF allows users to download the celebA database of images scraped from the internet
- TF is not hosting or redistributing the data, just enabling users to get it
- questions around copyright, photography rights, and permissions for using personal data in ways different to the original use are not answered
- emails to the Chinese University of Hong Kong (dataset source) on other questions are answered but questions on these issues are ignored thus far

A good solution is for Google/TF legal team to issue a statement assuring us that enabling use of celebaA by TF is fine in jurisdictions like the US and Europe. Norms for copyright, rights and personal data re-use are slightly different in China and Hong Kong compared to the US an UK for example.

So, to be clear, the issue not about commercial use of the data, or the ability for people to get it from the source website, but about TF enabling potentially unethical use.

previous (closed) issue:
https://github.com/tensorflow/datasets/issues/1432

**Comment by makeyourownneuralnetwork** [comment]
I should add - I really do want to use the data, I'm not trying to put a downer on it. I'd love a good credible explanation for how TF or others can enable the use of such data that is still ethical.

**Comment by Conchylicultor** [comment]
The question is perfectly valid. But this is not a question the TFDS team can answer, as we cannot not providing legal advices. If you have a doubt about whether you can or cannot use the data, you should contact the CelebA owner directly.
We cannot provide an answer on their behalf.

**Comment by makeyourownneuralnetwork** [comment]
thanks @Conchylicultor but this is a question for whether TF should be providing tools to enable downloading and using the dataset

**Comment by Conchylicultor** [comment]
From our readme:

> TFDS is a utility library that downloads and prepares public datasets. We do not host or distribute these datasets, vouch for their quality or fairness, or claim that you have license to use the dataset. It is your responsibility to determine whether you have permission to use the dataset under the dataset's license.

If this doesn't answer your question, could you clarify your question ?

**Comment by makeyourownneuralnetwork** [comment]
thanks @Conchylicultor I will try to clarify my question.

Should Tensorflow (Google) be providing tools to enable use of data where basic questions of privacy, personal data permissions and creative ownership rights have not been answered.

I understand the readme legal advice. The question is about ethics.

It would be unethical of me to provide a tool to download private copies of software for example, even if I provided the readme guidance. 

Also "public datasets" is difficult to assign to a dataset where the source provider, Chinese University in Hong King, has explicitly stated that they themselves do not own the images. 

Again - I'd love to use these images as they are useful, but I need some reassurance that tells me something like this: "the images are already online, so publicly downloadable for personal non-commercial use, and the tool automates this downloading for personal use, and this advice is valid in jurisdictions like the UK and US".

**Comment by brianzhang01** [comment]
Seems like a worthwhile discussion to be having. Any pointers to other forums where this has been discussed?

**Comment by brianzhang01** [comment]
I found this discussion on MS-Celeb-1M, but haven't seen anything similar for CelebA. https://megapixels.cc/msceleb/
