### ISSUE TITLE
Download Error- KITTI Dataset

### ISSUE THREAD

**Issue by JJW152** [tensorflow/datasets#1442]
**Environment information**
* Operating System: Windows 10
* Python version: 3.7.6
* `tensorflow-datasets` version: 1.2
* `tensorflow`/`tensorflow-gpu` version: 2.0

When running:
```
import tensorflow.compat.v2 as tf
import tensorflow_datasets as tfds

kitti= tfds.builder('kitti',data_dir='D:\\')

kitti.download_and_prepare()
```

 on Windows 10, I get the following error:

`DownloadError: Failed to get url https://s3.eu-central-1.amazonaws.com//avg-kitti\data_object_image_2.zip. HTTP code: 400.`

If I put the link into my browser, the zip file begins downloading without issue. 

Possibly related to https://github.com/tensorflow/datasets/issues/1221 but not a duplicate.

**Comment by Conchylicultor** [comment]
Thanks for reporting. The issue was that urls were joined with `\` instead of `/` due to `os.path.join` on Windows. Sending a fix now which should appear in tfds-nightly in a few days.

**Comment by JJW152** [comment]
> Thanks for reporting. The issue was that urls were joined with `\` instead of `/` due to `os.path.join` on Windows. Sending a fix now which should appear in tfds-nightly in a few days.

Sounds good. Thank you for the quick response. Closing.
