### ISSUE TITLE
[data request] STL-10 dataset

### ISSUE THREAD

**Issue by cyfra** [tensorflow/datasets#1444]
* Name of dataset: STL-10 dataset
* URL of dataset: http://ai.stanford.edu/~acoates/stl10/
* License of dataset: Imagenet license
* Short description of dataset and use case(s): Very popular image recognition dataset.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by dhirensr** [comment]
hello @cyfra : https://github.com/tensorflow/datasets/pull/1038 this ticket has included the dataset already and under review

**Comment by bosecodes** [comment]
@cyfra  , Is this for GSoC'20? Can I work on this?

**Comment by dhirensr** [comment]
@bosecodes : I have already added in  https://github.com/tensorflow/datasets/pull/1038 and working on the improvements

**Comment by cyfra** [comment]
This was a duplicate of #831
