### ISSUE TITLE
[Feature Request] Kaggle Datasets Download

### ISSUE THREAD

**Issue by captain-pool** [tensorflow/datasets#1499]
**Is your feature request related to a problem? Please describe.**
kaggle downloader of the core supports downloading only from competitions. However, it doesn't support downloading dataset from kaggle datasets.

**Describe the solution you'd like**
The `download_kaggle_data` function of the kaggle Downloader API must support downloading datasets too.

**Additional context**
This can be integrated in https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/download/kaggle.py by creating a new set of functions that calls `$ kaggle download datasets <dataset/path>` as a subprocess.

It would be nice to have an API like this:
```python3
dl_manager = tfds.download.DownloadManager(download_dir="download_dir")
dl_manager.download_kaggle_dataset("mikeortman/wikipedia-sentences")
```
**CC:** @Conchylicultor , @cyfra 
**Reference PR:** https://github.com/tensorflow/datasets/pull/1422

**Comment by bosecodes** [comment]
The issue raised here is similar to #232, and was probably said to have been resolved in #381 @captain-pool

**Comment by captain-pool** [comment]
@bosecodes I've added a PR to fix the kaggle datasets downloader. (#1504)
Once that gets merged you can freely use
```python3
download_manager.download_kaggle_data("mikeortman/wikipedia_sentences")
```
for the job.

**Comment by vijayphoenix** [comment]
Thanks for implementing this.
 The issue can be closed as PR https://github.com/tensorflow/datasets/pull/1504 merged internally
