### ISSUE TITLE
[GSOC] 🌟 Getting started with contributing to TFDS 🌟

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1506]
Edit: If you're looking to contribute to TFDS, please look at our [contributor guide](https://www.tensorflow.org/datasets/contribute).

**Comment by Eshan-Agarwal** [comment]
Hello, I love to work on this issue can you please assign me this. I can send you PR by day after tomorrow.

**Comment by Conchylicultor** [comment]
@Eshan-Agarwal , thanks for your contribution. This bug is just a placeholder with the instructions. You should look at our issue list and pick one from there.

**Comment by Eshan-Agarwal** [comment]
Okay Thanks

**Comment by MrAsimZahid** [comment]
Thank you so much @Conchylicultor for opening this issue. For the past few days, I was looking for a way to contact mentors and a pathway to contribution in TFDF through GSoC'2020.

**Comment by Yash-Varshney** [comment]
Thank you @Conchylicultor. these instructions are really helpful to get started ..

**Comment by aniketmaurya** [comment]
Hi! I want to start contribution to TF. Most of the `Contribution welcome` are already solved. Can someone please guide me through this?

**Comment by cyfra** [comment]
Hey folks,

We really need your help with PR reviewing too.
Especially the ones that are marked with "community:please_review". 

This is a great way to get more familiar with the code and give feedback to other community members.

https://github.com/tensorflow/datasets/pulls?q=is%3Apr+is%3Aopen+label%3Acommunity%3Aplease_review

**Comment by Eshan-Agarwal** [comment]
@cyfra  Yeah sure, I Will start review as many pr as I can

**Comment by aniketmaurya** [comment]
@cyfra sure

**Comment by Rubix982** [comment]
Please assign this post a label called 'gsoc2020', or just simply 'gsoc' since it might help to lookup for beginners and contributors interested coming here. I could not find this from Google's Search, and came here through Gitter.

**Comment by vijayphoenix** [comment]
@Conchylicultor Can be renamed or closed....

**Comment by thegautamkumarjaiswal** [comment]
Hi, I want to contribute in Tensorflow. I am looking forward in issues. Thank you for providing guidelines and guide of how to start.

**Comment by shreyaspj20** [comment]
Hello, I would like to contribute to this repository. Can anyone recommend the beginner first issues to start with? Thanks in advance.

**Comment by Devansh-46** [comment]
I am a beginner an recommendations!
