### ISSUE TITLE
downloaded c4 can‘t be loaded

### ISSUE THREAD

**Issue by gongel** [tensorflow/datasets#1516]
I use command: python -m tensorflow_datasets.scripts.download_and_prepare --datasets=c4 --data_dir='/home/ubuntu/efs' and c4 has been downloaded. All downloaded files are under the folder /home/ubuntu/efs/downloads and the fold /home/ubuntu/efs/c4/en is empty. When I load c4 like tfds.load(name='c4',split="train", shuffle_files=True, download=False, data_dir='/home/ubuntu/efs'),  and I raised the error:
AssertionError: Dataset c4: could not find data in /home/ubuntu/efs/c4. Please make sure to call dataset_builder.download_and_prepare(), or pass download=True to tfds.load() before trying to access the tf.data.Dataset object.

**Comment by gongel** [comment]
But other dataset like mnist can be loaded.

**Comment by Conchylicultor** [comment]
c4 is one of the biggest dataset that we have and require a lot of preprocessing (multiple days). I strongly doubt that you can generate it from your local machine.

You probably need a distributed system, like Dataflow. See instructions at: https://www.tensorflow.org/datasets/beam_datasets#generating_a_beam_dataset

**Comment by Conchylicultor** [comment]
Closing as beam should be used for c4
