### ISSUE TITLE
[GSoC] Update datasets to cleanup legacy code

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1519]
**Task**: We have migrated to a new reading API, however, some datasets still contains artifact from the old legacy API.

**Instructions:**

For all datasets:

 * Remove all versions using `tfds.core.Experiment.S3: False` from `supported_versions=` 
 * Remove `num_shards=` arguments from all `tfds.core.SplitGenerator`
 * Remove the `VERSION = experimental_latest` from the tests.

Example: https://github.com/tensorflow/datasets/pull/1518/files

Note:

 * As many datasets needs to be updated, if you want, you can send multiple PRs to only update a few datasets at a time (~20 datasets).
 * Don't hesitate to coordinates with each other to distribute the files among you.

**Complexity:** Easy

**Comment by abhinavsp0730** [comment]
Hi @Conchylicultor  I'm Abhinav Prakash and I'm working on this

**Comment by vijayphoenix** [comment]
PR https://github.com/tensorflow/datasets/pull/1522 addresses this issue.
Thank you

**Comment by Yash-Varshney** [comment]
hi @Conchylicultor. I am Yash, as this issue addresses a big problem. I would love to work on it and will inform about the results by saturday.
Thanks
