### ISSUE TITLE
Got an error while "Merging Splits with the Legacy API"

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/datasets#1526]
**Short description**
Description of the bug.
Got an error while "Merging Splits with the Legacy API". See the code below.

**Reproduction instructions**

```
<put a code snippet or link to a gist here>
all_splits = tfds.Split.TRAIN + tfds.Split.TEST

ds = tfds.load("mnist", split=all_splits)

print("Number of Records: {:,}".format(len(list(ds))))
```

*
**Expected behavior**
What you expected to happen.
Returning 70000 records.
but Got an error 
"AssertionError: Unrecognized instruction format: (NamedSplit('train')"

*

**Comment by abhinavsp0730** [comment]
Hey, @Conchylicultor  would you please look into this. I think it's a bug and if it's so, Kindly guide me on how to fix it.
Thanks

**Comment by Conchylicultor** [comment]
The legacy split is deprecated and do not works anymore.
You should use the new split API: https://www.tensorflow.org/datasets/splits

`split='train+test'`

**Comment by abhinavsp0730** [comment]
Okay, @Conchylicultor  I got it but I think the error should be better if it's like "The legacy API is depreciated please use new S3.API"?

**Comment by Conchylicultor** [comment]
You're right. Don't hesitate to send a PR to change the error message when a sub-split is passed.

**Comment by abhinavsp0730** [comment]
Hey, @Conchylicultor would you please guide where I have to do the changes So that I'll change it accordingly and then I'll send a PR.
Thanks.

**Comment by Conchylicultor** [comment]
@abhinavsp0730 , just try to find a good place to check the input split type and raise an error if the input is not the expected format.
