### ISSUE TITLE
[GSoC] Script to cleanup the testing/metadata dir

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1534]
**Task**: Our [metadata folder](https://github.com/tensorflow/datasets/tree/master/tensorflow_datasets/testing/metadata) is growing big, but some of the content is obsolete and do not match any existing version. We should add a script to cleanup the metadata versions which do not exists anymore.

**Instruction**

* Add an util to `registered.py` to get all available versions:

```python
def _get_all_versions(version_list):
  return set(str(v) for v in version_list)

def iter_dataset_full_names():
  """Yield all supported datasets full_names."""
  for builder_name, builder_cls in registered._DATASET_REGISTRY.items():  # pylint: disable=protected-access
    if builder_cls.BUILDER_CONFIGS:
      for config in builder_cls.BUILDER_CONFIGS:
        for v in _get_all_versions(
            [config.version] + config.supported_versions):
          yield os.path.join(builder_name, config.name, v)
    else:
      for v in _get_all_versions(
          [builder_cls.VERSION] + builder_cls.SUPPORTED_VERSIONS):
        yield os.path.join(builder_name, v)
```

* Add a script in `scripts/` which iterate over the all metadata directories and check if the metadata match a registered versions or not. If not, delete the metadata directory.
* The script should have a `--dry_run` option which print the folders to delete but without actually deleting the files.

**Dificulty:** Easy

**Comment by Eshan-Agarwal** [comment]
Hey! I want to confirm dew things.
 The code snippet you given above is a util to `registered.py` which get all available versions of datasets ?
And the code which we have to add in `scripts/` have `--dry_run` option which only prints folders to delete ?

**Comment by rohanreddych** [comment]
@Conchylicultor the `iter_dataset_full_names` is returning empty generator because `_DATASET_REGISTRY` is empty how should I test my script?

**Comment by rohanreddych** [comment]
@Conchylicultor Github skips through the empty directories do you want the script to remove those directories.

**Comment by Conchylicultor** [comment]
@Eshan-Agarwal yes, exactly

@rohanreddych To make `iter_dataset_full_names` return datasets, you have to import tensorflow_datasets as datasets are registered in __init__.py.
The goal of the script is to remove folders which correspond to old versions. Ex: `metadata/mnist/1.0.0/` should be deleted as `mnist` only exists in version `3.*.*`

**Comment by rohanreddych** [comment]
Thank you will make the changes now.

**Comment by ManishAradwad** [comment]
Hey @Conchylicultor , what is `_get_all_versions` function in the above script you've given. It doesn't seem to have been defined. Is it a part of some other script?

**Comment by Conchylicultor** [comment]
@ManishAradwad 

```
def _get_all_versions(version_list):
  return set(str(v) for v in version_list)
```
I'll update the code above
