### ISSUE TITLE
Generating a Beam dataset With a custom script

### ISSUE THREAD

**Issue by gongel** [tensorflow/datasets#1537]
The code below will raise error:
"AttributeError: module 'apache_beam' has no attribute 'options'"

`import tensorflow_datasets as tfds
import apache_beam as beam

flags = []

dl_config = tfds.download.DownloadConfig()
dl_config.beam_options = beam.options.pipeline_options.PipelineOptions(flags=flags)

builder = tfds.builder('wikipedia/20190301.en')
builder.download_and_prepare(
    download_config=dl_config
)`

Ref:[https://www.tensorflow.org/datasets/beam_datasets](https://www.tensorflow.org/datasets/beam_datasets)

**Comment by carlthome** [comment]
How strange. Can you try running `python -c "import apache_beam as beam; beam.options"` in a terminal to isolate the issue? Also probably good to paste the output of `pip show apache_beam` into this thread.

**Comment by Conchylicultor** [comment]
@gongel, could you check if you still got the error when updating to the last version of apache_beam ?

**Comment by Aakash1822** [comment]
@Conchylicultor updating to the latest version of apache_beam there is no error. I checked it

**Comment by Conchylicultor** [comment]
Thanks for checking. Closing this
