### ISSUE TITLE
Add test and fake data for nsynth

### ISSUE THREAD

**Issue by cyfra** [tensorflow/datasets#154]
Nsyth dataset is missing unittest and fake data.

Please follow 
https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md#testing-mydataset

**Comment by captain-pool** [comment]
@cyfra Can you assign this to me? I'll make the tests for both commonvoice and nsynth.

**Comment by cyfra** [comment]
@captain-pool - Thanks!

**Comment by captain-pool** [comment]
@cyfra Take a look. There's some bug with nsynth dataset builder, I created a new issue for that. That's a critical bug and it needs to be fixed for the unittest to start working.

**Comment by captain-pool** [comment]
@cyfra Take a look. There's some bug with nsynth dataset builder, I created a new issue for that.(#170) That's a critical bug and it needs to be fixed for the unittest to start working.
