### ISSUE TITLE
minst

### ISSUE THREAD

**Issue by orionjiang** [tensorflow/datasets#1546]
* Name of dataset: <name>
* URL of dataset: <url>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by vijayphoenix** [comment]
@orionjiang Hi, can you provide some links to the datasets.

FYI, the MNIST dataset is already a part of `tensorflow/datasets`.
For list of available datasets, see https://www.tensorflow.org/datasets/catalog/overview

**Comment by Conchylicultor** [comment]
As @vijayphoenix pointed out, mnist already exists in TFDS
