### ISSUE TITLE
Dataset wrong checksum in download

### ISSUE THREAD

**Issue by LuigiSavino** [tensorflow/datasets#1551]
**Short description**
Cannot load properly camelyon dataset.

**Reproduction instructions**

```
pcam, pcam_info = tfds.load("patch_camelyon", with_info=True)
```

**Output Error**
```
 raise NonMatchingChecksumError(resource.url, tmp_path)
tensorflow_datasets.core.download.download_manager.NonMatchingChecksumError: Artifact https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_x.h5.gz, downloaded to /home/luigi/tensorflow_datasets/downloads/zeno.org_reco_2546_file_came_leve_2_spli_trbOY5E-X_2wontwSZI65F3fEMTim90H_hpA4Swq0obJw.gz.tmp.5ca1a06c29894e8c8c543733097e6702/camelyonpatch_level_2_split_train_x.h5.gz, has wrong checksum.
```
**Expected behavior**
It should load all datasets from Zenodo but i think some urls have changed.

**Additional context**
Here are all of the URLs and checksums:
Name

**camelyonpatch_level_2_split_test_meta.csv**

https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_test_meta.csv?download=1

md5:3455fd69135b66734e1008f3af684566 

**camelyonpatch_level_2_split_test_x.h5.gz**

https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_test_x.h5.gz?download=1

md5:d8c2d60d490dbd479f8199bdfa0cf6ec 

**camelyonpatch_level_2_split_test_y.h5.gz**

https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_test_y.h5.gz?download=1

md5:60a7035772fbdb7f34eb86d4420cf66a 

**camelyonpatch_level_2_split_train_meta.csv**

https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_meta.csv?download=1

md5:5a3dd671e465cfd74b5b822125e65b0a 

**camelyonpatch_level_2_split_train_x.h5.gz**

https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_x.h5.gz?download=1

md5:1571f514728f59376b705fc836ff4b63 

**camelyonpatch_level_2_split_train_y.h5.gz**

https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_y.h5.gz?download=1

md5:35c2d7259d906cfc8143347bb8e05be7 

**camelyonpatch_level_2_split_valid_meta.csv**

https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_valid_meta.csv?download=1

md5:67589e00a4a37ec317f2d1932c7502ca 

**camelyonpatch_level_2_split_valid_x.h5.gz**

https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_valid_x.h5.gz?download=1

md5:d5b63470df7cfa627aeec8b9dc0c066e

**Comment by Eshan-Agarwal** [comment]
This patch_camelyon is which type of data image , text, object_detection etc

**Comment by LuigiSavino** [comment]
> This patch_camelyon is which type of data image, text, object_detection etc

I don't know what changed but suddenly after 10 equal tries, it worked.

Should  I close this issue?

**Comment by Eshan-Agarwal** [comment]
Actually its looks like checksum file for this dataset is not correctly mentioned. I am updating it and send PR.

**Comment by Eshan-Agarwal** [comment]
10 equal  tries means you run 10 times and it worked after it without any changes ?

**Comment by LuigiSavino** [comment]
> 10 equal tries means you run 10 times and it worked after it without any changes ?

Yes. After the forth time I always deleted already downloaded elements and restarted downloads.

Could it be some kind of server error zenodo side sending the wrong checksum? 

> Actually its looks like checksum file for this dataset is not correctly mentioned. I am updating it and send PR.

Are you sure it's not correct? It worked...late but it worked.

**Comment by Eshan-Agarwal** [comment]
According to your error 

> raise NonMatchingChecksumError(resource.url, tmp_path)
tensorflow_datasets.core.download.download_manager.NonMatchingChecksumError: Artifact https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_x.h5.gz, downloaded to /home/luigi/tensorflow_datasets/downloads/zeno.org_reco_2546_file_came_leve_2_spli_trbOY5E-X_2wontwSZI65F3fEMTim90H_hpA4Swq0obJw.gz.tmp.5ca1a06c29894e8c8c543733097e6702/camelyonpatch_level_2_split_train_x.h5.gz, has wrong checksum.

checksum for `train_x.h5.gz` is wrong given so i run 
`python -m tensorflow_datasets.scripts.download_and_prepare \
  --register_checksums \
  --datasets=my_new_dataset`
locally to check if it is correct or not and dataset is of big size so waiting for finishing after that I can check if checksum for `train_x.h5.gz` is correct or not.

**Comment by Eshan-Agarwal** [comment]
> Could it be some kind of server error zenodo side sending the wrong checksum?

I don't think it is server error.

**Comment by LuigiSavino** [comment]
> According to your error
> 
> > raise NonMatchingChecksumError(resource.url, tmp_path)
> > tensorflow_datasets.core.download.download_manager.NonMatchingChecksumError: Artifact https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_x.h5.gz, downloaded to /home/luigi/tensorflow_datasets/downloads/zeno.org_reco_2546_file_came_leve_2_spli_trbOY5E-X_2wontwSZI65F3fEMTim90H_hpA4Swq0obJw.gz.tmp.5ca1a06c29894e8c8c543733097e6702/camelyonpatch_level_2_split_train_x.h5.gz, has wrong checksum.
> 
> checksum for `train_x.h5.gz` is wrong given so i run
> `python -m tensorflow_datasets.scripts.download_and_prepare \ --register_checksums \ --datasets=my_new_dataset`
> locally to check if it is correct or not and dataset is of big size so waiting for finishing after that I can check if checksum for `train_x.h5.gz` is correct or not.

Let's wait

**Comment by LuigiSavino** [comment]
> > Could it be some kind of server error zenodo side sending the wrong checksum?
> 
> I don't think it is server error.

Just guessing 😁

**Comment by Conchylicultor** [comment]
Thanks for reporting. Please note that we do not use md5 for checksums, but sha256 I believe. If it worked after some times, it may indicates the server was temporary down or returned wrong checksum.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  I am running
 `python -m tensorflow_datasets.scripts.download_and_prepare \
  --register_checksums \
  --datasets=my_new_dataset`

locally after removing all URL in checksum file for `patch_camelyon.txt` and then for 

`camelyonpatch_level_2_split_train_x.h5.gz`

 got check sum : `https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_x.h5.gz 29275141 c5a38bcaa89a247da05c0ae9eb2c44db19ed4a348815d8911d4b817b24e1ee5d`

which is different from existing checksum of `patch_camelyon.txt`

After running above code locally whole checksum for `patch_camelyon.txt` look like : 

> https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_test_x.h5.gz 800875929 79174c2201ad521602a5888be8f36ee10875f37403dd3f2086caf2182ef87245
https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_test_y.h5.gz 3040 0a522005fccc8bbd04c5a117bfaf81d8da2676f03a29d7499f71d0a0bd6068ef
https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_x.h5.gz 29275141 c5a38bcaa89a247da05c0ae9eb2c44db19ed4a348815d8911d4b817b24e1ee5d
https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_y.h5.gz 21378 b74126d2c01b20d3661f9b46765d29cf4e4fba6faba29c8e0d09d406331ab75a
https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_valid_x.h5.gz 805965320 f82ee1670d027b4ec388048d9eabc2186b77c009655dae76d624c0ecb053ccb2
https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_valid_y.h5.gz 3038 ce1ae30f08feb468447971cfd0472e7becd0ad96d877c64120c72571439ae48c

and existing look like : 

> https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_test_x.h5.gz 800875929 79174c2201ad521602a5888be8f36ee10875f37403dd3f2086caf2182ef87245
https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_test_y.h5.gz 3040 0a522005fccc8bbd04c5a117bfaf81d8da2676f03a29d7499f71d0a0bd6068ef
https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_x.h5.gz 6421353462 d619e741468a7ab35c7e4a75e6821b7e7e6c9411705d45708f2a0efc8960656c
https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_train_y.h5.gz 21378 b74126d2c01b20d3661f9b46765d29cf4e4fba6faba29c8e0d09d406331ab75a
https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_valid_x.h5.gz 805965320 f82ee1670d027b4ec388048d9eabc2186b77c009655dae76d624c0ecb053ccb2
https://zenodo.org/record/2546921/files/camelyonpatch_level_2_split_valid_y.h5.gz 3038 ce1ae30f08feb468447971cfd0472e7becd0ad96d877c64120c72571439ae48c

**Comment by LuigiSavino** [comment]
> Thanks for reporting. Please note that we do not use md5 for checksums, but sha256 I believe. If it worked after some times, it may indicates the server was temporary down or returned wrong checksum.

Ok. Should I close this issue?

**Comment by Eshan-Agarwal** [comment]
@vijayphoenix  can you please look on previous comments

**Comment by vijayphoenix** [comment]
Please provide some more details like the type of file that failed during extraction and also the type of archive manager you have on your machine.

**Comment by Eshan-Agarwal** [comment]
Environment information

Operating System: Windows 10 (64bit)
Python version: 3.6.10
tfds version = 2.1.0
tensorflow version = 1.15.0

When loading this data set it gives error : `NonMatchingChecksumError: Artifact ` for `camelyonpatch_level_2_split_train_x.h5.gz`

So i manually run `python -m tensorflow_datasets.scripts.download_and_prepare \ --register_checksums \ --datasets=patch_camelyon` 

and check checksum for `camelyonpatch_level_2_split_train_x.h5.gz` is changed but while downloaing and extracting it give me

> ExtractError: Error while extracting C:\Users\eshan\tensorflow_datasets\downloads\zeno.org_reco_2546_file_came_leve_2_spli_trS5fpbFu_uQ373HXQ7JgSTYVXiaCDa8XGyti2tU0HYwM.gz to C:\Users\eshan\tensorflow_datasets\downloads\extracted\GZIP.zeno.org_reco_2546_file_came_leve_2_spli_trS5fpbFu_uQ373HXQ7JgSTYVXiaCDa8XGyti2tU0HYwM.gz (file: ) : Compressed file ended before the end-of-stream marker was reached

and whenever i run `python -m tensorflow_datasets.scripts.download_and_prepare \ --register_checksums \ --datasets=patch_camelyon` i got different checksum for `camelyonpatch_level_2_split_train_x.h5.gz`
