### ISSUE TITLE
Remove legacy Python 2 code

### ISSUE THREAD

**Issue by vijayphoenix** [tensorflow/datasets#1552]
As support for Python 2 has been dropped and we have also started adding Python 3 typing annotations https://github.com/tensorflow/datasets/issues/1517.
I think we can now remove all lot of unnecessary code like

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
```

**Comment by tanviagwl98** [comment]
> As support for Python 2 has been dropped and we have also started adding Python 3 typing annotations #1517.
> I think we can now remove all lot of unnecessary code like
> 
> ```
> from __future__ import absolute_import
> from __future__ import division
> from __future__ import print_function
> ```

I agree with your issue as with the advancement we cover up limitations.

**Comment by Eshan-Agarwal** [comment]
Can I remove 

> from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

From `core/` also ?
