### ISSUE TITLE
Problem while creating new dataset--Help

### ISSUE THREAD

**Issue by SoumyadeepJana** [tensorflow/datasets#156]
**What I need help with / What I was wondering**
I was trying to add a new dataset and the download link was from kaggle,but dl_manager unable to download the proper zip from kaggle,is it some permission issue from kaggle?

**What I've tried so far**
I have implemented the entire mydataset class as specified in the documentation of tensorflow_datasets
[Code Link](https://github.com/SoumyadeepJana/tfds/blob/master/fruits.py)

**Environment information**
(if applicable)
* Operating System: <Windows 10>
* Python version: <3.6>
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <tensorflow and 1.13.1>

**Comment by ChanchalKumarMaji** [comment]
When we download data from Kaggle we manually have to download a file known as <code>kaggle.json</code> which contains a <code>username</code> and a <code>key</code>. After authenticating we can download data from Kaggle.

**Comment by SoumyadeepJana** [comment]
Is it allowed to add datasets that require some sort of API key,will it not make it hard for others to use?

**Comment by ChanchalKumarMaji** [comment]
I think for such cases user have to manually download the data and then place it in the appropriate folder.

**Comment by us** [comment]
tfds has own kaggle downloader please check it.
`tensorflow_datasets.core.download.kaggle`

**Comment by rsepassi** [comment]
In the dataset, try using [`DownloadManager.download_kaggle_data`](https://github.com/tensorflow/datasets/blob/dde9c9d7fd14fff3458e59c120f50416657633a7/tensorflow_datasets/core/download/download_manager.py#L260). You'll still need the login, but it should provide an informative error message that lets users know what they need to do.

**Comment by SoumyadeepJana** [comment]
Thank you @rsepassi .This is what I was looking for.
