### ISSUE TITLE
Documentation more precise

### ISSUE THREAD

**Issue by tanviagwl98** [tensorflow/datasets#1560]
**Is your feature request related to a problem? Please describe.**

So far after getting through the documentation, I found links to software downloads required for the application are not provided.

**Describe the solution you'd like**

It would set easy path for newbies if link to required softwares be attached with the procedure explained in the documentation.

**Comment by vijayphoenix** [comment]
@tanviagwl98 what software are you trying to download? 
Please provide the link to the documentation, you are describing.

**Comment by tanviagwl98** [comment]
https://github.com/tensorflow/docs
This is the documentation link. If google colaboratory link can be directly added to this would be helpful... and also other sources to implement tensorflow .

**Comment by Conchylicultor** [comment]
I'm not sure I understand what you are trying to achieve. Could you try to rephrase ?
The link https://github.com/tensorflow/docs isn't part of TFDS.

To install tfds, just use `pip install tensorflow-datasets` as explained in https://www.tensorflow.org/datasets/overview#installation

**Comment by Conchylicultor** [comment]
Additionally, to see the list of required dependency, you can look at our setup.py: https://github.com/tensorflow/datasets/blob/master/setup.py#L42

But those are automatically added when installing with `pip install`.

**Comment by tanviagwl98** [comment]
Okay, thank you for your response I got it.
