### ISSUE TITLE
CNN-DailyMail fails to download with tfds.load()

### ISSUE THREAD

**Issue by lmoroney** [tensorflow/datasets#1563]
**Short description**
Trying to use tfds.load() to get cnn_dailymail fails with error (no field named "downloadSize".)

**Environment information**
* Operating System: Google Colab
* Python version: 3

**Reproduction instructions**
Run this code in Colab:
```
import tensorflow as tf
import tensorflow_datasets as tfds
data, info = tfds.load(name="cnn_dailymail", with_info=True)
print(info)

```

**Link to logs**
ERROR:absl:Failed to construct dataset cnn_dailymail
---------------------------------------------------------------------------
ParseError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    508                    message_descriptor.full_name, name,
--> 509                    [f.json_name for f in message_descriptor.fields]))
    510         if name in names:

ParseError: Message type "tensorflow_datasets.DatasetInfo" has no field named "downloadSize".
 Available Fields(except extensions): ['name', 'description', 'version', 'citation', 'sizeInBytes', 'location', 'downloadChecksums', 'schema', 'splits', 'supervisedKeys', 'redistributionInfo']

During handling of the above exception, another exception occurred:

ParseError                                Traceback (most recent call last)
12 frames
/usr/local/lib/python3.6/dist-packages/google/protobuf/json_format.py in _ConvertFieldValuePair(self, js, message)
    575           raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))
    576         else:
--> 577           raise ParseError(str(e))
    578       except ValueError as e:
    579         raise ParseError('Failed to parse {0} field: {1}.'.format(name, e))

ParseError: Message type "tensorflow_datasets.DatasetInfo" has no field named "downloadSize".
 Available Fields(except extensions): ['name', 'description', 'version', 'citation', 'sizeInBytes', 'location', 'downloadChecksums', 'schema', 'splits', 'supervisedKeys', 'redistributionInfo']

**Expected behavior**
Dataset downloads and I get the data :)

**Additional context**

**Comment by Conchylicultor** [comment]
Which version of TFDS are you using ? Does the problem goes away with tfds-nightly or the latest tensorflow_datasets 2.1.0 ?

**Comment by vijayphoenix** [comment]
The error goes away at least with tdfs-nightly
https://colab.research.google.com/drive/1vai1vv91FvLQRDupMnhsGcPYd7S_7BZ-

**Comment by Eshan-Agarwal** [comment]
@lmoroney  @Conchylicultor  Also it works fine in tfds 2.1.0 when using [Colab](https://colab.research.google.com/drive/1hOT1YoPxBDm2376WBaxcJT9mboxFS68l)

**Comment by lmoroney** [comment]
Confirmed that when I update colab to 2.1, this will work.
With colab defaulting to tfds 2.0.0, it's a bit misleading
