### ISSUE TITLE
[GSoC] Add `as_supervised=True` compatibility for `tfds.show_examples`

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1575]
It would be nice if `tfds.show_examples` was working with `as_supervised=True`. Currently it raise a not supported error:

```python
ds, ds_info = tfds.load('mnist', split='train', as_supervised=True)
tfds.show_examples(ds_info, ds)
```
Changes should only affect the `show_examples` function, so it should be fairly simple.

**Comment by vijayphoenix** [comment]
Working on it!

**Comment by abhinavsp0730** [comment]
Hi I'm Abhinav Prakash and I'm working on it.

**Comment by aniketmaurya** [comment]
@vijayphoenix is it fixed?
