### ISSUE TITLE
import failure on tf=1.14, tfds=2.1.0

### ISSUE THREAD

**Issue by levskaya** [tensorflow/datasets#1577]
**Short description**
python=3.5 tf=1.14 tfds=2.1.0
running pip install tensorflow tensorflow_datasets then "import tensorflow_datasets" fails w.:
AttributeError: module 'tensorflow.compat.v2' has no attribute 'contrib'

**Environment information**
* Operating System: Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
* Python version: 3.5
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets=2.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow=1.14
**Reproduction instructions**

```
import tensorflow_datasets
```

**Link to logs**
stacktrace at:
https://gist.github.com/levskaya/d8bd85e188a9836ad9107d874965d94c

**Expected behavior**
To import.

**Additional context**
N/A

**Comment by vijayphoenix** [comment]
@levskaya tensorflow_datasets has tensorflow >= 1.15.0 as dependency
See [dependencies](https://github.com/tensorflow/datasets/blob/38202b51cab90e5725b25ed72537172bbe905f4b/setup.py#L157)

**Comment by levskaya** [comment]
My apologies for the noise, this came about because of a stale pip version on a test machine, I thought it was installing a more recent version and was concerned.  Thanks!

**Comment by 980202006** [comment]
You can use a low version, such as 1.3.2
