### ISSUE TITLE
Broken link for `tfds.core.DatasetBuilder`

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/datasets#1579]
Link for `tfds.core.DatasetBuilder` is broken in https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md#datasetbuilder

**Comment by Eshan-Agarwal** [comment]
Thanks for finding it out soon sending PR with improved one.

**Comment by Eshan-Agarwal** [comment]
Ok its look like that datasetbuilder.md is missing from `https://github.com/tensorflow/datasets/tree/master/docs` its a bug soon send PR and add missing contents in docs.

**Comment by Eshan-Agarwal** [comment]
I created DatasetBuilder.md file. you can read all contents [here](https://www.tensorflow.org/datasets/api_docs/python/tfds/core/DatasetBuilder) as its not merged yet

**Comment by abhinavsp0730** [comment]
@ManishAradwad I checked the link now it's working. If it's resolved kindly close this issue.

**Comment by Eshan-Agarwal** [comment]
@abhinavsp0730  are you check link of `tfds.core.DatasetBuilder`, its not working because there is no file for DatasetBuilder.md

**Comment by abhinavsp0730** [comment]
After clicking the link I got the documentation  DatasetBuilder.
DatasetBuilder

Each dataset is defined as a subclass of tfds.core.DatasetBuilder implementing the following methods:

    _info: builds the DatasetInfo object describing the dataset
    _download_and_prepare: to download and serialize the source data to disk
    _as_dataset: to produce a tf.data.Dataset from the serialized data

Most datasets subclass tfds.core.GeneratorBasedBuilder, which is a subclass of tfds.core.DatasetBuilder that simplifies defining a dataset. It works well for datasets that can be generated on a single machine. Its subclasses implement:

    _info: builds the DatasetInfo object describing the dataset
    _split_generators: downloads the source data and defines the dataset splits
    _generate_examples: yields (key, example) tuples in the dataset from the source data

This guide will use GeneratorBasedBuilder.

**Comment by Eshan-Agarwal** [comment]
I think you wrong interpret it says link for tfds.core.DatasetBuilder is broken in given link

**Comment by abhinavsp0730** [comment]
Ok now got it.

**Comment by Conchylicultor** [comment]
Thank you for reporting, we have recently removed the API github and redirect people instead to: https://www.tensorflow.org/datasets/api_docs/python/tfds

If there are dead link, they should be removed (`tfds.core.DatasetBuilder` is automatically linkified), or updated to redirect to https://www.tensorflow.org/datasets/api_docs/python/tfds

**Comment by Eshan-Agarwal** [comment]
@ManishAradwad  please close this issue.
