### ISSUE TITLE
What happened to tfds.core.ReadInstruction ?

### ISSUE THREAD

**Issue by princyok** [tensorflow/datasets#1587]
**Short description**

AttributError when trying to access ReadInstruction.

**Environment information**
* Operating System: Windows 10
* Python version: 3.7.4
* `tensorflow-datasets`/`tfds-nightly` version:  1.2.0
* `tensorflow` version: 2.0.0

**Reproduction instructions**

```
import tensorflow_datasets as tfds
tfds.core.ReadInstruction

```

**Expected behavior**
Expected it to work as described in the [documentstion](https://www.tensorflow.org/datasets/api_docs/python/tfds/core/ReadInstruction).

**Comment by Conchylicultor** [comment]
`1.2.0` is an old TFDS version. Try upgrading to `2.1.0`

**Comment by princyok** [comment]
Oh my. How did I miss that? I changed computers and was getting frustrated why it wasn't working. Copied the versions to paste here but didn't even notice. My bad.
