### ISSUE TITLE
celeb_a has wrong checksum

### ISSUE THREAD

**Issue by vidyabhandary** [tensorflow/datasets#1598]
**What I need help with / What I was wondering**
I am trying to download  the tfds dataset **celeb_a** via the download_and_prepare() method. I get a wrong checksum error when executing.

**What I've tried so far**
The code so far

```
import tensorflow as tf
import tensorflow_datasets as tfds

celeba_bldr = tfds.builder('celeb_a')
celeba_bldr.download_and_prepare()
```
Error message

```
---------------------------------------------------------------------------
NonMatchingChecksumError                  Traceback (most recent call last)
<ipython-input-4-1847a08068cb> in <module>()
----> 1 celeba_bldr.download_and_prepare()

17 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/download/download_manager.py in _handle_download_result(self, resource, tmp_dir_path, sha256, dl_size)
    214       self._record_sizes_checksums()
    215     elif (dl_size, sha256) != self._sizes_checksums.get(resource.url, None):
--> 216       raise NonMatchingChecksumError(resource.url, tmp_path)
    217     download_path = self._get_final_dl_path(resource.url, sha256)
    218     resource_lib.write_info_file(resource, download_path, self._dataset_name,

NonMatchingChecksumError: Artifact https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM, downloaded to /root/tensorflow_datasets/downloads/ucexport_download_id_0B7EVK8r0v71pZjFTYXZWM3FlDDaXUAQO8EGH_a7VqGNLRtW52mva1LzDrb-V723OQN8.tmp.94f283c873dd4cba9ac93951f59cac50/uc, has wrong checksum.
```

**Environment information**
(if applicable)
* Operating System: Google Colab
* Python version: 3.6.9

* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets, tfds.version = 2.0.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow , tf.version = 1.15.0

**Comment by Eshan-Agarwal** [comment]
@vidyabhandary  maybe there is some server problem or dataset location was changed. So you have to update checksum.

**Comment by Eshan-Agarwal** [comment]
use this 

> python -m tensorflow_datasets.scripts.download_and_prepare \
  --register_checksums \
  --datasets=my_new_dataset

**Comment by Conchylicultor** [comment]
See: https://github.com/tensorflow/datasets/issues/1482
