### ISSUE TITLE
[data request] CNN DailyMail

### ISSUE THREAD

**Issue by rsepassi** [tensorflow/datasets#16]
* Name of dataset: CNN DailyMail summarization
* URL of dataset: https://cs.nyu.edu/~kcho/DMQA/
* License of dataset: unknown
* Short description of dataset and use case(s): news articles for question answering and summarization

Related URL that uses the data: https://github.com/abisee/cnn-dailymail

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by ayush1999** [comment]
@rsepassi Is this a high priority? I'm looking for a good place to start, was wondering if this could be assigned to me in case you're interested in having this dataset.

**Comment by rsepassi** [comment]
Yeah, we'd love to have this dataset in TFDS. Thanks for your interest! I've sent you a collaborator invite; let me know when you've accepted and I'll assign this to you.

**Comment by ayush1999** [comment]
Sure, I've accepted it. Please assign.

**Comment by rsepassi** [comment]
Done. Looking forward to your PR!

**Comment by ayush1999** [comment]
@rsepassi  Sure. Would be great if you could clarify a few things beforehand: I'm looking at the CNN/stories dataset, and it looks like each document contains a paragraph about an event, and a few question related to this paragraph. So here my `text` will be the paragraph, and my `label` will be the questions, right?

**Comment by peterjliu** [comment]
Hi, I started working on this after seeing this and it's almost done.

**Comment by peterjliu** [comment]
This is available here https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/cnn_dailymail.py

**Comment by us** [comment]
@rsepassi completed issue. Should close.
