### ISSUE TITLE
help for adding unsupervised split in STL-10 dataset

### ISSUE THREAD

**Issue by VaranRohila** [tensorflow/datasets#1600]
**What I need help with / What I was wondering**
The STL-10 has 3 splits: test, train, and an unsupervised split. Labels are not provided for the unsupervised split. So I needed help in adding the STL-10 to tfds.
Should I implement the unsupervised split in another class or should I try to incorporate it in the supervised class only (which has TEST and TRAIN splits)?

**What I've tried so far**
I have two solutions, 
1. I could add unsupervised to another class and supervised part to the other. 
2. I could try to work around the tfds.core.SplitGenerator by adding split other than TEST, TRAIN and VALIDATION.

**It would be nice if...**
You could provide some workaround for the problem.

**Environment information**
(if applicable)
* Operating System: Mac OS 10.15.3
* Python version: 3.7
* `tensorflow-datasets`/`tfds-nightly` version: 1.2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.0.0rc1

**Comment by Conchylicultor** [comment]
You can use `-1` when the labels are not provided

**Comment by VaranRohila** [comment]
Thank you for your quick reply. I actually wanted to create the dataset so that the unsupervised split can be accessed individually like the TEST and TRAIN splits since the main focus of the STL-10 is to learn unsupervised features from that split before performing the supervised learning.

Using `-1` I would have to add the split to the TRAIN split itself which would pose a problem later.

**Comment by Conchylicultor** [comment]
If the dataset has three split, then so should the implementation. You can just declare another tfds.core.SplitGenerator(name='unsupervised') in addition of train and test

**Comment by VaranRohila** [comment]
Okay thanks!
