### ISSUE TITLE
[GSoC] TranslateCsEnWmt19Test test is broken

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1638]
It seems that the [translate/wmt19_test.py](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/translate/wmt19_test.py) test is failing with:

```
tensorflow_datasets.core.download.extractor.ExtractError: Error while extracting /tmpfs/src/github/datasets/tensorflow_datasets/testing/test_data/fake_examples/wmt19_translate/data-plaintext-format.6.tar to 
/tmpfs/tmp/<string>6h1uzg9c/tmpgdkviubt/downloads/extracted/TAR.data-plaintext-format.6.tar (file: None) : 
module 'lzma' has no attribute 'LZMAFile'
```

Full stacktrace: https://gist.github.com/Conchylicultor/4358d48be974914ec2d0324e7abc1e16

If someone has the time, it would be nice to investigate what is happening.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  I am looking on it, are you running this script and getting error `python -m tensorflow_datasets.scripts.download_and_prepare \
  --register_checksums \
  --datasets=my_new_dataset`

**Comment by Eshan-Agarwal** [comment]
Can you please provide script that you are using while getting error

**Comment by Conchylicultor** [comment]
This is the test which is failing, which are run through https://github.com/tensorflow/datasets/blob/master/oss_scripts/oss_tests.sh

To reproduce:
`pytest -n auto --disable-warnings wmt19_test.py`

**Comment by ManishAradwad** [comment]
@Conchylicultor Could it be possible this issue is related with removal of python 2 legacy code.
Also when I tried reproducing it using the above command I'm getting following error:
`ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n tensorflow_datasets/translate/wmt19_test.py
  inifile: None
  rootdir: /home/shadow-man/open-source/datasets
`

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor @ManishAradwad  I am also getting same error then I am just using this `pytest tensorflow_datasets/translate/wmt19_test.py` and it runs but showing different errors some 16 failed, 4 skipped, 5 warnings

**Comment by Conchylicultor** [comment]
I think the `-n` option require pytest-xdist.

For info, the stacktrace is coming from: https://source.cloud.google.com/results/invocations/c253f7c7-dc9a-44c9-bcc2-76231bd71f05/targets/tensorflow_datasets%2Fgh_testing%2Fpresubmit/log

`pytest tensorflow_datasets/translate/wmt19_test.py` should works too to replicate the issue. Which error does it display ? Can you try to fix those ?
If other tests fails this likely mean there is an error in your set-up (maybe dependencies are not properly installed ?).
One way to check this is to try to run other tests and see if they are failing too.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  Yes by installing `pytest-xdist` it works fine.  And I got some `osError`, maybe dependencies are not installed. It show me this error for any other test file also.


```python
 [gw3] win32 -- Python 3.6.10 c:\users\eshan\anaconda3\envs\keras-gpu\python.exe

self = <tensorflow_datasets.image.mnist_test.EMNISTTest testMethod=test_baseclass>

    def setUp(self):
>     super(DatasetBuilderTestCase, self).setUp()

tensorflow_datasets\testing\dataset_builder_testing.py:153:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tensorflow_datasets\testing\test_case.py:71: in setUp
    self.tmp_dir = tempfile.mkdtemp(dir=tf.compat.v1.test.get_temp_dir())
..\..\..\anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_core\python\platform\test.py:76: in get_temp_dir
    return _googletest.GetTempDir()
..\..\..\anaconda3\envs\keras-gpu\lib\site-packages\tensorflow_core\python\platform\googletest.py:78: in GetTempDir
    temp_dir = tempfile.mkdtemp(prefix=temp_dir.rstrip('.py'))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

suffix = '', prefix = 'C:\\Users\\eshan\\AppData\\Local\\Temp\\<string>', dir = 'C:\\Users\\eshan\\AppData\\Local\\Temp'

    def mkdtemp(suffix=None, prefix=None, dir=None):
        """User-callable function to create and return a unique temporary
        directory.  The return value is the pathname of the directory.

        Arguments are as for mkstemp, except that the 'text' argument is
        not accepted.

        The directory is readable, writable, and searchable only by the
        creating user.

        Caller is responsible for deleting the directory when done with it.
        """

        prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)

        names = _get_candidate_names()
        if output_type is bytes:
            names = map(_os.fsencode, names)

        for seq in range(TMP_MAX):
            name = next(names)
            file = _os.path.join(dir, prefix + name + suffix)
            try:
>               _os.mkdir(file, 0o700)
E               OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\eshan\\AppData\\Local\\Temp\\<string>1s_x6inp'

..\..\..\anaconda3\envs\keras-gpu\lib\tempfile.py:370: OSError
```

**Comment by vijayphoenix** [comment]
Well, I got the following output. 
![image](https://user-images.githubusercontent.com/41972768/76681487-5422be00-6619-11ea-9f41-e59b3f43b950.png)
@Conchylicultor It works fine for me.

**Comment by Conchylicultor** [comment]
@vijayphoenix thank you for testing. I suspect an issue with Ubuntu 16.04, and the specific kokoro setting (e.g. wrong dependency installed or something similar). I haven't really looked if other people had similar error message.

**Comment by vijayphoenix** [comment]
FYI: I tested it in Ubuntu 19.10

**Comment by Conchylicultor** [comment]
Searching online, it seems to be: https://bugs.python.org/issue39430

**Comment by Conchylicultor** [comment]
Closing this as we disabled the test, waiting for https://bugs.python.org/issue39430 fix
