### ISSUE TITLE
'DatasetInfo' object has no attribute 'total_num_examples'.Is this expected or not ?

### ISSUE THREAD

**Issue by tarrade** [tensorflow/datasets#1656]
**Short description**
Description of the bug.

**Environment information**
* Operating System: Mac
* Python version: 3.7.6
* `tensorflow-datasets`/`tfds-nightly` version: 2.1.0 
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.1.0 

**Reproduction instructions**

```
import tensorflow as tf
import tensorflow_datasets as tfds
datasets, ds_info = tfds.load(name='mnist', with_info=True, as_supervised=True, data_dir=data_dir)
print(ds_info)
ds_info.total_num_examples
```

**Link to logs**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-b6bca6fbfb09> in <module>
      1 # bug in tf.datasets or mnist
----> 2 ds_info.total_num_examples

AttributeError: 'DatasetInfo' object has no attribute 'total_num_examples'
```

**Expected behavior**
if I print ds_info I see:
```
tfds.core.DatasetInfo(
    name='mnist',
    version=3.0.0,
    description='The MNIST database of handwritten digits.',
    homepage='http://yann.lecun.com/exdb/mnist/',
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    total_num_examples=70000,
    splits={
        'test': 10000,
        'train': 60000,
    },
    supervised_keys=('image', 'label'),
    citation="""@article{lecun2010mnist,
      title={MNIST handwritten digit database},
      author={LeCun, Yann and Cortes, Corinna and Burges, CJ},
      journal={ATT Labs [Online]. Available: http://yann. lecun. com/exdb/mnist},
      volume={2},
      year={2010}
    }""",
    redistribution_info=,
)
```
I can access :
```
ds_info.name
s_info.features
ds_info.splits
...
```
so I was expecting to be able to access:
`ds_info.total_num_examples`

is there some implementation for only some elements ? I didn't find it in the documentation I found.

**Comment by Eshan-Agarwal** [comment]
@tarrade  I think this is because when you look on [mnist.py](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/mnist.py#L101) in `_info` function there is no information is provided regarding total_num_examples. Also see [this](https://www.tensorflow.org/datasets/api_docs/python/tfds/core/DatasetInfo). Maybe we can include it their.

**Comment by Conchylicultor** [comment]
This is expected. This should be `ds_info.splits.total_num_examples` or `ds_info.splits['train'].num_examples` if you want the number os splits in a single split.

That may be confusing with how the informations get printed, maybe we should remove it from the dataset info, or update `SplitDict.__repr__` to print something like:

```
tfds.core.DatasetInfo(
    splits=SplitDict({
        'train': ,
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }, total_num_examples=70000),
```

**Comment by tarrade** [comment]
@Conchylicultor Exact, thanks for these explanations. I got confused, as you said, by the info printed. All good.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  Thanks for clarification. Can I create PR as you said above for updating dataset_info.
