### ISSUE TITLE
 Object of type 'uint8' is not JSON serializable 

### ISSUE THREAD

**Issue by SoumyadeepJana** [tensorflow/datasets#166]
**What I need help with / What I was wondering**
tdfs.features.Image() returns object of dtype uint8 which runs prefectly fine when i test other datasets but in the code below,it displays the error,'Object of type 'uint8' is not JSON serializable'.I am stuck on this for 3 days now,please help

**What I've tried so far**
I have implemented mydataset.py class for a custom dataset
[Code Link](https://github.com/SoumyadeepJana/tfds/blob/master/fruits.py)

**Environment information**
(if applicable)
* Operating System: <Windows 10>
* Python version: <3.6>
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <Tensorflow and 1.13.1>

**Comment by SoumyadeepJana** [comment]
@cyfra @rsepassi It would be helpful if you can kindly look into this

**Comment by Conchylicultor** [comment]
Could you post the full stacktrace ? It's difficult to debug otherwise

**Comment by Conchylicultor** [comment]
Actually, the reason it is not working is that you are passing string to your label example but you haven't defined the labels anywhere:

```
yield {
    'image': ...
    'label': 'some_label',
}
```

The program has no way of knowing what `some_label` correspond too. You should first specify the labels you want to use:

self.info.features['label'].names = sorted(['some_label', ...])

**Comment by Conchylicultor** [comment]
From our end, I agree the error is confusing. We should try make the error message more specific.

**Comment by SoumyadeepJana** [comment]
@Conchylicultor  Thank you for pointing this out,this relieved me,I was stuck on this for quite some time.
