### ISSUE TITLE
I want to Song/Muusic databases

### ISSUE THREAD

**Issue by SueMagic** [tensorflow/datasets#167]

**Comment by captain-pool** [comment]
@SueMagic Provide the Dataset Description and the Dataset Link you would like to see in tensorflow_datasets
Take a Look at the Other Dataset Request issues to get an Idea.

**Comment by SoumyadeepJana** [comment]
@SueMagic  There are a lot of datasets of music, could you pls specify which one are you talking about?
Have a look at this request to get an idea of the template format
[Link](https://github.com/tensorflow/datasets/issues/138)

**Comment by cyfra** [comment]
closing - as there was no answer from @SueMagic.
Please reopen when you provide more information.

**Comment by SueMagic** [comment]
I want a song or music dataset that contains song name, song id, song tag, song genre, song attention, song comment volume, song play volume, user id, user favorite song id, etc. I used to be I want to get it through last.fm, but I won't call the API (already have a key). I will be grateful if I can get help!
