### ISSUE TITLE
tfds.as_numpy() returns zero value arrays for moving_mnist

### ISSUE THREAD

**Issue by Eshan-Agarwal** [tensorflow/datasets#1678]
**Short description**
tfds.as_numpy(), returns zero size array of image sequences for `moving_mnist` dataset, while returns correct for image dataset like `mnist ` dataset 

**Environment information**
* Operating System: <os> Windows 10 (64 bit)
* Python version: <version> 3.7
* `tensorflow-datasets`/`tfds-nightly` version: <package and version> 2.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version>

**Reproduction instructions**

For reproduction check this [colab](https://colab.research.google.com/drive/14gdEgdr-L0CIATt3G5jPy93kPR1a0BZ6)

**Link to logs**
Gives output array of zero sizes

**Expected behavior**
Output is not of zero valued. It have some pixel values as image sequence array

**Additional context**
refer [here](https://www.tensorflow.org/datasets/api_docs/python/tfds/as_numpy) for `as_numpy() `doc.

* Maybe it also not worked for other video datasets. I will check for others as video data have of big size.

**Comment by cyfra** [comment]
I've verified, and it seems to be working fine. The dataset has a lot of 0s, but there are non-zero values too.
Try plotting the result:

import matplotlib.pyplot as plt
for example in tfds.as_numpy(ds):
    #print(example)
    plt.imshow(np.squeeze(example['image_sequence'][0]))
    break

**Comment by Eshan-Agarwal** [comment]
@cyfra thanks for helping me ,  Yes its working fine, I should check the results after plotting because of lots of zeros. 
Closing this issue as it's works fine
