### ISSUE TITLE
robonet.py was not downloaded after pip install

### ISSUE THREAD

**Issue by Eshan-Agarwal** [tensorflow/datasets#1682]
**Short description**
I am trying to load `robonet ` dataset after `pip install tensorflow_datasets` (without importing it from cloning repo) but it says no dataset name robonet exist.

**Environment information**
* Operating System: <os> Windows 10
* Python version: <version> 3.7
* `tensorflow-datasets`/`tfds-nightly` version: <package and version>2.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version>2.0

**Reproduction instructions**

Please make sure you run below script after  `pip install tensorflow_datasets` (Not with cloned one)
```
import tensorflow_datasets as tfds
data, data_info = tfds.load("robonet", with_info= True)
print(data_info)
```

**Expected behavior**
Like other datasets `robonet `also loaded successfully using `tfds.load`

**Comment by ChanchalKumarMaji** [comment]
`robonet.py` was added to TFDS in Mar 5, 2020. So, it is not registered in the latest pip package (which was released in Feb, 2020). Instead clone the repo and install it.

**Comment by Eshan-Agarwal** [comment]
@ChanchalKumarMaji  Thanks for response

**Comment by Conchylicultor** [comment]
Or alternativelly `pip install tfds-nightly`
