### ISSUE TITLE
How to find the download link for specific datasets?

### ISSUE THREAD

**Issue by tinyxuyan** [tensorflow/datasets#1690]
The net is quite slow here, therefore, I can not download the datasets through tfds.load command. I want to manually add the datasets to the desired path. However, I can not find the download link for the specific datasets, such as the MNIST. 
Hoping someone can teach me how to find the links.
Thanks in advance.

**Comment by Eshan-Agarwal** [comment]
@tinyxuyan  please see [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/mnist.py#L32) for `mnist ` dataset, you can find links for downloading other dataset manually in `tensorflow_datasets/images(videos/text/audio)`

**Comment by Eshan-Agarwal** [comment]
like this is the [link](https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz) for train images for mnist dataset. And you can see home page for mnist data set also in the file I specified above see [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/mnist.py#L110)

**Comment by tinyxuyan** [comment]
@Eshan-Agarwal thank you very much
