### ISSUE TITLE
A feature to show relationship between datasets

### ISSUE THREAD

**Issue by vijayphoenix** [tensorflow/datasets#1691]
As the no. of datasets (~ 200) in tfds is growing, soon it will become harder to iterate over the list of datasets.
So, it would be great if we could add some feature to 
* show the relationship between datasets or 
* give a hint of what are other similar datasets.

**Comment by Conchylicultor** [comment]
Could you provide more context. What do you mean by "relationship between datasets". Is it not what our catalog is doing ? https://www.tensorflow.org/datasets/catalog/overview

**Comment by ChanchalKumarMaji** [comment]
> Could you provide more context. What do you mean by "relationship between datasets". Is it not what our catalog is doing ? https://www.tensorflow.org/datasets/catalog/overview

I think there should be a search button for tfds similar to tf-hub. Instead of linearly searching through all the datasets one can find them by other prefix search techniques.

**Comment by vijayphoenix** [comment]
> I think there should be a search button for tfds similar to tf-hub. Instead of linearly searching through all the datasets one can find them by other prefix search techniques.

That's a nice idea.

> Could you provide more context? What do you mean by "relationship between datasets". Is it not what our catalog is doing ? https://www.tensorflow.org/datasets/catalog/overview

I meant we could have some `Tags` for each dataset which will allow the user to filter the datasets.

For example,

![image](https://user-images.githubusercontent.com/41972768/77408184-56390980-6ddd-11ea-8f26-938c038283ff.png)

**Comment by Conchylicultor** [comment]
I think adding some tagging mechanism could make sense. Not sure when we'll have time to work on this though.

There are still some question though, like how to decide which tags apply. Should the tags be user-defined ? If so, there is a risk that tags won't be consistent across datasets. If tags are pre-defined, it doesn't seems different from our current catalog section.

**Comment by vijayphoenix** [comment]
Closing this as we filter out Image_classification datasets.
We could add more sections in the future.
