### ISSUE TITLE
waymo_open_dataset does not work

### ISSUE THREAD

**Issue by karolmajek** [tensorflow/datasets#1692]
**Short description**
I wanted to use this one: https://www.tensorflow.org/datasets/catalog/waymo_open_dataset
and get:

```
DatasetNotFoundError: Dataset waymo_open_dataset not found. Available datasets:

```

**Environment information**
- Colab
- TF2

**Reproduction instructions**
https://colab.research.google.com/drive/1BLw3KWI6NkE19ZnOnO3As6WGUbpTiJ2r

```
try:
  # Use the %tensorflow_version magic if in colab.
  %tensorflow_version 2.x
except Exception:
  pass

!pip uninstall tensorflow_datasets -y
!pip install git+https://github.com/tensorflow/datasets.git

import tensorflow as tf
import tensorflow_datasets as tfds

tfds.object_detection.__dir__()
ds = tfds.load('waymo_open_dataset')
```
Result:
```
['__name__',
 '__doc__',
 '__package__',
 '__loader__',
 '__spec__',
 '__path__',
 '__file__',
 '__cached__',
 '__builtins__',
 'coco',
 'Coco',
 'kitti',
 'Kitti',
 'open_images',
 'OpenImagesV4',
 'voc',
 'Voc',
 'wider_face',
 'WiderFace']
DatasetNotFoundError: Dataset waymo_open_dataset not found. Available datasets:
[...]
```

**Expected behavior**
load Waymo Open Datset

**Comment by karolmajek** [comment]
CC: @cyfra

**Comment by Eshan-Agarwal** [comment]
@karolmajek this is because, it is not registered in the latest pip package (which was released in Feb, 2020). Instead clone the repo and install it.

**Comment by Eshan-Agarwal** [comment]
Please see [this](https://github.com/tensorflow/datasets/commit/58dab7d211d259e39951eb6e83b9b50b7daa26b7) `waymo_open_dataset` was added just 4 days ago

**Comment by karolmajek** [comment]
I used:
```
!pip install git+https://github.com/tensorflow/datasets.git
```

**Comment by Eshan-Agarwal** [comment]
Because when you are importing tensorflow_datasets in colab it will import it from `'/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/` not from your clonned repo

**Comment by ChanchalKumarMaji** [comment]
@karolmajek try `!pip install tfds-nightly`.

**Comment by Eshan-Agarwal** [comment]
Or you can also uninstall existing `tensorflow_datasets ` because when you call `tfds.load` it try to load from pip package not cloned one see this [colab](https://colab.research.google.com/drive/17xkYF214YWbeqsQbUgujOgrQemwcXqwj)

**Comment by karolmajek** [comment]
I cloned repo - it worked.
Thanks!
Any idea how to set configs to get rid of error and download dataset?
Can't find any info about this

**Comment by cyfra** [comment]
Hey @karolmajek  - this dataset is still under active development (I should have made it more clear in the comments).

**Comment by Eshan-Agarwal** [comment]
@cyfra  thanks for letting us know, I  got `PermissionDeniedError` when passing builder configs manually

**Comment by Eshan-Agarwal** [comment]
@karolmajek  Please close this issue if you get your answers
