### ISSUE TITLE
[GSoC] download_and_prepare.py ignore the dataset version

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1707]
When explicitly setting the dataset version in the name, the `download_and_prepare --datasets=ds_name:version` script should try to generate the given version (and fail if the version cannot be generated).

Currently, it silently overwrite the version number:

Example:
```
python -m tensorflow_datasets.scripts.download_and_prepare \
  --datasets=download_and_prepare scientific_papers:1.1.0
```
In the logs, it seems it generates `1.1.1`:
```
Downloading and preparing dataset scientific_papers/arxiv/1.1.1 to /home/epot/tensorflow_datasets/scientific_papers/arxiv/1.1.1...
```

**Comment by vijayphoenix** [comment]
@Conchylicultor I think this bug occurs because `version` is set to `None`
https://github.com/tensorflow/datasets/blob/886532109ab2a9dbfdd124c91455330542569040/tensorflow_datasets/scripts/download_and_prepare.py#L178.

If you agree, I can make a PR for the same.

**Comment by Conchylicultor** [comment]
Thank you for looking into this. There might be a conflict between version set here and the one defined passed in: https://github.com/tensorflow/datasets/blob/886532109ab2a9dbfdd124c91455330542569040/tensorflow_datasets/scripts/download_and_prepare.py#L183
`tfds.builder('name:1.2.0')` should be valid.

If you send a PR, could you check before that this is working as expected on the `scientific_papers:1.1.0` dataset ?

**Comment by vijayphoenix** [comment]
@Conchylicultor Please review #1712 
Thank you

**Comment by Eshan-Agarwal** [comment]
it works fine for me it shows

> Downloading and preparing dataset scientific_papers/arxiv/1.1.0 (download: 4.20 GiB, generated: Unknown size, total: 4.20 GiB) to...

**Comment by vijayphoenix** [comment]
Do you run this?
```
python -m tensorflow_datasets.scripts.download_and_prepare \
  --datasets=scientific_papers:1.1.0
```
and it should fail for 
```
python -m tensorflow_datasets.scripts.download_and_prepare \
  --datasets=scientific_papers:1.1.5
```

**Comment by Eshan-Agarwal** [comment]
yes I run for `scientific_papers:1.1.0` and its shows me correct logs but for `scientific_papers:1.1.5` its not failing instead shows correct logs

**Comment by vijayphoenix** [comment]
It should fail for incorrect versions.

**Comment by Conchylicultor** [comment]
The issue is that when running:

```
python -m tensorflow_datasets.scripts.download_and_prepare \
  --datasets=scientific_papers:1.1.0
```
It generate `1.1.1` instead of `1.1.0`

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  yes I know and when I was running above download_and_prepare script locally with dataset version it shows me correct logs but it also shows correct logs if I enter wrong version

**Comment by vijayphoenix** [comment]
@Conchylicultor This issue can be reopened as it is not fixed at the HEAD

```
(base) ➜  datasets git:(master) python -m tensorflow_datasets.scripts.download_and_prepare \
  --datasets=scientific_papers:1.1.0
I0408 20:25:21.932773 140048821352256 download_and_prepare.py:197] Running download_and_prepare for dataset(s):
scientific_papers:1.1.0
I0408 20:25:21.933061 140048821352256 dataset_builder.py:772] No config specified, defaulting to first: scientific_papers/arxiv
I0408 20:25:21.965444 140048821352256 dataset_builder.py:203] Load pre-computed datasetinfo (eg: splits) from bucket.
I0408 20:25:24.144156 140048821352256 dataset_info.py:428] Loading info from GCS for scientific_papers/arxiv/1.1.0
I0408 20:25:26.220055 140048821352256 dataset_info.py:400] Field info.description from disk and from code do not match. Keeping the one from code.
I0408 20:25:26.220351 140048821352256 dataset_info.py:400] Field info.citation from disk and from code do not match. Keeping the one from code.
I0408 20:25:26.221463 140048821352256 dataset_builder.py:203] Load pre-computed datasetinfo (eg: splits) from bucket.
I0408 20:25:27.627210 140048821352256 dataset_info.py:428] Loading info from GCS for scientific_papers/arxiv/1.1.1
I0408 20:25:29.775501 140048821352256 dataset_info.py:400] Field info.description from disk and from code do not match. Keeping the one from code.
I0408 20:25:29.775851 140048821352256 dataset_info.py:400] Field info.citation from disk and from code do not match. Keeping the one from code.
I0408 20:25:29.776513 140048821352256 download_and_prepare.py:136] download_and_prepare for dataset scientific_papers/arxiv/1.1.1...
I0408 20:25:29.777143 140048821352256 dataset_builder.py:337] Generating dataset scientific_papers (/home/vijay/tensorflow_datasets/scientific_papers/arxiv/1.1.1)
Downloading and preparing dataset scientific_papers/arxiv/1.1.1 (download: 4.20 GiB, generated: 7.07 GiB, total: 11.27 GiB) to /home/vijay/tensorflow_datasets/scientific_papers/arxiv/1.1.1...
```

Made a PR #1734 to fix this.

**Comment by vijayphoenix** [comment]
`download_and_prepare` to be deprecated and replaced.
