### ISSUE TITLE
[GSoC] Split `tfds.image` in smaller sections

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1709]
As the number of dataset is growing, it becomes harder to find images dataset: https://www.tensorflow.org/datasets/catalog/overview#all_datasets

We should try to split the image section into multiple ones. I think we should move all images datasets which have a `ClassLabel` into a new `image_classification` section.

As example, this was already done once for the object_detection section in https://github.com/tensorflow/datasets/commit/bc2d5c71351a51fb330d5d933dfbe12838610a65 and https://github.com/tensorflow/datasets/commit/9b948c44bccb9184c81ac4395a0aaab2257344a1

**Comment by vijayphoenix** [comment]
@Conchylicultor I think some more datasets like `lfw` should be a part of `image_supervised` section, right?

**Comment by Conchylicultor** [comment]
Yes, you're right `lfw` should be supervised.

For `supervised_keys`, I'll say it's depend if the second key is a label or not. For instance if `supervised_keys=(image1, image2)`, then it shouldn't be added in the new section.

You're right that this might be confusing. I think `image_supervised` could be renamed `image_classification` instead.

**Comment by vijayphoenix** [comment]
This issue can be closed as https://github.com/tensorflow/datasets/pull/1717 is merged internally
