### ISSUE TITLE
[GSoC] Update checksums for missing urls

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1716]
Thanks to https://github.com/tensorflow/datasets/commit/5a8ee376c39a885c9132cdd22a8b2669febe6366 (https://github.com/tensorflow/datasets/issues/1397), we now check that all urls from `dl_manager.download()` are correctly registered.

However, some of the urls are not registered for some of our datasets. We should generate the checksums for the missing urls by running `download_and_prepare` script with `--register_checksums` as per https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally.

Note: The dataset don't need to be fully generated, so you can modify the dataset implementation to only download the files.

The datasets to updates are the ones with `SKIP_CHECKSUMS = True`.
To know which urls are missing, just run the tests and the error message should show the missing urls.

**Comment by Eshan-Agarwal** [comment]
wmt_test.py also have skip_checksum = True because its checksum is defined individually like in wmt_19 etc, so no need to cahnge ?

**Comment by Eshan-Agarwal** [comment]
Also it shows `skip_checksum = True` for `wikipedia_test.py ` but wikipedia have correct checksum file
[see](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/url_checksums/wikipedia.txt)

**Comment by Conchylicultor** [comment]
@Eshan-Agarwal 

* wmt shouldn't be updated.
* If you run the wikipedia tests, there is one missing url.

**Comment by Eshan-Agarwal** [comment]
thanks for your response, we have to update checksums for existing wikipedia.txt or create new one ?

**Comment by Conchylicultor** [comment]
> thanks for your response, we have to update checksums for existing wikipedia.txt or create new one ?

Update the existing one. This is the only way to make tests pass.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  Thanks for reply, please have a look on PR #1718 I think checksum should be update in sun397 ?

**Comment by Conchylicultor** [comment]
@Eshan-Agarwal Nice catch, I'll update this internally when merging the dataset.

**Comment by Eshan-Agarwal** [comment]
Thanks for looking into this

**Comment by vijayphoenix** [comment]
The tests fail in sun_test.txt fail because the name of url_checksums doesn't match. Updating url_checksums in sun397.txt doesn't work for me.

**Comment by vijayphoenix** [comment]
@Conchylicultor Please see the code [here](https://colab.research.google.com/drive/1kdqmjjp-Omg3GfKO4FthubegCnJUrNqf)

I am unable to make a `url_checksum file` with `--register_checksums=True`.
Is this a bug?

**Comment by Eshan-Agarwal** [comment]
@vijayphoenix  why are you removing `mnist.txt` using `!rm -rf ./tensorflow_datasets/url_checksums/mnist.txt`

**Comment by vijayphoenix** [comment]
Because I want to create it again using `register_checksums` flag

**Comment by Eshan-Agarwal** [comment]
I think` register_checksums` flag not create directory its only update existing one if it not find checksums files. If I am wrong please correct me ?

**Comment by Eshan-Agarwal** [comment]
If i remove mnist.txt contents and run download_and_prepare using register_checksums = True it raiese this error : 

> Traceback (most recent call last):
  File "/content/datasets/tensorflow_datasets/testing/test_utils.py", line 199, in decorated
    f(self, *args, **kwargs)
  File "/content/datasets/tensorflow_datasets/testing/dataset_builder_testing.py", line 280, in test_download_and_prepare_as_dataset
    self._test_checksums()
  File "/content/datasets/tensorflow_datasets/testing/dataset_builder_testing.py", line 303, in _test_checksums
    "\n{}".format(filepath, err_msg)
  File "/usr/local/lib/python3.6/dist-packages/absl/testing/absltest.py", line 834, in assertEmpty
    self.fail('{!r} has length of {}.'.format(container, len(container)), msg)
  File "/usr/local/lib/python3.6/dist-packages/absl/testing/absltest.py", line 1704, in fail
    return super(TestCase, self).fail(self._formatMessage(prefix, msg))
AssertionError: {'https://storage.googleapis.com/cvdf-datasets/mnist/train-labels-idx1-ubyte.gz', 'https://storage.googleapis.com/cvdf-datasets/mnist/t10k-labels-idx1-ubyte.gz', 'https://storage.googleapis.com/cvdf-datasets/mnist/train-images-idx3-ubyte.gz', 'https://storage.googleapis.com/cvdf-datasets/mnist/t10k-images-idx3-ubyte.gz'} has length of 4. : Some urls checksums are missing at: /content/datasets/tensorflow_datasets/url_checksums/mnist.txt Did you forgot to record checksums with `--register_checksums` ? See instructions at: https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally
If you are developping outside TFDS and want to opt-out, please add `SKIP_CHECKSUMS = True` to the `DatasetBuilderTestCase`

I think there is a bug but not with register_checksums

**Comment by vijayphoenix** [comment]
No, it should work fine for both deleted and modified files

**Comment by vijayphoenix** [comment]
@Conchylicultor some parts of the issue are not solved.
Also, please see the code [here](https://colab.research.google.com/drive/1kdqmjjp-Omg3GfKO4FthubegCnJUrNqf)
I am unable to modify a `url_checksum` file with `--register_checksums=True`.
Is this a bug?

**Comment by Conchylicultor** [comment]
@vijayphoenix why are you trying to register checksums for mnist ? Mnsit don't have `SKIP_CHECKSUMS = True` no ?

**Comment by vijayphoenix** [comment]
@Conchylicultor I was just trying to show that `url_checksums` file does not update with `--register_checksums=True` in case of datasets like MNIST and Wikipedia on Colab as well as my local workstation.
But `url_checksums` file gets updated with `--register_checksums=True` for datasets like `crema_d` on both colab (updated [link](https://colab.research.google.com/drive/1kdqmjjp-Omg3GfKO4FthubegCnJUrNqf)) and my local workstation.

**Comment by Conchylicultor** [comment]
@vijayphoenix 
Oh, I see what you mean. My bad. The reason is that wikipedia and mnist are directly loaded from our GCS bucket: https://pantheon.corp.google.com/storage/browser/tfds-data/datasets/
So the original files are not downloaded.

You can pass `tfds.download.DownloadConfig(try_download_gcs=False)` to `tfds.load` to disable auto-loading

**Comment by Conchylicultor** [comment]
It seems `c4` checksums are still missing.

**Comment by Conchylicultor** [comment]
Closing this as all datasets seems to have been updated.
