### ISSUE TITLE
dataset_builder_test fails

### ISSUE THREAD

**Issue by Eshan-Agarwal** [tensorflow/datasets#1724]
**Short description**
Running `!python ./tensorflow_datasets/core/dataset_builder_test.py` fails (After uninstalling pip package of tfds). otherwise tests fails

**Environment information**
* Operating System: <os> Colab
* Python version: <version>
* `tensorflow-datasets`/`tfds-nightly` version: <package and version>
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version> 2.0.0

**Reproduction instructions**
See this [colab ](https://colab.research.google.com/drive/1y31DXfhGZbWE0_EXIJLpoDNfFgMd173Z)notebook

**Link to logs**
Shows 

> Traceback (most recent call last):
  File "./tensorflow_datasets/core/dataset_builder_test.py", line 29, in <module>
    from tensorflow_datasets import testing
ModuleNotFoundError: No module named 'tensorflow_datasets'

**Expected behavior**
It should run fine and all tests are passed sucessfully.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  please review this PR #1725
Thank you

**Comment by vijayphoenix** [comment]
Run `pip install -e .` before running the tests.

**Comment by preeti13456** [comment]
Done 
https://colab.research.google.com/drive/1d06UQYHoV5yaTGvNJaRsHYjEQKZNCcoX#scrollTo=-tHNmifLbROF

**Comment by preeti13456** [comment]
Done
https://colab.research.google.com/drive/1d06UQYHoV5yaTGvNJaRsHYjEQKZNCcoX

**Comment by Eshan-Agarwal** [comment]
thanks for suggestions I forgot about developer mode and its work fine
