### ISSUE TITLE
Load ImageNet from processed tfrecord files via tfds.load.

### ISSUE THREAD

**Issue by Gsunshine** [tensorflow/datasets#1739]
**What I've tried so far**
Since ImageNet changed its rule of downloading the dataset, I could not directly access the dataset via tfds.load. I followed [URL](https://cloud.google.com/tpu/docs/imagenet-setup) to transform local ImageNet 2012 dataset to tfrecord files. However I find it seems to be incompatible with current tfds API, especially tfds.load.

I cannot load those tfrecord files through tfds.load. And it failed to continue even I resorted to tf.data.TFRecordDataset because I use the framework of tfgan [data_provider.py](https://github.com/tensorflow/gan/blob/master/tensorflow_gan/examples/self_attention_estimator/data_provider.py) and it presumed some features from the return type of tfds.load.

I also tried to apply manual_dir through download_and_prepare_kwargs={'download_config':tfds.download.DownloadConfig(manual_dir=flags.FLAGS.manual_dir)} for tfds.load but failed again since we had no original tar files except extrated images only.

**What I need help with / What I was wondering**
I am not sure how to meet the demand. It is more prefered to load the dataset from extracted images or processed tfrecord files via tfds.load since tfgan is well tested thus a re-implementation of data provider may change the training behavior.

Thx for help!

**Comment by Eshan-Agarwal** [comment]
You have to manually download `imagenet2012` dataset by register it [here ](http://www.image-net.org/download-images).

**Comment by Gsunshine** [comment]
> You have to manually download `imagenet2012` dataset by register it [here ](http://www.image-net.org/download-images). You cannot load directly using `tfds.load()`

I have a downloaded one. However there are no tar files left except extracted images. It seems incompatible to set the manual_dir to it via download_and_prepare_kwargs={'download_config':tfds.download.DownloadConfig(manual_dir=flags.FLAGS.manual_dir)}

**Comment by Gsunshine** [comment]
Thanks for your suggestions! 

However, google tpu team provides a series data loader & protocal for ImageNet 2012. See [tpu inception v3](https://github.com/tensorflow/tpu/blob/master/models/experimental/inception/inception_v3.py) and [imagenet_to_gcs.py](https://github.com/tensorflow/tpu/tree/master/tools/datasets). Should tfds support their protocal as a standard method to load ImageNet 2012?

Note: their methods have been tested on tpu for ImageNet 2012. tfds's ImageNet 2012 is now nearly broken.

**Comment by Conchylicultor** [comment]
@Gsunshine did you tried the link you pasted ? The link seems broken http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_val.tar

**Comment by Conchylicultor** [comment]
Closing this for know. Please re-open if you find direct link to download imagenet.

**Comment by Gsunshine** [comment]
@Conchylicultor I used a downloaded ImageNet cached locally. 

Though ImageNet changed its protocal to download the dataset, I think kwargs like user_name=None and password=None could be added to tfds.load for automatically download the dataset as what [imagenet_to_gcs.py](https://github.com/tensorflow/tpu/tree/master/tools/datasets) did.

An interface to coordinate with the tfrecord files from google tpu team's script  [imagenet_to_gcs.py](https://github.com/tensorflow/tpu/tree/master/tools/datasets) is also necessary.

**Comment by Conchylicultor** [comment]
Did you tried to run the `imagenet_to_gcs.py` script ? It tried to download  http://www.image-net.org/challenges/LSVRC/2012/nnoupb/ILSVRC2012_img_val.tar which is not a valid url.

https://github.com/tensorflow/tpu/blob/master/tools/datasets/imagenet_to_gcs.py#L78

**Comment by Gsunshine** [comment]
@Conchylicultor I used a locally cache ImageNet2012 that has been extracted as images. 

My account is still under check by ImageNet thus I do not know if it could really download ImageNet2012. But this scripts could handle normally extracted image files and transform images to  tfrecord. 

I think at least tfds should support an API to automatically process local cached extracted images without tar files on par with tpu team's [pipeline](https://github.com/tensorflow/tpu/blob/master/models/experimental/inception/inception_v3.py). It is better to add kwargs in tfds.load than suggest a user-defined tf.data.Dataset since tfds.load is widely applied in large projects like tfgan and a officially supported API can guarantee consistent behaviors in down stream tasks.
