### ISSUE TITLE
[GSoC] Update Groove and Nsynth to use tfds.features.Audio

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1741]
It seems that groove dataset is currently using `tfds.features.Tensor` to store the audio. For consistency with other datasets, we should use `tfds.features.Audio` instead.

https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/audio/groove.py#L135

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  woking on it,

**Comment by vijayphoenix** [comment]
We can update `nsynth` dataset also.

**Comment by Conchylicultor** [comment]
@vijayphoenix you're right. Thank you for catching this

**Comment by Conchylicultor** [comment]
Closing this as this has been fixed internally
