### ISSUE TITLE
[data request] LibriSpeech

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/datasets#175]
* Name of dataset: LibriSpeech
* URL of dataset: http://www.openslr.org/12/
* License of dataset: CC BY 4.0
* Short description of dataset and use case(s): 
LibriSpeech is a corpus of approximately 1000 hours of 16kHz read English speech, prepared by Vassil Panayotov with the assistance of Daniel Povey. The data is derived from read audiobooks from the LibriVox project, and has been carefully segmented and aligned.

**Comment by KumarArindam** [comment]
I am interested in working on this @zh794390558 
Please provide me the details of the work that needs to be done here.

**Comment by captain-pool** [comment]
It's already there. 
[https://github.com/tensorflow/datasets/tree/master/tensorflow_datasets/audio/librispeech.py](https://github.com/tensorflow/datasets/tree/master/tensorflow_datasets/audio/librispeech.py)

**Comment by KumarArindam** [comment]
@captain-pool Thanks for pointing it out.

**Comment by KumarArindam** [comment]
@captain-pool Thanks for pointing it out and saving a lot of unnecessary work :)
