### ISSUE TITLE
[GSOC] Checksum mismatch for Pix3D

### ISSUE THREAD

**Issue by aradhyamathur** [tensorflow/datasets#1753]
While implementing the dataset for Pix3D I run into error due to a checksum mismatch from the DownloadManager. The error is as follows -

`~/anaconda3/envs/gsoc/lib/python3.7/site-packages/tensorflow_datasets-2.1.0-py3.7.egg/tensorflow_datasets/core/download/download_manager.py in callback(val)
    260       checksum, dl_size = val
    261       return self._handle_download_result(
--> 262           resource, download_dir_path, checksum, dl_size)
    263     return self._downloader.download(url, download_dir_path).then(callback)
    264 

~/anaconda3/envs/gsoc/lib/python3.7/site-packages/tensorflow_datasets-2.1.0-py3.7.egg/tensorflow_datasets/core/download/download_manager.py in _handle_download_result(self, resource, tmp_dir_path, sha256, dl_size)
    215       self._record_sizes_checksums()
    216     elif (dl_size, sha256) != self._sizes_checksums.get(resource.url, None):
--> 217       raise NonMatchingChecksumError(resource.url, tmp_path)
    218     download_path = self._get_final_dl_path(resource.url, sha256)
    219     resource_lib.write_info_file(resource, download_path, self._dataset_name,

NonMatchingChecksumError: Artifact http://pix3d.csail.mit.edu/data/pix3d.zip, downloaded to ./pix3d.csail.mit.edu_pix3d4gh-bf6GMM2oHrBcmQyos_K1PupfuBITgTic9qdZ2Xc.zip.tmp.3b8459f449b34fc68ed246e8c371495f/pix3d.zip, has wrong checksum.`

* Operating System: Ubuntu 18.04
* Python version: 3.7.6
* `tensorflow-datasets`/`tfds-nightly` version: 2.1.0

Could you please guide how this error could be resolved ?

**Comment by Eshan-Agarwal** [comment]
@aradhyamathur  are you following instructions provided [here ](https://www.tensorflow.org/datasets/add_dataset) properly for implementing dataset ?

Please provide some code

**Comment by vijayphoenix** [comment]
Use `--register_checksum=True` while preparing a dataset for the first time

**Comment by shikhar2707** [comment]
python -m tensorflow_datasets.scripts.download_and_prepare --registrer_checksums=True --datasets='dataset_name'

This command line too will work!

**Comment by Eshan-Agarwal** [comment]
Yes this is exactly you have to pass when implementing new dataset

**Comment by aradhyamathur** [comment]
Thanks

**Comment by Eshan-Agarwal** [comment]
@aradhyamathur  If it solves your issue please close this issue
