### ISSUE TITLE
Error in implementing some datasets

### ISSUE THREAD

**Issue by shikhar2707** [tensorflow/datasets#1757]
Upon implementing some datasets such as Pix3D for the first time, one ends up with an error showing-
`NonMatchingChecksumError: Artifact http://pix3d.csail.mit.edu/data/pix3d.zip, downloaded to ./pix3d.csail.mit.edu_pix3d4gh-bf6GMM2oHrBcmQyos_K1PupfuBITgTic9qdZ2Xc.zip.tmp.3b8459f449b34fc68ed246e8c371495f/pix3d.zip, has wrong checksum.`

Hence, I'll be sending a PR correcting the issue. Check if its fine.

**Comment by Eshan-Agarwal** [comment]
I think adding these comments here is not necessary, as this is example for how to use tfds to load data not implement it. Also [here](https://github.com/shikhar2707/datasets/blob/984c8b233a4550324ff7941ed8bb149e1984692b/README.md#want-a-certain-dataset) it clearly mention these things

**Comment by Rubix982** [comment]
There doesn't really seem to be a reason for this issue. As @Eshan-Agarwal mentioned, following that link leads me to [add_dataset.md](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md), which is basically a whole README.md concerned with addressing issues like this, and yes, `--register_checksums` is mentioned there. 
You can however write on [add_dataset.md](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md) about this specific issue, and about `why` it's even there in the first place to give a better insight. It would help later on rather then just a person trying random solutions to solve that problem.

**Comment by vijayphoenix** [comment]
Can be closed
