### ISSUE TITLE
Improve the TFDS Getting Started Documentation

### ISSUE THREAD

**Issue by ashutosh1919** [tensorflow/datasets#1762]
Duplicate of issue [#37330](https://github.com/tensorflow/tensorflow/issues/37330) from tf repo.
As per @lamberta's [#37330 comment](https://github.com/tensorflow/tensorflow/issues/37330#issuecomment-597806716), this issue is opened so that  issue on tf repo can be closed and this will be monitored. 
PR #1633  will fix this issue.

**Comment by ashutosh1919** [comment]
@Conchylicultor , please review PR #1633 .

**Comment by vijayphoenix** [comment]
Documentation Updated
