### ISSUE TITLE
Wrong sentence formation in colab notebook

### ISSUE THREAD

**Issue by shikhar2707** [tensorflow/datasets#1765]
The line underneath tfds.load() says
tfds.load() is a convenient method that is, the simplest way to build and load a `tf.data.Dataset.`
Doesnt seem a correctly formed sentence.
I have sent a PR regarding this. @Conchylicultor please check if it is okay.

**Comment by Conchylicultor** [comment]
Thank you for your contribution, but I think the current phrasing is fine, and seems too much of a minor change to really matter. We're in the process of rewriting the doc anyway.
Also, typo are not bugs.
