### ISSUE TITLE
[GSoc Dataset Request] <COVID-19 Complete Dataset>

### ISSUE THREAD

**Issue by shikhar2707** [tensorflow/datasets#1771]
* Name of dataset: COVID-19 Complete Dataset
* URL of dataset: <https://www.kaggle.com/imdevskp/corona-virus-report>
* License of dataset: None
* Short description of dataset and use case(s): <A new coronavirus designated 2019-nCoV was first identified in Wuhan, the capital of China's Hubei province
People developed pneumonia without a clear cause and for which existing vaccines or treatments were not effective.
The virus has shown evidence of human-to-human transmission
Transmission rate (rate of infection) appeared to escalate in mid-January 2020>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by pawarharshit** [comment]
Please assign this to me. 
I want to work on it

**Comment by vijayphoenix** [comment]
@pawarharshit Thank you for looking into this

**Comment by pawarharshit** [comment]
thanks for assigning it to me

**Comment by pawarharshit** [comment]
this is my first time contribution. so i need help .
when i clone the repository  i getting the warning of check out failed and also i not get the folders (text ,translate,url_checksum,video) and some files  in tensorflow_dataset directory

**Comment by pawarharshit** [comment]
and i run command for generating file of my_dataset it generate my_dataset.py file in my installed tensorflow_dataset not in git repository

**Comment by pawarharshit** [comment]
![Capture](https://user-images.githubusercontent.com/49332515/85303071-a6506680-b4c7-11ea-86d6-7b79cd5c343b.PNG)

**Comment by vijayphoenix** [comment]
This is because the PATH Length is restricted on windows `Filename too long`.
You will have to remove this constraint.

**Comment by pawarharshit** [comment]
shikhar2707 this dataset contains following  5 files 
1)country_wise_latest.csv
2) covid_19_clean_complete.csv
3) day_wise.csv
4) full_grouped.csv
5)usa_county_wise.csv
6) worldometer_data.csv

which you want to add in tfds please tell me the feature and target name for task
