### ISSUE TITLE
Error while extracting long named datasets.

### ISSUE THREAD

**Issue by Eshan-Agarwal** [tensorflow/datasets#1783]
**Environment information**
* Operating System: <os> Windows 10
* Python version: <version>
* `tensorflow-datasets`/`tfds-nightly` version: <package and version> 2.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version> 2.1.0

**Short description**
Got extract error when try to extract `plant_village` dataset using `tfds.load()`. This error occurs because path name of extraction file is very long for `plant_village `dataset. `ZIP.data.mend.com_data_tywb_1_file_127d-7c63-4rDQyRTmE0CqGGXmH53WlQp0NWefMfDW89aj1A0m5D_A.zip.incomplete_ee6bd33c39f64df4a87a438bdda8bc29/Plant_leave_diseases_dataset_without_augmentation`. due to which it fails to make new directory inside this directory, I tried manually to make folder but it fails and give error `file name too long` .

**Reproduction instructions**

```
import tensorflow_datasets as tfds
ds,ds_info = tfds.load("plant_village", with_info = True)
print(ds_info)
```

**logs**
ExtractError: Error while extracting C:\Users\eshan\tensorflow_datasets\downloads\data.mend.com_data_tywb_1_file_127d-7c63-4rDQyRTmE0CqGGXmH53WlQp0NWefMfDW89aj1A0m5D_A.zip to C:\Users\eshan\tensorflow_datasets\downloads\extracted\ZIP.data.mend.com_data_tywb_1_file_127d-7c63-4rDQyRTmE0CqGGXmH53WlQp0NWefMfDW89aj1A0m5D_A.zip (file: Plant_leave_diseases_dataset_without_augmentation\Apple___Apple_scab\image (1).JPG) : Failed to create a directory: C:\Users\eshan\tensorflow_datasets\downloads\extracted\ZIP.data.mend.com_data_tywb_1_file_127d-7c63-4rDQyRTmE0CqGGXmH53WlQp0NWefMfDW89aj1A0m5D_A.zip.incomplete_ee6bd33c39f64df4a87a438bdda8bc29\Plant_leave_diseases_dataset_without_augmentation/Apple___Apple_scab; No such file or directory

**Expected behavior**
There is no problem in extraction of dataset.

**Additional context**
This works fine in colab as error occur only when user forgot to disable path length limit in python.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  is we have to give some warning or exception if user forgot to disable path length limit in python.

**Comment by vijayphoenix** [comment]
@Eshan-Agarwal does it work fine after disabling path length limit on your local machine?

**Comment by csmcallister** [comment]
Also receiving this error on Windows 10 with `coco_data = tfds.load('coco/2017')`.  A more descriptive error message pointing to the path length limit issues on Windows (e.g. the[ python docs](https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation)) would be helpful.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  I can send PR for fix this but is code solution (if possible) be better than error message ?

**Comment by Eshan-Agarwal** [comment]
> Also receiving this error on Windows 10 with `coco_data = tfds.load('coco/2017')`. A more descriptive error message pointing to the path length limit issues on Windows (e.g. the[ python docs](https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation)) would be helpful.

@csmcallister  Thanks for reporting will fix this soon as suggested by you or maybe some code solution, if you want to fix you can ?

**Comment by maxiuw** [comment]
For me the issue was specifying the folder which does not exists, i.e. 
dataset = tfds.load('cats_vs_dogs', split=tfds.Split.TRAIN, data_dir='data/') # didn't work
dataset = tfds.load('cats_vs_dogs', split=tfds.Split.TRAIN) # works with some warning about certificate 
Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
