### ISSUE TITLE
[data request] Yesno

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/datasets#179]
* Name of dataset:  Yesno 
* URL of dataset: http://www.openslr.org/1/
* License of dataset:  No formal license but free to use for any purpose.
* Short description of dataset and use case(s):

This dataset was created for the Kaldi project (see kaldi.sf.net), by a contributor who prefers to remain anonymous. The main point of the dataset is to provide an easy and fast way to test out the Kaldi scripts for free.

The archive "waves_yesno.tar.gz" contains 60 .wav files, sampled at 8 kHz. All were recorded by the same male speaker, in Hebrew. In each file, the individual says 8 words; each word is either the Hebrew for "yes" or "no", so each file is a random sequence of 8 yes-es or noes. There is no separate transcription provided; the sequence is encoded in the filename, with 1 for yes and 0 for no, for instance:

# tar -xvzf waves_yesno.tar.gz
waves_yesno/1_0_1_1_1_0_1_0.wav
waves_yesno/0_1_1_0_0_1_1_0.wav
...

**Comment by SoumyadeepJana** [comment]
Would like to work on this

**Comment by mandroid6** [comment]
@rsepassi @cyfra I would like to work on this

**Comment by mandroid6** [comment]
@rsepassi @cyfra  I have created a script to save the ``.wav`` file names as text features for individual audio file; but which ``tfds.features.FeatureConnector`` should be used for such a dataset?

**Comment by SoumyadeepJana** [comment]
@mandroid6 I was about to start working on this but glad that you have already started working,please go ahead and make a PR.  👍

**Comment by SoumyadeepJana** [comment]
@mandroid6 Use tfds.features.Audio as the FeatureConnector for .wav files,text features won't work in this case.
In case you want to read more about it 
[Audio FeatureConnector](https://github.com/tensorflow/datasets/blob/master/docs/api_docs/python/tfds/features/Audio.md)

**Comment by mandroid6** [comment]
Yup, already using Audio feature connector for the audio clips; but the
file names are values of the order in which YES and NO is being spoken in
Hebrew

**Comment by SoumyadeepJana** [comment]
@mandroid6 You might use tfds.features.Text

**Comment by Conchylicultor** [comment]
The way I would do it would be something like:

```python
{
    'audio': tfds.features.Audio(),
    'labels': tfds.features.Sequence(tfds.features.ClassLabel(names=['no', 'yes'], len=8)),
}
```
This way, it will return two tensors, the 'labels' should be a tf.Tensor(shape=(8,), dtype=tf.int64)

**Comment by mandroid6** [comment]
**YesNo Class**
``
class YesNo(tfds.core.GeneratorBasedBuilder):
	"""
	Sixty recordings of one individual saying yes or no in Hebrew; each recording is eight words long.
	"""
	
	_DESCRIPTION ='contains 60 .wav files, sampled at 8 kHz. \
	All were recorded by the same male speaker, in Hebrew. \
	In each file, the individual says 8 words; \
	each word is either the Hebrew for "yes" or "no", \
	so each file is a random sequence of 8 yes-es or noes'

	VERSION = tfds.core.Version('0.1.0')
	
	def _info(self):
		return tfds.core.DatasetInfo(
			builder=self,
			description=_DESCRIPTION,
			features=tfds.features.FeaturesDict({
				"audio":tfds.features.Audio(),
				'labels': tfds.features.Sequence(tfds.features.ClassLabel(names=['no', 'yes'], len=8))
			}),
			urls=["http://www.openslr.org/1/"]
		)
``

**Split generator**
``
def _split_generators(self, dl_manager):
		dl_url = _DL_URL
		dl_paths = dl_manager.download_and_extract(dl_urls)
		
		#dl_paths[create_and_return_transcript_file
		#self.info.features["labels"] = labels

		return [
			tfds.core.SplitGenerator(
				name=tfds.Split.TRAIN,
				num_shards=10,
				gen_kwargs={
					"dirs": dl_paths[tfds.Split.TRAIN],
				}),
			tfds.core.SplitGenerator(
				name=tfds.Split.VALIDATION,
				num_shards=10,
				gen_kwargs={
					"dirs": dl_paths[tfds.Split.VALIDATION],
				}),
			tfds.core.SplitGenerator(
				name=tfds.Split.TEST,
				num_shards=10,
				gen_kwargs={
					"dirs": dl_paths[tfds.Split.TEST],
				}),
		]
``

**Generate examples**
``
def _generate_examples(self, directory):
		#transcript_file = create_and_return_transcript_file(directory):
		for example in _walk_yesno_dir(directory):
			yeild {
				"audio" = example.audio_file,
				"labels"= example.transcript
			}
``

**Helper Functions**
``
YesNoExample = collections.namedtuple(
    "_YesNoExample",["audio_file", "labels"])

	def _walk_yesno_dir(directory):
		"""Walk a YesNo directory and yield examples."""
		directory = os.path.join(directory, "YesNo")
		for path, _, files in tf.io.gfile.walk(directory):
			if not files:
				continue

			transcript_file = [f for f in files if f.endswith(".txt")]
			if not transcript_file:
				continue
			assert len(transcript_file) == 1
			transcript_file, = transcript_file
			transcripts = {}
			with tf.io.gfile.GFile(os.path.join(path, transcript_file)) as f:
				for line in f:
					line = line.strip()
					key, transcript = line.split(" ", 1)
					transcripts[key] = transcript
			audio_files = [f for f in files if  f.endswith(".wav")]
			for audio_file in audio_files:
				assert audio_file.endswith(".wav")
				key = audio_file[:-len(".wav")]
				transcript = transcripts[key]
				yield YesNoExample(
					audio_file=os.path.join(path, audio_file),
					labels=transcript)

``
``
	def create_and_return_transcript_file(directory):
		labels = []
		for filename in os.listdir(directory):
			if filename.endswith('.wav'):
				label =filename.split('.')[0].split('_')
				labels.append(label)

		output_file = open('transcript.txt', 'w')
		for label in labels:
			for ch in label:
				output_file.write(str(ch))
				output_file.write(' ')
			output_file.write('\n')
		output_file.close()

		return os.path.join(directory,'transcript.txt')
``
@Conchylicultor @rsepassi  can you tell me if I am taking the correct approach? It's still not clear how the file-names will be included as the audio file transcripts/labels.

**Comment by Conchylicultor** [comment]
@mandroid6 To include the filename (which is a good idea), you can just add an additional field:

```
features=tfds.features.FeaturesDict({
    'audio':tfds.features.Audio(),
    'labels': tfds.features.Sequence(tfds.features.ClassLabel(names=['no', 'yes'], len=8))
    'audio/filename': tfds.features.Text(),
}),
```
And then yield the relative filename.wav file. Otherwise, this looks good.

**Comment by Conchylicultor** [comment]
But are you sure the dataset is defining train, test, validation ? It seems that only a single split is provided, in which case you should only keep tfds.Split.TRAIN

**Comment by Conchylicultor** [comment]
Closing this as this dataset was been added in tfds-nightly.
