### ISSUE TITLE
[data request] TED-LIUM

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/datasets#180]
* Name of dataset: TED-LIUM
* URL of dataset: http://www.openslr.org/7/
* License of dataset: Creative Commons BY-NC-ND 3.0 (attribution/non-commercial/no-derivatives).
* Short description of dataset and use case(s): <description>

The TED-LIUM corpus (mirrored here) is English-language TED talks, with transcriptions, sampled at 16kHz. It contains about 118 hours of speech.

**Comment by ChanchalKumarMaji** [comment]
This dataset looks interesting. @cyfra please assign this issue to me.

**Comment by SoumyadeepJana** [comment]
I would like to work on this,@cyfra @rsepassi @Conchylicultor  Please assign me this

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as tedlium is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/audio/tedlium.py and https://www.tensorflow.org/datasets/catalog/tedlium for more info.
Thank you for your contribution
