### ISSUE TITLE
[data request] VoxCeleb

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/datasets#181]
* Name of dataset: VoxCeleb
* URL of dataset: http://www.openslr.org/49/
* License of dataset: Not copyrighted
* Short description of dataset and use case(s): 

This resource contains files for the VoxCeleb corpora that are helpful in speaker recognition recipes.

**Comment by SoumyadeepJana** [comment]
@rsepassi @cyfra @dynamicwebpaige  I want to work on this dataset,kindly assign it to me.

**Comment by Conchylicultor** [comment]
@SoumyadeepJana Thanks for looking into this. I just assigned you

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as VoxCeleb is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/audio/voxceleb.py and https://www.tensorflow.org/datasets/catalog/voxceleb for more info.
Thank you for your contribution
