### ISSUE TITLE
data.map fails when as_supervised=True in tfds.load

### ISSUE THREAD

**Issue by dandawg** [tensorflow/datasets#1812]
**Short description**
After loading data using `as_supervised=True`, I get the following error when using a lambda function inside of `map`:
```
TypeError: in converted code:
    TypeError: <lambda>() takes 1 positional argument but 2 were given
```
The error vanishes if `as_supervised=False`

**Environment information**
* Operating System: Linux Mint 18.1 Cinnamon 64-bit
* Python version: 2.1.0
* `tensorflow-datasets`/`tfds-nightly` version: 2.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: NA

**Reproduction instructions**

```
data = tfds.load('iris', as_supervised=True, split='train')
data = data.map(lambda ds: ds)

# Returned error
Traceback (most recent call last):
...
TypeError: in converted code:
    TypeError: <lambda>() takes 1 positional argument but 2 were given

```
As I mentioned, if I take out `as_supervised=True`, the map function runs just fine. I believe this is a bug because the `as_supervised` flag should just change the format of the Tensor elements, but not whether the `map` function works or not.

**Comment by vijayphoenix** [comment]
Try something like
```
data = data.map(lambda a, b: (a, b))
```

**Comment by Conchylicultor** [comment]
@vijayphoenix is correct. This is not an issue with TFDS.
