### ISSUE TITLE
download_and_prepare for c4 dataset fails on DownloadManager error

### ISSUE THREAD

**Issue by shepsels** [tensorflow/datasets#1816]
**Short description**
When trying to generate c4 dataset on google cloud dataflow, download manager fails on ''DownloadManager' object has no attribute '_downloader' [while running 'Map(download_url)']'

**Environment information**
* Python version: 3.7.4
* tensorflow-datasets v2.1.0
* tensorflow v2.1.0

**Reproduction instructions**
* Following the instructions provided here: https://www.tensorflow.org/datasets/beam_datasets#on_google_cloud_dataflow (including running successfully the quickstart document). The dataflow job was created successfully and started uploading binaries and incomplete data to gs bucket, and failed in the step 'create_wet_files'.
```
File "../.pyenv/versions/3.7.4/envs/datasets-temp/lib/python3.7/site-packages/tensorflow_datasets/text/c4.py", line 258, in download_url
  File "/usr/local/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 315, in download
    with self._downloader.tqdm():
AttributeError: 'DownloadManager' object has no attribute '_downloader'
```

**Comment by Eshan-Agarwal** [comment]
@shepsels  Its working fine, please provide some code and make sure you setup your credentials correctly. See this [colab](https://colab.research.google.com/drive/1fgxnE1T3iNpdhC43SuddoJKMRPChxmz8) and run, replace `your_project_id` and with project ID of yours google project and same for bucket name

**Comment by shepsels** [comment]
@Eshan-Agarwal I ran it just as shown in this colab, and did not have any credentials issue. It started running, created the dataflow job successfully and started uploading to the correct bucket without any problem, but failed on one of the pipeline steps. Logs are available here: https://drive.google.com/file/d/1urokm_qgyMPR0VR0awzV2lygCytkl8U9/view?usp=sharing
Thanks for your help.

**Comment by Eshan-Agarwal** [comment]
Can you please try with `pip install tfds-nightly` if it works?

**Comment by shepsels** [comment]
@Eshan-Agarwal tried, and it failed much earlier, on 
`I0405 17:35:16.591695 4642289088 stager.py:498] Executing command: ['/Users/pazshepsels/.pyenv/versions/3.7.4/envs/datasets-temp/bin/python', '-m', 'pip', 'download', '--dest', '/var/folders/p9/n_p62drd2ljcj1cn09p4x16w0000gn/T/dataflow-requirements-cache', '-r', '/tmp/beam_requirements.txt', '--exists-action', 'i', '--no-binary', ':all:']
Traceback (most recent call last):
  File "/Users/pazshepsels/.pyenv/versions/3.7.4/envs/datasets-temp/lib/python3.7/site-packages/apache_beam/utils/processes.py", line 85, in check_output
    out = subprocess.check_output(*args, **kwargs)
  File "/Users/pazshepsels/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Users/pazshepsels/.pyenv/versions/3.7.4/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/pazshepsels/.pyenv/versions/3.7.4/envs/datasets-temp/bin/python', '-m', 'pip', 'download', '--dest', '/var/folders/p9/n_p62drd2ljcj1cn09p4x16w0000gn/T/dataflow-requirements-cache', '-r', '/tmp/beam_requirements.txt', '--exists-action', 'i', '--no-binary', ':all:']' returned non-zero exit status 2.
`
but the first try which actually created the dataflow job was with the latest commit from this repo, cloned manually.

**Comment by Conchylicultor** [comment]
I would guess there is some conflict between the tfds version installed in the workers and the one installed in your master job. Could you make sure that both `beam_requirements.txt` and the master jobs are using `tfds-nightly` or `2.1.0` ?

**Comment by Eshan-Agarwal** [comment]
I checked on my bucket tfds version is 2.1.0 and also on `temp/dataflow-requirements-cache` directory version is 2.1.0, And got same error 

> File "../.pyenv/versions/3.7.4/envs/datasets-temp/lib/python3.7/site-packages/tensorflow_datasets/text/c4.py", line 258, in download_url
  File "/usr/local/lib/python3.7/site-packages/tensorflow_datasets/core/download/download_manager.py", line 315, in download
    with self._downloader.tqdm():
AttributeError: 'DownloadManager' object has no attribute '_downloader'

By master job means version of tfds on my local machine or colab ?

**Comment by Conchylicultor** [comment]
From: 
```
File "../.pyenv/versions/3.7.4/envs/datasets-temp/lib/python3.7/site-packages/tensorflow_datasets/text/c4.py", line 258, in download_url
```
The `download_url` in `c4.py` function has been added after the `2.1.0` release, so it means that you are not running `2.1.0`, but `tfds-nightly`.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  I copy stacktrace from above and I tried it after cloning repo , [colab](https://colab.research.google.com/drive/18zsaXOJLP56oa7ntH3vT9zP3Ouh8fQK4)

**Comment by Conchylicultor** [comment]
From your colab
```
! echo "tensorflow_datasets[$DATASET_NAME]==2.1.0" > /tmp/beam_requirements.txt
```
You need to use tfds-nightly

**Comment by shepsels** [comment]
@Conchylicultor you were correct, it was a version mismatch and I should use only tfds-nightly since I'm using download_url. 
Thank both of you!

**Comment by Eshan-Agarwal** [comment]
> From your colab
> 
> ```
> ! echo "tensorflow_datasets[$DATASET_NAME]==2.1.0" > /tmp/beam_requirements.txt
> ```
> 
> You need to use tfds-nightly

@Conchylicultor  Thank you so much, you are right It's using `tensorflow_datasets==2.1.0 ` pip package which is not updated yet so instead `tfds-nightly` works fine
