### ISSUE TITLE
Got Unrecognized instruction format while spiting using subsplit 

### ISSUE THREAD

**Issue by Eshan-Agarwal** [tensorflow/datasets#1821]
**Short description**
I am loading `mnist` dataset using weighted subsplit ( `tfds.Split.TRAIN.subsplit(weighted = [2, 1, 1])` ) as per instruction [here](https://www.tensorflow.org/datasets/api_docs/python/tfds/core/NamedSplit#top_of_page) and got 

> AssertionError: Unrecognized instruction format: NamedSplit('train')(tfds.percent[0:50])

**Environment information**
* Operating System: <os> Colab
* Python version: <version>
* `tensorflow-datasets`/`tfds-nightly` version: <package and version> 2.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version>

**Reproduction instructions**

```
import tensorflow_datasets as tfds

s1, s2, s3 = tfds.Split.TRAIN.subsplit(weighted = [2, 1, 1])

dataset,info= tfds.load('mnist',with_info=True, split=s1)
```

**Link to logs**
logs [link](https://gist.github.com/Eshan-Agarwal/20d0694760b971ef3281400455f30f33)

**Expected behavior**
Spliting works fine

**Additional context**
See this [colab ](https://colab.research.google.com/drive/1Aai-803eDuifSHGaPwLBUhQu7LTMf0_r)

**Comment by Conchylicultor** [comment]
Where did you see those instructions, this API is deprecated and shouldn't be used. Please use the new subsplit API instead. https://www.tensorflow.org/datasets/splits

**Comment by Conchylicultor** [comment]
We're gonna remove soon those functions from the API. Thanks for pointing this out.

**Comment by Eshan-Agarwal** [comment]
> Where did you see those instructions ? this API is deprecated and shouldn't be used. Please use the new subsplit API instead. https://www.tensorflow.org/datasets/splits

Thanks you for considering it, got when exploring TFDS API
