### ISSUE TITLE
[GSoC] Update document_datasets to indicate which datasets are tfds-nightly only

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1825]
Currently, some datasets are present in `tfds-nightly` but not yet on the stable version. This confuse users which think the dataset do not exists (like in https://github.com/tensorflow/datasets/issues/1692).

We should add a `Note:` in the dataset documentation `.md` to explain the dataset is only available in https://www.tensorflow.org/api_docs/python/tf/raw_ops/Abort.

To do this:

1. Add a new script `freeze_dataset_versions.py` which call [`list_full_names`](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/registered.py#L407) to save all datasets full names (e.g. `mnist/3.0.2`, `c4/en/2.0.0`) to some `stable_versions.txt` file.
2. Update the [document_datasets.py](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/scripts/document_datasets.py) script to update the dataset documentation when dataset name/config/version isn't found in the `stable_version.txt` list.

In addition of the `Note:`, we should add the [nights_stay](https://material.io/resources/icons/?icon=nights_stay&style=baseline) icon with a tooltip saying "Only available in tfds-nigthly": 
   * When the dataset name is new, the icon should be added on the dataset name header.
   * When the config is new, the icon should appear on the config name header (e.g. https://www.tensorflow.org/datasets/catalog/wikipedia#wikipedia20200301cho)
   * When the version is new, the icon should be added next to the version number. Note that the previous stable version should still be displayed on the list.

Note: The solution should not reload the `stable_version.txt` for each dataset but instead load it once and re-use it across all datasets.

To test the documentation generation, you can use the following code snippet:

```python
import os

from tensorflow_datasets.scripts import generate_visualization  # Your new script
from tensorflow_datasets.scripts import document_datasets

DATASET_TO_TESTS = ['mnist', 'cifar10',...]  # Datasets you want to test the script on.
dst_dir = ...  # Destination directory

def main(_):
  for ds_name in DATASET_TO_TESTS:
    # 1) Generate the datasets (as script assume the datasets are already generated)
    tfds.load(ds_name)  

    # 2) Generate and save the documentation page
    doc_content = document_datasets.dataset_docs_str([ds_name])
    with open(os.path.join(dst_dir, f'{ds_name}.md')) as f:
      f.write(doc_content)
```

**Comment by vijayphoenix** [comment]
This can be closed as PR https://github.com/tensorflow/datasets/pull/1831 got merged internally
