### ISSUE TITLE
[GSoC] Clevr dataset generation is failing

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1834]
Clevr was updated recently in https://github.com/tensorflow/datasets/commit/af54aaf4b525fd6624319a0e38d6b3fc50870e23. 

However generation seems to be failing for the `test` set with:

```
tensorflow_datasets/image/clevr.py", line 107, in _generate_examples
    "answer": q["answer"],
KeyError: 'answer'
```

We should investigate and fix Clevr generation.

**Comment by vijayphoenix** [comment]
clevr_test.py runs without any errors.
So, this bug was encountered during actual dataset generation?

**Comment by Conchylicultor** [comment]
@vijayphoenix yes, tests pass bug actual generation fail for the tests set.

**Comment by vijayphoenix** [comment]
Actually, there are no answers in the test data.
So, for the test set answers field should be empty

**Comment by Conchylicultor** [comment]
@vijayphoenix Could you send a PR to fix this ?
