### ISSUE TITLE
DatasetBuilder is failing to load a certain datasets

### ISSUE THREAD

**Issue by shikhar2707** [tensorflow/datasets#1846]
**Short description**
The tfds DatasetBuilder is failing to load a certain dataset.
I wrote a basic piece of code to check if it can load all the registered datasets or not.
The code - 
`Dataset_List = tfds.list_builders()`
`Count = 0`
`for i in range(len(Dataset_List)):`
    `try:`
        `tfds.builder(Dataset_List[i]).info`
    `except:`
        `Count += 1`
which in turns returns the error
`ERROR:absl:Failed to construct dataset my_dataset`
`ERROR:absl:Failed to construct dataset open_images_v4`
`ERROR:absl:Failed to construct dataset wmt_translate`

**Environment information**
* Operating System:  Windows 10 x64 4GB RAM
* Python version: 3.7
* `tensorflow-datasets`/`tfds-nightly` version: Tensorflow 2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version>

**Expected behavior**
The Datasets should load comfortably.
on

**Comment by Conchylicultor** [comment]
* `mydataset`: We don't have any datasets like this in our repository, it's probably comes from your codebase where you define `class MyDataset`
* `wmt_translate`: This is expected:
```python
      raise ValueError(
          "The raw `wmt_translate` can only be instantiated with the config "
          "kwargs. You may want to use one of the `wmtYY_translate` "
          "implementation instead to get the WMT dataset for a specific year."
      )
```
* `open_images_v4`: This may be a bug. Which error is raised ?

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor open_images_v4 runs fine see [colab](https://colab.research.google.com/drive/1ImdwOnNED4us5x2K-dU5NrsQiPm35Ka_)

**Comment by shikhar2707** [comment]
my_dataset is one from my repo. But the other two? It shows absl:failed there.

**Comment by Conchylicultor** [comment]
@Eshan-Agarwal Thanks for confirming. Closing this. Please reopen a bug with the specific `open_images_v4` error message if you still encounter this.

**Comment by Eshan-Agarwal** [comment]
> my_dataset is one from my repo. But the other two? It shows absl:failed there.

Please try it with tfds-nightly or after cloning tfds repo, maybe you are using pip package, Also for `wmt_translate `see above comment should call it by some [configs ](https://www.tensorflow.org/datasets/catalog/wmt14_translate)

**Comment by Conchylicultor** [comment]
@shikhar2707 You should try with `tfds-nightly`. It's possible we have fixed the open_images bug already in the nightly release.
