### ISSUE TITLE
Typo.

### ISSUE THREAD

**Issue by haakontk** [tensorflow/datasets#1849]
Typo in [cbis_ddsm.py](https://github.com/tensorflow/datasets/blob/f2f1267a25f7b25eb8fefd2960e7570b72b1ba28/tensorflow_datasets/image_classification/cbis_ddsm.py#L416) line 416.
`benign_or_malignant = 'BENING'` -> `benign_or_malignant = 'BENIGN'`

**Comment by Eshan-Agarwal** [comment]
@haakontk thanks for looking please send PR

**Comment by vijayphoenix** [comment]
@haakontk Thanks for pointing this out.
It was a bit more than one typo.
