### ISSUE TITLE
`stable_versions.txt` should not have `VERSION` equal to `None`

### ISSUE THREAD

**Issue by vijayphoenix** [tensorflow/datasets#1853]
**Short description**
The list of stable versions of the datasets includes `wmt_translate/None`
https://github.com/tensorflow/datasets/blob/d87ac2c0ecc0655400841a3a502c7c6775f1b6bf/tensorflow_datasets/stable_versions.txt#L1525

So, this can be interpreted as a stable dataset `wmt_translate` with `VERSION = None`

**Enviroment-info**
* `tensorflow-datasets`/`tfds-nightly` version: tfds:2.1.0 and tfds-nightly

**Expected behavior**
Include a default version field in `wmt_translate` or exclude `wmt_translate` from the `tfds.core.registered.list_full_names()`.

**Comment by Conchylicultor** [comment]
Thanks for catching this. The proper fix would be to filter datasets which do not have version defined as those datasets are not supposed to be instanciated.
