### ISSUE TITLE
[data request] <COCO>

### ISSUE THREAD

**Issue by renzhiwei1997** [tensorflow/datasets#1866]
* Name of dataset: <name>
* URL of dataset: <url>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by Eshan-Agarwal** [comment]
@renzhiwei1997  coco dataset is already in tfds [Here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/object_detection/coco.py). Also if you are requesting new dataset provide all the information mentioned above.

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as COCO is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/object_detection/coco.py and https://www.tensorflow.org/datasets/catalog/coco for more info.
Thank you for your contribution
