### ISSUE TITLE
Adding duke_ultrasound dataset to gs://tfds-data/datasets

### ISSUE THREAD

**Issue by Ouwen** [tensorflow/datasets#1867]
* Name of dataset: duke_ultrasound
* URL of dataset: `https://www.tensorflow.org/datasets/catalog/duke_ultrasound`
* License of dataset: Creative Commons BY-NC Attribution-NonCommercial 4.0 International

I am the creator of the `duke_ultrasound` dataset and was interested in hosting the dataset through `gs://tfds-data/datasets`. I believe this will make it easier for researchers to use/access and is better than hosting it in our own bucket. Please let me know if the license for the data would need to change, or if there are other steps for the data transfer. Much appreciated!

**Comment by Conchylicultor** [comment]
Thank you very much! We would like to be able to re-distribute as many datasets as we can to help researchers!
I'm gonna check internally if there is any issues and will update there.

**Comment by Ouwen** [comment]
@Conchylicultor I was wondering if there were any updates regarding the storage of this dataset!

**Comment by Conchylicultor** [comment]
Sorry for the delayed answer. In order for us to re-host the dataset, we also need to make sure that the individual images have a valid licence. Those images are probably owned by the university so it's not clear if we can redistribute it or not.

**Comment by Ouwen** [comment]
So right now the images in this dataset are released through the Creative Commons BY-NC Attribution-NonCommercial 4.0 International License.

Is there a particular license we need to change the dataset being released to?

**Comment by Conchylicultor** [comment]
The licence would be good, but how have the images been obtained ?
Is there for us a way to check that the images have indeed been released under this license ?

**Comment by Ouwen** [comment]
Ah yes: https://research.repository.duke.edu/concern/datasets/jh343s87k?locale=en
This is the official data repo supported by Duke library with the CC license.

Will this work?

**Comment by Conchylicultor** [comment]
Thanks for pointing the original data! I've added duke_ultrasound to the list of mirrored datasets.

**Comment by tonyreina** [comment]
Is this dataset still available? It doesn't show up in the list.
