### ISSUE TITLE
[data request] Binary Alphadigits

### ISSUE THREAD

**Issue by samuelmurray** [tensorflow/datasets#189]
* Name of dataset: Binary Alphadigits
* URL of dataset: https://cs.nyu.edu/~roweis/data.html
* License of dataset: None
* Short description of dataset and use case(s): Binary 20x16 digits of "0" through "9" and capital "A" through "Z". 39 examples of each class.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by SoumyadeepJana** [comment]
This dataset seems interesting to work with.
@rsepassi @Conchylicultor  would like to work on this.

**Comment by Conchylicultor** [comment]
Thanks @SoumyadeepJana

**Comment by SoumyadeepJana** [comment]
@Conchylicultor Thank you for assigning this.

**Comment by SoumyadeepJana** [comment]
@Conchylicultor Completed implementing this.Will make a PR after my previous PR gets reviewed and merged.

**Comment by cyfra** [comment]
Closed by #241
