### ISSUE TITLE
[data request] MultiNLI

### ISSUE THREAD

**Issue by georgedahl** [tensorflow/datasets#19]
* Name of dataset: MultiNLI
* URL of dataset: https://www.nyu.edu/projects/bowman/multinli/
* License of dataset: 
License
See details in the data description paper: https://www.nyu.edu/projects/bowman/multinli/paper.pdf

* Short description of dataset and use case(s): 

The Multi-Genre Natural Language Inference (MultiNLI) corpus is a crowd-sourced collection of 433k sentence pairs annotated with textual entailment information. The corpus is modeled on the SNLI corpus, but differs in that covers a range of genres of spoken and written text, and supports a distinctive cross-genre generalization evaluation. The corpus served as the basis for the shared task of the RepEval 2017 Workshop at EMNLP in Copenhagen.

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by adikolsur** [comment]
Hi @georgedahl , I would like to work on adding to this dataset. I want to get started with this Project. Can you please help me get started and assign this issue to me.

Thanks

**Comment by rsepassi** [comment]
Hi @adikolsur, thanks for your interest! Actually this dataset was added by #80, so closing this issue. Let's find you another dataset to work on. Here are the current [unassigned dataset requests](https://github.com/tensorflow/datasets/issues?q=is%3Aissue+is%3Aopen+label%3A%22dataset+request%22+no%3Aassignee).
