### ISSUE TITLE
caltech_birds yields no examples on windows

### ISSUE THREAD

**Issue by Eshan-Agarwal** [tensorflow/datasets#1901]
**Environment information**
* Operating System: <os>Windows 10
* Issue is specific to windows.

**Short description**
`caltech_birds.py` yields no example on windows this is due to windows take `\` in path and other platform takes `/`. Error is in [line#49](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image_classification/caltech_birds.py#L49) & [line#173](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image_classification/caltech_birds.py#L173)

**Reproduction instructions**

```
import tensorflow_datasets as tfds
ds, ds_info = tfds.load("caltech_birds", with_info = True)
print(ds_info)
```

**Link to logs**
For full stacktrace is [here](https://gist.github.com/Eshan-Agarwal/c2b54f8fa60e5863fdeeda96261977e6)

**Expected behavior**
`caltech_birds` dataset able to loaded and yield examples on windows also

**Additional context**
1. This works fine on Linux/Mac as error is due to windows path using backslash while other using forward slash.
2. [line#49](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image_classification/caltech_birds.py#L49) can be replaced as `_NAME_RE = re.compile(r"((\w*)[/\\])*(\d*).(\w*)[/\\](\w*.jpg)$")`, but paths in archive is like `CUB_200_2011\images\035.Purple_Finch\Purple_Finch_0091_27425.jpg` and windows takes `\035` as hexadecimal `\x035` and gives path string as `CUB_200_2011\images\x035.Purple_Finch\Purple_Finch_0091_27425.jpg` so suggested regx pattern wont help much.

**Comment by CoolNamesAllTaken** [comment]
I just did a fresh install of tensorflow and tensorflow_datasets on Windows 10 and ran into this exact issue with caltech_birds2011. Is it possible that this issue didn't actually get fixed?

**Comment by vijayphoenix** [comment]
Please mention the versions of tf and tfds.

**Comment by Conchylicultor** [comment]
It seems the issue was fixed in tfds-nightly. Did you try ?
