### ISSUE TITLE
[data request] Rockyou

### ISSUE THREAD

**Issue by captain-pool** [tensorflow/datasets#192]
* Name of dataset: Rockyou Dataset for Leaked Passwords
* URL of dataset: https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt
* License of dataset: N/A
* Short description of dataset and use case(s): Dataset of Unencrypted Leaked Passwords from the famous Rockyou Databreach in December 2009. It is used in Security Researches, mainly to train password guessing models. For Example: (PassGAN: A Deep Learning Approach for Password Guessing)[https://arxiv.org/pdf/1709.00440.pdf]

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by ChanchalKumarMaji** [comment]
@captain-pool , Can I work with you on this issue.

**Comment by captain-pool** [comment]
Yep, You can. Ask @cyfra to assign you.

**Comment by ChanchalKumarMaji** [comment]
@cyfra can you please assign this to me, if this dataset is approved to be added to tfds.

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as RockYou is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/structured/rock_you.py and https://www.tensorflow.org/datasets/catalog/rock_you for more info.
Thank you for your contribution
