### ISSUE TITLE
Typo in description of duke_ultrasound "avalible"

### ISSUE THREAD

**Issue by MaxGhenis** [tensorflow/datasets#1928]
**Short description**
https://www.tensorflow.org/datasets/catalog/duke_ultrasound says:
>A usage example is avalible here.

Should be "available"

https://github.com/tensorflow/datasets/blob/d4e0e83a2c7b5ee8b807d036493ef0329e8f446e/tensorflow_datasets/testing/metadata/duke_ultrasound/1.0.0/dataset_info.json#L3

**Comment by Eshan-Agarwal** [comment]
@MaxGhenis  #1850 fix this by @vijayphoenix

**Comment by Naman-Bhrgv** [comment]
@MaxGhenis  I wanna work on this issue.Please assign this issue to me and please guide me since I am new in this repo.

**Comment by MaxGhenis** [comment]
@Naman-Bhrgv I'm not a maintainer so I can't add assignees, but it's already being fixed in pull request #1850.

**Comment by Naman-Bhrgv** [comment]
@MaxGhenis Okay thanks.
