### ISSUE TITLE
[GSoC] Fix documentation images

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#1949]
https://github.com/tensorflow/datasets/pull/1948 is adding visualisation to the documentation, however it seems that images have visual artefacts (missing images, bad labels,...).
It is likely due to the fact that matplotlib do not support multi-threading. We should investigate if the `scripts/generate_visualization.py`  can use multi-processing instead of multi-processing.

**Comment by Eshan-Agarwal** [comment]
working on it

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  using `ProcessPoolExecutor ` instead `ThreadPoolExecutor ` works for me it don't save
(missing images, bad labels,...).

**Comment by Eshan-Agarwal** [comment]
I think this can be closed, as tfds datasets [catalog ](https://www.tensorflow.org/datasets/catalog/flic) looks great with visualizations :)

**Comment by Conchylicultor** [comment]
Yes, thanks @Eshan-Agarwal !
