### ISSUE TITLE
AssertionError: No examples were yielded for Rock_Paper_Scissors

### ISSUE THREAD

**Issue by balajivenky06** [tensorflow/datasets#1963]
**Short description**
Description of the bug.
AssertionError: No examples were yielded.
Shuffling and writing examples to C:\Users\hp\tensorflow_datasets\rock_paper_scissors\3.0.0.incomplete6IRJSB\rock_paper_scissors-train.tfrecord
**Environment information**
* Operating System: windows 10
* Python version: <3.7>
_NAME_RE = re.compile(r"^(rps|rps-test-set)/(rock|paper|scissors)/[\w-]*\.png$") re.compile is wrong... please check

**Comment by Eshan-Agarwal** [comment]
@balajivenky06  can you try with `pip install tfds-nightly` ?, its been updated and probably you are using pip package

**Comment by balajivenky06** [comment]
I installed tensorflow dataset through pycharm as per instructions from Google tensorflow certification... Almost all dataset have similar issues.

**Comment by Eshan-Agarwal** [comment]
Which datasets are you facing problem for and what type of problems ?. Try with `tfds-nightly `

**Comment by vijayphoenix** [comment]
@balajivenky06 eshan is correct.
Please upgrade to the lastest tfds package, i.e `tfds-nightly`.
A lot of bugs (related windows OS) have been recently fixed and some more are on their way.

If you need an urgent fix on some other datasets, please follow the issue #1911. You can find a potential fix in related PRs.

**Comment by balajivenky06** [comment]
Thanks, issue resolved with tfds-nightly.
