### ISSUE TITLE
Checksums for oxford_flowers102 changed

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/datasets#1977]
**Short description**
The checksum for `oxford_flowers102` changed recently which breaks downloading of the dataset.

**Environment information**
* Operating System: macOS
* Python version: 3.7
* `tensorflow-datasets`/`tfds-nightly` version: 3.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.2.0rc3

**Reproduction instructions**

```
rm -r ~/tensorflow_datasets/oxford_flowers102/
rm -r ~/tensorflow_datasets/downloads
```
```python
tfds.load("oxford_flowers102", split="train")
```

**Link to logs**
```
Artifact https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz, downloaded to ~/tensorflow_datasets/downloads/robots.ox.ac.uk_vgg_flowers_102_102flowersoWedSp98maBn1wypsDib6T-q2NVbO40fwvTflmPmQpY.tgz.tmp.9496e46fb0ed404fa5b339ba8c39a725/102flowers.tgz, has wrong checksum. This might indicate:
 * The website may be down (e.g. returned a 503 status code). Please check the url.
 * For Google Drive URLs, try again later as Drive sometimes rejects downloads when too many people access the same URL. See https://github.com/tensorflow/datasets/issues/1482
 * The original datasets files may have been updated. In this case the TFDS dataset builder should be updated to use the new files and checksums. Sorry about that. Please open an issue or send us a PR with a fix.
 * If you're adding a new dataset, don't forget to register the checksums as explained in: https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally
```

**Expected behavior**
Checksums should match and extraction would succeed.

**Comment by elfelround** [comment]
probably this

**Comment by elfelround** [comment]
probably this:


Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.
© 2020 Google - Help - Privacy & Terms

**Comment by lgeiger** [comment]
@elfelround Looks like the file is still available at https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz so something probably changed.

**Comment by elfelround** [comment]
have a look at this thread https://github.com/tensorflow/datasets/issues/965

**Comment by elfelround** [comment]
well if ur downloads download the tgz why not unzip it outside of downloads and see if it compiles?
could be that the centralised checksum is different from the one on the site too? one of them updated or tampered, or some sort of cdn download limit

**Comment by vijayphoenix** [comment]
@lgeiger @elfelround It seems that http://www.robots.ox.ac.uk/~vgg/data/ site had some changes.

I have updated the checksums. 
Thanks for reporting the issue.

**Comment by lgeiger** [comment]
Thanks for the fix :+1:

**Comment by harshag24** [comment]
The problem still persists! Is it due to too many users using the file because even after @vijayphoenix  has updated checksums it persists?

**Comment by Eshan-Agarwal** [comment]
Can you try with tfds-nightly ?

**Comment by danielmapar** [comment]
Tried `%pip install tfds-nightly` on my local machine with no success. Any suggestions?

**Comment by danielmapar** [comment]
`pip --no-cache-dir install tfds-nightly` fixes the issue for me

**Comment by Eshan-Agarwal** [comment]
Here is [colab ](https://colab.research.google.com/drive/170t-Y_k1vMfRMwXdT9kK222komUcBzM3) with `tfds-nightly` working with no issue.

**Comment by mikechen66** [comment]
lgeiger and danielmapar are correct. 

I solve the issue by removing the old files and installing tfds-nightly

### 1. Remove the downloaded files

```
rm -rf ~/tensorflow_datasets/oxford_flowers102/
rm -rf ~/tensorflow_datasets/downloads

```
### 2. Install tfds-nightly

`$ pip --no-cache-dir install tfds-nightly`

Thank a lot.

**Comment by ngocdung03** [comment]
I came into this problem then found out that I forgot to restart the kernel after installing tfds-nightly through Jupiter Notebook.
