### ISSUE TITLE
Checksums for oxford_iiit_pet changed, and the dataset cannot be loaded.

### ISSUE THREAD

**Issue by greentec** [tensorflow/datasets#1978]
**Short description**
Checksums for oxford_iiit_pet dataset is changed.

**Environment information**
* Operating System: Google Colab
* Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]
* `tensorflow-datasets`/`tfds-nightly` version: 2.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.2.0-rc3

**Reproduction instructions**

```
import tensorflow_datasets as tfds
# dataset, info = tfds.load('oxford_iiit_pet:3.0.0', with_info=True)
dataset, info = tfds.load('oxford_iiit_pet:3.*.*', with_info=True)
```

**Link to logs**
https://gist.github.com/greentec/f36b550c9b8c51b559ae3bb80588ae53

**Expected behavior**
Load the Oxford Pet Dataset normally.

**Comment by Eshan-Agarwal** [comment]
@greentec  Thanks for reporting

**Comment by vijayphoenix** [comment]
@Conchylicultor @Eshan-Agarwal 
I think we need to generate checksums of all the datasets with base URL `robots.ox.ac.uk/~vgg/`.

```
oxford_flowers102
dtd
vgg_face2
oxford_iiit_pet
visual_domain_decathlon
voxceleb
```

**Comment by Eshan-Agarwal** [comment]
@vijayphoenix  Yes it seems they have some internal change

**Comment by mch55** [comment]
Hi folks, fantastic you are over this. I am on a course and it uses the oxford_flowers102 dataset so all of us are currently stuck and have fingers crossed it is an easy fix?
I am not the strongest programmer and have spent the last 48 hours trying to import the dataset other ways / generate the check_sum file for you but no luck so far.

If there is something we can do to help let us know?

**Comment by Eshan-Agarwal** [comment]
In PR #1980, checksums for `oxford_flowers102` are updated. Also try with `pip install tfds-nightly` it's recently merged. And if you are using `oxford_iiit_pet` dataset it's updated in PR #1979

**Comment by greentec** [comment]
@Eshan-Agarwal I tried `pip install tfds-nightly` and loaded `oxford_iiit_pet` dataset again, but failed again.

https://gist.github.com/greentec/c962f27fc67bf6899fdf87ca928bc034

**Comment by vijayphoenix** [comment]
After PR #1979 is merged, the changes will be reflected in `tfds-nightly` within few days

**Comment by greentec** [comment]
Okay. Thank you for checking.

**Comment by logiccodes** [comment]
In Colab this `has wrong checksum.` error seems to exist even if the `tensorflow_datasets` is updated to the nighty version. 
```
!pip install git+https://github.com/tensorflow/datasets.git
import tensorflow_datasets as tfds
# dataset, info = tfds.load('oxford_iiit_pet:3.0.0', with_info=True)
dataset, info = tfds.load('oxford_iiit_pet:3.*.*', with_info=True)
```

**Comment by greentec** [comment]
@logiccodes I am also waiting for the tfds-nightly version update.
If you are in a hurry, you can download the dataset manually with the following command and then load it to execute normally.

```
!python -m tensorflow_datasets.scripts.download_and_prepare --register_checksums --datasets=oxford_iiit_pet:3.1.0

import tensorflow_datasets as tfds
dataset, info = tfds.load('oxford_iiit_pet:3.*.*', with_info=True)
```

**Comment by Conchylicultor** [comment]
The PR was rolled back as it was creating issue with TF colab. I'll try to re-merge it sometimes today.

**Comment by Eshan-Agarwal** [comment]
What exact problem is in colab, as I successfully run it here is [colab](https://colab.research.google.com/drive/16Kk4A1q9Y7o4pDGfOy4G5Nn6LBpny_2Z?usp=sharing)

**Comment by Conchylicultor** [comment]
@Eshan-Agarwal yesterday we removed the change, so it break `tfds-nightly`. I resubmitted it in #1995, so it should be fixed (again) in the next `tfds-nightly`. Sorry for the inconvinience.
