### ISSUE TITLE
AttributeError: 'Split' object has no attribute 'subsplit'

### ISSUE THREAD

**Issue by DeqianBai** [tensorflow/datasets#1998]
**What I need help with / What I was wondering**
Traceback (most recent call last):
  File "F:/ML/Deep Learning/NLP/Paper/07-Transformer/NMT-Transformer/Data_process/01.py", line 17, in <module>
    train_half_1, train_half_2 = tfds.Split.TRAIN.subsplit(2)
AttributeError: 'Split' object has no attribute 'subsplit'

**What I've tried so far**
I search this error in google , but there is no such issue like this. I first encounter when I try to download the dataset "newscommentary_v14" in "wmt19_translate/zh-en" :
```
config = tfds.translate.wmt.WmtConfig(
            version=tfds.core.Version("1.0.0"),
            language_pair=("zh", "en"),
            subsets={
                tfds.Split.TRAIN: ["newscommentary_v14"]
            }
        )
builder = tfds.builder("wmt_translate", config=config)
builder.download_and_prepare(download_dir=self.download_dir)

# 3. 切割数据集，使用 tfds.Split 定义一个将此数据集切成多个部分的 split：
train_perc = 20
val_prec = 1
drop_prec = 100 - train_perc - val_prec

split = tfds.Split.TRAIN.subsplit([train_perc, val_prec, drop_prec])

# 将前两个 splits 拿来当作训练以及验证集，剩余的部分（第 3 个 split）舍弃不用：
examples = builder.as_dataset(split=split, as_supervised=True)
train_examples, val_examples, _ = examples
```
**It would be nice if...**
The question was happened when I run the code in Pycharm with .py file.
but it is OK when I run the code in Colab of google with .ipynb  file.

**Environment information**
(if applicable)
* Operating System: windows 10
* Python version: 3.6
* `tensorflow-datasets: 3.1.0
* `tensorflow` version:  2.0.0

**Comment by Conchylicultor** [comment]
`.subsplit` was part of the deprecated API, so cannot be used anymore.

Instead you should use:
*  the new subsplit API: https://www.tensorflow.org/datasets/splits
* Or if running on distributed setting, you can use `tfds.ReadConfig(input_context)` in tfds-nightly to shard the data across workers.

Where did you saw you could use `.subsplit` ? I though we had updated our doc.

**Comment by DeqianBai** [comment]
thank you , I resolve the problem based on your method-1

and I see the use of `.subsplit` in a blog : https://leemeng.tw/neural-machine-translation-with-transformer-and-tensorflow2.html#%E5%88%87%E5%89%B2%E8%B3%87%E6%96%99%E9%9B%86

**Comment by 275761919** [comment]
@Conchylicultor  
https://www.tensorflow.org/tutorials/keras/text_classification_with_hub?hl=zh-cn
this doc has not been updated.

**Comment by vijayphoenix** [comment]
@275761919 I see that the English version of the doc is updated.

**Comment by ghkil74** [comment]
train_validation_split = tfds.load('mnist', split=['train[:60%]', 'train[:40%]'])

(train_data, validation_data), test_data = tfds.load(
    name="imdb_reviews", 
    split=(train_validation_split, tfds.Split.TEST),
    as_supervised=True)

**Comment by sekewei** [comment]
examples = builder.as_dataset(split=tfds.Split.TRAIN.subsplit([20, 1, 79]), as_supervised=True)
can be replaced by
   examples = builder.as_dataset(split=['train[:20%]','train[20%:21%]','train[21%:]'], as_supervised=True)
