### ISSUE TITLE
Example in README not working

### ISSUE THREAD

**Issue by piyush-kgp** [tensorflow/datasets#2]
Example given in README not implemented as of yet.
`AttributeError: module 'tensorflow_datasets' has no attribute 'load'`

**Comment by piyush-kgp** [comment]
#3 is a step in that direction. @rsepassi I am very much willing to contribute to this project. Please let me know/raise Issues on this repo on where you would like help.

**Comment by rsepassi** [comment]
As the README states, tensorflow-datasets is not yet functional so this is expected for now. We'd be happy to have contributions once we have some of the initial code out.
