### ISSUE TITLE
[data request] SNLI

### ISSUE THREAD

**Issue by nikiparmar** [tensorflow/datasets#20]
* Name of dataset: SNLI
* URL of dataset: https://nlp.stanford.edu/projects/snli/
* License of dataset: Creative Commons Attribution-ShareAlike 4.0 International License
* Short description of dataset and use case(s):
The SNLI corpus (version 1.0) is a collection of 570k human-written English sentence pairs manually labeled for balanced classification with the labels entailment, contradiction, and neutral, supporting the task of natural language inference (NLI), also known as recognizing textual entailment (RTE)

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by adikolsur** [comment]
I would like to contribute to this dataset. Kindly assign it to me. And can you also explain exactly what has to be done here?

**Comment by rsepassi** [comment]
Hi @adikolsur, thanks for your interest. Please see the [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by ParthS007** [comment]
@nikiparmar @rsepassi @cyfra @Conchylicultor I have worked on this dataset request since it was inactive for 19 days. I have made a PR #308 adding this dataset. Please review and let me know if I have to do any changes. Thanks :)

**Comment by cyfra** [comment]
SNLI was added in #679 

Thanks @ParthS007 for your commit.
