### ISSUE TITLE
URL changing for XNLI and MNLI/MultiNLI

### ISSUE THREAD

**Issue by sleepinyourhat** [tensorflow/datasets#2004]
**Short description**
NYU is turning down the server/site that hosts the reference copies of XNLI and MNLI shortly, so the URLs will have to change.

New URLs:
https://cims.nyu.edu/~sbowman/multinli
https://cims.nyu.edu/~sbowman/xnli

**Comment by Conchylicultor** [comment]
Thank you for the heads up. It should be easy to update the urls and re-run the generation with `--record_checksums` to update the checksums.

**Comment by vijayphoenix** [comment]
@sleepinyourhat Thank you for the notice.
I have updated the checksums in #2006
