### ISSUE TITLE
Catalog Dataset Example Throws Error

### ISSUE THREAD

**Issue by TaylorBradshaw** [tensorflow/datasets#2010]
**Description of issue**

The example on https://www.tensorflow.org/datasets/catalog/overview is not usable.  The int2str function inside of the print function throws a ValueError because it's trying to print the label of 32 images at once.  Removing the line 'ds = ds.batch(32)' fixed the value error for me, and caused the program to print out all of the labels of each image, though I'm not sure that's the intended result as there's a lot of images in some of these datasets.

**Comment by vijayphoenix** [comment]
Thanks for reporting this.

We could do something like this instead.
```python
ds, info = tfds.load('mnist', split='train', shuffle_files=True, with_info=True)
ds = ds.shuffle(info.splits['train'].num_examples)
ds = ds.batch(32)

# `tfds.as_numpy` converts `tf.Tensor` -> `np.array`
for ex in tfds.as_numpy(ds.take(1)):
    for label in ex['label']:
      print(info.features['label'].int2str(label))

```

**Comment by acharles7** [comment]
@vijayphoenix Do you know how to fix this?

**Comment by vijayphoenix** [comment]
> Thanks for reporting this.
> 
> We could do something like this instead.
> ```python
> ds, info = tfds.load('cifar10', split='train', shuffle_files=True, with_info=True)
> ds = ds.shuffle(info.splits['train'].num_examples)
> ds = ds.batch(32)
> 
> # `tfds.as_numpy` converts `tf.Tensor` -> `np.array`
> for ex in tfds.as_numpy(ds.take(2)):
>     for label in ex['label']:
>       print(info.features['label'].int2str(label))
> 
> ``` 

@acharles7 This fix did not work for you?

**Comment by acharles7** [comment]
@vijayphoenix Do you know how to change catalog  https://www.tensorflow.org/datasets/catalog/overview

**Comment by vijayphoenix** [comment]
The catalog is generated from [this](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/scripts/documentation/templates/catalog_overview.mako.md) `.mako` file.

**Comment by acharles7** [comment]
Thank you. 
I am making PR if you don't mind

**Comment by vijayphoenix** [comment]
PRs are always welcomed :-)

**Comment by acharles7** [comment]
Thank you
