### ISSUE TITLE
oxford_iiit_pet has wrong Checksum

### ISSUE THREAD

**Issue by djdongjin** [tensorflow/datasets#2011]
**Short description**
Description of the bug.

The `oxford_iiit_pet` dataset has a wrong checksum value.

**Environment information**
* Operating System: colab
* Python version: 3.6.9
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets 2.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow 2.2.0-rc4

**Reproduction instructions**

```
import tensorflow_datasets as tfds
dataset, info = tfds.load('oxford_iiit_pet', with_info=True)
```

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
What you expected to happen.

**Additional context**

**Comment by Eshan-Agarwal** [comment]
@djdongjin  try with `tfds-nightly` works fine as PR #1995 recently merged, here is [colab](https://colab.research.google.com/drive/1UE-AgGy7pXuoOXdfqt8cY1qlCZGK8vxb?usp=sharing)

**Comment by djdongjin** [comment]
@Eshan-Agarwal tks!
