### ISSUE TITLE
 cifar10_1 error: wrong checksum 

### ISSUE THREAD

**Issue by Vinnitsky** [tensorflow/datasets#2016]
**Short description**
When I load cifar10_1 dataset I got an error - the wrong checksum 

**Environment information**
* Operating System: ubuntu 18.4
* Python version: 3.6.10               hcf32534_1    anaconda
* `tensorflow-datasets` version: 3.1.0                    pypi_0    pypi
* `tensorflow-gpu` version: 2.1.0                h0d30ee6_0
**Reproduction instructions**

```
raw_ds, info = tfds.load('cifar10_1', split='train', shuffle_files=True, with_info=True)
```
or 
```
builder = tfds.builder('cifar10_1')
info = builder.info
builder.download_and_prepare()
```

**Link to logs**
Downloading and preparing dataset cifar10_1/v4/1.0.0 (download: 5.93 MiB, generated: Unknown size, total: 5.93 MiB) to /home/ip/tensorflow_datasets/cifar10_1/v4/1.0.0...

---------------------------------------------------------------------------
NonMatchingChecksumError                  Traceback (most recent call last)
 in 
      1 # Construct a tf.data.Dataset
----> 2 raw_ds, info = tfds.load('cifar10_1', split='train', shuffle_files=True, with_info=True)
      3 
      4 # Dispaly info
      5 print(info)

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     67     _check_no_positional(fn, args, ismethod, allowed=allowed)
     68     _check_required(fn, kwargs)
---> 69     return fn(*args, **kwargs)
     70 
     71   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/registered.py in load(name, split, data_dir, batch_size, shuffle_files, download, as_supervised, decoders, read_config, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
    367   if download:
    368     download_and_prepare_kwargs = download_and_prepare_kwargs or {}
--> 369     dbuilder.download_and_prepare(**download_and_prepare_kwargs)
    370 
    371   if as_dataset_kwargs is None:

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/api_utils.py in disallow_positional_args_dec(fn, instance, args, kwargs)
     67     _check_no_positional(fn, args, ismethod, allowed=allowed)
     68     _check_required(fn, kwargs)
---> 69     return fn(*args, **kwargs)
     70 
     71   return disallow_positional_args_dec(wrapped)  # pylint: disable=no-value-for-parameter

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_builder.py in download_and_prepare(self, download_dir, download_config)
    361           self._download_and_prepare(
    362               dl_manager=dl_manager,
--> 363               download_config=download_config)
    364 
    365           # NOTE: If modifying the lines below to put additional information in

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_builder.py in _download_and_prepare(self, dl_manager, download_config)
    994     super(GeneratorBasedBuilder, self)._download_and_prepare(
    995         dl_manager=dl_manager,
--> 996         max_examples_per_split=download_config.max_examples_per_split,
    997     )
    998 

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_builder.py in _download_and_prepare(self, dl_manager, **prepare_split_kwargs)
    914         prepare_split_kwargs)
    915     for split_generator in self._split_generators(
--> 916         dl_manager, **split_generators_kwargs):
    917       if str(split_generator.split_info.name).lower() == "all":
    918         raise ValueError(

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/image_classification/cifar10_1.py in _split_generators(self, dl_manager)
    125     image_path, label_path = dl_manager.download([
    126         image_url,
--> 127         label_url,
    128     ])
    129 

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py in download(self, url_or_urls)
    359     # Add progress bar to follow the download state
    360     with self._downloader.tqdm():
--> 361       return _map_promise(self._download, url_or_urls)
    362 
    363   def iter_archive(self, resource):

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py in _map_promise(map_fn, all_inputs)
    460   """Map the function into each element and resolve the promise."""
    461   all_promises = utils.map_nested(map_fn, all_inputs)  # Apply the function
--> 462   res = utils.map_nested(_wait_on_promise, all_promises)
    463   return res

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/utils/py_utils.py in map_nested(function, data_struct, dict_only, map_tuple)
    159     if isinstance(data_struct, tuple(types)):
    160       mapped = [map_nested(function, v, dict_only, map_tuple)
--> 161                 for v in data_struct]
    162       if isinstance(data_struct, list):
    163         return mapped

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/utils/py_utils.py in (.0)
    159     if isinstance(data_struct, tuple(types)):
    160       mapped = [map_nested(function, v, dict_only, map_tuple)
--> 161                 for v in data_struct]
    162       if isinstance(data_struct, list):
    163         return mapped

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/utils/py_utils.py in map_nested(function, data_struct, dict_only, map_tuple)
    165         return tuple(mapped)
    166   # Singleton
--> 167   return function(data_struct)
    168 
    169 

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py in _wait_on_promise(p)
    444 
    445   def _wait_on_promise(p):
--> 446     return p.get()
    447 
    448 else:

~/anaconda3/envs/fv/lib/python3.6/site-packages/promise/promise.py in get(self, timeout)
    508         target = self._target()
    509         self._wait(timeout or DEFAULT_TIMEOUT)
--> 510         return self._target_settled_value(_raise=True)
    511 
    512     def _target_settled_value(self, _raise=False):

~/anaconda3/envs/fv/lib/python3.6/site-packages/promise/promise.py in _target_settled_value(self, _raise)
    512     def _target_settled_value(self, _raise=False):
    513         # type: (bool) -> Any
--> 514         return self._target()._settled_value(_raise)
    515 
    516     _value = _reason = _target_settled_value

~/anaconda3/envs/fv/lib/python3.6/site-packages/promise/promise.py in _settled_value(self, _raise)
    222             if _raise:
    223                 raise_val = self._fulfillment_handler0
--> 224                 reraise(type(raise_val), raise_val, self._traceback)
    225             return self._fulfillment_handler0
    226 

~/anaconda3/envs/fv/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    701             if value.__traceback__ is not tb:
    702                 raise value.with_traceback(tb)
--> 703             raise value
    704         finally:
    705             value = None

~/anaconda3/envs/fv/lib/python3.6/site-packages/promise/promise.py in try_catch(handler, *args, **kwargs)
     83     # type: (Callable, Any, Any) -> Union[Tuple[Any, None], Tuple[None, Tuple[Exception, Optional[TracebackType]]]]
     84     try:
---> 85         return (handler(*args, **kwargs), None)
     86     except Exception as e:
     87         tb = exc_info()[2]

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py in callback(val)
    304       checksum, dl_size = val
    305       return self._handle_download_result(
--> 306           resource, download_dir_path, checksum, dl_size)
    307     return self._downloader.download(url, download_dir_path).then(callback)
    308 

~/anaconda3/envs/fv/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py in _handle_download_result(self, resource, tmp_dir_path, sha256, dl_size)
    259       self._record_sizes_checksums()
    260     elif (dl_size, sha256) != self._sizes_checksums.get(resource.url, None):
--> 261       raise NonMatchingChecksumError(resource.url, tmp_path)
    262     download_path = self._get_final_dl_path(resource.url, sha256)
    263     resource_lib.write_info_file(resource, download_path, self._dataset_name,

NonMatchingChecksumError: Artifact https://github.com/modestyachts/CIFAR-10.1/blob/master/datasets/cifar10.1_v4_data.npy?raw=true, downloaded to /home/ip/tensorflow_datasets/downloads/mode_CIFA-10.1_blob_mast_data_cifaNq0Cwy9MOL7TDNeozV80r6_1TggOEPcU1qi0prAIGnc.npyraw=true.tmp.e6e20b6b04a04146b10698deb40a2cdf/cifar10.1_v4_data.npy, has wrong checksum. This might indicate:
 * The website may be down (e.g. returned a 503 status code). Please check the url.
 * For Google Drive URLs, try again later as Drive sometimes rejects downloads when too many people access the same URL. See https://github.com/tensorflow/datasets/issues/1482
 * The original datasets files may have been updated. In this case the TFDS dataset builder should be updated to use the new files and checksums. Sorry about that. Please open an issue or send us a PR with a fix.
 * If you're adding a new dataset, don't forget to register the checksums as explained in: https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally

**Expected behavior**
loaded dataset

**Additional context**
No

**Comment by vijayphoenix** [comment]
Thanks for reporting this @Vinnitsky.
Thanks @Eshan-Agarwal for the update.

The dataset files got updated because it now uses the numpy format version 2.0.
https://github.com/modestyachts/CIFAR-10.1/tree/master/datasets

**Comment by Eshan-Agarwal** [comment]
@Vinnitsky Thanks for reporting I think checksums are changed because of some [`numpy formating`](https://github.com/modestyachts/CIFAR-10.1/tree/master/datasets) from owners.
