### ISSUE TITLE
[data request] Stanford Online Products

### ISSUE THREAD

**Issue by dandelin** [tensorflow/datasets#203]
* Name of dataset: Stanford Online Products
* URL of dataset: http://cvgl.stanford.edu/projects/lifted_struct/
* License of dataset: MIT
* Short description of dataset and use case(s): Stanford Online Products dataset, 120k images of 23k classes of online products for metric learning.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by captain-pool** [comment]
@rsepassi , @dynamicwebpaige , @Conchylicultor , @cyfra This looks interesting, can you assign me this issue?

**Comment by captain-pool** [comment]
@cyfra Can suggest how to handle FTP Links?

**Comment by captain-pool** [comment]
@cyfra @rsepassi Can you please suggest how to Handle FTP links for `tfds.download.DownloadManager`

**Comment by cyfra** [comment]
Fixed in #238
