### ISSUE TITLE
Accessing a newly created tfds dataset

### ISSUE THREAD

**Issue by tonyboston-au** [tensorflow/datasets#2035]
A dataset was created and the guidance for adding the dataset to tfds from: https://www.tensorflow.org/datasets/add_dataset 

After creating the dataset.py file, ran the command:
$ python -m tensorflow_datasets.scripts.download_and_prepare   --register_checksums=True   --datasets=auslssm2018

This downloaded my dataset and generated output: 

Dataset auslssm2018 downloaded and prepared to /Users/tboston/tensorflow_datasets/auslssm2018/0.1.0. Subsequent calls will reuse this data.
name: "auslssm2018"
description: "The Australian Landsat LCC 2018 dataset was created from a 100km square Landsat geomedian RGB images of southern NSW with a resoliution of 25 metres. The 3968x3968 pixel image has been broken up into 961 128x128 pixel chips. Label (segmentation mask) data is was created based on \'Catchment scale land use of Australia - Update December 2018\' and \'Forests of Australia (2018)\' available from ABARES. Label data represents a simplified 10 member LCC: 0:nodata, 1:forest, 2:grassland, 3:horticulture, 4:crop, 5:plantation, 6:bare, 7:water, 8:builtup, 9:unknown."
citation: "@misc{AusLandsat2018,\n    title={AusLandsat2108: A Dataset to test deep learning models for Land Use and Land Cover Classification},\n    author={Tony Boston},\n    year={2020},\n    eprint={},\n    archivePrefix={},\n    primaryClass={}\n}"
splits {
  name: "test"
  shard_lengths: 130
  num_bytes: 638115
}
splits {
  name: "train"
  shard_lengths: 700
  num_bytes: 3430588
}
splits {
  name: "validation"
  shard_lengths: 131
  num_bytes: 642160
}
version: "0.1.0"
download_size: 4373797

Attempts to access the dataset now seem to fail. A command like this:
dataset = tfds.load('auslssm2018', download=False)

always generates a DatasetNotFoundError error.

Sorry this is obviously a basic issue. Thanks in advance for any pointers.

**Comment by Conchylicultor** [comment]
`DatasetNotFoundError` indicates the dataset isn't registered. You should import your dataset to make sure TFDS is aware of your dataset existance:

```
import tensorflow_datasets as tfds
import my_dataset

ds = tfds.load('my_dataset')
```

**Comment by tonyboston-au** [comment]
Thanks for your help @Conchylicultor 

import my_dataset (as in import auslssm2018) generates this error:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-b34add673966> in <module>
      1 import tensorflow as tf
      2 import tensorflow_datasets as tfds
----> 3 import auslssm2018

ModuleNotFoundError: No module named 'auslssm2018'
```

ds = tfds.load('auslssm2018') generates a ```DatasetNotFoundError```

**Comment by Conchylicultor** [comment]
@tonyboston-au By `import my_dataset`, you need to import the module where you defined the dataset. See: https://docs.python.org/3/tutorial/modules.html

**Comment by tonyboston-au** [comment]
This is what I get when running python from ~/tensorflow_datasets:

(dea-sb) TonysMacBook:tensorflow_datasets tboston$ python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:01:53) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow_datasets
>>> import tensorflow_datasets as tfds
>>> import auslssm2018
>>> ds = tfds.load('auslssm2018')
Traceback (most recent call last):
  File "/Users/tboston/anaconda3/envs/dea-sb/lib/python3.6/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 409, in try_reraise
    yield
  File "/Users/tboston/anaconda3/envs/dea-sb/lib/python3.6/site-packages/tensorflow_datasets/core/registered.py", line 244, in builder
    return builder_cls(name)(**builder_kwargs)
  File "/Users/tboston/anaconda3/envs/dea-sb/lib/python3.6/site-packages/tensorflow_datasets/core/registered.py", line 212, in builder_cls
    raise DatasetNotFoundError(name)
tensorflow_datasets.core.registered.DatasetNotFoundError: Dataset auslssm2018 not found. Available datasets:
	- abstract_reasoning

**Comment by tonyboston-au** [comment]
Also is it possible to run a notebook within Google Colab that can access the dataset I have created and loaded into tfds?

**Comment by vijayphoenix** [comment]
Hi @tonyboston-au,
When adding a new dataset, I generally do the following 
```
git clone https://github.com/tensorflow/datasets
cd datasets
pip install -e .         # or       python setup.py develop
```
This automatically adds the current directory in the `sys.path`. 
Now add the new `my_dataset.py` and other files here and generate the dataset.
Then the code

```
import tensorflow_dataset as tfds
ds = tfds.load("my_dataset")
```
should work fine even in colab.

If you don't want to add your dataset to tfds then you might wanna follow https://www.tensorflow.org/datasets/add_dataset#define_the_dataset_outside_tfds

**Comment by tonyboston-au** [comment]
Thanks @vijayphoenix 
That worked up to a point, cloned the repository, did pip install -e, was able to generate the dataset. tfds.load works in python but not in colab.
```
import tensorflow as tf
import tensorflow_datasets as tfds
ds = tfds.load("ausls2018")
```
```
DatasetNotFoundError                      Traceback (most recent call last)

<ipython-input-18-985aa61e4a5e> in <module>()
      1 import tensorflow as tf
      2 import tensorflow_datasets as tfds
----> 3 ds = tfds.load("ausls2018") 
```
```
/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/registered.py in builder(name, **builder_init_kwargs)
    168     elif name in _ABSTRACT_DATASET_REGISTRY:
    169       raise ValueError(
--> 170           "Dataset with name %s already registered as abstract." % name)
    171 
    172     if _skip_registration:

DatasetNotFoundError: Dataset ausls2018 not found. Available datasets:
	- abstract_reasoning
...
```

**Comment by tonyboston-au** [comment]
Hi again @vijayphoenix 
I guess I could use GCS to host the dataset then use Colab as discussed here: #486. But I would prefer not to have to do this if there is a way to access a user-created tfds dataset via Colab.

Thanks in advance for your help.

**Comment by Conchylicultor** [comment]
@tonyboston-au Basically it seems that the TFDS version you have installed on colab do not contain your dataset. As @vijayphoenix said, you need to install your custom TFDS version on Colab. Like:
https://colab.sandbox.google.com/drive/14lbqVnYBNIqRpz1woF6RE03JtVM8HbJF

Or import your dataset somehow.

**Comment by tonyboston-au** [comment]
Thanks @Conchylicultor @vijayphoenix 
Now TFDS with my dataset (ausls2018) is installed on Colab. I was able to prepare and download the dataset using: python -m tensorflow_datasets.scripts.download_and_prepare   --register_checksums   --datasets=ausls2018

But when I try to load the dataset, a Datasetnotfound error is still ghenerated:
```
%cd /root/tensorflow_datasets
%ls -l
ds = tfds.load(name="ausls2018")
```
which generates:
```
/root/tensorflow_datasets
total 8
drwxr-xr-x 3 root root 4096 May 20 11:02 ausls2018/
drwxr-xr-x 3 root root 4096 May 20 11:02 downloads/

---------------------------------------------------------------------------

DatasetNotFoundError                      Traceback (most recent call last)

/content/datasets/tensorflow_datasets/core/utils/py_utils.py in try_reraise(*args, **kwargs)
    408   try:
--> 409     yield
    410   except Exception:   # pylint: disable=broad-except

12 frames

/content/datasets/tensorflow_datasets/core/registered.py in builder(name, **builder_init_kwargs)
    243       prefix="Failed to construct dataset {}".format(name)):
--> 244     return builder_cls(name)(**builder_kwargs)
    245 

/content/datasets/tensorflow_datasets/core/registered.py in builder_cls(name)
    211   if name not in _DATASET_REGISTRY:
--> 212     raise DatasetNotFoundError(name)
    213   return _DATASET_REGISTRY[name]

DatasetNotFoundError: Dataset ausls2018 not found. Available datasets:
- abstract_reasoning
...
```

**Comment by vijayphoenix** [comment]
@tonyboston-au Here is an example colab [notebook](https://colab.research.google.com/drive/1kdqmjjp-Omg3GfKO4FthubegCnJUrNqf).

It downloads and loads a new dataset, not in tfds (PR #1427).

Follow similar steps and you will be able to load the data

**Comment by tonyboston-au** [comment]
Thanks @vijayphoenix (@Conchylicultor)
That seems to work when the Colab runtime type is set to no hardware accelerator, but strangely when the runtime type is set to GPU or TPU I can't get it to work on my own dataset (ausls2018). I get the DatasetNotFoundError:
```
---------------------------------------------------------------------------

DatasetNotFoundError                      Traceback (most recent call last)

/content/datasets/tensorflow_datasets/core/utils/py_utils.py in try_reraise(*args, **kwargs)
    408   try:
--> 409     yield
    410   except Exception:   # pylint: disable=broad-except
```
Any advice is really appreciated.

**Comment by vijayphoenix** [comment]
Changing Hardware accelerator to GPU should not cause any problem and it is difficult to point out the problem without more information.

Can u share the colab notebook?

**Comment by tonyboston-au** [comment]
@vijayphoenix - the colab notebook is unremarkable.

I worked out what the problem is. I needed to include this statement before loading my dataset using tfds.load('ausls2018'):
```
from tensorflow_datasets.image.ausls2018 import Ausls2018
```
Seems to work fine now with any of the runtime environments. 

Thanks for your help. Issue can be closed.
