### ISSUE TITLE
Can i resume download of C4 dataset

### ISSUE THREAD

**Issue by nikregrado** [tensorflow/datasets#2036]
When i download this dataset in one of link i got 503 error and script was stopped. When i trying to run script again i got OsError: Not enough disk space...  Can I resume download, or i need to delete all downloaded files and try it again?

**Comment by vijayphoenix** [comment]
@nikregrado As of now resume feature is not implemented in TFDS.

Similar issue: https://github.com/tensorflow/datasets/issues/1077

**Comment by Conchylicultor** [comment]
Even if there is no caching within a single file, there is caching per-file. All downloads are saved on a temporary directory until completion when they are renamed.

If the rename is atomic for your system, then it should be safe retry the download without having to delete all files.

**Comment by nikregrado** [comment]
Thanks for replies
