### ISSUE TITLE
ValueError: Shapes (28, 28) and (28, 28, 1) must have the same rank

### ISSUE THREAD

**Issue by muhammadfahid51** [tensorflow/datasets#2039]
My dataset is in MNIST format.
When I load the data in tensorflow-datasets, it gives me the titled error. I don't know what and where the problem actually lies.

**Comment by vijayphoenix** [comment]
With the given context it is not possible to point out the error.

The error message is produced because of some mismatch in the matrix shape. Try using some reshape function to fix the error

**Comment by muhammadfahid51** [comment]
It was solved and it was the shape mismatch issue. It happened during loading saved files from hard drive (cache). Then I had to change the shape of images to (28, 28, 1) and it started working.
@vijayphoenix Thanks for the reply though
