### ISSUE TITLE
Image datasets set encoding_format incorrectly

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/datasets#2042]
**Short description**

Many image datasets set `encoding_format`  metadata incorrectly to `png` even though real data uses `jpeg`.

**Environment information**
* Operating System: macOS
* Python version: 3.7.7
* `tensorflow-datasets`/`tfds-nightly` version: 3.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.2.0

**Reproduction instructions**

```python
import tensorflow as tf
import tensorflow_datasets as tfds

ds, ds_info = tfds.load(
    "imagenette",
    split="train",
    decoders={"image": tfds.decode.SkipDecoding()},
    with_info=True,
)

for data in ds.take(1):
    assert tf.io.is_jpeg(data["image"]).numpy()

# fails because encoding format is set to png
assert ds_info.features["image"]._encoding_format == "jpeg"
```

**Expected behavior**
Encoding format saved in metadata should match the actual data format.

**Additional context**

E.g. ImageNet or Imagenette return `jpeg` data, but set `png` as metadata see
https://github.com/tensorflow/datasets/blob/672ae9a64ec200c7ff21f12faebf128671c88fa1/tensorflow_datasets/testing/metadata/imagenette/full-size-v2/0.1.0/image.image.json#L1
or
https://github.com/tensorflow/datasets/blob/672ae9a64ec200c7ff21f12faebf128671c88fa1/tensorflow_datasets/testing/metadata/imagenet2012/5.0.0/image.image.json#L1

This is due to the fact that the image features uses `encoding_format=png`  by default if not set in the `FeatureDict`. So the problem likely exists for every image feature that doesn't explicitely set an encoding format:
https://github.com/tensorflow/datasets/blob/672ae9a64ec200c7ff21f12faebf128671c88fa1/tensorflow_datasets/image_classification/imagenette.py#L101

During normal decoding this issue doesn't come up since `decode_example` uses `tf.image.decode_image` which accepts both jpeg and png images:
https://github.com/tensorflow/datasets/blob/672ae9a64ec200c7ff21f12faebf128671c88fa1/tensorflow_datasets/core/features/image_feature.py#L178-L183

Unfortunately when using custom preprocessing with `tfds.decode.SkipDecoders()` for improved performance which often relies on `tf.image.extract_jpeg_shape` to do the cropping and decoding in one step this can lead to issues.
Also when using `tfds.testing.mocking.mock_data()` with `tfds.decode.SkipDecoders()` it will fail since fake `png`s will be generated instead of `jpeg`s which breaks preprocessing in user code since many `tf` functions like `tf.image.extract_jpeg_shape` don't support `png`s.

@Conchylicultor since this likely affects many datasets and the generated metadata files, what would be the best way to fix this? For my use case having a workaround for `tfds.testing.mocking.mock_data()` would suffice but I think this could lead to more confusing issues down the line.

**Comment by Conchylicultor** [comment]
I agree this is confusing. We should:

* Make `encoding=None` by default, and require an explicit encoding if the user yield `np.array`. Encoding would still be optional when yielding `bytes`/paths.
* If the encoding is explicitly set, we should make sure that the given encoding match the given bytes.

Don't hesitate to send a PR if you have time.

**Comment by Conchylicultor** [comment]
Fixed by https://github.com/tensorflow/datasets/pull/2099
