### ISSUE TITLE
Disable check sum checkings

### ISSUE THREAD

**Issue by aaronhma** [tensorflow/datasets#2054]
**Is your feature request related to a problem? Please describe.**
This feature request relates to my issue: #2053 and many other people's issues.

**Describe the solution you'd like**
I think that there should be an option to disable the checking the checksum of a dataset. 

Thanks!

**Comment by vijayphoenix** [comment]
A solution I could think of is:
Passing `register_checksums=True` in `download_and_prepare_kwargs` option in `tfds.load`

See [tfds.download.DownloadConfig](https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadConfig) for various download options.

**Comment by aaronhma** [comment]
#2053 Fixed
