### ISSUE TITLE
Visualizations as examples/manual validation

### ISSUE THREAD

**Issue by jackd** [tensorflow/datasets#208]
Most people (myself included) will write scripts to visualize their datasets during development. These not only allow one to visually verify the output is what they'd expect, it would also provide others attempting to use the dataset a good place to start. However, most datasets don't have examples (except those in the main README.md which are more about the use of `tfds` rather than the specific datasets).

I don't feel this should necessarily be a _requirement_ for submissions. In many cases it's fairly straight-forward (e.g image classification). Others require a bit more to fully comprehend though, and given they're mostly being written for visual validation it seems a waste to me to not make them available.

I've put a few extensive examples in [docstrings](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/video/moving_sequence.py#L123) up until now, but that's not all that satisfying. I feel nested `README`s close to the source might be difficult to find (since people using `tfds.load` don't necessarily understand the file structure).

Would the tfds team consider a separate examples directory containing only minimal working visualization examples? It would probably be difficult to test automatically, but I still believe it'd be better than nothing.

**Comment by cyfra** [comment]
@jackd  - that's a good idea. I'd suggest creating a colab file.
