### ISSUE TITLE
[data request] <ImageNet>

### ISSUE THREAD

**Issue by garychanchan** [tensorflow/datasets#2086]
* Name of dataset: <name>
* URL of dataset: <url>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by lgeiger** [comment]
ImagenNet is already available. Checkout https://www.tensorflow.org/datasets/catalog/imagenet2012

**Comment by garychanchan** [comment]
it doesnt matter.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Conchylicultor"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月13日(星期六) 凌晨1:11
收件人:&nbsp;"tensorflow/datasets"<datasets@noreply.github.com&gt;;
抄送:&nbsp;"陈国祥"<335184725@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/datasets] [data request] <ImageNet&gt; (#2086)





 
Closed #2086.
