### ISSUE TITLE
Data set problem

### ISSUE THREAD

**Issue by ahmadnazeeh** [tensorflow/datasets#2092]
**What I need help with / What I was wondering**
I have my own data set in ".csv" format with 2-columns, I need to use my own data set instead of "ted_hrlr_translate/pt_to_en", that is loaded as an example for data set from TED Talks. The code is:

examples, metadata = tfds.load('ted_hrlr_translate/pt_to_en', with_info=True,
                               as_supervised=True)
train_examples, val_examples = examples['train'], examples['validation']

my own data set is " ATB3-all.csv "

**Comment by Conchylicultor** [comment]
`ted_hrlr_translate` will load TED data. If you want your own data, you can create your own dataset: https://www.tensorflow.org/datasets/add_dataset.

We could make it easier to create custom datasets. We've started with `tfds.ImageFolder` in tfds-nightly.

**Comment by vijayphoenix** [comment]
Similar issue https://github.com/tensorflow/datasets/issues/1402
We can simplify this use case by providing some API like `tfds.TranslationDataset`.

Basically, create a dataset from a folder with the given structure.
Each example of a language `lang1` will be a line of text from the file `lang1.split_name`
  ```
  path/to/manual_dir/<dataset_name>/
      lang1.train
      lang2.test
      lang1.test
      lang2.test
      ...
  ```
Some References APIs:
- [tf.data.TextLineDataset](https://www.tensorflow.org/api_docs/python/tf/data/TextLineDataset)
- https://pytorch.org/text/datasets.html#machine-translation

**Comment by omerfbaspinar** [comment]
is there any step by step example for this ? 
i read this and can not apply for my csv dataset. 
https://www.tensorflow.org/datasets/add_dataset#tldr
