### ISSUE TITLE
Update Waymo Open Dataset

### ISSUE THREAD

**Issue by sharanramjee** [tensorflow/datasets#2096]
**Is your feature request related to a problem? Please describe.**
TFDS currently supports [Waymo Open Dataset v1.0](https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_0_0_individual_files/)

**Describe the solution you'd like**
Add [Waymo Open Dataset v1.2](https://console.cloud.google.com/storage/browser/waymo_open_dataset_v_1_2_0_individual_files/) support to TFDS

**Additional context**
Simply need to update links in [waymo_open_dataset.py](https://github.com/tensorflow/datasets/blob/f3042ca38f93cf2ca69a88a4dbeaf2ad51fe8625/tensorflow_datasets/object_detection/waymo_open_dataset.py) and add test split

**Comment by acharles7** [comment]
@Conchylicultor do we have to update this dataset?

**Comment by Conchylicultor** [comment]
@acharles7, what would be the drawback of updating the dataset ? Note that with `BuilderConfig`, the two versions could be available (e.g. as `waymo/v1.0` and `waymo/v1.2`)

**Comment by acharles7** [comment]
Thank you, Working on it.

**Comment by Conchylicultor** [comment]
@acharles7 Thank you for your motivation but I believe @sharanramjee has already started working on this. There might be other issues for you.

**Comment by vijayphoenix** [comment]
Closing as PR #2104 got merged
