### ISSUE TITLE
[data request] UCF101

### ISSUE THREAD

**Issue by rsepassi** [tensorflow/datasets#21]
* Name of dataset: UCF101
* URL of dataset: http://crcv.ucf.edu/data/UCF101.php
* License of dataset: unknown
* Short description of dataset and use case(s):
UCF101 is an action recognition data set of realistic action videos, collected from YouTube, having 101 action categories. This data set is an extension of UCF50 data set which has 50 action categories. 

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by yunpengli** [comment]
+1.

**Comment by navneet-nmk** [comment]
@rsepassi I would like to take a crack at including UCF101

**Comment by rsepassi** [comment]
Hi @navneet-nmk, thank you! Let me know when you've accepted the collaborator invite and I'll assign it to you.

**Comment by navneet-nmk** [comment]
Hi @rsepassi, I have accepted the invite. Looking forward to start.

**Comment by Conchylicultor** [comment]
It has been added, so closing this

**Comment by dsalaj** [comment]
It does not really work. Including it:

    dataset = tfds.load(name="ucf101")

fails with following error:

    tensorflow.python.framework.errors_impl.NotFoundError: /home/.../tensorflow_datasets/video/ucf101_labels.txt; No such file or directory

Running the tests (`ucf101_test.py`) fails with the same error.
The conda environment is:

    tensorboard               1.12.2           py36he6710b0_0
    tensorflow                1.12.0          gpu_py36he74679b_0
    tensorflow-base           1.12.0          gpu_py36had579c0_0
    tensorflow-datasets       1.0.2                     <pip>
    tensorflow-gpu            1.12.0               h0d30ee6_0
    tensorflow-metadata       0.13.0                    <pip>
