### ISSUE TITLE
NonMatchingChecksumError with tfds.load on GCP 

### ISSUE THREAD

**Issue by yashjakhotiya** [tensorflow/datasets#2109]
**Short description**
tfds.load returns NonMatchingChecksumError when used on a GCP hosted Jupyter Server. There is no issue with the same dataset if I run tfds.load on my local machine.

**Environment information**
* Operating System: Ubuntu 18.04
* Python version: 3.6.9
* `tensorflow-datasets`/`tfds-nightly` version: `tensorflow datasets 3.1.0`
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: `tensorflow 2.1.0`

**Reproduction instructions**

```
dataset, info = tfds.load('imdb_reviews/subwords8k', with_info=True,
                          as_supervised=True)

```
**Link to logs**
https://gist.github.com/yashjakhotiya/d5b7bc7657e7a78eed2b8b492482e8cd

**Expected behavior**
tfds.load should work on GCP without NonMatchingChecksumError or should point out to actual error.

**Additional context**
The Jupyter Notebook is managed by Kubeflow

**Comment by yashjakhotiya** [comment]
cc @Conchylicultor

**Comment by Conchylicultor** [comment]
It seems to indicates that the file downloaded on GCS isn't the same as locally.
Could you try with `record_checksums=True` ?
Also have you tried to download the file again to check if this was a one-of issue ?

**Comment by yashjakhotiya** [comment]
This happened multiple times yesterday. Apparently, it works today even on GCP.
Thanks!
