### ISSUE TITLE
download_kaggle_data() fails

### ISSUE THREAD

**Issue by sharanramjee** [tensorflow/datasets#2113]
**Short description**
download_kaggle_data() fails if there are a lot of files to be downloaded.
Ex: Attempting to download the [money species dataset](https://www.kaggle.com/slothkong/10-monkey-species) results in an error with the following error message: "429 - Too Many Requests" despite it being a reasonably small dataset with not a lot of files

**Environment information**
* Operating System: Windows 10
* Python version: 3.7.2
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets 3.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow 2.2.0

**Reproduction instructions**

```
path = dl_manager.download_kaggle_data('slothkong/10-monkey-species')
```

**Link to logs**
https://gist.github.com/sharanramjee/6a7eb94f806c2e39d114a660af81dfee

**Expected behavior**
Expected to download the dataset from kaggle and proceed with TFDS dataset preparation

**Additional context**
Need to install kaggle API and set up CLI authentication as described [here](https://www.kaggle.com/docs/api) in order to use download_kaggle_data()

**Comment by vijayphoenix** [comment]
@sharanramjee I think got the issue
```
kaggle datasets download --file "Country-data.csv" --path "tensorflow_datasets/kaggle/" -d "rohan0301/unsupervised-learning-on-country-data"
```
gives output
```
Downloading datasets%2F721951%2F1255613%2FCountry-data.csv to tensorflow_datasets/kaggle
```

Expected output
```
```
Downloading Country-data.csv to tensorflow_datasets/kaggle
```

**Comment by vijayphoenix** [comment]
Created an issue upstream https://github.com/Kaggle/kaggle-api/issues/276

**Comment by vijayphoenix** [comment]
This got solved by replacing this

https://github.com/tensorflow/datasets/blob/8bf6dfe26a1d132f7563f17e71a3bb6cc22f7353/tensorflow_datasets/core/download/kaggle.py#L172

by

```python
    output = _run_kaggle_command(command, self._competition_name)
    real_path = os.path.join(output_dir, output.split(' ')[1])
    tf.io.gfile.rename(real_path, os.path.join(output_dir, fname))
```
