### ISSUE TITLE
tfds not returning tf.data.Dataset object?

### ISSUE THREAD

**Issue by abhinavsp0730** [tensorflow/datasets#2115]
why tfds is not returning tf.data.Dataset object.

I'm not able to use map function, that I can easily used in  tf.data.Dataset.
```
def res_img(img, lbl):
  return tf.cast(img, tf.float32)/255., lbl
train.map(res_img)

```

Getting the following error:
TypeError                                 Traceback (most recent call last)
<ipython-input-10-bd20e19a7769> in <module>()
----> 1 train.map(res_img)

10 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py in wrapper(*args, **kwargs)
    263       except Exception as e:  # pylint:disable=broad-except
    264         if hasattr(e, 'ag_error_metadata'):
--> 265           raise e.ag_error_metadata.to_exception(e)
    266         else:
    267           raise

TypeError: in user code:

    TypeError: tf__res_img() missing 1 required positional argument: 'lbl'

**Comment by Conchylicultor** [comment]
`res_img(img, lbl)` requires two argument, but your `train` contains example as `{'imge', 'label'}`. You should use `as_supervised=True`.
See: https://www.tensorflow.org/datasets/overview#as_tuple

**Comment by abhinavsp0730** [comment]
Thanks, got it. But is there any way by which tfds.load returns simple
tf.data.Dataset object?

**Comment by Conchylicultor** [comment]
Have you tested ? `tfds.load` already returns a `tf.data` object. You can see the doc: https://www.tensorflow.org/datasets/overview

**Comment by abhinavsp0730** [comment]
Thanks it has been resolved.
