### ISSUE TITLE
Allow uint16 for png encoded image feature

### ISSUE THREAD

**Issue by razorx89** [tensorflow/datasets#213]
Currently, `tfds.features.Image` with `png` encoding defaults to `tf.uint8` data type and cannot be customized. 
https://github.com/tensorflow/datasets/blob/96fe8c3156b43eb776456522ac739a0a6cdb86d2/tensorflow_datasets/core/features/image_feature.py#L149
However, `tf.image.decode_png` also allows `tf.uint16`, which is for instance important for medical data. One option would be to make the `dtype` for the decoding function configurable.
The encoding constraint at
https://github.com/tensorflow/datasets/blob/96fe8c3156b43eb776456522ac739a0a6cdb86d2/tensorflow_datasets/core/features/image_feature.py#L130 
should also be modified for `png` encoding to allow `np.uint8` as well as `np.uint16`.

**Comment by Conchylicultor** [comment]
In this case, because the uint8/uint16 choice would be fixed for each dataset (medical images always uses uint16, imagenet always uses uint8), it should be added as an option of the constructor `tfds.features.Image(shape=(128, 128, 3), dtype=tf.uint16)`.

So the decoding would be automatically done in the right format without any additional set-up from the user.
Do you agree ?

**Comment by razorx89** [comment]
Configuration through the constructor of the feature would be perfectly fine.

**Comment by ParthS007** [comment]
@Conchylicultor @razorx89 I want to work on this Issue. Can you please assign it to me and help me moving forward with this Issue. Thanks :)

**Comment by ParthS007** [comment]
@Conchylicultor Can you please help me moving forward with this Issue. Thanks for assigning it. :)

**Comment by Conchylicultor** [comment]
The idea would be to add a dtype kwargs in the constructor of `tfds.features.Image`: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/features/image_feature.py#L72

If encoding type is png and decoding is uint16, then it should use `tf.image.decode_png` during decoding here: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/features/image_feature.py#L148

**Comment by ParthS007** [comment]
okay, got it :+1: Thanks for the help :)

**Comment by Suhasnama** [comment]
Hello ,
If this issue is still open for contributions I would like to contribute. Please let me know.
Thanks!!

**Comment by Suhasnama** [comment]
Hello @ParthS007 @Conchylicultor  @razorx89 ,
I made a pull request #712 about this issue , please suggest me changes if any or did I miss anything please let me know.
Thank you all!!
