### ISSUE TITLE
Checksum of dataset

### ISSUE THREAD

**Issue by liubaoryol** [tensorflow/datasets#2131]
**Short description**
Checksum of dataset `cifar10_1` does not match, hindering the download of data. The URL for downloading `cifar10_1` is up and running, so I believe that the data has been updated

**Comment by vijayphoenix** [comment]
Similar issue https://github.com/tensorflow/datasets/issues/2016
PR https://github.com/tensorflow/datasets/pull/2017

**Comment by Conchylicultor** [comment]
Sorry for the delay. Will merge this soon
