### ISSUE TITLE
TensorFlow Datasets IMDB reviews dataset page - HTML in the description

### ISSUE THREAD

**Issue by 8bitmp3** [tensorflow/datasets#2132]
See the rendering at the beginning of the IMDB reviews dataset page: https://www.tensorflow.org/datasets/catalog/imdb_reviews. The source code should be here https://github.com/tensorflow/datasets/blob/master/docs/catalog/imdb_reviews.md

Screenshot:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/19637339/85954091-f23e5800-b96c-11ea-85b9-c67a3671c782.png">

HTML line affected: 
```html
<meta itemprop="description" content="Large Movie Review Dataset.&#10;This is a dataset ... ;See [the guide](https://www.tensorflow.org/datasets/overview) for more&#10;informations on [tensorflow_datasets](https://www.tensorflow.org/datasets).&#10;&#10;" />
```

I couldn't find a bug by comparing `imdb_reviews.md` to the other raw Markdown files of other datasets at https://github.com/tensorflow/datasets/tree/master/docs/catalog. Can you check on your side?

**Comment by Conchylicultor** [comment]
Thank you for reporting. This is very strange indeed. I'm not sure what is happening here. We'll investigate

**Comment by yashk2810** [comment]
This is now fixed: https://www.tensorflow.org/datasets/catalog/imdb_reviews

**Comment by Conchylicultor** [comment]
Thank to Yash for the quick fix. Closing this now
