### ISSUE TITLE
TFDS just download the tfrecord

### ISSUE THREAD

**Issue by tommywei110** [tensorflow/datasets#2135]
**What I need help with / What I was wondering**
I'm trying to create an API on top of tfds that requires the downloadable to just be the tfrecord.
I wonder if there's way to configure the builder such that it only downloads the tfrecords.

**What I've tried so far**
Looking at the documentations and searching for solution

**Comment by Conchylicultor** [comment]
We currently do this automatically for a limited number of datasets that we are allowed to redistribute. The code is here: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/dataset_builder.py#L369

You could try to patch `is_dataset_on_gcs` and `download_gcs_dataset` to do what you're trying to achieve. It would bypass the generation code and directly download the pre-processed dataset locally.

**Comment by tommywei110** [comment]
Thanks for the swift response.
