### ISSUE TITLE
[data request] Add PAWS dataset

### ISSUE THREAD

**Issue by dakshvar22** [tensorflow/datasets#2156]
* Name of dataset: PAWS and PAWS-X
* URL of dataset: https://github.com/google-research-datasets/paws
* License of dataset: [Free to distribute](https://github.com/google-research-datasets/paws)
* Short description of dataset and use case(s): It's a paraphrase identification dataset with a lot of adversarial tough examples generated in a controlled setting. PAWS-X is the multi-lingual version of it which is amazing.

I am working on adding this dataset to the repo.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

**Comment by Conchylicultor** [comment]
Closing this as this dataset was been added in tfds-nightly.
