### ISSUE TITLE
[data request] BAIR Robot Pushing Dataset (original resolution)

### ISSUE THREAD

**Issue by martinengelcke** [tensorflow/datasets#2157]
* Name of dataset: BAIR Robot Pushing Dataset
* URL of dataset: https://sites.google.com/view/sna-visual-mpc/
* License of dataset: NA
* Short description of dataset and use case(s): The "small" version of this dataset is already available at https://www.tensorflow.org/datasets/catalog/bair_robot_pushing_small but only supports 64x64 images. It would be great to be able to load this dataset at the original resolution or a custom resolution as the 64x64 resolution is very limiting.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by rushabh-v** [comment]
I would like to contribute it.

Should I implement it for custom resolution or If fixed then what resolution should the dataset support, optimally? 
The paper [Self-Supervised Visual Planning with Temporal Skip Connections](https://arxiv.org/pdf/1710.05268.pdf) has used 64 x 64 frames only.

**Comment by martinengelcke** [comment]
Thanks for your interest!

Looking at the paper code (https://github.com/febert/visual_mpc/blob/master/python_visual_mpc/video_prediction/read_tf_record.py), my first impression was that the original data supported up to 128x128. The documentation for bair_robot_pushing_small also sounds like frames at resolutions higher than 64x64 are in principle available, but I am not 100% sure this is actually true.

A data loader for custom resolution would be ideal but involve more effort. As a start, 128x128 - if possible - would be great and make visual details a lot more discernible.

**Comment by rushabh-v** [comment]
I see [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/testing/fake_data_generation/bair_robot_pushing.py#L54-L56) that the fake dataset for `bair_robot_pushing_small` was created for size `64 x 64`. 
So, should I just replace that data with `128 x 128` and then explicitly set the path of `fakedata` in the testing of one of the dataset builders or should I generate a different fake dataset for it?

**Comment by martinengelcke** [comment]
Maybe generate a separate one?

**Comment by rushabh-v** [comment]
I have opened a PR. Can you please review it @martinengelcke ? https://github.com/tensorflow/datasets/pull/2279

**Comment by martinengelcke** [comment]
What's the original resolution of the images in DATA_URL = "http://rail.eecs.berkeley.edu/datasets/bair_robot_pushing_dataset_v0.tar"?

**Comment by rushabh-v** [comment]
Looks like it's `512 x 640`.

**Comment by martinengelcke** [comment]
Closing this issue. See #2279
