### ISSUE TITLE
Error downloading UCF101

### ISSUE THREAD

**Issue by OrrAvrech** [tensorflow/datasets#2159]
**Short description**
Hi,
I couldn't load UCF101 dataset in tensorflow-datasets. 
Got this error: 
`DownloadError: Failed to get url https://www.crcv.ucf.edu/data/UCF101/UCF101TrainTestSplits-RecognitionTask.zip. HTTP code: 404.`
Then I saw that the homepage PHP file doesn't exist anymore.
Any chance of solving it?

**Environment information**
* `tensorflow-datasets` version: 2.1.0

**Comment by Conchylicultor** [comment]
Thank you for reporting. Please don't hesitate to send a PR to fix this.

**Comment by vijayphoenix** [comment]
The page is opening up for me https://www.crcv.ucf.edu/data/UCF101.php
Also, the dataset loads up without any error.

Please try downloading the dataset again with a newer version of tfds like `tfds-nightly`.

Feel free to reopen the issue
