### ISSUE TITLE
[data request] <KMNIST>

### ISSUE THREAD

**Issue by SoumyadeepJana** [tensorflow/datasets#216]
* Name of dataset: <KMNIST(Kuzushiji MNIST)>
* URL of dataset: <http://codh.rois.ac.jp/kmnist/index.html.en>
* License of dataset: <Creative Commons Attribution Share-Alike 4.0 International License.>
* Short description of dataset and use case(s): <Kuzushiji-MNIST contains 70,000 28x28 grayscale images spanning 10 classes (one from each column of hiragana), and is perfectly balanced like the original MNIST dataset (6k/1k train/test for each class).>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by cyfra** [comment]
KMIST is already there.
(see image/mnist.py).

Please reopen if I misunderstood something
