### ISSUE TITLE
Script to add a new dataset generates files in ~/.local/lib/python3.6

### ISSUE THREAD

**Issue by enigmaeth** [tensorflow/datasets#2160]
Script to add a new dataset generates files in `~/.local/lib/python3.6/site-packages/tensorflow_datasets`.
https://www.tensorflow.org/datasets/add_dataset#writing_my_datasetpy

**Environment information**
* Operating System: elementary OS, 5.1.4 Hera
* Linux kernel: 4.15.0-101-generic
* Python version: 3.6.9
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets==3.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow-gpu==1.13.1
```
$ pip freeze | grep "tensorflow"
tensorflow==2.2.0
tensorflow-datasets==3.1.0
tensorflow-estimator==2.2.0
tensorflow-gpu==1.13.1
tensorflow-metadata==0.22.1
tensorflow-probability==0.10.0
```

**Reproduction instructions**     
```
python3 tensorflow_datasets/scripts/create_new_dataset.py \  
  --dataset test_dataset_audio \  
  --type audio
```

**Expected behavior**
These files should be generated in the repository clone, but it gets generated inside `~/.local/lib/python3.6` which is a hard place to find.

**Additional context**
[`flags.DEFINE_string('tfds_dir', None, 'Root directory of tfds (auto-computed)')`](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/scripts/create_new_dataset.py#L54) might be computing the root dir incorrectly?

**Comment by enigmaeth** [comment]
Ah yes, the path in [`get tfds_dir() -> str`](https://github.com/tensorflow/datasets/blob/a46a6df7f0f8ec308e36f38262a97c9c766fb1b3/tensorflow_datasets/core/utils/py_utils.py#L354) when logged is:
`.local/lib/python3.6/site-packages/tensorflow_datasets`. 

Is this intentional or should it be the directory of tensorflow_datasets repository clone and not the tfds python package?

**Comment by Conchylicultor** [comment]
I think you need to run `pip install -e .` in your cloned repository in order to correctly update the path.

We're working on a better way to set-up datasets but it might takes more time.

**Comment by vijayphoenix** [comment]
Made a PR updating the `Adding a Dataset` doc https://github.com/tensorflow/datasets/pull/1611
