### ISSUE TITLE
Slow Speed

### ISSUE THREAD

**Issue by jsl303** [tensorflow/datasets#2176]
Is this normal to be this slow?
According to speedtest-cli, I have 254.38 Mbit/s downstream and 232.71 Mbit/s upstream.
```
test_data, info = tfds.load(name="voc/2007", with_info=True, split="validation")
←[1mDownloading and preparing dataset voc/2007/4.0.0 (download: 868.85 MiB, generated: Unknown size, total: 868.85 MiB) to
Dl Size...:  10%|██████▏                                                          | 83/868 [06:16<1:04:41,  4.94s/ MiB]
```

**Comment by Conchylicultor** [comment]
Many datasets are hosted in academic websites which unfortunately have limited bandwidth. You could look at the source code and try to download the url from the browser to check that the download is also slow when downloading outside TFDS.

**Comment by vijayphoenix** [comment]
Closing as the issue seems to be with http://host.robots.ox.ac.uk/pascal/VOC/voc2007/ server
