### ISSUE TITLE
Can't download example datasets from google

### ISSUE THREAD

**Issue by LaBaum** [tensorflow/datasets#2182]
Hello,
Im trying to get into AI Development with tensorflow, but I can't download the example datasets. Every time I try it, Ill get a error from the debug console and from vsc.

Here my code:

`import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds
print(tfds.list_builders())
ds = tfds.load('mnist', split='train', shuffle_files=True)
assert isinstance(ds, tf.data.Dataset)
`

and the errors I recieve:
`W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Failed precondition: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cert (path? access rights?)', error details: error setting certificate verify locations: CAfile: /etc/ssl/certs/ca-certificates.crt`

`Exception has occurred: TypeError
__init__() missing 2 required positional arguments: 'op' and 'message'
  File "/home/Dokumente/Python Workspace/TF Einstieg/TfTextClassificication.py", line 7, in <module>
    ds = tfds.load('mnist', split='train', shuffle_files=True)`

It would be nice if theire is somebody who can help me, because I can't figure out by myself :/
**Environment information**
* Operating System: Fedora32
* Python version: 3.8.3
* `tensorflow-datasets: 3.2.0
* `tensorflow: 2.2.0

**Comment by Lothedr** [comment]
Did you solve this issue? I have same problem.

**Comment by Conchylicultor** [comment]
Sorry for the breakage. We'll fix the issue soon but please downgrade to `3.1.0` in the meantime. This is a duplicate of #2190.
