### ISSUE TITLE
ImportError: cannot import name 'ContextManager'

### ISSUE THREAD

**Issue by SinaChavoshi** [tensorflow/datasets#2199]
**Short description**
tfds 3.2.0 requires later version of typing 3.6.0>= which includes support for "ContextManager" (ref https://docs.python.org/3/library/typing.html#typing.ContextManager). However this is not specified in requirements file resulting in failure python 3.5.2 environment. 

**Environment information**
* Operating System: ubuntu 18.0
* Python version: 3.5.2 
* `tensorflow-datasets` version: 3.2.0
* `tensorflow` version: 2.2

**Reproduction instructions**

setup an environment with python 3.5.2. 

```shell
pip3 install tensorflow 
python -c "import tensroflow_datasets as tfds" 
```

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
What you expected to happen.
tfds should pull required dependancies

**Additional context**

**Comment by vijayphoenix** [comment]
Fixed by #2222
