### ISSUE TITLE
Dataset error with uc_merced dataset

### ISSUE THREAD

**Issue by gallorob** [tensorflow/datasets#2212]
_Note_: Bug was originally wrongly opened on the tensorflow repository, see [here](https://github.com/tensorflow/tensorflow/issues/41078)

**System information**
- Using Google Colab's default TF installation
- TensorFlow version: 2.2.0
- Python version: 3.6

**Describe the current behavior**
Dataset's samples are not all of the expected 256x256x3 shape, I found 44 out of 2100 samples with different shape. Currently, during preprocessing, I have to rescale the image if necessary.

**Describe the expected behavior**
All samples should have 256x256x3 shape.

**Standalone code to reproduce the issue**
```
import tensorflow.compat.v2 as tf
import tensorflow_datasets as tfds

dataset, info = tfds.load('uc_merced',
                            split='train',
                            as_supervised=True,
                            with_info=True,
                            shuffle_files=True)

exp_shape = (256, 256, 3)
n = 0
for sample in dataset.take(-1):
    if sample[0].shape != exp_shape:
        n += 1

print('Found {} samples with wrong shape'.format(n))
```

**Other info / logs**
`Found 44 samples with wrong shape`

**Additional notes**
This may seem to be a problem with the original dataset (http://weegee.vision.ucmerced.edu/datasets/landuse.html). If a fix is not possible, it may be a good idea to add a note in the documentation page https://www.tensorflow.org/datasets/catalog/uc_merced to let new users know about the issue.
Alternatively, a possible solution that the user would have to implement is something like:
```
def correct_dims(x, y):
    some_resizing_function(x, (256, 256, 3))
```
and after loading the dataset:
```
dataset = dataset.map(correct_dims)
```

**Comment by vijayphoenix** [comment]
> FeaturesDict({
       'filename': Text(shape=(), dtype=tf.string),
       'image': Image(shape=(None, None, 3), dtype=tf.uint8),
       'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=21),
})

The documentation already indicates that the dataset images don't have a fixed size.

However, you could use some preprocessing techniques like [tf.image.resize](https://www.tensorflow.org/api_docs/python/tf/image/resize?version=nightly). To integrate it with tf.data you can refer to the guide [here](https://www.tensorflow.org/guide/data#decoding_image_data_and_resizing_it)

or filter those images with `ds.filter` to make sure all images have the same shape 

or add padding with `ds.map` or `ds.padded_batch`

**Comment by gallorob** [comment]
I wasn't sure that saying that the image has shape `(None, None, 3)` automatically implies it has no fixed size, mostly because in the dataset's description it says that "Each image measures 256x256 pixels"; it may be worthwile having both documentation and description say the same thing (though this would be a documentation issue and not a bug).

Thank you for the functions you suggested, I ended up using `tf.image.resize` already.
