### ISSUE TITLE
Split the core library from all the datasets

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/datasets#2232]
I want to use the library as a library and be able to create custom datasets without having to fork the repository and nesting adding my scripts in the forked repository.

If you install tensorflow_datasets as a library it get all kind of resolutions errors because seems that is trying to find your custom dataset in your installed path. 

There are  three main use cases that should be supported:

```
# download assets and applies transforms to get a final set of assets
tfds download_and_build  <PATH TO A DIRECTORY>
```

```
# test the logic
tfds test  <PATH TO A DIRECTORY>/
```

```
# each directory is a full python package that has as a dependency the tfds.Dataset interface
pip install <PATH TO A DIRECTORY> 
from my_custom_module import Dataset
```

DIRECTORY should contain a fixed name of files:
```
- dataset.py 
- dataset_test.py
- test_data 
- requirements.txt
- setup.py
```

Also here like in many other "ONLY ONE LINE TO GET YOUR PROJECT DONE" we are focusing in doing too much magic for the entry level users and not focusing on the professional use cases of these tools where we want to have fixed deterministic behavior even if we have to write 100 lines of code but we know exactly what each line is doing. 

forking for now

**Comment by vijayphoenix** [comment]
Thanks for your input.
We have started working on [TFDS cli](https://github.com/tensorflow/datasets/issues/2161) and [better support for dataset defined outside TFDS](https://github.com/tensorflow/datasets/pull/2141)

**Comment by vijayphoenix** [comment]
Closing in favor of https://github.com/tensorflow/datasets/issues/2447
