### ISSUE TITLE
 [data request] Stanford Dogs Dataset

### ISSUE THREAD

**Issue by InduManimaran** [tensorflow/datasets#230]
* Name of dataset: Stanford Dogs Dataset
* URL of dataset: http://vision.stanford.edu/aditya86/ImageNetDogs/main.html
* License of dataset:  Unknown
* Short description of dataset and use case(s):
The Stanford Dogs dataset contains images of 120 breeds of dogs from around the world. This dataset has been built using images and annotation from ImageNet for the task of fine-grained image categorization.

**Comment by SoumyadeepJana** [comment]
@Conchylicultor @cyfra @rsepassi I would like to work on this if approved.

**Comment by iswariyam** [comment]
@cyfra @rsepassi @Conchylicultor I would also to collaborate and contribute to this dataset

**Comment by iswariyam** [comment]
@cyfra @rsepassi @Conchylicultor I would like to send in a pull request if this is assigned to me.

**Comment by cyfra** [comment]
Done in #264
