### ISSUE TITLE
Functionality of dataset.repeat(-1) in tensorflow 1

### ISSUE THREAD

**Issue by engrmz** [tensorflow/datasets#2300]
Hello everyone, 
Can you please help in understanding the functionality of `dataset = dataset.repeat(-1)` in tensorflow 1? In my case, when I am using it, it iterates the dataset infinitely. However, when I set it any other number than -1, it fetches only a single sample.

**Comment by engrmz** [comment]
Here is the

**Comment by Conchylicultor** [comment]
Without reproductible code we can't reproduce the issue. But `repeat` works as you would expect.

```py
ds = tf.data.Dataset.range(5)
print(len(ds))  # 5
ds = ds.repeat(2)
print(len(ds))  # 10
```

**Comment by engrmz** [comment]
Thanks @Conchylicultor. I got the point, repeat is repeating the entire dataset N times. Also, for N is -1, the dataset will repeat infinite time.

**Comment by Conchylicultor** [comment]
@engrmz Exactly. Closing this as it seems the issue was resolved.
