### ISSUE TITLE
Download dataset from Kaggle using dataset name

### ISSUE THREAD

**Issue by SoumyadeepJana** [tensorflow/datasets#232]
**Is your feature request related to a problem? Please describe.**
Currently, the download manager only supports downloading the datasets which are associated with a competition on kaggle. There are many datasets on kaggle that don't have a competition name associated with them.

**Describe the solution you'd like**
Extend the download manager to add support for downloading datasets from kaggle using the name of the dataset.

**Comment by rsepassi** [comment]
Could you link to an example of a competition dataset and a dataset not associated with a competition? Can they be unified? i.e. Do competition datasets also just have dataset names? Maybe we can only use dataset names and get rid of competition names altogether.

**Comment by SoumyadeepJana** [comment]
@respassi Dataset not associated with a competition [HAM10000](https://www.kaggle.com/kmader/skin-cancer-mnist-ham10000)  Dataset associated with competition[Histopathologic Cancer Detection](https://www.kaggle.com/c/histopathologic-cancer-detection/data).I don't think they have different names as such for competition or the dataset itself,every purpose is served using one name.We can use only the name to download the dataset,maybe that would make it more robust,your views?

**Comment by vijayphoenix** [comment]
This issue can be closed as PR #1504 got merged internally
