### ISSUE TITLE
Extract multiple and nested files error.

### ISSUE THREAD

**Issue by us** [tensorflow/datasets#234]
**Short description**
 The current tfds.core.download_manager is unable to extract multiple and nested files. For example we need to download nested compressed files and `dl_manager.download_and_extract` download but then given an error.
File structure like this:
.
+-- gzip.zip
�   +-- emnist-balanced-test-images-idx3-ubyte.gz
�   +-- emnist-balanced-test-labels-idx1-ubyte.gz
�   +-- emnist-balanced-train-images-idx3-ubyte.gz
�   +-- emnist-balanced-train-labels-idx1-ubyte.gz

It's just extract the gzip.zip doesn't extract later.

**Environment information**
* Operating System: `macOS 10.14.3 (Mojave) 64-bit`
* Python version: `3.6.8`
* `tensorflow-datasets`/`tfds-nightly` version: `1.0 / 1.14`
* `tensorflow` version: `1.2`

**Expected behavior**
dl_manager download all files recursively.

**Additional context**
I found this bug when I added emnist dataset.
Related pr #198 
Because of that I used to `dl_manager.manual_dir` 
[related line](https://github.com/tensorflow/datasets/pull/198/files/7699041a9157d9df5c1407fb3f98f28515b8a443#r264791715)

**Comment by rsepassi** [comment]
@us does it error? Or is this a feature you would want?
Could you not call `dl_manager.extract` on each of the files in the interior directory?

**Comment by rsepassi** [comment]
And are you saying that EMNIST could actually be sourced from the web and the only reason you used manual_dir was because of this nested extraction? If the `dl_manager.extract` method works (or `dl_manager.iter_archive`), could we switch EMNIST to not have to use `manual_dir`?

**Comment by us** [comment]
Yes you are right I couldn't understand all of library. I will fixed it.
and yes this is a feature than a bug. I will corrected.

**Comment by us** [comment]
#251

**Comment by rsepassi** [comment]
Thank you. Do you think you could update EMNIST? It's much more usable without using manual_dir.

**Comment by us** [comment]
Yes I will update as a soon as possible.

**Comment by rsepassi** [comment]
Thanks!
