### ISSUE TITLE
Logging error with Python 3.8 on Windows 10

### ISSUE THREAD

**Issue by yugimani** [tensorflow/datasets#2347]
**Short description**
Similar to https://github.com/tensorflow/tensorflow/issues/35027 

**Environment information**
* Operating System: Windows 10
* Python version: 3.8.5
* tensorflow-datasets version: 3.2.1
* tensorflow version: 2.3.0

**Reproduction instructions**
`
python tensorflow_datasets/scripts/create_new_dataset.py --dataset my_dataset --type image`

https://www.tensorflow.org/datasets/add_dataset#writing_my_datasetpy

**Link to logs**

> C:\datasets>python tensorflow_datasets/scripts/create_new_dataset.py --dataset my_dataset --type image
> 2020-08-27 23:50:00.809257: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
> 2020-08-27 23:50:00.809521: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> Traceback (most recent call last):
>   File "tensorflow_datasets/scripts/create_new_dataset.py", line 35, in <module>
>     from tensorflow_datasets.core import naming  # pylint: disable=g-import-not-at-top
>   File "C:\datasets\tensorflow_datasets\__init__.py", line 51, in <module>
>     from tensorflow_datasets import __init__py3 as api
>   File "C:\datasets\tensorflow_datasets\__init__py3.py", line 54, in <module>
>     from tensorflow_datasets import text
>   File "C:\datasets\tensorflow_datasets\text\__init__.py", line 50, in <module>
>     from tensorflow_datasets.text.salient_span_wikipedia import SalientSpanWikipedia
>   File "C:\datasets\tensorflow_datasets\text\salient_span_wikipedia.py", line 38, in <module>
>     class SalientSpanWikipediaConfig(tfds.core.BuilderConfig):
>   File "C:\datasets\tensorflow_datasets\text\salient_span_wikipedia.py", line 42, in SalientSpanWikipediaConfig
>     def __init__(self,
>   File "C:\datasets\tensorflow_datasets\core\api_utils.py", line 54, in disallow_positional_args
>     logging.warning(
>   File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\logging\__init__.py", line 322, in warning
>     log(WARNING, msg, *args, **kwargs)
>   File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\logging\__init__.py", line 485, in log
>     _absl_logger.log(standard_level, msg, *args, **kwargs)
>   File "C:\Users\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\logging\__init__.py", line 1047, in log
>     super(ABSLLogger, self).log(level, msg, *args, **kwargs)
>   File "C:\Users\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1500, in log
>     self._log(level, msg, args, **kwargs)
>   File "C:\Users\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 1565, in _log
>     fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
> TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given

**Expected behavior**
Should generate files as described in the guide (https://www.tensorflow.org/datasets/add_dataset#writing_my_datasetpy)

**Additional context**
I am trying to build a custom dataset

**Comment by yugimani** [comment]
Bug also present in tfds-nightly-3.2.1.dev202008270105

**Comment by Conchylicultor** [comment]
This should be fixed with https://github.com/tensorflow/datasets/pull/2349

**Comment by yugimani** [comment]
> 
> 
> This should be fixed with #2349

Patch works!
