### ISSUE TITLE
[Cleanup] Add script to delete old versions on disk

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2355]
When generating new dataset version, we are ending up with many old datasets inside `data_dir/`, some which do not correspond to code anymore. It would be nice to have a script to cleanup all old/non-existing dataset versions, like:

Before:
```
data_dir/old_dataset0/1.0.0/  # Dataset don't exists anymore
data_dir/dataset0/1.0.0/  # More recent version exists
data_dir/dataset0/1.2.0/
data_dir/dataset1/config0/1.0.0/  # More recent version exists
data_dir/dataset1/config0/1.1.0/
data_dir/dataset1/config1/1.0.0/
data_dir/dataset1/old_config0/1.0.0/  # Config don't exists anymore
```

After:
```
data_dir/dataset0/1.2.0/
data_dir/dataset1/config0/1.1.0/
data_dir/dataset1/config1/1.0.0/
```

For the implementation, on way would be to use the `tfds.core.load.list_full_names()` to check all current dataset version and remove all other folders.

There should be a dry_mode so the user can previous which dataset is gonna be kept and deleted. Relative filepath should be sorted. Ex of output:

<pre>
The script will delete the following modifications to `/path/to/data_dir`:
Path indicated in bold will be kept, the other will be deleted.

my_dataset/1.0.0
my_dataset/1.2.0
<b>my_dataset/1.3.0</b>
my_other_dataset/config/1.2.0
<b>my_other_dataset/config/1.3.0</b>
my_other_dataset/other_config/1.2.0
<b>my_other_dataset/other_config/1.3.0</b>
old_dataset

Are you sure to continue ? Y/N:
</pre>

**Comment by NikhilBartwal** [comment]
@Conchylicultor I am working on the script.
There was one thing i wanted to ask, how do I get the `data_dir`? Using `tfds.core.constants.DATA_DIR` gives `~\\tensorflow-datasets` which is not the absolute path. We will need the `data_dir` to delete the old versions of the datasets.
Thanks!

**Comment by NikhilBartwal** [comment]
Hey @Conchylicultor I have made a PR for the script. It would be great if you could review it!

**Comment by vijayphoenix** [comment]
Closed via https://github.com/tensorflow/datasets/commit/cdd5484a3478ba9d8a3412c85cf6a712f304c081
