### ISSUE TITLE
[data request] PatchCamelyon

### ISSUE THREAD

**Issue by RoujiaW** [tensorflow/datasets#2369]
* Name of dataset: PatchCamelyon
* URL of dataset: https://github.com/basveeling/pcam
* License of dataset: MIT License
* Short description of dataset and use case(s): This dataset contains 327,680 color images (96 x 96px) extracted from histopathologic scans of lymph node sections. Each image is annoted with a binary label indicating presence of metastatic tissue. 

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by Ouwen** [comment]
https://www.tensorflow.org/datasets/catalog/patch_camelyon

**Comment by RoujiaW** [comment]
> https://www.tensorflow.org/datasets/catalog/patch_camelyon

Thanks for the head up! I will work on another dataset and resubmit the google form.
