### ISSUE TITLE
NonMatchingChecksumError with Dataset DTD

### ISSUE THREAD

**Issue by DanielGrigorasch** [tensorflow/datasets#2375]
I get a NonMatchingChecksumError when trying to load the Describable Textures Dataset with the following code:
```x_train, x_test = tfds.load('dtd', split=['train', 'test'], shuffle_files=True)```

However doing the same with other datasets like mnist works.

I am using google colaboration.

Thanks

**Comment by vijayphoenix** [comment]
@DanielGrigorasch Please update to latest tfds version or tfds-nightly

The checksums were recently updated 2b8f8f5f
