### ISSUE TITLE
Update TFDS version on various platforms

### ISSUE THREAD

**Issue by vijayphoenix** [tensorflow/datasets#2389]
A lot of people use the `conda` packaging tool instead of `pip`, so it would nice to have an updated version of TFDS on https://anaconda.org/anaconda/tensorflow-datasets.
(Currently, anaconda has a very old TFDS v1.2.0)

Also, we should upgrade Google-Colab to use the latest version.
Related issue https://github.com/googlecolab/colabtools/issues/1390

**Comment by vijayphoenix** [comment]
Publish the latest version of TFDS. See https://anaconda.org/vijayphoenix/tensorflow-datasets

Documentation used:
https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html

**Comment by vijayphoenix** [comment]
If anyone is interested in adding `tfds` on [conda-forge](https://conda-forge.org/) then,
- They can read [guide](https://conda-forge.org/docs/maintainer/adding_pkgs.html#) and fix https://github.com/conda-forge/staged-recipes/issues/12911 or
- They can help me out by fixing https://github.com/conda-forge/staged-recipes/pull/12858 :-)

**Comment by vijayphoenix** [comment]
Closing as TFDS can be installed via Conda-forge. https://anaconda.org/conda-forge/tensorflow-datasets

**Comment by mhlhr** [comment]
When I try to install tensorflow-datasets using conda, I always get version 1.2.0 installed. I even tried to add 4.3.0 as version but still version 1.2.0 installs?? I cannot access cnndailymail text dataset through this version.

**Comment by vijayphoenix** [comment]
Please install TFDS via `conda-forge` channel.

```
conda install -c conda-forge tensorflow-datasets
````

**Comment by mhlhr** [comment]
Thanks for your kind reply. I tried to install TensorFlow datasets using conda-forge like you mentioned. I even tried your method. However, always 1.2.0 installed like given on Conda"s page.

**Comment by vijayphoenix** [comment]
Please try to install TFDS in a new environment.
And if the problem is still not resolved, please share the procedure you followed (along with the logs).
