### ISSUE TITLE
`tfds.load('celeb_a')`  throws errors after few seconds downloading

### ISSUE THREAD

**Issue by moonman925** [tensorflow/datasets#2401]
There's only one line of code which is  `tfds.load('celeb_a')` . It works within first few seconds and then throws errors. It did download things to `~/tensorflow_datasets/download` but obviously incomplete. Any way to fix this? I am using proxy tho. Proxy works fine.
Actually I have a downloaded `celeb_a` on my disk but I don't know how to load it with `tfds.load()`. Would you please tell me how to achieve this please 😢 Thx!!!!
```
raise NonMatchingChecksumError(resource.url, tmp_path)
tensorflow_datasets.core.download.download_manager.NonMatchingChecksumError: Artifact https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM, downloaded to C:\Users\aaa\tensorflow_datasets\downloads\ucexport_download_id_0B7EVK8r0v71pZjFTYXZWM3FlDDaXUAQO8EGH_a7VqGNLRtW52mva1LzDrb-V723OQN8.tmp.4bab998c97b54a6aa18804a4de8b1777\uc, has wrong checksum. This might indicate:
 * The website may be down (e.g. returned a 503 status code). Please check the url.
 * For Google Drive URLs, try again later as Drive sometimes rejects downloads when too many people access the same URL. See https://github.com/tensorflow/datasets/issues/1482
 * The original datasets files may have been updated. In this case the TFDS dataset builder should be updated to use the new files and checksums. Sorry about that. Please open an issue or send us a PR with a fix.
 * If you're adding a new dataset, don't forget to register the checksums as explained in: https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally

```
**Environment information**
* Operating System: windows10
* Python version: 3.7.9
* `tensorflow-datasets`/`tfds-nightly` version: tfds-nightly
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tf-nightly-gpu

**Comment by vijayphoenix** [comment]
As the error msg says

> For Google Drive URLs, try again later as Drive sometimes rejects downloads when too many people access the same URL.

So, please try again later

Similar issues https://github.com/tensorflow/datasets/issues/1482.
