### ISSUE TITLE
[coco] Script getting killed upon loading examples.

### ISSUE THREAD

**Issue by rajgodse** [tensorflow/datasets#2402]
**Short description**
When loading the coco dataset from tfds (after downloading and extraction is shown to be successful), the process gets killed just as it starts to load examples.

**Environment information**
* Operating System: Linux
* Python version: 3.8
* `tensorflow-datasets` version: 3.2.1
* `tensorflow` version: 2.3.0

**Reproduction instructions**
```
import tensorflow_datasets as tfds
tfds.load('coco')
```
**Logs**
```
Downloading and preparing dataset coco/2014/1.1.0 (download: 37.57 GiB, generated: Unknown size, total: 37.57 GiB) to ./tfds_cache/coco/2014/1.1.0...
Dl Completed...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [36:31<00:00, 322.18s/ url]
Extraction completed...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [36:31<00:00, 313.02s/ file]
Extraction completed...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [36:31<00:00, 333.02s/ file]
Dl Size...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 38469/38469 [36:31<00:00, 17.56 MiB/s]

Dl Completed...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [36:31<00:00, 313.02s/ url]
0 examples [00:00, ? examples/s]Killed
```

**Expected behavior**
For the dataset to download without the process getting killed.

**Additional context**
The problem appears to be similar to [this previous issue](https://github.com/tensorflow/datasets/issues/1781), but I am unsure if it is due to a similar bug, and if so, how to rectify it.

**Comment by Conchylicultor** [comment]
I believe killed process indicates that your RAM is full, so your OS kill the process automatically

**Comment by rajgodse** [comment]
Okay, that makes sense. I can close the issue if that is the case, but does anyone know if there is an easy way to download and prepare the dataset without actually internally calling tfds.download_and_prepare()?

Basically, what are the folders in which I would need to put the extracted files in order for me to call tfds.load('coco', download=False) without getting an error?

**Comment by vijayphoenix** [comment]
The downloaded files will be reused.
So, no need to add a `download=False` flag
