### ISSUE TITLE
Update tfds.testing.mock_data to not require metadata.

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2404]
Currently, `tfds.testing.mock_data` require the metadata (`dataset_info.json`,...). This force users to copy those metadata into their repository which doesn't feel user friendly.

It would be nice if `tfds.testing.mock_data` could work using the code only:

```py
with tfds.testing.mock_data():
  ds = tfds.load('mnist')
```

Note that not all feature can be available (e.g. `str2int`, split names,... would be unavailable). This mean that any split name would be available:

```py
tfds.load('mnist', split='non_existing')
```

But this seem a good trade-off considering the usability benefit.

Signature would be updated to:

```py
class MockPolicy(enum.Enum):
  """Strategy to use to mock the dataset.

  Attributes:
    AUTO: Try to load metadata (dataset_info.json,...) from `data_dir`, otherwise fallback to `CODE_ONLY` mode
    CODE_ONLY: Do not use data_dir, instead try to infer everything from the code.
    DIR_ONLY: Only use data_dir, raise error if data_dir not reachable
  """
  AUTO = enum.auto()
  CODE_ONLY = enum.auto()
  DIR_ONLY = enum.auto()

def mock_data(data_dir: Optional[str] = None, policy: MockPolicy = MockPolicy.AUTO,...):
  ...
```

And if the data_dir is detected, then the data could still be.

**Comment by NikhilBartwal** [comment]
Hey @Conchylicultor, I would like to work on this. Could to point me out as to how I should start? Thanks!

**Comment by Conchylicultor** [comment]
Thanks for your motivation @NikhilBartwal . I believe @vijayphoenix wanted to take this issue as it requires some knowledge of TFDS already.
I'll add additional feature request open to contributor if you want to contribute.

**Comment by NikhilBartwal** [comment]
@Conchylicultor I would definitely like to contribute to any other feature that we need to add :)
