### ISSUE TITLE
Update documentation add dataset

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2418]
We should refactor the documentation add_dataset with the new features:

- Split `add_dataset` documentation into `create_dataset` about how to create a dataset in general, and `add_dataset_to_tfds` about how to add the dataset into TFDS.
- Advertise the new CLI `tfds new <dataset>` to create the template
- Describe the dataset-as-folder model/structure.
- Make the implementation less test-centric (1st part: add a new dataset, 2nd part: test the dataset)
- Remove the light config section: https://www.tensorflow.org/datasets/add_dataset#light_configuration_with_constructor_args

**Comment by vijayphoenix** [comment]
https://github.com/tensorflow/datasets/commit/6acf4fa4304c992793f94d1cab50290e46038b6b
