### ISSUE TITLE
Better error message for dataset-as-folder model

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2421]
Currently, errors are not really informative when using dataset-as-folder model:

 * Missing checksums file (`register_checksums=True`)
 * Fake data dir not found (during testing),... 
 * Other ?

Error messages are raised assuming the old structure (checksums in `tensorflow_datasets/checksums/`,...).
Instead, we should raise better error message indicating the path relative to the `DatasetBuilder.code_path` path.

**Comment by gaurav-singh1998** [comment]
Hi, @Conchylicultor I would like to take this issue. Thanks

**Comment by NikhilBartwal** [comment]
@Conchylicultor I would like to take this up. Could you clarify a bit more about the issue as to what needs to be changed? Thanks!

**Comment by Conchylicultor** [comment]
This should be mostly fixed I believe.
