### ISSUE TITLE
Allow users to skip download and use manually downloaded data instead.

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2422]
Users often encounter issue during download (e.g. VPN, dead link,...). But they may have already downloaded the data themself.

Currently, users are forced to rely on the automatic `DownloadManager` download. Instead, we should add a mode to check whether the download already exists in the `DownloadConfig.manual_dir`, and skip the download if so.

Mini-design doc:
* In order to detect whether the file is present or not in the `manual/` dir, we should update `record_checksums=True` mode to save the real name in `checksums.tsv`.
* When the user `download_and_prepare()` and `dl_manager.download` is called:
   * If checksums are not-found for the url, then try to download the url as usual
   * If `checkusms.tsv` file is present but the `manual/<filename>` not found, try to download the url as usual
   * If `manual/<filename>` is found, should validate the checksums (cached with some `<filename>.INFO`, similar to https://github.com/tensorflow/datasets/blob/3e90c815a61db5236063817cf699f2bd4d7eef58/tensorflow_datasets/core/download/download_manager.py#L310), then return the path.

**Comment by harsh020** [comment]
Hi, @Conchylicultor I am very interested to work on this issue, but I am new here so, would like your help in it.
I went through `DatasetBuilder` class and `DownloadManager` class, what I didn't understand is that the `DatasetBuilder` class already has a `data_dir` which if exists would not execute the entire `download_and_prepare()`, so I am a bit unclear on where you want it to be implemented.
I would be very grateful if you provided some resources about TFDS's `checksum`, `record_checksums` and `checksums.tsv`

Thanks.

**Comment by harsh020** [comment]
Hi, @Conchylicultor I was trying to understand how and what to do, for this issue. I think I figured out what to do. So, what I understood is -

- we need to add a `record_checksum` flag to `store_checksums()` to store the `dataset_name` along with other details.

- and when the user uses `download_and_prepare` we need to check if `dataset_name` is present and also the `manual/<dataset_name>` is preset, if so, no need to download the dataset.

Kindly, let me know, if I figured it out correctly.

Thanks.

**Comment by Conchylicultor** [comment]
Thank you for looking into it.

As a first step: https://github.com/tensorflow/datasets/blob/09e720f0755c3e808a562dbb49de9c0368463116/tensorflow_datasets/core/download/checksums.py#L36

should be updated to also include the dataset name:

```py
@dataclasses.dataclass(eq=True)
class UrlInfo():
  size: int
  checksum: str
  filename: Optional[str]
```

Then update the different places where `UrlInfo` is used to save, restore the name correctly. Like:
* store_checksums
* _parse_url_infos
* https://github.com/tensorflow/datasets/blob/09e720f0755c3e808a562dbb49de9c0368463116/tensorflow_datasets/core/download/downloader.py#L155
* ...

Note:
 * You can run the tests in download/ to view which places should be updated.
 * For backward compatibility, `_parse_url_infos` should check whether the filenames are present or not, and set `filename=None` if filename are missing: https://github.com/tensorflow/datasets/blob/09e720f0755c3e808a562dbb49de9c0368463116/tensorflow_datasets/core/download/checksums.py#L154

**Comment by harsh020** [comment]
@Conchylicultor Hi, thanks for the info. I was working on the `URLInfo` class and was wondering that if we convert it to a `dataclass` I don't think we need to override the `__eq__` magic method, bcs `dataclass` default compares the data of two instances and not their location in memory.

Thanks.

**Comment by harsh020** [comment]
@Conchylicultor Hi, I've been trying to understand it for about 4 days now, but I think I would need a bit of your help. I'm not able to understand the flow of `DownloadManager` like which class is using it. So, I'm not able to understand where in class should I implement this - 
>> In order to detect whether the file is present or not in the manual/ dir, we should update record_checksums=True 
>> mode to save the real name in checksums.tsv.

**Comment by Conchylicultor** [comment]
> @Conchylicultor Hi, thanks for the info. I was working on the URLInfo class and was wondering that if we convert it to a dataclass I don't think we need to anylonger override the __eq__ and __repr__ magic methods.

Yes, if `@dataclasses.dataclass(eq=True)` is used, then `__eq__` and `__repr__` will automatically be generated

> @Conchylicultor Hi, I've been trying to understand it for about 4 days now, but I think I would need a bit of your help. I'm not able to understand the flow of DownloadManager like which class is using it. So, I'm not able to understand where in class should I implement this -

## PR1: Add UrlInfo.filename

The first PR should only be about adding a new `url_info.filename`, even if it isn't used yet.

Could you send a draft PR with what you have accomplished so far ? It's normal to not understand everything. As suggested above, for the first PR, simply update `UrlInfo` to have an additional `url_info.filename` attribute, then simply fix the unittests inside `core/` which are now failing.
You can send the PR for review and I can comment on it.

UrlInfo is currently saved as `checksums.tsv` file:

```tsv
http://url <checksums> <size>
```
We want to add a new filename field:
```tsv
http://url <checksums> <size> <filename>
```
For instance:
```tsv
https://drive.google.com/uc?export=download&id=0BwmD_ndKcjQ 4b2cf3f 128492 cnn_stories.tgz
```

The url_info is saved inside `download/checksums.py`.

## PR2: Update DownloadManager

Once the above `url_info.filename` has been added in the first PR, we can use this new field to auto-detect whether the file has already been added in the manual_dir folder:
So when executing:

```py
path = dl_manager.download('http://some-url.org/data')
```

The `DownloadManager.download` function should be updated to do something like:
```py
url_info = self._url_infos.get(url)
# If the url info where recorded with the filename and the file exists in manual dir
if url_info and url_info.filename:
  manually_downloaded_filepath = os.path.join(self._manual_dir, url_info.filename)
  if tf.io.gfile.exists(manually_downloaded_path):  # File already downloaded
    # Should check the checksums here of manually_downloaded_path
    return manually_downloaded_filepath
# Otherwise, download the file from the internet
```

You only need to update `DownloadManager` here. You don't need to understand where `DownloadManager` will be used.

**Comment by harsh020** [comment]
@Conchylicultor Yup, I have already finished the work for 1st PR few days ago. Will open a PR now.

Thanks.

**Comment by harsh020** [comment]
@Conchylicultor, I'm sorry for the delay, I will open the 2nd PR by 16th night.

Thanks.

**Comment by vijayphoenix** [comment]
https://github.com/tensorflow/datasets/commit/24211da0508a86f0a9efd82c69bab9d25cda0a20
