### ISSUE TITLE
Typo in Fake data generation of Horses or Humans Script

### ISSUE THREAD

**Issue by ParthS007** [tensorflow/datasets#243]
**Short description**
Description of the bug.
The typo can be found [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/testing/horses_or_humans.py#L16)

**Expected behavior**
It should be corrected.

I am working on this Issue.

@cyfra Please assign the Issue to me.

**Comment by rsepassi** [comment]
Thanks!
