### ISSUE TITLE
Add a `tfds build` CLI command

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2447]
The idea would be to deprecate the `download_and_prepare.py` script to instead use the `tfds build my_dataset` command.

Note:

 * Implementation should be split in small independents cls. (e.g. first PR only create an new `script/build.py` file and register the command, but without any logic)
 * Gradually, all features from `download_and_prepare.py` should be migrated, but each feature should be added in a separate PR.
 * When using `tfds build` inside a `dataset-as-folder/`, the dataset would be automatically built.
 * Argparse arguments should be grouped by type using argparse group, for better `tfds build --help`.
 * In additional PRs, we could allow loading datasets from multiple ways:

```py
tfds build my_dataset  # tfds.builder('my_dataset')
tfds build my_dataset my_other_dataset # tfds.builder('my_dataset') ; tfds.builder('my_other_dataset')
tfds build some_module.MyDataset  # import some_module ; builder = some_module.MyDataset()
tfds build /path/to/my_dataset/  # Use `builder_cls_from_module()`
tfds build /path/to/my_dataset/my_dataset.py  # Use `builder_cls_from_module()`
```

**Comment by acharles7** [comment]
@Conchylicultor I would like to work on this.

**Comment by vijayphoenix** [comment]
https://www.tensorflow.org/datasets/cli#tfds_build_download_and_prepare_a_dataset
