### ISSUE TITLE
CleanUp Dataset Code

### ISSUE THREAD

**Issue by vijayphoenix** [tensorflow/datasets#2460]
**Short description**
Recently, the bug #2423 related to the auto-detection of filename and extension was fixed.

So, we can remove some unnecessary code from the datasets given below.

Steps:
* Remove `tfds.download.resource` from the datasets given below.
* Download and prepare the datasets.
* Add the link to generated `dataset_info.json`

For reference, see https://github.com/tensorflow/datasets/commit/9a78f9eba3ce2ca2d69083b1de33e98722e08ef7

* [x] audio/tedlium
* [x] audio/spoken_digit/spoken_digit
* [x] image/arc
* [x] image/bccd/
* [x] image_classification/cbis_ddsm
* [x] image_classification/deep_weeds
* [x] image_classification/dtd
* [x] image_classification/geirhos_conflict_stimuli
* [ ] image_classification/inaturalist
* [x] image_classification/oxford_flowers102
* [x] image_classification/oxford_iiit_pet
* [ ] image_classification/sun
* [x] image_classification/visual_domain_decathlon
* [ ] object_detection/open_images
* [x] summarization/aeslc
* [x] text/gpt3
* [x] text/irc_disentanglement
* [x] text/scan

**Comment by SuryashankarDas** [comment]
If no one is already working on it, I would like to work on this. btw, should i squash it all in a single commit or do it one by one?

**Comment by Keshav15** [comment]
I would Also  like to work on this issue

**Comment by vijayphoenix** [comment]
Please fix only 3-5 datasets per pull request.
Feel free to distribute the work among yourself.

**Comment by Ak0303** [comment]
I would also like to work on this !!

**Comment by vijayphoenix** [comment]
This issue seems to be fixed.
