### ISSUE TITLE
Problem with checksum value for imagenet_v2 dataset

### ISSUE THREAD

**Issue by shahaf-m** [tensorflow/datasets#2461]
Hey,

I'm getting this error when trying to work with [imagenet_v2 dataset](https://www.tensorflow.org/datasets/catalog/imagenet_v2), The website is up and running and it is not a google drive or a new dataset. Could you please look into it?
Thank you!

tensorflow_datasets.core.download.download_manager.NonMatchingChecksumError: Artifact https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-matched-frequency.tar.gz, downloaded to C:\SPB_Data\tensorflow_datasets\downloads\s3-us-west-2_image_image-match-frequc56VsOLVttUFrJ7Ka21jcV9uodSP_TSQV-yxfB4t3_U.tar.gz.tmp.1d28266042254fc39e0e56ff1246d0c5\imagenetv2-matched-frequency.tar.gz, has wrong checksum. This might indicate:
 * The website may be down (e.g. returned a 503 status code). Please check the url.
 * For Google Drive URLs, try again later as Drive sometimes rejects downloads when too many people access the same URL. See https://github.com/tensorflow/datasets/issues/1482
 * The original datasets files may have been updated. In this case the TFDS dataset builder should be updated to use the new files and checksums. Sorry about that. Please open an issue or send us a PR with a fix.
 * If you're adding a new dataset, don't forget to register the checksums as explained in: https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally

**Environment information**
* Operating System: windows 10
* Python version: 3.6.1
* `tensorflow-datasets version: 3.2.1

**Comment by pkubik** [comment]
Looks like directory structure has been changed again and now:
- The checksum is obviously wrong
- The code doesn't work even after manual unpacking

The previous convention was `<class_id>/<filename>` where `<class_id>` is one of [0, 1000) classes. Now it seems like they retreated to the original ImageNet convention with `<synset_id>/<filename>`. I guess the original `imagenet2012` code can be reused to make it work.
