### ISSUE TITLE
Command tfds.as_dataframe fails to make dataframe 

### ISSUE THREAD

**Issue by rd16395p** [tensorflow/datasets#2476]
**Short description**
When I call tfds.as_dataframe, it gives the error below. 

**Environment information**
* Operating System: Ubuntu 20.04
* Python version: 3.8
* `tensorflow-datasets`/`tfds-nightly` version: tfds-nightly v3.2.1.dev202009090105
* `tensorflow`/`tf-nightly` version: tensorflow v2.3

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? Yes

**Reproduction instructions**

```
import tensorflow.compat.v2 as tf
import tensorflow_datasets as tfds
import pandas as pd

tfds.disable_progress_bar()
tf.enable_v2_behavior()

(ds_train, ds_test), ds_info = tfds.load(
    'mnist',
    split=['train', 'test'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True,
)

def normalize_img(image, label):
  """Normalizes images: `uint8` -> `float32`."""
  return tf.cast(image, tf.float32) / 255., label

ds_test = ds_test.map(
    normalize_img, num_parallel_calls=tf.data.experimental.AUTOTUNE)
ds_test = ds_test.batch(128)
ds_test = ds_test.cache()
ds_test = ds_test.prefetch(tf.data.experimental.AUTOTUNE)

df = tfds.as_dataframe(ds_test.take(10), ds_info)
```

**Link to logs**

```
Traceback (most recent call last):
  File "mnist_test.py", line 31, in <module>
    df = tfds.as_dataframe(ds_test.take(10), ds_info)
  File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow_datasets/core/as_dataframe.py", line 192, in as_dataframe
    columns = _make_columns(ds.element_spec, ds_info=ds_info)
  File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow_datasets/core/as_dataframe.py", line 148, in _make_columns
    return [
  File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow_datasets/core/as_dataframe.py", line 149, in <listcomp>
    ColumnInfo.from_spec(path, ds_info)
  File "/home/ubuntu/miniconda3/envs/tensorflow/lib/python3.8/site-packages/tensorflow_datasets/core/as_dataframe.py", line 61, in from_spec
    name = '/'.join(path)
TypeError: sequence item 0: expected str instance, int found
```

**Expected behavior**
Conversion from dataset to into a pandas dataframe

**Comment by Conchylicultor** [comment]
Thank you for reporting the issue. This is because `tfds.as_dataframe` does not support `as_supervised=True` when `ds_info` is set. I'm sending a fix for this now.

However, what are you trying to use as_dataframe for ? If this is for visualization, you shouldn't batch, nor normalize image before calling `as_dataframe`.

**Comment by rd16395p** [comment]
@Conchylicultor Just an application I have.

Should I load the dataset with as_supervised=True?

**Comment by Conchylicultor** [comment]
If you do NOT use `tfds.as_dataframe` for visualization, then: do no pass `ds_info`:

```py
df = tfds.as_dataframe(ds_test.take(10))
```

**Comment by rd16395p** [comment]
Ok, thank you!

**Comment by riibeirogabriel** [comment]
Hi everyone, i have the same issue when trying run this code
```python
import tensorflow_datasets as tfds
(ds_train, ds_test), ds_info = tfds.load(
    'mnist',
    split=['train', 'test'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True,
)
ds_train = tfds.as_dataframe(ds_train)
ds_test = tfds.as_dataframe(ds_test)

```

**Comment by Conchylicultor** [comment]
@riibeirogabriel Make sure you're using the last TFDS version by installing `tfds-nightly`

**Comment by mirik123** [comment]
I have the same issue with versions:
- tensorflow==2.4.1 
- tensorflow-datasets==4.2.0

**Comment by Conchylicultor** [comment]
The fix was added in tfds-nightly. Make sure you install this.

**Comment by mainguyenanhvu** [comment]
I have the same issue with versions:
- tfds-nightly-4.4.0.dev202108110107
- tensorflow == 2.5.0

Please help me. Thank you very much.

**Comment by Conchylicultor** [comment]
> I have the same issue with versions:
> 
> * tfds-nightly-4.4.0.dev202108110107
> * tensorflow == 2.5.0
> 
> Please help me. Thank you very much.

Could you share snippet/stacktrace ?

**Comment by mainguyenanhvu** [comment]
I found that the type of df columns is not string. Therefore, I edited the code line create df column names in origin code by using type casting to fix it.

**Comment by antoine-carpentier** [comment]
I am running into the same issue trying to turn my datasets into dataframes

    import tensorflow as tf
    import tensorflow_datasets as tfds

    batch_size = 32
    img_height = 180
    img_width = 180

    art_directory = 'C:/Users/elver/Documents/Art/VanGoghML'

    train_ds = tf.keras.utils.image_dataset_from_directory(
        art_directory,
        validation_split=0.3,
        subset="training",
        seed=123,
        image_size=(img_height, img_width),
        batch_size=batch_size
    )

    val_ds = tf.keras.utils.image_dataset_from_directory(
        art_directory,
        validation_split=0.3,
        subset="validation",
        seed=123,
        image_size=(img_height, img_width),
        batch_size=batch_size
    )


    df_train = tfds.as_dataframe(train_ds)
    df_test = tfds.as_dataframe(val_ds)


Here is the log:

```
Traceback (most recent call last):
  File "C:\Users\elver\PycharmProjects\ds_to_csv\main.py", line 44, in <module>
    ds_to_csv()
  File "C:\Users\elver\PycharmProjects\ds_to_csv\main.py", line 35, in ds_to_csv
    df_train = tfds.as_dataframe(train_ds)
  File "C:\Users\elver\PycharmProjects\ds_to_csv\venv\lib\site-packages\tensorflow_datasets\core\as_dataframe.py", line 216, in as_dataframe
    columns = _make_columns(ds.element_spec, ds_info=ds_info)
  File "C:\Users\elver\PycharmProjects\ds_to_csv\venv\lib\site-packages\tensorflow_datasets\core\as_dataframe.py", line 168, in _make_columns
    return [
  File "C:\Users\elver\PycharmProjects\ds_to_csv\venv\lib\site-packages\tensorflow_datasets\core\as_dataframe.py", line 169, in <listcomp>
    ColumnInfo.from_spec(path, ds_info)
  File "C:\Users\elver\PycharmProjects\ds_to_csv\venv\lib\site-packages\tensorflow_datasets\core\as_dataframe.py", line 64, in from_spec
    name = '/'.join(path)
TypeError: sequence item 0: expected str instance, int found
```

**Comment by mainguyenanhvu** [comment]
Please access this file: C:\Users\elver\PycharmProjects\ds_to_csv\venv\lib\site-packages\tensorflow_datasets\core\as_dataframe.py
And cast path into str:
name = '/'.join(map(str,path))

**Comment by antoine-carpentier** [comment]
Casting the path to str and then installing jinja2 package fixed it!
Thanks for the very swift help.
