### ISSUE TITLE
[data request] COCO 2018

### ISSUE THREAD

**Issue by rodrigob** [tensorflow/datasets#25]
* Name of dataset: COCO 2018
* URL of dataset: http://cocodataset.org/#panoptic-2018
* License of dataset: CC 4.0 see http://cocodataset.org/#termsofuse
* Short description of dataset and use case(s): Thing and stuff annotations over Coco images

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by kaustumbh7** [comment]
Can anyone please guide me what all has to be done here? I am interested in working on this.

**Comment by Conchylicultor** [comment]
That would be great. Thank you!
It shouldn't be too much work.

You can look at the current Coco2014 to create a similar Coco2018 by changing the downloaded data used. Try to reuse code as possible (by using inheritance).
https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/coco.py

Additionally, while doing this, it would be great if you also where adding a `"image/id": tfds.features.Text(),` field to the `FeaturesDict` corresponding to the Coco image_id associated with each image. This was another feature requested by some users. This is required to use the official Coco evaluation tool.

**Comment by kaustumbh7** [comment]
Okay. No problem! If I have any doubts can I ask you @Conchylicultor ?

**Comment by Conchylicultor** [comment]
Yes of course, don't hesitate if you encounter any issues

**Comment by kaustumbh7** [comment]
@rodrigob Can you please share the link from where the dataset can be downloaded ? I am unable to find it because it is not available in the COCO api.

**Comment by Conchylicultor** [comment]
I simply found the links from the official website: http://cocodataset.org/#download

I think 2018 uses the same data from 2017 (see http://cocodataset.org/#panoptic-2018):
`Participants are recommended but not restricted to train their algorithms on COCO 2017 train and val sets. The download page has links to all COCO 2017 data.`

The dataset should be named `Coco2017` then

**Comment by Conchylicultor** [comment]
I agree their website is confusing. from what I understand, "2017 Train/Val/Test"should contains 2018 annotations:
`2017 Train/Val/Test:  Detection 2017, Keypoints 2017, Stuff 2017, Detection 2018, Keypoints 2018, Stuff 2018, Panoptic 2018`

`Note: the split year refers to the year the image splits were released, not the year in which the annotations were released.`

**Comment by kaustumbh7** [comment]
Yes, even I thought so. Thanks for the help! 😊

**Comment by pyaf** [comment]
Hey, @kaustumbh7 are you taking up this issue? If not, then I would like to take this up. I've used COCO dataset in some of my object detection projects, and I'm well familiar with it. :)

**Comment by kaustumbh7** [comment]
Hey, @pyaf I would like to take this up issue and have already started working on it 😊

**Comment by pyaf** [comment]
Cool :)

**Comment by kaustumbh7** [comment]
@Conchylicultor The panoptic annotations for COCO-2017 contains annotation in both json and image form. So in `builder._generate_examples` how should I yield the feature dictionaries?

**Comment by Conchylicultor** [comment]
@kaustumbh7 

> The panoptic annotations for COCO-2017 contains annotation in both json and image form. So in builder._generate_examples how should I yield the feature dictionaries?

I think the user expect information as image as this is the simplest to manipulate.
```
{
    'image': tfds.feature.Image(...),
    'panoptic': tfds.feature.Image(...),  # Segmentation mask
    'objects': tfds.SequenceDict({
        'bboxes': tfds.features.BBoxes(),
        ...
    })
}
```
However as a first iteration, you may want to drop the segmentation annotations, similarly to `Coco2014`. Those can be added later on.

> I found out that unlike COCO detection format that stores each segment independently, COCO panoptic format stores all segmentations for an image in a single PNG file.

Segmentation correspond to image mask, so it make sense to store them to as png. BBoxes are coordinates, so it make sense that the representation is different.

> So I think the main change that I have to make to current Coco2014 is to have builder._generate_examples yield multiple bbox instead of just one for each annotation.

I'm not sure that I understand this one. The current coco2014 allow for multiple bboxes for each image. Do you mean that a single object instance may be associated with multiple bboxes ? Can you post an example of this ? BBoxes and panoptic segmentation annotations are two different types of annotations.

**Comment by kaustumbh7** [comment]
@Conchylicultor I meant each annotation in Coco-2014 has a single `bbox` where as Coco Panoptic has multiple `bbox` in `segmentation` for each annotation.

So for the first iteration, leaving `segmentation` from annotations leaves us with only `image_id` and `file_name`. 

Information to the user will be returned as-
`
{
    'image': tfds.feature.Image(...),
     'image_name': tfds.feature.Text(...)
    'panoptic': tfds.feature.Image(...),  # Segmentation mask
    'panoptic_name': tfds.feature.Text(...) 
    })
}
`

**Comment by Conchylicultor** [comment]
By `segmentation`, I meant the mask segmentation task (so the mask png images), not the `segments_info` field in the `json` file. It is important that bounding boxes are present in the `FeatureDict`.

I do not really understand what you mean by `Coco2014` has a single bbox per annotation.
Are you talking about the json format which encode the data ? If so, yes, it is possible that the .json format for 2014 and 2017 has changed. If so, you may not be able to reuse the Coco2014 generation code for the 2017 version.

For 2018, by quickly exploring the data:

```python
with open('.../panoptic_annotations_trainval2017/annotations/panoptic_val2017.json') as f:
  data = json.load(f)
print(data['annotations'][0])  # Print annotation of first image
```

Gives me:
```
{u'file_name': u'000000000139.png',
 u'image_id': 139,
 u'segments_info': [{u'area': 2840,
   u'bbox': [413, 158, 53, 138],
   u'category_id': 1,
   u'id': 3226956,
   u'iscrowd': 0},
  {u'area': 439,
...
  {u'area': 12618,
   u'bbox': [135, 359, 336, 67],
   u'category_id': 200,
   u'id': 6391959,
   u'iscrowd': 0}]}
```

So it seems that each image contains a list of bboxes, similarly to 2014, but in a slightly different format.
I'm not sure if this help.

**Comment by kaustumbh7** [comment]
> By `segmentation`, I meant the mask segmentation task (so the mask png images), not the `segments_info` field in the `json` file. It is important that bounding boxes are present in the `FeatureDict`.
> 
> I do not really understand what you mean by `Coco2014` has a single bbox per annotation.
> Are you talking about the json format which encode the data ? If so, yes, it is possible that the .json format for 2014 and 2017 has changed. If so, you may not be able to reuse the Coco2014 generation code for the 2017 version.
Yes, I meant the .json format. 
> 
> For 2018, by quickly exploring the data:
> 
> ```python
> with open('.../panoptic_annotations_trainval2017/annotations/panoptic_val2017.json') as f:
>   data = json.load(f)
> print(data['annotations'][0])  # Print annotation of first image
> ```
> 
> Gives me:
> 
> ```
> {u'file_name': u'000000000139.png',
>  u'image_id': 139,
>  u'segments_info': [{u'area': 2840,
>    u'bbox': [413, 158, 53, 138],
>    u'category_id': 1,
>    u'id': 3226956,
>    u'iscrowd': 0},
>   {u'area': 439,
> ...
>   {u'area': 12618,
>    u'bbox': [135, 359, 336, 67],
>    u'category_id': 200,
>    u'id': 6391959,
>    u'iscrowd': 0}]}
> ```
> So it seems that each image contains a list of bboxes, similarly to 2014, but in a slightly different format.
> I'm not sure if this help.
Yes, I know the format is slightly different. I am working on it and will soon be ready with a pull request. Thanks for the help! 😊

**Comment by kaustumbh7** [comment]
@Conchylicultor Should I be assigned to this issue before raising a pull request?

**Comment by Conchylicultor** [comment]
Sure, please send the pull request.

**Comment by cyfra** [comment]
This dataset was added.
