### ISSUE TITLE
Allow images with 4 channels in Image FeatureConnector for png encoding

### ISSUE THREAD

**Issue by tobiasmaier** [tensorflow/datasets#2503]
**Is your feature request related to a problem? Please describe.**
I have RGBA images that I would like to use with TFDS using the Image FeatureConnector.

**Describe the solution you'd like**
Add 4 channels to ACCEPTABLE_CHANNELS for png encoding.
```
ACCEPTABLE_CHANNELS = {
    'png': (0, 1, 2, 3, 4),
    'jpeg': (0, 1, 3),
}
```

**Describe alternatives you've considered**
Currently this requires me subclass tfds.features.Image to allow 4 channel images.

**Additional context**
2 channel images (grayscale+alpha) are already specified in ACCEPTABLE_CHANNELS for png encoding. Allowing all 
supported channels would be consistent.

**Comment by Conchylicultor** [comment]
I believe that when we added `tfds.features.Image`, `tf.image.decode` didn't supported image yet.

Please don't hesitate to send a PR to fix this (with a test to make sure this is working).
