### ISSUE TITLE
Tensorflow Datasets TypeError: __array__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by whatwilliam** [tensorflow/datasets#2513]
**Short description**
Draft of #2399
I created a tensorflow datset code that takes in a folder of mp3 files and a dictionary that matches the mp3s to their labels and returns two tensors, an audio tensor and a label tensor. tfds.load is able to run and create a dataset however when running a tfds test, it is unable to run test_download_and_prepare_as_datset.

**Environment information**
* Python version: 3.8.0
* `tensorflow-datasets` version: 3.2.1
* `tensorflow` version: 2.3.0

**Logs**

```
2020-10-02 00:20:54.722953: I tensorflow_io/core/kernels/cpu_check.cc:128] Your CPU supports instructions that this TensorFlow IO binary was not compiled to use: AVX2 FMA
Running tests under Python 3.7.8: /opt/conda/bin/python3
[ RUN      ] AudioSetTest.test_baseclass
INFO:tensorflow:time(__main__.AudioSetTest.test_baseclass): 0.26s
I1002 00:20:55.194009 140623569565056 test_util.py:1973] time(__main__.AudioSetTest.test_baseclass): 0.26s
[       OK ] AudioSetTest.test_baseclass
[ RUN      ] AudioSetTest.test_download_and_prepare_as_dataset
Total configs: 0
I1002 00:20:55.196529 140623569565056 dataset_builder.py:358] Generating dataset audioset (/tmp/runmulqsrjk/tmp04tb3m6j/audioset/0.1.0)
Downloading and preparing dataset audioset/0.1.0 (download: Unknown size, generated: Unknown size, total: Unknown size) to /tmp/runmulqsrjk/tmp04tb3m6j/audioset/0.1.0...
I1002 00:20:55.240417 140623569565056 dataset_builder.py:988] Generating split train
0 examples [00:00, ? examples/s]2020-10-02 00:20:55.405197: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2300000000 Hz
2020-10-02 00:20:55.406191: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a36ca68a90 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-02 00:20:55.406231: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-02 00:20:55.406430: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2020-10-02 00:20:55.407146: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at whole_file_read_ops.cc:116 : Failed precondition: /home/jupyter/datasets/tensorflow_datasets/testing/test_data/fake_examples/audioset/trimmed_audio/.ipynb_checkpoints; Is a directory
Shuffling and writing examples to /tmp/runmulqsrjk/tmp04tb3m6j/audioset/0.1.0.incompleteWO0GI5/audioset-train.tfrecord
  0%|                                                                                                                                                                        | 0/4 [00:00<?, ? examples/s]I1002 00:20:55.907156 140623569565056 tfrecords_writer.py:226] Done writing /tmp/runmulqsrjk/tmp04tb3m6j/audioset/0.1.0.incompleteWO0GI5/audioset-train.tfrecord. Shard lengths: [4]
/opt/conda/lib/python3.7/site-packages/apache_beam/typehints/typehints.py:524: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if not isinstance(type_params, (collections.Sequence, set)):
I1002 00:20:56.328425 140623569565056 dataset_builder.py:413] Skipping computing stats for mode ComputeStatsMode.SKIP.
Dataset audioset downloaded and prepared to /tmp/runmulqsrjk/tmp04tb3m6j/audioset/0.1.0. Subsequent calls will reuse this data.
I1002 00:20:56.329698 140623569565056 dataset_builder.py:512] Constructing tf.data.Dataset for split train, from /tmp/runmulqsrjk/tmp04tb3m6j/audioset/0.1.0
I1002 00:20:56.386478 140623569565056 dataset_builder.py:512] Constructing tf.data.Dataset for split train, from /tmp/runmulqsrjk/tmp04tb3m6j/audioset/0.1.0
I1002 00:20:56.650481 140623569565056 dataset_info.py:355] Load dataset info from /tmp/runmulqsrjk/tmp04tb3m6j/audioset/0.1.0
I1002 00:20:56.651347 140623569565056 dataset_builder.py:512] Constructing tf.data.Dataset for split train, from /tmp/runmulqsrjk/tmp04tb3m6j/audioset/0.1.0
I1002 00:20:56.678382 140623569565056 dataset_builder.py:512] Constructing tf.data.Dataset for split train, from /tmp/runmulqsrjk/tmp04tb3m6j/audioset/0.1.0
INFO:tensorflow:time(__main__.AudioSetTest.test_download_and_prepare_as_dataset): 1.6s
I1002 00:20:56.796965 140623569565056 test_util.py:1973] time(__main__.AudioSetTest.test_download_and_prepare_as_dataset): 1.6s
WARNING:tensorflow:From /opt/conda/lib/python3.7/contextlib.py:82: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
W1002 00:20:56.799427 140623569565056 deprecation.py:323] From /opt/conda/lib/python3.7/contextlib.py:82: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
2020-10-02 00:20:56.800127: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Total configs: 0
I1002 00:20:56.800700 140623569565056 dataset_builder.py:358] Generating dataset audioset (/tmp/runmulqsrjk/tmp8uycbooq/audioset/0.1.0)
Downloading and preparing dataset audioset/0.1.0 (download: Unknown size, generated: Unknown size, total: Unknown size) to /tmp/runmulqsrjk/tmp8uycbooq/audioset/0.1.0...
I1002 00:20:56.801388 140623569565056 dataset_builder.py:988] Generating split train
INFO:tensorflow:time(__main__.AudioSetTest.test_download_and_prepare_as_dataset): 0.05s
I1002 00:20:56.847491 140623569565056 test_util.py:1973] time(__main__.AudioSetTest.test_download_and_prepare_as_dataset): 0.05s
[  FAILED  ] AudioSetTest.test_download_and_prepare_as_dataset
Exception ignored in: <generator object Audioset._generate_examples at 0x7fe419f3c7d0>
RuntimeError: generator ignored GeneratorExit
[ RUN      ] AudioSetTest.test_info
INFO:tensorflow:time(__main__.AudioSetTest.test_info): 0.0s
I1002 00:20:56.863561 140623569565056 test_util.py:1973] time(__main__.AudioSetTest.test_info): 0.0s
[       OK ] AudioSetTest.test_info
[ RUN      ] AudioSetTest.test_registered
INFO:tensorflow:time(__main__.AudioSetTest.test_registered): 0.0s
I1002 00:20:56.865559 140623569565056 test_util.py:1973] time(__main__.AudioSetTest.test_registered): 0.0s
[       OK ] AudioSetTest.test_registered
[ RUN      ] AudioSetTest.test_session
[  SKIPPED ] AudioSetTest.test_session
======================================================================
ERROR: test_download_and_prepare_as_dataset (__main__.AudioSetTest)
test_download_and_prepare_as_dataset (__main__.AudioSetTest)
Run the decorated test method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jupyter/datasets/tensorflow_datasets/testing/test_utils.py", line 341, in decorated
    f(self, *args, **kwargs)
  File "/home/jupyter/datasets/tensorflow_datasets/testing/dataset_builder_testing.py", line 306, in test_download_and_prepare_as_dataset
    self._download_and_prepare_as_dataset(self.builder)
  File "/home/jupyter/datasets/tensorflow_datasets/testing/dataset_builder_testing.py", line 370, in _download_and_prepare_as_dataset
    builder.download_and_prepare(download_config=download_config)
  File "/home/jupyter/datasets/tensorflow_datasets/core/dataset_builder.py", line 388, in download_and_prepare
    download_config=download_config)
  File "/home/jupyter/datasets/tensorflow_datasets/core/dataset_builder.py", line 1042, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "/home/jupyter/datasets/tensorflow_datasets/core/dataset_builder.py", line 992, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/home/jupyter/datasets/tensorflow_datasets/core/dataset_builder.py", line 1058, in _prepare_split
    example = self.info.features.encode_example(record)
  File "/home/jupyter/datasets/tensorflow_datasets/core/features/features_dict.py", line 195, in encode_example
    in utils.zip_dict(self._feature_dict, example_dict)
  File "/home/jupyter/datasets/tensorflow_datasets/core/features/features_dict.py", line 194, in <dictcomp>
    for k, (feature, example_value)
  File "/home/jupyter/datasets/tensorflow_datasets/core/features/feature.py", line 605, in encode_example
    example_data = np.array(example_data, dtype=np_dtype)
TypeError: __array__() takes 1 positional argument but 2 were given

----------------------------------------------------------------------
Ran 5 tests in 1.928s

FAILED (errors=1, skipped=1)
```

link to audioset.py: https://github.com/whatwilliam/datasets/blob/master/tensorflow_datasets/audio/audioset.py
link to audioset_test.py: https://github.com/whatwilliam/datasets/blob/master/tensorflow_datasets/audio/audioset_test.py
test data location: https://github.com/whatwilliam/datasets/tree/master/tensorflow_datasets/testing/test_data/fake_examples/audioset

Relvant Code:
```python
def _generate_examples(self, data_dir=None):
        """Yields examples."""
        my_files = tf.io.gfile.listdir(os.path.join(data_dir, 'trimmed_audio')) #gets list of files in folder given
        with tf.io.gfile.GFile(os.path.join(data_dir, 'id2label.json'), "r") as read_file: #uses json to match ids to labels
            datas = json.load(read_file)
        
        for f in my_files:
            try:
                label_list = []
                filepath = os.path.join(data_dir,'trimmed_audio',f)
                audio_binary = tf.io.read_file(filepath)
                audio_tensor = tfio.audio.decode_mp3(audio_binary) #audio_tensor read and decoded
                ids = f.replace(".mp3","")
                for x in datas[ids]:
                    indices_list = []
                    for y in x:
                        label_list.append(y) #gets multiple labels that apply to audio in a list in label_list
                    for i in label_list:
                        indice = []
                        indice.append(i)
                        indices_list.append(indice)
                    indices = tf.constant(indices_list, dtype=tf.int32)
                    updates = tf.ones(len(indices_list), dtype=tf.int32)
                    label_tensor = tf.zeros(527, dtype=tf.int32)
                    label_tensor = tf.tensor_scatter_nd_add(label_tensor, indices, updates) # creates a tensor of zeros with ones at indices that indicate positive for a label
                    break
                yield f, {
                    'audio': audio_tensor,
                    'label': label_tensor,
                }
            except:
                pass
```

**Expected behavior**
It should pass all tests because I'm able to load a dataset with tfds.load successfully using this code:

```python
ds = tfds.load('audioset', data_dir='bucketpath', download_and_prepare_kwargs={
    'download_config': tfds.download.DownloadConfig(manual_dir='bucketpath/manual', compute_stats=tfds.download.ComputeStatsMode['SKIP'])
})
```

**Comment by Conchylicultor** [comment]
I think the reason you're seing this error is because you're yielding `tf.Tensor`:

Instead during generation you should yield `np.array`, `int`,... for the audio, you can directly yield the filepath:

```py
                yield f, {
                    'audio': filepath,
                    'label': 32,
                }
```

TFDS will automatically convert the int, str into `tf.Tensor`

**Comment by whatwilliam** [comment]
I had the program yield the filepath and had the label feature take in a list of ints and it worked! Thank you so much.

**Comment by whatwilliam** [comment]
'''
CouldntDecodeError                        Traceback (most recent call last)
<ipython-input-4-4b6210c7bbc3> in <module>
      1 ds = tfds.load('audioset', data_dir='gs://bme590/william/cake5', download_and_prepare_kwargs={
----> 2     'download_config': tfds.download.DownloadConfig(manual_dir='gs://bme590/william/manual', compute_stats=tfds.download.ComputeStatsMode['SKIP'])
      3 })

~/datasets/tensorflow_datasets/core/load.py in load(name, split, data_dir, batch_size, shuffle_files, download, as_supervised, decoders, read_config, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
    312   if download:
    313     download_and_prepare_kwargs = download_and_prepare_kwargs or {}
--> 314     dbuilder.download_and_prepare(**download_and_prepare_kwargs)
    315 
    316   if as_dataset_kwargs is None:

~/datasets/tensorflow_datasets/core/dataset_builder.py in download_and_prepare(self, download_dir, download_config)
    386           self._download_and_prepare(
    387               dl_manager=dl_manager,
--> 388               download_config=download_config)
    389 
    390           # NOTE: If modifying the lines below to put additional information in

~/datasets/tensorflow_datasets/core/dataset_builder.py in _download_and_prepare(self, dl_manager, download_config)
   1040     super(GeneratorBasedBuilder, self)._download_and_prepare(
   1041         dl_manager=dl_manager,
-> 1042         max_examples_per_split=download_config.max_examples_per_split,
   1043     )
   1044 

~/datasets/tensorflow_datasets/core/dataset_builder.py in _download_and_prepare(self, dl_manager, **prepare_split_kwargs)
    990 
    991       # Prepare split will record examples associated to the split
--> 992       self._prepare_split(split_generator, **prepare_split_kwargs)
    993 
    994     # Update the info object with the splits.

~/datasets/tensorflow_datasets/core/dataset_builder.py in _prepare_split(self, split_generator, max_examples_per_split)
   1056     for key, record in utils.tqdm(generator, unit=" examples",
   1057                                   total=split_info.num_examples, leave=False):
-> 1058       example = self.info.features.encode_example(record)
   1059       writer.write(key, example)
   1060     shard_lengths, total_size = writer.finalize()

~/datasets/tensorflow_datasets/core/features/features_dict.py in encode_example(self, example_dict)
    193         k: feature.encode_example(example_value)
    194         for k, (feature, example_value)
--> 195         in utils.zip_dict(self._feature_dict, example_dict)
    196     }
    197 

~/datasets/tensorflow_datasets/core/features/features_dict.py in <dictcomp>(.0)
    192     return {
    193         k: feature.encode_example(example_value)
--> 194         for k, (feature, example_value)
    195         in utils.zip_dict(self._feature_dict, example_dict)
    196     }

~/datasets/tensorflow_datasets/core/features/audio_feature.py in encode_example(self, audio_or_path_or_fobj)
     75       file_format = self._file_format or filename.split('.')[-1]
     76       with tf.io.gfile.GFile(filename, 'rb') as audio_f:
---> 77         return self._encode_file(audio_f, file_format)
     78     else:
     79       return self._encode_file(audio_or_path_or_fobj, self._file_format)

~/datasets/tensorflow_datasets/core/features/audio_feature.py in _encode_file(self, fobj, file_format)
     63   def _encode_file(self, fobj, file_format):
     64     audio_segment = lazy_imports_lib.lazy_imports.pydub.AudioSegment.from_file(
---> 65         fobj, format=file_format)
     66     np_dtype = np.dtype(self.dtype.as_numpy_dtype)
     67     return super(Audio, self).encode_example(

/opt/conda/lib/python3.7/site-packages/pydub/audio_segment.py in from_file(cls, file, format, codec, parameters, **kwargs)
    723             raise CouldntDecodeError(
    724                 "Decoding failed. ffmpeg returned error code: {0}\n\nOutput from ffmpeg/avlib:\n\n{1}".format(
--> 725                     p.returncode, p_err.decode(errors='ignore') ))
    726 
    727         p_out = bytearray(p_out)

CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7.5.0 (crosstool-NG 1.24.0.131_87df0e6_dirty)
  configuration: --prefix=/opt/conda --cc=/home/conda/feedstock_root/build_artifacts/ffmpeg_1596712246804/_build_env/bin/x86_64-conda-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[cache @ 0x557950c345c0] Inner protocol failed to seekback end : -38
    Last message repeated 1 times
[mp3 @ 0x557950c33d40] Failed to read frame size: Could not seek to 1026.
[cache @ 0x557950c345c0] Statistics, cache hits:2 cache misses:1
cache:pipe:0: Invalid argument
'''
So it seems that when I use tfds.load with just a filepath given to tfds.features.Audio, though it passes testing, it seems that pydub can't decode one or possible more of my mp3 files. There are a lot of files in the folder, is there anyway for me to catch this 'Couldn'tDecodeError' and just ignore it and move on in the load?

**Comment by Conchylicultor** [comment]
You could hardcode the files which are buggy and filter them. I'm sending a PR to improve error message.

**Comment by whatwilliam** [comment]
I was able to run through the load successfully by doing what you suggested and running Audiosegment.from_file within the try catch of the generate examples. Thank you so much!

**Comment by flutterq2** [comment]
[[already solved] TypeError: __array__() takes 1 positional argument but 2 were given](https://exerror.com/typeerror-array-takes-1-positional-argument-but-2-were-given/)
