### ISSUE TITLE
Eager or not eager? TF 2.0 or TF 1?

### ISSUE THREAD

**Issue by drozzy** [tensorflow/datasets#252]
It's confusing to a newcomer whether tf datasets works with eager or non-eager by default.
Is enabling eager the same as using TF 2.0?

The presentation of this was at the TF 2.0 announcement, so I kind of assumed this was part of TF 2.0:
https://www.youtube.com/watch?v=-nTe44WT0ZI

But it seems it is separate.

Just pointing out some potential confusion.
Thanks!

**Comment by rsepassi** [comment]
Thanks. Maybe we should make it more clear on the README. TFDS works in both Eager and Graph modes and with TF 1.12+ and 2.0.

**Comment by drozzy** [comment]
Ok got it!

One more question - how would I do something like this - create a vocabulary of indicies (example from torchtext - where `build_vocab` builds a vocab):

```
TEXT = data.Field()
LABELS = data.Field()

train, val, test = data.TabularDataset.splits(
    path='/data/pos_wsj/pos_wsj', train='_train.tsv',
    validation='_dev.tsv', test='_test.tsv', format='tsv',
    fields=[('text', TEXT), ('labels', LABELS)])

train_iter, val_iter, test_iter = data.BucketIterator.splits(
    (train, val, test), batch_sizes=(16, 256, 256),
    sort_key=lambda x: len(x.text), device=0)

TEXT.build_vocab(train)
LABELS.build_vocab(train)
```
