### ISSUE TITLE
`version` should be optional for `BuilderConfig`

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2522]
The vast majority of `BuilderConfig` are using the same version and are updated at the same time. It is boilerplate to have to specify the version for each config. Instead, the global version should be used by default.

Before:
```py
class MyDataset:
  BUILDER_CONFIGS = [
      tfds.core.BuilderConfig('en', version='1.0.0'),
      tfds.core.BuilderConfig('fr', version='1.0.0'),
  ]
```

After
```py
class MyDataset:
  BUILDER_CONFIGS = [
      tfds.core.BuilderConfig('en'),
      tfds.core.BuilderConfig('fr'),
  ]
  VERSION = tfds.core.Version('1.0.0')
```
If both global and `BuilderConfig` versions are specified, the `BuilderConfig` version should be used.

**Comment by codeboy5** [comment]
Hey i was interested in taking up this issue. 
So what we want is that inside the `DatasetBuilder` class, we should set the version to the global version if that argument is not passed and to the value if argument is passed.
Is that the right way to go about it ? @Conchylicultor

**Comment by Conchylicultor** [comment]
Yes, exactly: `builder.version` should be `.VERSION` if `builder.builder_config.version` do not exists.

**Comment by Nikhil1O1** [comment]
@Conchylicultor I made an attempt to fix this, But i need you to see whether they are appropriate or not. If they are i will apply these changes to remaining files.

**Comment by Conchylicultor** [comment]
@Nikhil1O1 , thank you! But the PR you linked seems unrelated to this issue. Is it expected ?

**Comment by Nikhil1O1** [comment]
> @Nikhil1O1 , thank you! But the PR you linked seems unrelated to this issue. Is it expected ?

Ohh looks like I submitted a wrong branch, My apologies for this.
But I only meant for the changes i made in fuss.py
Please go through it while i rectify my mistake.

**Comment by Nikhil1O1** [comment]
@Conchylicultor I submitted a fresh PR, I hope this meets your expectations.

**Comment by Conchylicultor** [comment]
I'm still not sure I understand how this is related to this issue. For instance, you should add test to check that

```py
class MyDataset:
  BUILDER_CONFIGS = [
      tfds.core.BuilderConfig('en'),
      tfds.core.BuilderConfig('fr'),
  ]
  VERSION = tfds.core.Version('1.0.0')

builder('my_dataset/en').version == '1.0.0'
```

**Comment by Nikhil1O1** [comment]
@Conchylicultor  looks like I picked an issue that i'm not ready to deal with. 
But still can you point where is the concerned file you intend to modify?

**Comment by Conchylicultor** [comment]
The files to modified would be `core/dataset_builder.py` and `core/dataset_builder_test.py`

**Comment by Nikhil1O1** [comment]
> Yes, exactly: `builder.version` should be `.VERSION` if `builder.builder_config.version` do not exists.
> And similarly for release notes. We could add a `builder.release_notes` `@property` which select `builder.RELEASE_NOTES` or `builder.builder_config.release_notes`

```
if builder.builder_config.version == True:
    builder.version = builder.VERSION

else:
    pass
```
Is this snippet getting close to becomming correct?  😬
