### ISSUE TITLE
Add config_description to the dataset_info.proto

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2541]
Similar to #2326 but for the config description.

Currently, only the `DatasetInfo.description` is saved in `dataset_info.json`, but not `DatasetBuilder.builder_config.description`. We should update the `dataset_info.proto` to also save the config description.. This will make sure that generated datasets can be properly documented, even if the original source code isn't present.

**Comment by iamsdas** [comment]
Added PR

**Comment by vijayphoenix** [comment]
Fixed by https://github.com/tensorflow/datasets/pull/2544
