### ISSUE TITLE
`tfds.as_numpy` output is missing attribute '__qualname__'

### ISSUE THREAD

**Issue by SamuelMarks** [tensorflow/datasets#2545]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.3.0-54-gfcc4b966f1 2.3.1
- Python version: 3.8.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
`tfds.as_numpy` used to give this attribute to `_IterableDataset`

But now:
> AttributeError: '_IterableDataset' object has no attribute '__qualname__'

**Describe the expected behavior**
It used to be set to `_eager_dataset_iterator`.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
It broke in the last few days, see these two commits & runs:
https://github.com/SamuelMarks/ml-params-tensorflow/actions/runs/290907221
https://github.com/SamuelMarks/ml-params-tensorflow/actions/runs/293448591

**Comment by Conchylicultor** [comment]
Could you share how are you are using `tfds.as_numpy` and point out to the code line where `__qualname__` is called (this isn't obvious from the link you posted). Why are you trying to use `__qualname__` for ?

I think this is working as intended. `__qualname__` is a property of type, not instance (like `__name__`), so:

```
ds = tfds.as_numpy(ds)
ds.__qualname__  # Fail
type(ds).__qualname__  # Works
```

**Comment by SamuelMarks** [comment]
Hmm… was able to replicate it locally, looks like the different came between 3.2.1 and 4.0.1. My tests pass on tfds 3.2.1 and tf 3.2.1; but fail when tfds is upgraded to 4.0.1.

**Comment by Conchylicultor** [comment]
`tfds.as_numpy` now returns a re-usable iterable, instead of an iterator. So

```py
ds = tfds.as_numpy(ds)
ex = next(ds)
```

has to be replaced by:
```py
ds = tfds.as_numpy(ds)
ex = next(iter(ds))
```

**Comment by Conchylicultor** [comment]
The previous `ds` returned by `as_numpy` might have a `__qualname__` explicitly set. So `instance.__qualname__` would have worked accidentally. The new TFDS might has broken this, so you should update your code where `__qualname__` was called on an instance, to be consistent with Python

**Comment by SamuelMarks** [comment]
Use to work accidentally must be it.

Ended up replacing this:
https://github.com/SamuelMarks/ml-params-tensorflow/blob/80b485d/ml_params_tensorflow/tests/test_datasets.py#L74

With this:
https://github.com/SamuelMarks/ml-params-tensorflow/blob/80b485d/ml_params_tensorflow/tests/test_datasets.py#L74
