### ISSUE TITLE
Add a test to check that filename isn't used as key

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2549]
In TFDS, the example order is guarantee to be deterministic, using the key yield by `_generate_examples`.

However, a few dataset has been badly implemented by using non-deterministic key:

```py
def _generate_examples(self):
  for file in listdir(path):
    key = os.path.join(path, file)
    yield key, {'image': ..., 'label': ...}
```

This is a bug, the key contains the user path (`key == '/home/conchylicultor/tensorflow_datasets/download/...'`), so multiple users generating the dataset will get examples in different order. The correct implementation would be:

```py
def _generate_examples(self):
  for file in listdir(path):
    key = file
    yield key, {'image': ..., 'label': ...}
```

Instead, we should make sure that the `dl_manager.manual_dir`, `.extract_dir`, `.download_dir`,... are not contained in the key. `DatasetBuilderTestCase` could be updated to make sure that: `DatasetBuilderTestCase.example_dir not in key`

**Comment by sladyn98** [comment]
Hey, this sounds a cool issue. I would love to work on it :)

**Comment by sourabhsingh282** [comment]
I would like to work on this

**Comment by Conchylicultor** [comment]
@sourabhsingh282 thank you! Don't hesitate to send a PR.

**Comment by sourabhsingh282** [comment]
@vijayphoenix I would like to get into this issue please guide me

**Comment by vijayphoenix** [comment]
Hi @sourabhsingh282,

AFAIU, we have to check the values yielded by `_generate_examples` by adding some tests in the `DatasetBuilderTestCase`. https://github.com/tensorflow/datasets/blob/370d2d782bf884a22dbd4a735449ce2a322728c9/tensorflow_datasets/testing/dataset_builder_testing.py#L82

The test should check that `DatasetBuilderTestCase.example_dir` is not present in the key, i.e a parent path of the key yielded by `_generate_examples`.

**Comment by sourabhsingh282** [comment]
Thankyou @vijayphoenix  I will definitely send the PR

**Comment by NikhilBartwal** [comment]
@Conchylicultor I would like to work on the test and was looking at the code for it. 

But I'm confused as to how can i access the keys returned by the `_generate_examples` from the `DatasetBuilderTestCase`. I think that I haven't completely understood how the `DatasetBuilder` class works. It would be really kind of you if you could guide me. Thanks!

**Comment by Conchylicultor** [comment]
> But I'm confused as to how can i access the keys returned by the `_generate_examples` from the `DatasetBuilderTestCase`. I think that I haven't completely understood how the `DatasetBuilder` class works. It would be really kind of you if you could guide me. Thanks!

Thank you for your interest. One way would be to use `from unittest import mock` to patch `_generate_examples` and access the value you want.

**Comment by Conchylicultor** [comment]
Note: To support beam datasets (https://www.tensorflow.org/datasets/beam_datasets#instructions), if you detect a beam.PCollection, you could add `| beam.Map(_check_key_and_return)` to the pipeline.

**Comment by NikhilBartwal** [comment]
@Conchylicultor Thank you for the directions. I think i understand the issue now and will send a PR soon!

**Comment by NikhilBartwal** [comment]
@Conchylicultor I had been learning about the `mock.Mock()` and the `mock.patch()` for some time.
AFAIU, we need to patch the `_generate_examples` using something on the lines of:

`with mock.patch.object(self.builder, '_generate_examples') as mock_generate`

But I'm lost as to how to access the actual `keys` from it. Also. the `_generate_examples` usually takes a `path` or `dir` argument, so I'm not sure how to manage that. 

Actually, this is my first time working with tests and i would really like to get this to the end.

**Comment by Conchylicultor** [comment]
You need to replace the `_generate_examples` by your own version of `_generate_examples`:

```python
original_generate_examples = BUILDER_CLS._generate_examples

def new_generate_examples(self, *args, **kwargs):
  original_generate_examples(self, *args, **kwargs)

with mock.patch.object(BUILDER_CLS, '_generate_examples', new_generate_examples):
  ...
```

**Comment by NikhilBartwal** [comment]
@Conchylicultor I have created an in-progress PR and it would be great if you could have a look at it. I'm pretty sure that the implementation is not right for now, I hope you could provide me with some pointers for further improvements.



> You need to replace the `_generate_examples` by your own version of `_generate_examples`:
> 
> ```python
> original_generate_examples = BUILDER_CLS._generate_examples
> 
> def new_generate_examples(self, *args, **kwargs):
>   # Here you can perform the validation
>   return original_generate_examples(self, *args, **kwargs)
> 
> with mock.patch.object(BUILDER_CLS, '_generate_examples', new_generate_examples):
>   ...
> ```
 I was confused as to how would we perform the validation before calling the `original_generate_examples` itself.

**Comment by vijayphoenix** [comment]
https://github.com/tensorflow/datasets/pull/2822
