### ISSUE TITLE
[data request] VCTK

### ISSUE THREAD

**Issue by zh794390558** [tensorflow/datasets#256]
* Name of dataset: VCTK

* URL of dataset:  
https://homepages.inf.ed.ac.uk/jyamagis/page3/page58/page58.html

* License of dataset:  Open Data Commons Attribution License (ODC-By) v1.0. 
* Short description of dataset and use case(s): 

All speech data was recorded using an identical recording setup: an omni-directional head-mounted microphone (DPA 4035), 96kHz sampling frequency at 24 bits and in a hemi-anechoic chamber of the University of Edinburgh. All recordings were converted into 16 bits, were downsampled to 48 kHz based on STPK, and were manually end-pointed. This corpus was recorded for the purpose of building HMM-based text-to-speech synthesis systems, especially for speaker-adaptive HMM-based speech synthesis using average voice models trained on multiple speakers and speaker adaptation technologies.

**Comment by SoumyadeepJana** [comment]
@rsepassi @cyfra @Conchylicultor I would like to work on this,if approved.

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as VCTK is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/audio/vctk.py and https://www.tensorflow.org/datasets/catalog/vctk for more info.
Thank you for your contribution
