### ISSUE TITLE
Add a Pathlib-like API around tf.io.gfile

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2568]
pathlib.Path is a modern, typed, oriented object file API. However, it can't access GCS and other filesystem.

It would be nice to have a GPath wrapper around the gfile API. Not all pathlib API need to be implemented but the main methods iterdir, isdir, read_text,...

~~~py

class GPath(type_utils.ReadWritePath):
  """GPath path.

  GPath class main purpose is to be a universal pathlib.Path like
  interface which constructor redirect to the correct implementation
  (pathlib.Path, resource_utils.ResourcePath,...):

  ```py
  path = tfds.core.GPath()  # return pathlib.Path()
  path = tfds.core.GPath('gs://some-file/...')  # return GcsPath('gs://some-file/...')
  path = tfds.core.GPath(tfds.core.tfds_path())  # return ResourcePath('.../')
  path = tfds.core.GPath('/some/local/file')  # return pathlib.Path('/some/local/file')

  isinstance(path, tfds.core.GPath)  # True for all above cases
  ```
  """
  

  def __new__(cls, path: type_utils.PathLike))
      path: type_utils.PathLike) -> type_utils.ReadWritePath:
      if isinstance(path, str):
        if path.startswith('gs://'):
          return _GPath(path)
        else:
          return Path(path)
      elif isinstance(path, (GcsGPath, resource_utils.ResourcePath, pathlib.Path)):
        return path
      else:
        raise TypeError

  def __isinstance__(self, other):
    # Also __issubclass__ ?
    # Should return True for pathlib.Path, resource_utils.ResourcePath


class GcsPath(pathlib.PurePosixPath, type_utils.ReadWritePath):

  def __new__(cls, *parts: type_utils.PathLike):
    full_path = '/'.join(os.fspath(p) for p in parts)
    if full_path.startswith(('gs://')):
      return super().__new__(cls, full_path.replace('gs://', '/gs/', 1))
    if full_path.startswith(('/gs/'')):
      return super().__new__(cls, *parts)
    else:
      raise ValueError('Invalid path')

  def _get_path_str(self) -> str:
    value = super().__str__()
    if value.startswith('/gs/'):
      return value.replace('/gs/', 'gs://', 1)
    return value  # TODO: Could cache the value

  def __fpath__(self) -> str:
    return self._get_path_str()

  def __str__(self) -> str:
    return self._get_path_str()

  def exists(self) -> bool:
    return tf.io.gfile.exists(self._get_path_str())

  def iterdir(self) -> Iterator['GPath']:
    for f in tf.io.gfile.listdir(self):
      yield GPath(f)

  def isdir(self) -> bool:
    return tf.io.gfile.isdir(self._get_path_str())

  ...
~~~

**Comment by acharles7** [comment]
@Conchylicultor  I would like to work on this.

**Comment by acharles7** [comment]
> @Conchylicultor I would like to work on this.

Where to add this class? 
Create new file `tensorflow_datasets/core/utils/g_path.py` or 
Add in existing  `tensorflow_datasets/core/utils/type_utils.py`?

**Comment by Conchylicultor** [comment]
Thank you @acharles7 ! This should be added in a new `utils/gpath.py` and `utils/gpath_test.py`

**Comment by acharles7** [comment]
Thank you, working on it.

**Comment by Conchylicultor** [comment]
> Thank you, working on it.

Thank you. Don't hesitate to send a draft PR if you want early feedback

**Comment by acharles7** [comment]
Sure, thank you,
for testing, do you have any suggestions? i.e which module to use for mocking etc...

**Comment by Conchylicultor** [comment]
You can try `tfds.testing.mock_fs()` which mock `tf.io.gfile` API: https://github.com/tensorflow/datasets/blob/7236ada6ff7183294cb17501bc3ee9f57f603dc2/tensorflow_datasets/testing/test_utils.py#L74

**Comment by Conchylicultor** [comment]
I believe the easier would be to add a fixture to mock the tf API to convert gs:// path into regular local paths:

```py
@pytest.fixture
def mocked_gfile_path(tmp_path: pathlib.Path):

    def _norm_path(path: str):
      return path.replace('gs://', os.fspath(tmp_path))

    with tfds.testing.mock_tf(
        'tf.io.gfile',
        exists=lambda p: os.path.exists(_norm_path(p)),
        listdir=lambda p: os.path.listdir(_norm_path(p)),
        GFile=lambda p, *args, **kwargs: open(_norm_path(p), *args, **kwargs),
        rename=lambda p1, p2: os.path.rename(_norm_path(p1), _norm_path(p2)),
        ...
    ):
      yield tmp_path
```

Then:

```py
def test_gpath(mocked_gfile_path: pathlib.Path):
  path = GPath('gs://some-bucket/some-dir')
  assert not path.exists()
  path.makedir(parent=True)  # This call the mock tf.io.gfile.makedirs
  assert path.exists()
  # The data is created in '{tmp_path}/some-bucket/some-dir'
  assert mocked_gfile_path.joinpath('some-bucket/some-dir').exists()
```

**Comment by acharles7** [comment]
Thank you very much

**Comment by Conchylicultor** [comment]
I just remember there is an issue with the current implementation of `pathlib.Path` where the constructor isn't always called. See: https://bugs.python.org/issue41109.

It shouldn't impact you here, as you shouldn't need additional `self.xyz` attributes. If you really need this, it is possible to use `_init` instead of `__init__` like: https://github.com/tensorflow/datasets/pull/2228/files#diff-2e99bb1a6ffb72fe0bd448927f1e52ef2ad0dd165f0d075f80c202e121993c07R251

But try to avoid this as much as possible. In the above implementation, it isn't requiring any additional `self.xyz` attribute.

**Comment by Conchylicultor** [comment]
I also realised that this issue could be splitted in two issues (and 2 PRs):

 1) Add a `GcsPath` wrapper around tf.io.gfile with a pathlib-like interface.
 2) Add a `GPath` which only have a `__new__` method which redirect toward the `GcsPath`, `pathlib.Path`,... implementation

I updated the code snippet in the first comment to reflect the change

**Comment by acharles7** [comment]
Thank you. 
Will add `GcsPath` class  first and then in the following PR, I will add `GPath`

**Comment by Conchylicultor** [comment]
Thank you,
For PR nb 2 implementation, I think I'll do this one myself as I want to experiment how this is works with pytype.
