### ISSUE TITLE
TFDS clonning issue

### ISSUE THREAD

**Issue by sourabhsingh282** [tensorflow/datasets#2578]
**Short description**
I am trying to clone the  TensorFlow dataset repository on my GitHub desktop but it is showing me an error

**Environment information**
* Operating System: <windows home 10>
* Python version: <3.9.2>
**Reproduction instructions**

```
 
![Capture7](https://user-images.githubusercontent.com/47795037/96031085-84b22b00-0e7a-11eb-9753-991c732801e9.PNG)

```
![Capture8](https://user-images.githubusercontent.com/47795037/96031699-56811b00-0e7b-11eb-954a-aeb0106f2cd8.PNG)

**Comment by vijayphoenix** [comment]
On windows, there is a limit on max path length. (`Filename too long`)

It should be fixed after disabling the max-path limitation.
https://docs.python.org/3/using/windows.html#removing-the-max-path-limitation
