### ISSUE TITLE
[data request] LFW

### ISSUE THREAD

**Issue by SinghKislay** [tensorflow/datasets#261]
- Name of dataset: LFW(labeled faces in wild)

- URL of dataset:
  http://vis-www.cs.umass.edu/lfw/lfw.tgz

- Short description of dataset and use case(s):

 The data set contains more than 13,000 images of faces collected from the web. Each face has been labeled with the name of the person pictured. 1680 of the people pictured have two or more distinct photos in the data set.

**Comment by captain-pool** [comment]
This should be marked as dataset request.

**Comment by cyfra** [comment]
Fixed in #379
