### ISSUE TITLE
NotFoundError: data_info.json no such file or directory

### ISSUE THREAD

**Issue by HamLaertes** [tensorflow/datasets#2613]
**What I need help with / What I was wondering**
When I ran this command `python -m tensorflow_datasets.scripts.download_and_prepare --datasets=imagenet2012`, it raises NotFoundError. Where should I get them?

**What I've tried so far**
I have tried to first generate a builder and call builder.info to get data_info.json. But it raises the same error. I have manually downloaded train/validation tars

**It would be nice if...**
Could we have done anything to make things better (documentation, etc.)?

**Environment information**
* Operating System: <Centos>
* Python version: <3.6.9>
* `tensorflow-datasets`/`tfds-nightly` version: <4.0.1+nightly>
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <tensorflow/tensorflow-gpu 2.3.1>

**Comment by HamLaertes** [comment]
By the way, I am trying to download and prepare imagenet datasets.

**Comment by Conchylicultor** [comment]
Could you share the stacktrace ?

**Comment by HamLaertes** [comment]
> Could you share the logs and stacktrace ?

`2020-10-20 12:31:37.122888: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
I1020 12:31:38.950512 140057473963840 download_and_prepare.py:200] Running download_and_prepare for dataset(s):
imagenet2012
I1020 12:31:38.953433 140057473963840 dataset_info.py:361] Load dataset info from /root/tensorflow_datasets/imagenet2012/5.1.0
Traceback (most recent call last):
  File "/workspace/datasets/tensorflow_datasets/core/utils/py_utils.py", line 454, in try_reraise
    yield
  File "/workspace/datasets/tensorflow_datasets/core/load.py", line 207, in builder
    return cls(data_dir=data_dir, **builder_kwargs, **builder_init_kwargs)  # pytype: disable=not-instantiable
  File "/workspace/datasets/tensorflow_datasets/core/dataset_builder.py", line 188, in __init__
    self.info.read_from_directory(self._data_dir)
  File "/workspace/datasets/tensorflow_datasets/core/dataset_info.py", line 366, in read_from_directory
    parsed_proto = read_from_json(json_filename)
  File "/workspace/datasets/tensorflow_datasets/core/dataset_info.py", line 519, in read_from_json
    dataset_info_json_str = f.read()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 116, in read
    self._preread_check()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    self.__name, 1024 * 512)
tensorflow.python.framework.errors_impl.NotFoundError: /root/tensorflow_datasets/imagenet2012/5.1.0/dataset_info.json; No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/datasets/tensorflow_datasets/scripts/download_and_prepare.py", line 242, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/workspace/datasets/tensorflow_datasets/scripts/download_and_prepare.py", line 203, in main
    for name in datasets_to_build
  File "/workspace/datasets/tensorflow_datasets/scripts/download_and_prepare.py", line 203, in <dictcomp>
    for name in datasets_to_build
  File "/workspace/datasets/tensorflow_datasets/core/load.py", line 207, in builder
    return cls(data_dir=data_dir, **builder_kwargs, **builder_init_kwargs)  # pytype: disable=not-instantiable
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/workspace/datasets/tensorflow_datasets/core/utils/py_utils.py", line 456, in try_reraise
    reraise(e, *args, **kwargs)
  File "/workspace/datasets/tensorflow_datasets/core/utils/py_utils.py", line 422, in reraise
    raise exception from e
RuntimeError: NotFoundError: Failed to construct dataset imagenet2012: /root/tensorflow_datasets/imagenet2012/5.1.0/dataset_info.json; No such file or directory
`

Thanks! Here is the stacktrace.

The reason why I use tensorflow-datasets:4.0.1+nightly is that I want to call the module `tensorflow_datasets.scripts.download_and_prepare` and get the generated tfrecord datasets. 

I can get a copy of dataset_info.json by running builder.info.asjson in Colab and copy it to my server. But colab's tensorflow-datasets is at version:2.1.0. When I used version 2.1.0 not 4.0.1+nightly,  the module `tensorflow_datasets.scripts.download_and_prepare` cannot generate the tfrecord datasets. So maybe you can help me about transforing raw imagenet datasets into the corresponding tfrecords, and the better if the imagenet dataset version is 2.0.1, please.

**Comment by Conchylicultor** [comment]
It seems that he think the dataset was already created as the `/root/tensorflow_datasets/imagenet2012/5.1.0/` exists. Did you created the directory manually ?

**Comment by Conchylicultor** [comment]
Could you delete `/root/tensorflow_datasets/imagenet2012/5.1.0` and try again ?

**Comment by HamLaertes** [comment]
> Could share the content of the `/root/tensorflow_datasets/imagenet2012/5.1.0/` dir ?
> 
> ```shell
> ls /root/tensorflow_datasets/imagenet2012/5.1.0
> ```
> 
> Could you delete `/root/tensorflow_datasets/imagenet2012/5.1.0` and try again ?

Thanks a lot! It seems to work fine.
But does it generate the same tfrecords as the imagenet version 2.0.1?

**Comment by Conchylicultor** [comment]
> But does it generate the same tfrecords as the imagenet version 2.0.1?

You can see which version is generated by looking into `/root/tensorflow_datasets/imagenet2012/`

**Comment by HamLaertes** [comment]
Thank u very much. I'll close this issue.

**Comment by Sheetal-balekar** [comment]
ds=tfds.load('mnist',
             data_dir='/home/shee/Downloads/tfds_datasets',
             download='True')

output:
WARNING:absl:Variant folder /home/shee/Downloads/tfds_datasets/mnist/3.0.1 has no dataset_info.json

Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to /home/shee/Downloads/tfds_datasets/mnist/3.0.1...

Dl Completed...: 100%
 4/4 [00:01<00:00,  2.75 url/s]
Dl Size...: 100%
 10/10 [00:01<00:00,  6.95 MiB/s]
Extraction completed...: 100%
 4/4 [00:01<00:00,  2.85 file/s]

Dataset mnist downloaded and prepared to /home/shee/Downloads/tfds_datasets/mnist/3.0.1. Subsequent calls will reuse this data.
=====================================================================================================
When I run the above code in google colab. it downloaded the data . However, I was not able to see any dataset in the above mentioned folder. The folder is empty.

Please can anyone help me with this. 
Thank You in advance.
