### ISSUE TITLE
Support sequence length 0 for images with unknown shape

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2616]
Currently if is not possible to have an empty sequence with unknown shapes:

Like: `tfds.features.Sequence(tfds.feature.Image(shape=(None, None, 3)))`

E.g. adding the following test in https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/features/sequence_feature_test.py will fail:

```py
    self.assertFeature(
        feature=feature_lib.Sequence(tfds.feature.Image(shape=(None, None, 3)),
        shape=(None, None, None, 3),  # (length, h, w, c)
        tests=[
            testing.FeatureExpectationItem(
                value=[],  # Empty input
                expected=[],  # 
            ),
    )
```

`tf.map_fn` will fail with `InvalidArgumentError: Tried to stack elements of an empty list with non-fully-defined element_shape: [?,?,1]`:

This is because this code get executed during decoding:
```py
imgs = tf.map_fn(
    decode_image,  # () -> (None, None, 3)
    encoded_imgs,  # Tensor(shape=(0,), dtype=tf.string)
    dtype=tf.uint8,
)
```

This is triggered when:

 * Image shapes are dynamic: `decode_example has in/out shapes: () -> (None, None, 3)
 * When the sequence is empty (encoded_imgs[0] == 0) (here when the image has no mask).

`tf.map_fn` try to decode: `Tensor(shape=(0,), dtype=tf.string)` -> `Tensor(shape=(0, None, None, 3), dtype=tf.uint8)`

Because there is no images to decode, TF cannot infer the implicit missing dimensions `(0, None, None, 3)`.

To fix the issue, we should try to update the `decode_batch_example` in 

https://github.com/tensorflow/datasets/blob/ad114d874b9b92d6474b44e0aa92bc918a9b3b94/tensorflow_datasets/core/features/feature.py#L419

```py
def decode_batch_example(self, tfexample_data):
  if None in self.shape[1:] and tfexample_data.shape[0] is None:
    # Length and shape unknown, should deal with length == 0 case
    # as (0, None, None, 3) isn't supported by tf.map_fn
    zero_shape = (0 if s is None else s for s in self.shape)
    return tf.cond(
        tf.len(tfexample_data) == 0,
        lambda: tf.constant(shape=(0, 0, 0, self.shape[-1]), dtype=self.dtype),
        lambda: _decode_batch_example(tfexample_data),
    )
  else:  # Shape statically defined
    return _decode_batch_example(tfexample_data)
```

Note: the tf.len() and likely do not work as-is, but you get the idea. Or something like that. Implementation should also support the nested case (with the help of tf.nest API), like:

```py
    self.assertFeature(
        feature=feature_lib.Sequence({'a': tfds.feature.Image(shape=(None, None, 3), 'b': tf.int32}),
        shape={
            'a': (None, None, None, 3),
            'b': (None,),
        },
        tests=[
            testing.FeatureExpectationItem(  # This works
                value=[np.ones(8, 8, 3) for _ in range(4)],
                expected=np.ones(4, 8, 8, 3),
            ),
            testing.FeatureExpectationItem(
                value=[],  # Empty input
                expected=[],  # 
            ),
    )
```

**Comment by PrattJena** [comment]
I want to contribute to this but I am not sure as to how and where to start

**Comment by Conchylicultor** [comment]
@PrattJena Thank you for your contribution.
As a first step, you could try to reproduce the bug by adding and executing the above tests to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/features/sequence_feature_test.py.

Then you can update datasets/tensorflow_datasets/core/features/feature.py until the tests pass.

**Comment by PrattJena** [comment]
@Conchylicultor  Sorry for the delay. Will this test be added under the method `test_image` replacing [this](https://github.com/tensorflow/datasets/blob/11c82e310c047f9b45f3916c867319812dac03ac/tensorflow_datasets/core/features/sequence_feature_test.py#L420) line to produce the error?

**Comment by PrattJena** [comment]
@Conchylicultor On adding and executing the tests I am running into this bug instead of the bug you mentioned
`TypeError: assertFeature() missing 1 required positional argument: 'dtype'`
Where am I going wrong ?

**Comment by PrattJena** [comment]
I was able to reproduce the bug on adding and executing the above tests. As for making changes in `decode_batch_example` in feature.py and then re-executing sequence_feature_test.py I am running into the following error.
`AttributeError: module 'tensorflow.compat.v2' has no attribute 'len'`
Should I make a PR to look into it?

**Comment by PrattJena** [comment]
@vijayphoenix Can you help me ? Is this the pseudocode of the changes to be made? 
```python
def decode_batch_example(self, tfexample_data):
  if None in self.shape[1:] and tfexample_data.shape[0] is None:
    # Length and shape unknown, should deal with length == 0 case
    # as (0, None, None, 3) isn't supported by tf.map_fn
    zero_shape = (0 if s is None else s for s in self.shape)
    return tf.cond(
        tf.len(tfexample_data) == 0,
        lambda: tf.constant(shape=(0, 0, 0, self.shape[-1]), dtype=self.dtype),
        lambda: _decode_batch_example(tfexample_data),
    )
  else:  # Shape statically defined
    return _decode_batch_example(tfexample_data)
```

**Comment by Conchylicultor** [comment]
As the error said, `tf.len` is an invalid symbol. You need to find the right symbol in the TF API.

**Comment by PrattJena** [comment]
@Conchylicultor As mentioned above since image shapes are dynamic so i used tf.shape instead. The function looks like this now.

```python

  def decode_batch_example(self, tfexample_data):
    """Decode multiple features batched in a single tf.Tensor.

    This function is used to decode features wrapped in
    `tfds.features.Sequence()`.
    By default, this function apply `decode_example` on each individual
    elements using `tf.map_fn`. However, for optimization, features can
    overwrite this method to apply a custom batch decoding.

    Args:
      tfexample_data: Same `tf.Tensor` inputs as `decode_example`, but with
        and additional first dimension for the sequence length.

    Returns:
      tensor_data: Tensor or dictionary of tensor, output of the tf.data.Dataset
        object
    """
    if None in self.shape[1:] and tfexample_data.shape[0] is None:
    # Length and shape unknown, should deal with length == 0 case
    # as (0, None, None, 3) isn't supported by tf.map_fn
      zero_shape = (0 if s is None else s for s in self.shape)
      return tf.cond(
        tf.shape(tfexample_data) == 0,
        lambda: tf.constant(shape=(0, 0, 0, self.shape[-1]), dtype=self.dtype),
        lambda: decode_batch_example(tfexample_data),
      )
    else:  # Shape statically defined
      return decode_batch_example(tfexample_data)

    # Note: This all works fine in Eager mode (without tf.function) because
    # tf.data pipelines are always executed in Graph mode.

    # Apply the decoding to each of the individual distributed features.
    return tf.map_fn(
        self.decode_example,
        tfexample_data,
        fn_output_signature=self.dtype,
        parallel_iterations=10,
        back_prop=False,
        name='sequence_decode',
    )

```
On running tests I am running into this error. 
```
  File "/home/pratt/.local/lib/python3.8/site-packages/tensorflow/python/ops/cond_v2.py", line 62, in cond_v2
    raise TypeError("pred must not be a Python bool", pred)
TypeError: ('pred must not be a Python bool', False)
```

**Comment by Conchylicultor** [comment]
It means `tf.shape(tfexample_data) == 0` is a Python bool, not a `tf.Tensor`. You should use tf.equal, or similar ops (I don't know the exact name)

**Comment by PrattJena** [comment]
@Conchylicultor  what is zero_shape here?

**Comment by PrattJena** [comment]
What will the two lambda functions decode_batch_example call? As its giving me this error 
`name '_decode_batch_example' is not defined`
I have update my function to this 
```python
  def decode_batch_example(self, tfexample_data):
    """Decode multiple features batched in a single tf.Tensor.

    This function is used to decode features wrapped in
    `tfds.features.Sequence()`.
    By default, this function apply `decode_example` on each individual
    elements using `tf.map_fn`. However, for optimization, features can
    overwrite this method to apply a custom batch decoding.

    Args:
      tfexample_data: Same `tf.Tensor` inputs as `decode_example`, but with
        and additional first dimension for the sequence length.

    Returns:
      tensor_data: Tensor or dictionary of tensor, output of the tf.data.Dataset
        object
    """
    if None in self.shape[1:] and tfexample_data.shape[0] is None:
    # Length and shape unknown, should deal with length == 0 case
    # as (0, None, None, 3) isn't supported by tf.map_fn
      zero_shape = (0 if s is None else s for s in self.shape)
      return tf.cond(
        tf.math.equal(tf.shape(tfexample_data),0),
        lambda: tf.constant(zero_shape,shape=(0, 0, 0, self.shape[-1]), dtype=self.dtype),
        lambda: decode_batch_example(tfexample_data)
      )
    else:  # Shape statically defined
      return decode_batch_example(tfexample_data)

    # Note: This all works fine in Eager mode (without tf.function) because
    # tf.data pipelines are always executed in Graph mode.

    # Apply the decoding to each of the individual distributed features.
    return tf.map_fn(
        self.decode_example,
        tfexample_data,
        fn_output_signature=self.dtype,
        parallel_iterations=10,
        back_prop=False,
        name='sequence_decode',
    )
```

**Comment by PrattJena** [comment]
I have updated my function to this 
```python

  def decode_batch_example(self, tfexample_data):
    
    if None in self.shape[1:] and tfexample_data.shape[0] is None:
    # Length and shape unknown, should deal with length == 0 case
    # as (0, None, None, 3) isn't supported by tf.map_fn
      zero_shape = (0 if s is None else s for s in self.shape)
      return tf.cond(
        tf.math.equal(tf.shape(tfexample_data),0),
        lambda: tf.constant(zero_shape,shape=(0, 0, 0, self.shape[-1]), dtype=self.dtype),
        lambda: tf.map_fn(
          self.decode_example,
          tfexample_data,
          fn_output_signature=self.dtype,
          parallel_iterations=10,
          back_prop=False,
          name='sequence_decode')
      )
    else:  # Shape statically defined
      return tf.map_fn(
        self.decode_example,
        tfexample_data,
        fn_output_signature=self.dtype,
        parallel_iterations=10,
        back_prop=False,
        name='sequence_decode',
    )
```
On running the test  
```python
    self.assertFeature(
        feature=feature_lib.Sequence(tfds.feature.Image(shape=(None, None, 3)),
        shape=(None, None, None, 3),  # (length, h, w, c)
        tests=[
            testing.FeatureExpectationItem(
                value=[],  # Empty input
                expected=[],  # 
            ),
    )
```
I get the following error 
```
AssertionError: Tuples differ: (0, 0, 0, 3) != (0,)

First tuple contains 3 additional elements.
First extra element 1:
0

- (0, 0, 0, 3)
+ (0,) : Shape mismatch: expected (0, 0, 0, 3), got (0,). Contents: array([], dtype=float64). 
.

```

**Comment by PrattJena** [comment]
@Conchylicultor Can you help me out with the bug in the above code?

**Comment by Conchylicultor** [comment]
* `shape=(0, 0, 0, self.shape[-1])` should be computed in function of self.shape, replacing `None` by 0.
* `tf.shape(tfexample_data),0` seems buggy to me. `tf.shape` will returns a `tf.Tensor(shape=(len(shape)))` while we want to check that only the first dimension is 0.

**Comment by Conchylicultor** [comment]
In your code you're hardcoding `tf.constant(zero_shape,shape=(0, 0, 0, self.shape[-1]), dtype=self.dtype),`. In practice, the shape do not have to be (0, 0, 0, ...) but could be anything (e.g. `(0, 12, 35)` or `(0, 0, 10)`). So the shape should dynamically computed from `self.shape`

**Comment by PrattJena** [comment]
@Conchylicultor Very sorry for the big delay. Can you pls explain me the first point. I didnt quite understand it.

**Comment by PrattJena** [comment]
@Conchylicultor  I updated the code to this and ran it on the first test case
```python 
def decode_batch_example(self, tfexample_data):
    # Since length will be 0 and not None
    if None in self.shape[1:] and tfexample_data.shape[0] == 0: #<============ 1 
    # Length and shape unknown, should deal with length == 0 case
    # as (0, None, None, 3) isn't supported by tf.map_fn
      zero_shape = (0 if s is None else s for s in self.shape)
      return tf.cond(
        tf.math.equal(tfexample_data.shape[0],0), #<============ 2
        lambda: tf.constant(zero_shape,shape=(0, self.shape[1], self.shape[2], self.shape[-1]),  dtype=self.dtype), #<=========== 3
        lambda: tf.map_fn(
          self.decode_example,
          tfexample_data,
          fn_output_signature=self.dtype,
          parallel_iterations=10,
          back_prop=False,
          name='sequence_decode')
      )
    else:  # Shape statically defined
      return tf.map_fn(
        self.decode_example,
        tfexample_data,
        fn_output_signature=self.dtype,
        parallel_iterations=10,
        back_prop=False,
        name='sequence_decode',
    )
```
On running this I run into this error 
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Tried to stack elements of an empty list with non-fully-defined element_shape: [?,?,3]
         [[{{node sequence_decode/TensorArrayV2Stack/TensorListStack}}]]
         [[IteratorGetNext_1]]
```
 Also on changing back `change no. <======= 1` to this
```python
if None in self.shape[1:] and tfexample_data.shape[0] is None
``` 
I run into this error 
`ValueError: Tried to convert 'x' to a tensor and failed. Error: None values not supported.`

What changes should I make. Sorry If I am taking too long for this issue as this is my second time taking up a PR issue and I am still getting acquainted with the functions and code.

**Comment by Conchylicultor** [comment]
Thank you for the update.

* `shape=(0, self.shape[1], self.shape[2], self.shape[-1])` assume that the shape is of rank 4. We want to solve the general case where rank could be anything `(0)`, `(0, 3)`,...
* You can use `tf.print` inside the graph to help you debug
* It would be easier to comment on a draft PR.
* I think it might help you if you where experimenting in a Colab. For example where you create a `tf.data.Dataset.from_generator` pipeline which yield both empty and non-empty arrays (e.g. `np.array(shape=(0,...))`). And then apply `ds = ds.map(_apply_map)` and `_apply_map` would apply the `tf.map` on a dummy function
