### ISSUE TITLE
[data request] <CAVE>

### ISSUE THREAD

**Issue by aayu04** [tensorflow/datasets#262]
* Name of dataset: coil100
* URL of dataset: <http://www1.cs.columbia.edu/CAVE/software/softlib/coil-100.php>
* License of dataset: <NA>
* Short description of dataset and use case(s): <100 different objects imaged at every angle in a 360 rotation.>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by ChanchalKumarMaji** [comment]
This dataset looks interesting. @cyfra , please assign this issue to me.

**Comment by cyfra** [comment]
Code in: #825
