### ISSUE TITLE
Use core.constants.get_default_data_dir() for DEFAULT_DATA_DIR value in download_and_prepare.py

### ISSUE THREAD

**Issue by 0x0badc0de** [tensorflow/datasets#2623]
**Short description**
Right now if data dir is changed via TFDS_DATA_DIR env variable it is ignored by download_and_prepare.py script since it uses hardcoded path in home directory. Should use related constant instead.

**Environment information**
* Operating System: <os>
* Python version: <version>
* `tensorflow-datasets`/`tfds-nightly` version: <package and version>
* `tensorflow`/`tf-nightly` version: <package and version>

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?

**Reproduction instructions**

```
TFDS_DATA_DIR=/tmp/tfds python -m tensorflow_datasets.scripts.download_and_prepare --datasets=<any ds>
```

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
All scripts should use data dir configured via TFDS_DATA_DIR env variable.

**Comment by vijayphoenix** [comment]
`tfds build` should be used instead of `download_and_prepare`

**Comment by Conchylicultor** [comment]
This was fixed with tfds-nightly
