### ISSUE TITLE
TFDS : deep_weeds dataset hosting address is no longer valid

### ISSUE THREAD

**Issue by ymodak** [tensorflow/datasets#2637]
**Short description**
Transferring issue https://github.com/tensorflow/tensorflow/issues/44053 to `tensorflow-datasets` repository for visibility
TFDS : deep_weeds dataset hosting address is no longer valid

**Reproduction instructions**
https://github.com/tensorflow/tensorflow/issues/44053

**Link to logs**
https://github.com/tensorflow/tensorflow/issues/44053#issuecomment-712513593

**Comment by Conchylicultor** [comment]
Thank you for reporting. Don't hesitate to send a PR to update.

**Comment by PrattJena** [comment]
I am working on this

**Comment by PrattJena** [comment]
@Conchylicultor pls review if the following code is correct.

**Comment by PrattJena** [comment]
@Conchylicultor I have made the required changes for this bug. Can you pls review the PR.

**Comment by vijayphoenix** [comment]
Fixed by https://github.com/tensorflow/datasets/pull/2642
