### ISSUE TITLE
UnsafeArchiveError while extracting .tgz 

### ISSUE THREAD

**Issue by iswariyam** [tensorflow/datasets#267]
**Short description**
I am working on Caltech Birds 2010 dataset [Issue 200](https://github.com/tensorflow/datasets/issues/200#issue-419145585).
I am not able to extract the contents of the dataset after the .tgz is downloaded by download manager.

**Environment information**
* Operating System: Ubuntu 16.04
* Python version: 3.6.8
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets-1.0.1
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow-gpu-1.12.0

**Reproduction instructions**

```
import tensorflow as tf
import tensorflow_datasets.public_api as tfds

download_dir = "/home/iswariya/Downloads/working"
_SPLIT_URL = "http://www.vision.caltech.edu/visipedia-data/CUB-200/lists.tgz"
dl = tfds.download.DownloadManager(download_dir=download_dir)
train_test_split_archive = dl.download_and_extract([_SPLIT_URL])

```

**Link to logs**
[Error log](https://gist.github.com/iswariyam/a3f347e8e4f48d07b42cd651c66e7871)

**Expected behavior**
dl.download_and_extract([_SPLIT_URL]) should be able to ignore contents which have the absolute path and extract the remaining contents.

**Additional context**
I did a temporary workaround by modifying line 123 of https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/download/extractor.py to return None

**Comment by rsepassi** [comment]
@pierrot0, could you please take a look?
