### ISSUE TITLE
About the TokenTextEncoder with lowercase=True

### ISSUE THREAD

**Issue by jihunchoi** [tensorflow/datasets#268]
**Short description**
The current behavior of `TokenTextEncoder` when `lowercase` is `True` makes word indices not continuous if multiple (case-sensitive) words share the same lowercase form.
I don't know whether it is intended or not and it will not be problematic in most cases, but I think indices not connected to any token may be misleading.

**Environment information**
* Operating System: Ubuntu, 16.04
* Python version: 3.6
* `tensorflow-datasets`/`tfds-nightly` version: tfds-nightly / 1.0.1.dev201903130105
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow-gpu / 2.0.0-alpha0

**Reproduction instructions**

```
encoder = tfds.features.text.TokenTextEncoder(vocab_list=['the', 'The', 'THE'])
encoder.encode('the The THE')  # [1, 2, 3]
encoder._vocab_list  # ['the', 'The', 'THE']
encoder.vocab_size  # 5 (PAD, the, The, THE, UNK)
encoder._token_to_id  # {'the': 0, 'The': 1, 'THE': 2}

encoder_lower = tfds.features.text.TokenTextEncoder(vocab_list=['the', 'The', 'THE'], lowercase=True)
encoder_lower._token_to_id  # {'the': 2}
encoder_lower._vocab_list  # ['the', 'the', 'the']
encoder_lower.vocab_size  # 5 (PAD, the, the, the, UNK)
encoder_lower.encode('the The THE')  # [3, 3, 3]
```

**Expected behavior**
Duplicate entries are removed from `vocab_list`.
```
encoder_lower = tfds.features.text.TokenTextEncoder(vocab_list=['the', 'The', 'THE'], lowercase=True)
encoder_lower._token_to_id  # {'the': 0}
encoder_lower._vocab_list  # ['the']
encoder_lower.vocab_size  # 3 (PAD, the, UNK)
encoder_lower.encode('the The THE')  # [1, 1, 1]
```

**Comment by rsepassi** [comment]
Thanks for finding this. Yes, it should remove the duplicates.

**Comment by tmatha** [comment]
I am interested in fixing this issue. I am first time contributor. Please advise how to proceed. Thanks.

**Comment by ShambhaviCodes** [comment]
I want to fix this bug if it isn't fixed yet.

**Comment by Conchylicultor** [comment]
With tf.Text https://medium.com/tensorflow/introducing-tf-text-438c8552bd5e and in-graph tokenizer, our long term plan is to deprecate our tokenizer to replace them by the TensorFlow ones.
So we have deprioritized this, and we encourage to try https://github.com/tensorflow/text instead.

**Comment by Conchylicultor** [comment]
Closing this as the TFDS text API is gonna be removed from TFDS. Users should use https://github.com/tensorflow/text instead.
