### ISSUE TITLE
'Command not found' when trying to install tfds

### ISSUE THREAD

**Issue by beqiris** [tensorflow/datasets#2714]
Received the error message ‘command not found’ when trying to install tfds on a GCP VM. 
Have attempted via:
conda install -c anaconda tensorflow-dataset,
pip install tensorflow-datasets,
pip install -q tfds-nightly

none of the above are working..
Any suggestions would be very helpful!

**Comment by Conchylicultor** [comment]
> Received the error message ‘command not found’ when trying to install tfds on a GCP VM.

Which command is failing ?

Are you talking about the `tfds` CLI or the `pip` command ? You might have to install pip on your VM
I believe Conda TFDS version is very old, but `pip` should install the CLI.

**Comment by beqiris** [comment]
<img width="956" alt="Screenshot 2020-11-09 at 19 17 21" src="https://user-images.githubusercontent.com/74211142/98718748-bf7a8680-2386-11eb-8175-3bcd6f09c385.png">

**Comment by beqiris** [comment]
After I install TFDS using the pip command, I then try to use tfds --version, and it gives me the error 'tfds: command not found'.
I'm not sure why this is the case as it seems that tfds is installed.

**Comment by NikhilBartwal** [comment]
Hey @beqiris, `tfds` is not a command name by itself like `pip` or `python`. That's why it shows an error.
You can checkout the installed `tfds` version along with other packages' versions using `pip freeze`
I hope this solved your query!

**Comment by Conchylicultor** [comment]
Thank you for reporting. I'm not familiar how [Python entry-points](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html#entry-points) are registered on Google cloud. I'll try to investigate. If someone already solved the issue, don't hesitate to share.

@NikhilBartwal `pip install` should install the `tfds` CLI (as per https://www.tensorflow.org/datasets/cli)

**Comment by Conchylicultor** [comment]
I just tried to create a new Cloud VM and this seem to work as expected:

```sh
epot@epot:~$ gcloud compute ssh test-central1a  # Log into ssh into the Cloud VM

epot@test-central1a:~$ pip install tfds-nightly
Collecting tfds-nightly
  WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
  Downloading tfds_nightly-4.1.0.dev202011100107-py3-none-any.whl (3.6 MB)
     |????????????????????????????????| 3.6 MB 5.1 MB/s 
Requirement already satisfied: tqdm in /opt/conda/lib/python3.7/site-packages (from tfds-nightly) (4.46.0)
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from tfds-nightly) (1.15.0)
[...]
Requirement already satisfied: googleapis-common-protos in /opt/conda/lib/python3.7/site-packages (from tensorflow-metadata->tfds-nightly) (1.51.0)
Installing collected packages: importlib-resources, tfds-nightly
Successfully installed importlib-resources-3.3.0 tfds-nightly-4.1.0.dev202011100107
WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..
WARNING: Keyring is skipped due to an exception: Failed to create the collection: Prompt dismissed..

epot@test-central1a:~$ tfds --version
TensorFlow Datasets: 3.1.0

epot@test-central1a:~$ 
```

**Comment by Conchylicultor** [comment]
It seems that `tensorflow_datasets` was already installed on the machine through Conda. `pip install tfds-nightly` installed the `tfds` CLI, but the strange thing is that `tfds --version` display the conda version installed (`3.1.0`), which do not have CLI.
I'm quite confused. I tried again, but this time `tfds --version` display the correct `TensorFlow Datasets: 4.1.0+nightly`

**Comment by NikhilBartwal** [comment]
> Thank you for reporting. I'm not familiar how [Python entry-points](https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html#entry-points) are registered on Google cloud. I'll try to investigate. If someone already solved the issue, don't hesitate to share.
> 
> @NikhilBartwal `pip install` should install the `tfds` CLI (as per https://www.tensorflow.org/datasets/cli)

@Conchylicultor Apologies, I was away for some time and did not read that much about the tfds CLI :(

**Comment by ali-soltani** [comment]
just had the same problem on windows. powershell didnt recognized tfds.
turned out that something removed the path of the python scripts from my environment variables.
pip said to add the folder to path while installing it the 3rd time if this helps anyone.

**Comment by Conchylicultor** [comment]
Thank you for reporting those issues. We want to make it easier for other to debug so please continue sharing those issues. Do you remember the steps you took to solve the issue ? I'll add a troubleshooting section on https://www.tensorflow.org/datasets/cli

**Comment by RobinBaumann** [comment]
Any update on this? I just tried to install TFDS via `pip install tensorflow-datasets` and can't find the `tfds` CLI with the error: `Command 'tfds' not found`. 

TFDS Version = 3.2.1
Operating System: Linux 5.3.0-61-generic #55~18.04.1-Ubuntu SMP x86_64

**Comment by Conchylicultor** [comment]
@RobinBaumann The CLI was added with TFDS 4+. Please upgrade to last version. I would suggest to install `tfds-nightly` which has additional bug fixes.

**Comment by Royston2708** [comment]
I am getting the following error when running the commands 
>> !pip install -q tfds-nightly (Executes Successfully)
>> tfds --version (Throws and Error)

Error Message:
Traceback (most recent call last):
  File "/usr/local/bin/tfds", line 5, in <module>
    from tensorflow_datasets.scripts.cli.main import launch_cli
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/scripts/cli/main.py", line 40, in <module>
    from tensorflow_datasets.scripts.utils import flag_utils
ModuleNotFoundError: No module named 'tensorflow_datasets.scripts.utils'

NOTE: 

On inspection of these this path --> /usr/local/lib/python3.7/dist-packages/tensorflow_datasets/scripts/cli/main.py 
I realize that there should exist a path --> usr/local/lib/python3.7/dist-packages/tensorflow_datasets/scripts/utils.py with the flag_utils function in it but it does not exist in the Google Colab directory.

**Comment by Conchylicultor** [comment]
Could you try to `pip uninstall` `tensorflow_datasets`, then re-install `tfds-nightly` ? It's possible the 2 versions conflicts

**Comment by Royston2708** [comment]
Does not work....
![Screen Shot 2021-11-17 at 12 36 18 PM](https://user-images.githubusercontent.com/35322634/142252557-cd1758a7-2e3b-449a-82e8-db362edd4d8a.png)

**Comment by jackd** [comment]
My `tfds-nightly` installed via `pip install tfds-nightly` doesn't have a `tensorflow_datasets/scripts/utils` directory, nor if I clone this repo and `pip install .`. If I clone the repo and `pip install -e .` it works fine.

**Comment by Conchylicultor** [comment]
Maybe this is due to the missing `__init__.py` files. Let me add those now

**Comment by CYHSM** [comment]
I just had the same problem on Ubuntu with tensorflow 2.9, python 3.9 and tfds nightly. Solved it by adding at the top of my notebook: 
```
import os
os.environ["CURL_CA_BUNDLE"] = "/etc/ssl/certs/ca-certificates.crt"
```
