### ISSUE TITLE
FR: Support auxiliary data with datasets

### ISSUE THREAD

**Issue by rhofour** [tensorflow/datasets#2733]
**Is your feature request related to a problem? Please describe.**
Some datasets are designed to be used with other data that isn't really part of the training set. Consider the existing web_questions dataset which clears states "The questions are supposed to be answerable by Freebase, a large knowledge graph." TFDS makes it easy to get the web_questions training and test sets, but it does nothing to help get the Freebase data.

**Describe the solution you'd like**
I'd like to see some standardized way to link additional data to a dataset. In my case I'm particularly interested in including a knowledge base along with a dataset for knowledge base completion (which is obviously highly dependent on the knowledge base).

**Describe alternatives you've considered**
There are two obvious alternatives.
1) Simply don't use TFDS and handle everything myself.
2) Use TFDS for the training and test data, but handle loading the knowledge graph myself. Presumably this is what people currently do with web_questions.

**Comment by Conchylicultor** [comment]
This is already available through `tfds.core.MetadataDict` and `info.metadata`. See: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/wordnet.py for example

**Comment by Conchylicultor** [comment]
I think this has been resolved. Let us know if not
