### ISSUE TITLE
DownloadManager._handle_download_result moves to outdated path

### ISSUE THREAD

**Issue by jackd** [tensorflow/datasets#274]
**Short description**
`DownloadManager._handle_download_result` [moves the downloaded files to the incorrect location](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/download/download_manager.py#L200).

Setting the `Resource.sha256` unsets `Resource._fname` but does not unset `Resource.path`. The path is set [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/download/download_manager.py#L216). If this is the first time it is run, `Resource.fname` will be based on the sha256 of the url, not the downloaded file. When run after the download has been handled and the checksums have been registered, the file cannot be found in the updated location.

**Environment information**
* Operating System: ubuntu 16.04
* Python version: 2.7.12
* `tensorflow-datasets`/`tfds-nightly` version: master branch, commit `6358a39e937dd43ea7d5915cf97733ab81d65275`
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow-gpu 1.13

**Steps to Reproduce**
* Delete contents of `mnist.txt` checksums
`python -m tensorflow_datasets.scripts.download_and_prepare --register_checksums --datasets=mnist`
* Delete generated mnist data (leave download files)
`python -m tensorflow_datasets.scripts.download_and_prepare --datasets=mnist`
observe second download.

**Expected behavior**
Handled download result is saved to the same place where subsequent runs look for it, even during development.

**Comment by Conchylicultor** [comment]
Thanks for reporting.
@pierrot0 Could you have a look at this ?
