### ISSUE TITLE
Add `tensorflow_datasets.__version__`

### ISSUE THREAD

**Issue by rsepassi** [tensorflow/datasets#278]
Use `tensorflow/probability` as an example:

In `__init__.py` ([example](https://github.com/tensorflow/probability/blob/c3f72714fb0566dba92f1bfe1397f0039fdff071/tensorflow_probability/__init__.py#L79)).

And in `setup.py` ([example](https://github.com/tensorflow/probability/blob/c3f72714fb0566dba92f1bfe1397f0039fdff071/setup.py#L25)).

Related to tensorflow/tensorboard#2020

**Comment by ChanchalKumarMaji** [comment]
@rsepassi please check #279.

**Comment by ChanchalKumarMaji** [comment]
@rsepassi @cyfra @Conchylicultor , I think we can close this issue :relaxed:.
