### ISSUE TITLE
Confusing licensing

### ISSUE THREAD

**Issue by hyandell** [tensorflow/datasets#2780]
The following two files have both Apache-2.0 and Creative Commons Attribution-ShareAlike identified as the license for the files. Which license applies?

https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/wiki40b.py
https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/wikipedia.py

**Comment by NikhilBartwal** [comment]
Hey @hyandell, the two mentioned files, along with all others that are a part of Tensorflow Datasets fall under the Apache 2.0 license as mentioned in the scripts.
The datasets, however, have their own licenses as defined by the owner/admin if that very dataset. 
`wikipedia` and `wiki40b` datasets fall under the Creative Commons licence.

If this solved your query, please close the issue!

**Comment by Conchylicultor** [comment]
As @NikhilBartwal explained, the dataset definition source code `wiki40b.py` is under Apache 2.0. But the data itself is CC.
