### ISSUE TITLE
CLI does not understand GCS data_dir

### ISSUE THREAD

**Issue by lakshmanok** [tensorflow/datasets#2799]
Doing:

`tfds build --datasets coco_captions --data_dir gs://practical-ml-vision-book/tfds_cache`

creates a local directory named gs instead of caching to GCS (the behavior of the Python API).

**Comment by Conchylicultor** [comment]
Thank you for reporting. This is due to: https://github.com/tensorflow/datasets/blob/26587ec6d4b23a501210a687be667e2f8256f32a/tensorflow_datasets/scripts/cli/build.py#L78

The fix should be fairly easy.
