### ISSUE TITLE
Even with verify_ssl = False still SSL errors when downloading dataset

### ISSUE THREAD

**Issue by RobinSmits** [tensorflow/datasets#2800]
/!\ IF YOU WANT PEOPLE TO HELP YOU, PLEASE GIVE AS MUCH DETAIL AS POSSIBLE, INCLUDING THE FULL STACKTRACE AND CODE SNIPPET

**Short description**
For a computer vision experiment I need tensorflow dataset UCF101. Even when disabling the SSL cert verification with 'verify_ssl = False' I still get the following error:

SSLError: HTTPSConnectionPool(host='www.crcv.ucf.edu', port=443): Max retries exceeded with url: /data/UCF101/UCF101TrainTestSplits-RecognitionTask.zip (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

**Environment information**
* Operating System: Google Colab and Windows 10
* Python version: Colab 3.6 and Windows 10 3.7
* `tensorflow-datasets` version: 4.1.0
* `tensorflow` version: 2.3.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? Yes.

**Reproduction instructions**
Reproducable in [link](https://colab.research.google.com/drive/1HwIn_kK0g7y8J9ocXn_fN_JKXJ20tilf?usp=sharing) to shared Google Colab.

**Link to logs**
Logs in [link](https://colab.research.google.com/drive/1HwIn_kK0g7y8J9ocXn_fN_JKXJ20tilf?usp=sharing) to shared Google Colab.

**Expected behavior**
The download of the dataset should work without doing seperate manual download and processing.

**Additional context**
None...

**Comment by Conchylicultor** [comment]
In your colab:

```
tfds.download.DownloadConfig(verify_ssl = False)

# Get data and datasets
dataset, info = tfds.load('ucf101', split = ['train','test'], with_info = True, shuffle_files = True, as_supervised = True)
```

You should pass `tfds.download.DownloadConfig` to:

```python
tfds.load(..., download_and_prepare_kwargs={
      'download_config': dl_config,
})
```

**Comment by RobinSmits** [comment]
Thanks for clarifying! Much appreciated :-)

**Comment by shm007g** [comment]
```
dl_config = tfds.download.DownloadConfig(verify_ssl=False)  # Do this shit, or you get a request error!
examples, metadata = tfds.load('cnn_dailymail', with_info=True,
                               as_supervised=True,
                               download_and_prepare_kwargs={'download_config': dl_config})
```
