### ISSUE TITLE
Update documentation to display dataset module

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2813]
With community datasets coming in, TFDS will automatically document datasets generated outside of TFDS, but publicly available (e.g. in GCS).
We would like to point to the original source code which generated the dataset. Like the current "Source code" section: (e.g. https://www.tensorflow.org/datasets/catalog/accentdb).

We should save the `builber_cls.__module__` inside `dataset_info.json`. This require adding a new `module` field in dataset_info.proto (https://github.com/tensorflow/datasets/tree/master/tensorflow_datasets/core/proto)

Once community datasets are available, we could read the original module location and point to it in our documentation.

**Comment by NikhilBartwal** [comment]
@Conchylicultor I would like to take this up. Could you guide me how should i get started with `dataset_info.proto`. Thanks!

**Comment by Conchylicultor** [comment]
@NikhilBartwal Thank you for your interest.
You should:
* have a look at `dataset_info.proto` and add a new string `module` field.
* Regenerate the dataset_info_generated_pb2.py with instruction from https://github.com/tensorflow/datasets/tree/master/tensorflow_datasets/core/proto
* Then you should fill this field in the `dataset_info.py`
* Then add test in `dataset_info_test.py` to make sure this field is properly set and restored.

**Comment by vijayphoenix** [comment]
Closed by https://github.com/tensorflow/datasets/pull/2831
