### ISSUE TITLE
`tfds.image_classification.image_folder.ImageLabelFolder` has been deleted

### ISSUE THREAD

**Issue by SamuelMarks** [tensorflow/datasets#2861]
This PR removed a `class` I use in my codebase: https://github.com/tensorflow/datasets/pull/2089 c47aa6ecd0dd62e114102286fec478af1330107f

The `class` is documented here: https://www.tensorflow.org/datasets/catalog/image_label_folder - but the link breaks (because the file was deleted in that PR).

If this isn't a mistake, then dropping it from the documentation would be a good idea. If this is a mistake, then adding the file back would be prudent.

_In the meantime I'll copy the file into my codebase_

EDIT: Found it - https://www.tensorflow.org/datasets/api_docs/python/tfds/folder_dataset/ImageFolder https://github.com/tensorflow/datasets/blob/v4.1.0/tensorflow_datasets/core/folder_dataset/image_folder.py#L40-L163

**Comment by Conchylicultor** [comment]
As you pointed out, `tfds.image_classification.image_folder.ImageLabelFolder` was deprecated. New code should use:
 https://www.tensorflow.org/datasets/api_docs/python/tfds/folder_dataset/ImageFolder

Thank you for reporting. I'm sending a PR to remove the deprecated page.
