### ISSUE TITLE
How do I `decode_example` using the `tfds.features.FeaturesDict` from `tfds.folder_dataset.ImageFolder`?

### ISSUE THREAD

**Issue by SamuelMarks** [tensorflow/datasets#2875]
**What I was wondering**
How do I [`decode_example`](https://www.tensorflow.org/datasets/api_docs/python/tfds/features/FeaturesDict#decode_example) from the same [`tfds.features.FeaturesDict`](https://www.tensorflow.org/datasets/api_docs/python/tfds/features/FeaturesDict) as [`tfds.folder_dataset.ImageFolder`](https://www.tensorflow.org/datasets/api_docs/python/tfds/folder_dataset/ImageFolder) defines? 
Inheriting from [`tfds.core.GeneratorBasedBuilder`](https://www.tensorflow.org/datasets/api_docs/python/tfds/core/GeneratorBasedBuilder), I defined a `def _info(self) -> tfds.core.DatasetInfo` like:
```py
dataset_info = tfds.core.DatasetInfo(
    features=tfds.features.FeaturesDict(
        {
            "image": tfds.features.Image(  # shape=resolution + ((3 if rgb else 1),),
                encoding_format="jpeg",
                shape=self._image_shape,
                dtype=self._image_dtype,
            ),
            "label": tfds.features.ClassLabel(
                num_classes=2
            ),
            "image/filename": tfds.features.Text(),
        }
    ),
    supervised_keys=("image", "label")
)
```

**What I've tried so far**
I want to open up that [tfrecord](https://www.tensorflow.org/api_docs/python/tf/train/Example#ParseFromString) properly and efficiently:
```py
ds = tf.data.TFRecordDataset(("path_to_tfrecords",))
# Just testing, maybe `map` will be sufficiently efficient in production
for raw_record in ds.take(1):
    dataset_info.features.decode_example(raw_record)
```

I've also tried [`tf.io.parse_single_example`](https://www.tensorflow.org/api_docs/python/tf/io/parse_single_example) with that feature dict or:
```py
{
    'image/filename': tf.io.FixedLenFeature([], tf.string),
    'label': tf.io.FixedLenFeature([], tf.int64),
    'image': tf.io.FixedLenSequenceFeature(shape=self._image_shape,
                dtype=self._image_dtype)
    #'image_raw': tf.io.FixedLenFeature([], tf.string),
}
```

**It would be nice if...**
Currently I get this error, which means (I'm sure) that I'm doing something wrong:
```
File "3-8/lib/python3.8/site-packages/tensorflow_datasets/core/features/top_level_feature.py", line 48, in decode_example
    flat_example = self._flatten(serialized_example)
  File "3-8/lib/python3.8/site-packages/tensorflow_datasets/core/features/features_dict.py", line 201, in _flatten
    raise ValueError(
ValueError: Error while flattening dict: FeaturesDict received a non dict item: b'\n\xb2\x83\x04\n\x86\x01\n\x0eimage/filename\x12t\nr\np/var/folders/4l/k_7bksrn5dv6lr_sn6f7d8200000gn/T/mydatasetnamegy570nrf/datasetlabelname_7172_WA184736L2-4
```

**Environment information**

* Operating System: macOS Big Sur 11.1 (20C69)
* Python version: 3.8.6
* `tensorflow-datasets` version: 4.1.0
* `tensorflow` version: 2.4.0

**Comment by Conchylicultor** [comment]
TFDS automatically decode the TFDS records for you. Once the dataset is generated, you just have to do:

```python
ds = tfds.load('my_dataset', split='train')
```

**Comment by SamuelMarks** [comment]
I prefer to `class MyDataset(tfds.core.GeneratorBasedBuilder, skip_registration=True):`, which obviously skips this registration. I have the `class` in scope, how do I manually register it (just locally), e.g., is there a `tfds.add_dataset_cls(MyDataset)` interface?

**Comment by SamuelMarks** [comment]
Yep, that worked [`tfds.core.builder_from_directory`](https://www.tensorflow.org/datasets/api_docs/python/tfds/core/builder_from_directory) then `ds.as_dataset("train")`

**Comment by Conchylicultor** [comment]
1.

>  I have the class in scope, how do I manually register it (just locally), e.g., is there a tfds.add_dataset_cls(MyDataset) interface?

I'm confused. Why skipping dataset registration if you want to register it ?

 2. Once the data is generated, `tfds.load` should works even for non generated datasets. Please share a reproductible example and FULL stacktrace if this doesn't work for you.

3. To load an non-registered dataset, you can also directly instanciate `ds = MyDataset().as_dataset(split='train')`.

**Comment by SamuelMarks** [comment]
@Conchylicultor I am hacking around an issue with [`download_and_prepare`](https://www.tensorflow.org/datasets/api_docs/python/tfds/core/DatasetBuilder#download_and_prepare), where it used to download even when the tfrecords of the right version have been generated. Here is my [`_split_generators`](https://github.com/SamuelMarks/ml-prepare/blob/5333ea9/ml_prepare/_tfds/base.py#L92-L105)

So I explicitly look for the right version folder, and if it exists I try and read the tfrecords:
https://github.com/SamuelMarks/ml-params/blob/b18c948/ml_params/utils.py#L58-L113

Without this runaround the [`as_dataset`](https://www.tensorflow.org/datasets/api_docs/python/tfds/core/DatasetBuilder#as_dataset) line fails, because the info gives `total_num_examples=0, splits={}`. (this happens even after `download_and_prepare` now)

Maybe there's a non hacky way of doing this?
