### ISSUE TITLE
FeaturesDict({'image': Image(shape=(None, None, 3), dtype=tf.uint8)}) gives (1,224,224,3) shape

### ISSUE THREAD

**Issue by SamuelMarks** [tensorflow/datasets#2893]
**What I need help with / What I was wondering**
Training my NN, and I'm stuck on this error:
> ValueError: logits and labels must have the same shape ((None, None, None, 1) vs (None, 1))

Which made me think that maybe my image data isn't as expected. Here is [`my class`](https://github.com/SamuelMarks/ml-prepare/blob/503736e/ml_prepare/_tfds/base.py#L65-L86).

**What I've tried so far**
So I ran:
```py
import tensorflow_datasets.public_api as tfds


ds_builder = tfds.builder(my_name, data_dir=my_data_dir)
train_ds = ds_builder.as_dataset(split="train", as_supervised=True, batch_size=1)

tfds.show_examples(train_ds, ds_builder.info)
```

And got:
```py
ValueError: Image dimension should be 3. tfds.show_examples does not support batched examples or video.
```

So then I wrote a custom function, with also a call to [`tf.ensure_shape`](https://www.tensorflow.org/api_docs/python/tf/ensure_shape) to double check things:
```py
import matplotlib.pyplot as plt


def view_images(ds, num_examples):
    fig = plt.figure(figsize=(22, 22))    
    for example in ds.take(num_examples):
        image, label = example[0], example[1].numpy()
        
        image = tf.ensure_shape(image, [224, 224, 3])
        #if len(image.shape)==3:
        #    input_image = input_image.resize(input_image.shape()[0], input_image.shape()[1])

        ax = fig.add_subplot(4, 5, i+1, xticks=[], yticks=[])
        ax.imshow(image)
        ax.set_title(f"Label: {label}")

view_images(train_ds, 20)
```

But that gave:
```
InvalidArgumentError: Shape of tensor dummy_input [1,224,224,3]
                      is not compatible with expected shape [224,224,3]. [Op:EnsureShape]
``` 

**It would be nice if...**
There was a clear way of creating tfrecords from image folders

**Environment information**
* Operating System: macOS 11.1 (20C69)
* Python version: 3.8.6
* `tensorflow-datasets` version: 4.1.0
* `tensorflow` version: 2.4.0

**Comment by Conchylicultor** [comment]
You're passing `batch_size=1`:

```
train_ds = ds_builder.as_dataset(split="train", as_supervised=True, batch_size=1)
```
So images are batched. You should pass `batch_size=None` or use `ds_builder.as_dataset(split="train", as_supervised=True)` if you do not want to batch examples
