### ISSUE TITLE
Leverage tf.io.gfile as a downloader

### ISSUE THREAD

**Issue by mr-ubik** [tensorflow/datasets#29]
**Is your feature request related to a problem? Please describe.**
Using `tf-datasets` with private datasets stored on Google Cloud Storage returns an error code 403 since the current download method using request does not handle the authentification. Also, paths specified in the form of `gs://...` are not currently supported

**Describe the solution you'd like**
Using `tf.GFile` whenever possible (in place of the current `requests` based approach) would solve both of these issues.

**Additional context**
A possible implementation could add a check (or something like that) during the call of `_sync_download()` and then if the given URI matches `gs://` (or any supported URL) use tf.GFile to download it.

**Comment by rsepassi** [comment]
That's a great idea.

So just to be clear, `download_manager.download` fails on a `gs://...` path?

**Comment by rsepassi** [comment]
Confirmed that `gs://...` does not work. Working on a fix.
