### ISSUE TITLE
Unable to load the citrus_leaves dataset

### ISSUE THREAD

**Issue by Nikhileswar-Komati** [tensorflow/datasets#2903]
**Short description**
Description of the bug.
I was trying to perform image classification on "citrus_leaves" dataset. But I'm unable to load the dataset.

**Environment information**
* Operating System: Google Colab
* Python version: 3.6.9
* ``tfds-nightly` version: 4.1.0
* `tensorflow`: 2.4.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? - **"YES"**

**Reproduction instructions**

```
import tensorflow_datasets as tfds
ds = tfds.load('citrus_leaves', split='train', shuffle_files=True)
assert isinstance(ds, tf.data.Dataset)
print(ds)
```

**Link to logs**
Downloading and preparing dataset 63.87 MiB (download: 63.87 MiB, generated: 37.89 MiB, total: 101.76 MiB) to /root/tensorflow_datasets/citrus_leaves/0.1.1...
Dl Completed...: 100%
1/1 [00:01<00:00, 1.03s/ url]
Dl Size...:
0/0 [00:00<?, ? MiB/s]
Extraction completed...:
0/0 [00:00<?, ? file/s]

---------------------------------------------------------------------------
NonMatchingChecksumError                  Traceback (most recent call last)
<ipython-input-10-a7e74e62f145> in <module>()
      1 import tensorflow_datasets as tfds
----> 2 ds = tfds.load('citrus_leaves', split='train', shuffle_files=True)
      3 assert isinstance(ds, tf.data.Dataset)
      4 print(ds)

16 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_datasets/core/download/download_manager.py in _validate_checksums(url, path, computed_url_info, expected_url_info, force_checksums_validation)
    755         'https://www.tensorflow.org/datasets/overview#fixing_nonmatchingchecksumerror'
    756     )
--> 757     raise NonMatchingChecksumError(msg)
    758 
    759 

NonMatchingChecksumError: Artifact https://data.mendeley.com/datasets/3f83gxmv57/2/files/53398b67-6f0e-4a67-8384-e2b574b2ebf4/Citrus.zip, downloaded to /root/tensorflow_datasets/downloads/data.mend.com_data_3f83_2_file_5339-6f0e-4iYqD9qOtwvchSraf1DtLOTDd-g-auLIv-kMKGqn3wQU.zip.tmp.72880f8e3d8b445f82d267f96228f494/Citrus.zip, has wrong checksum. Expected: UrlInfo(size=63.87 MiB, checksum='9786d349b136a6e45359e64ababc857496d5909b313811707e0cb28a951977c7', filename='Citrus.zip'). Got: UrlInfo(size=29.28 KiB, checksum='6e5070ff4c0eaa675152002f615ea7efd24e9440a9f3f268aeaf895d19e5b987', filename='Citrus.zip').To debug, see: https://www.tensorflow.org/datasets/overview#fixing_nonmatchingchecksumerror

**Expected behavior**
What you expected to happen.

**Additional context**

**Comment by NikhilBartwal** [comment]
Thank you @Nikhileswar-Komati for pointing this out! The website URL seemed to be outdated and has been fixed in the recent PR.
The PR will be merged into the repo in a few days approx. 

However, if you need to use the dataset urgently, you can fork and build the local TFDS repo from [here](https://github.com/NikhilBartwal/datasets/tree/citrus_url) containing the required patch.

Please feel free to report any other issues you might encounter in the future!

**Comment by paperd** [comment]
Dataset still doesn't download with tfds.load()

**Comment by vijayphoenix** [comment]
Hi @paperd
Please use the latest version of tfds or `tfds-nightly`.
