### ISSUE TITLE
Modify existing checksum file

### ISSUE THREAD

**Issue by vijayphoenix** [tensorflow/datasets#2905]
**Short description**
Changing the download URL should modify the existing checksum file of a dataset.

For example:
Changing the download URL of the `citrus` dataset should modify `url_checksums/citrus_leaves.txt`.
However, `--register_checksum` flag in `tfds build` creates a new checksum file in `image_classification/checksums.tsv`

**Environment information**
* Operating System: Ubuntu 20.04
* Python version: 3.8
* `tensorflow-datasets`/`tfds-nightly` version: tfds-nightly

**Reproduction instructions**

```
tfds build --dataset citrus_leaves --register_checksums
```

**Expected behavior**
 `url_checksums/citrus_leaves.txt` should be modified

**Comment by NikhilBartwal** [comment]
Hey @vijayphoenix, I would like to take this up. As per what i understood what we can do is:

- When using the `--register_checksums` flag, check whether the dataset has the new folder structure and update/add the `checksums.tsv` file in the necessary location.
- Else, if the dataset follows the traditional structure, then add/update the `DATASET_NAME.txt` in `/url_checksums`

It would be great if you could point me to the script/file which is used for generating checksums and parsing the flags.Thanks!

**Comment by vijayphoenix** [comment]
`tfds build` is the part of CLI script files. The `register_checksum` flag is used here https://github.com/tensorflow/datasets/blob/9b5e431f1c9d90e207d69972edc1d71ee02b57e4/tensorflow_datasets/scripts/cli/build.py#L367

To modify the default checksum file path, you will have to make some changes here.

https://github.com/tensorflow/datasets/blob/9b5e431f1c9d90e207d69972edc1d71ee02b57e4/tensorflow_datasets/core/dataset_builder.py#L833

Let me know if you need any help.

**Comment by NikhilBartwal** [comment]
Thank you @vijayphoenix for the pointers and apologies for the late reply. 
As far as i understand, we will need to change the code to check the structure of the dataset and then record checksums accordingly.

I'm having network issues on my end today but I'll be sending the PR soon.
