### ISSUE TITLE
No easy way to build a validation set & test set when just one split is provided

### ISSUE THREAD

**Issue by ageron** [tensorflow/datasets#291]
**Short description**
In datasets like tf_flowers, only one split is provided. There does not seem to be any easy way to split this set into a training set, a validation set and a test set. I tried this:

```python
test_set = dataset["train"].take(500)
valid_set = dataset["train"].skip(500).take(1000)
train_set = dataset["train"].skip(3670 - 500 - 1000)
```

Unfortunately, this does not work because `dataset["train"]` is a shuffled dataset, so the code does not actually skip the same instances every time.

**Environment information**
* Operating System: MacOSX 10.13.6
* Python version: 3.6.8
* `tfds-nightly` version: tfds-nightly-1.0.1.dev201903180105
* `tf-nightly-2.0-preview` version: tf-nightly-2.0-preview-2.0.0.dev20190319

**Reproduction instructions**

```python
import tensorflow as tf
import tensorflow_datasets as tfds
from hashlib import md5

dataset = tfds.load("tf_flowers", as_supervised=True)

test_set = dataset["train"].take(500)
valid_set = dataset["train"].skip(500).take(1000)
train_set = dataset["train"].skip(3670 - 500 - 1000)

def image_hash(image):
    return md5(image.numpy()).hexdigest()    

test_image_hashes = set()
for test_image, test_label in test_set:
    h = image_hash(test_image)
    test_image_hashes.add(h)

for valid_image, valid_label in valid_set:
    h = image_hash(valid_image)
    assert h not in test_image_hashes  # ERROR: assertion fails!
```

This shows that at least one image from the test set also appears in the validation set.

**Expected behavior**
I wish there was a way to prevent the dataset from being shuffled differently every time I iterate over it. Arguably, when there's a single split, it should not be shuffled by default.

More generally, I wish there was a way to split a dataset easily into a training set, a validation set and a test set. Perhaps this should be an option in the `tfds.load()` function, like this:

```python
dataset = tfds.load("tf_flowers", validation_ratio=0.2, test_ratio=0.1)
```

Or more generally:

```python
dataset = tfds.load("tf_flowers", split_ratios={"valid": 0.2, "test": 0.1})
```

**Additional context**
It's sunny today.

**Comment by ageron** [comment]
Oops, sorry, it's actually possible and [documented here](https://github.com/tensorflow/datasets/blob/e53f3af5997bd0af9f7e61de3b8c98d8254e07b6/docs/splits.md).

Here's an example:

```python
test_split, valid_split, train_split = tfds.Split.TRAIN.subsplit([10, 15, 75])

test_set = tfds.load("tf_flowers", split=test_split, as_supervised=True)
valid_set = tfds.load("tf_flowers", split=valid_split, as_supervised=True)
train_set = tfds.load("tf_flowers", split=train_split, as_supervised=True)
```

**Comment by benihime91** [comment]
`AttributeError: 'Split' object has no attribute 'subsplit``... I get this error .

**Comment by Conchylicultor** [comment]
@benihime91 have a look to the new split API: https://www.tensorflow.org/datasets/splits

**Comment by smnrdln** [comment]
> `AttributeError: 'Split' object has no attribute 'subsplit``... I get this error .

I have the same issue.
