### ISSUE TITLE
How can I pass parameters to the builder config from the `load` method?

### ISSUE THREAD

**Issue by AmitMY** [tensorflow/datasets#2924]
**What I need help with / What I was wondering**
I have a dataset where I need to supply a decryption key when loading.

```python
import tensorflow_datasets as tfds
 
my_dataset = tfds.load('my_dataset', train_decryption_key='***')
```

I could not find any reference how to pass such parameter that it would appear in the `_builder_config`. I tried the above code, but the parameter is unexpected.

**Comment by Conchylicultor** [comment]
I'm not sure where you want to pass the kwargs. to MyDataset ? Or to MyDatasetBuilderConfig ? In both cases, you can use `builder_kwargs=` kwarg of `tfds.load`.

```python
builder_kwargs=dict(train_decryption_key='***')
# or
builder_kwargs=dict(config=MyDatasetConfig(train_decryption_key))
```

**Comment by AmitMY** [comment]
Thanks for detailing both options :)
I decided to go with the first one. Cheers
