### ISSUE TITLE
Unable to import tensorflow_datasets, 'tensorflow_datasets.core.download' has no attribute 'checksums'

### ISSUE THREAD

**Issue by kristalization** [tensorflow/datasets#2957]
AttributeError: module 'tensorflow_datasets.core.download' has no attribute 'checksums'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-26-66fff9018d39> in <module>
----> 1 import tensorflow_datasets

~\anacondaNov3\envs\tensorflow\lib\site-packages\tensorflow_datasets\__init__.py in <module>
     49   from tensorflow_datasets.__init__py2 import *
     50 else:
---> 51   from tensorflow_datasets import __init__py3 as api
     52   from tensorflow_datasets.__init__py3 import *
     53 

~\anacondaNov3\envs\tensorflow\lib\site-packages\tensorflow_datasets\__init__py3.py in <module>
     41 # needs to happen before anything else, since the imports below will try to
     42 # import tensorflow, too.
---> 43 from tensorflow_datasets.core import tf_compat
     44 tf_compat.ensure_tf_install()
     45 

~\anacondaNov3\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\__init__.py in <module>
     23 # pylint:disable=g-import-not-at-top
     24 
---> 25 from tensorflow_datasets.core import community  # pylint: disable=g-bad-import-order
     26 
     27 from tensorflow_datasets.core.constants import add_data_dir

~\anacondaNov3\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\community\__init__.py in <module>
     16 """Community dataset API."""
     17 
---> 18 from tensorflow_datasets.core.community.load import builder_cls_from_module
     19 
     20 

~\anacondaNov3\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\community\load.py in <module>
     20 from typing import Type
     21 
---> 22 from tensorflow_datasets.core import dataset_builder
     23 from tensorflow_datasets.core import registered
     24 

~\anacondaNov3\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in <module>
     81 
     82 
---> 83 class DatasetBuilder(registered.RegisteredDataset):
     84   """Abstract base class for all datasets.
     85 

~\anacondaNov3\envs\tensorflow\lib\site-packages\tensorflow_datasets\core\dataset_builder.py in DatasetBuilder()
    302   @classmethod
    303   @functools.lru_cache(maxsize=None)
--> 304   def url_infos(cls) -> Optional[Dict[str, download.checksums.UrlInfo]]:
    305     """Load `UrlInfo` from the given path."""
    306     # Note: If the dataset is downloaded with `record_checksums=True`, urls

AttributeError: module 'tensorflow_datasets.core.download' has no attribute 'checksums'

 Environment Information
absl-py==0.10.0
argon2-cffi @ file:///C:/ci/argon2-cffi_1596828549974/work
astunparse==1.6.3
async-generator==1.10
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
backcall==0.2.0
bleach @ file:///tmp/build/80754af9/bleach_1600439572647/work
brotlipy==0.7.0
cachetools==4.2.0
certifi==2020.12.5
cffi @ file:///C:/ci/cffi_1606255207413/work
chardet==4.0.0
colorama @ file:///tmp/build/80754af9/colorama_1607707115595/work
cryptography @ file:///C:/ci/cryptography_1607639129468/work
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.3
entrypoints==0.3
flatbuffers==1.12
future==0.18.2
gast==0.3.3
google-auth==1.24.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
googleapis-common-protos==1.52.0
grpcio==1.32.0
h5py==2.10.0
idna==2.10
importlib-metadata==3.4.0
importlib-resources==5.0.0
ipykernel @ file:///C:/ci/ipykernel_1596208728219/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///C:/ci/ipython_1604101327119/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
jedi @ file:///C:/ci/jedi_1608902611503/work
Jinja2==2.11.2
json5==0.9.5
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1601311786391/work
jupyter-core @ file:///C:/ci/jupyter_core_1606130908768/work
jupyterlab==2.2.6
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///tmp/build/80754af9/jupyterlab_server_1594164409481/work
Keras-Preprocessing==1.1.2
Markdown==3.3.3
MarkupSafe @ file:///C:/ci/markupsafe_1594405949945/work
mistune @ file:///C:/ci/mistune_1594373272338/work
nbclient @ file:///tmp/build/80754af9/nbclient_1602783176460/work
nbconvert @ file:///C:/ci/nbconvert_1601914921407/work
nbformat @ file:///tmp/build/80754af9/nbformat_1610738111109/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1606153767164/work
notebook @ file:///C:/ci/notebook_1608829952595/work
numpy==1.19.5
oauthlib==3.1.0
opt-einsum==3.3.0
packaging @ file:///tmp/build/80754af9/packaging_1607971725249/work
pandocfilters @ file:///C:/ci/pandocfilters_1605102427207/work
parso==0.7.0
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
prometheus-client @ file:///tmp/build/80754af9/prometheus_client_1606344362066/work
promise==2.3
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
protobuf==3.14.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
Pygments @ file:///tmp/build/80754af9/pygments_1610565767015/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing==2.4.7
pyrsistent @ file:///C:/ci/pyrsistent_1600123688363/work
PySocks @ file:///C:/ci/pysocks_1594394709107/work
python-dateutil==2.8.1
pywin32==227
pywinpty==0.5.7
pyzmq==20.0.0
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7
Send2Trash @ file:///tmp/build/80754af9/send2trash_1607525499227/work
six==1.15.0
tensorboard==2.4.1
tensorboard-plugin-wit==1.7.0
tensorflow==2.4.0
tensorflow-datasets==4.2.0
tensorflow-estimator==2.4.0
tensorflow-metadata==0.26.0
termcolor==1.1.0
terminado==0.9.2
testpath==0.4.4
tfds-nightly==4.2.0.dev202101160107
tornado @ file:///C:/ci/tornado_1606935947090/work
tqdm==4.56.0
traitlets @ file:///tmp/build/80754af9/traitlets_1602787416690/work
typing-extensions==3.7.4.3
urllib3==1.26.2
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
Werkzeug==1.0.1
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306165655/work
wincertstore==0.2
wrapt==1.12.1
zipp==3.4.0

**Comment by jatin-code777** [comment]
Unable to reproduce this.

Have you tried using tfds-nightly?

**Comment by kristalization** [comment]
yes, I have tried that!

**Comment by kristalization** [comment]
> Unable to reproduce this.
> 
> Have you tried using tfds-nightly?

Yes, I have tried that!

**Comment by kristalization** [comment]
I am not sure what I did, but it works now. Installed a completely new environment.
