### ISSUE TITLE
Kitti dataset

### ISSUE THREAD

**Issue by claireroman** [tensorflow/datasets#2958]
Hi, 

I don't understand Kitti dataset. Indeed, when I run : 

ds = tfds.load('kitti', split='train', shuffle_files=True)
print(ds)

I have some strange info (copied below). Why is image shape (None, None, 3) ?

Thank you in advance.

{'train': <PrefetchDataset shapes: {image: (None, None, 3), image/file_name: (), objects: {alpha: (None,), bbox: (None, 4), dimensions: (None, 3), location: (None, 3), occluded: (None,), rotation_y: (None,), truncated: (None,), type: (None,)}}, types: {image: tf.uint8, image/file_name: tf.string, objects: {alpha: tf.float32, bbox: tf.float32, dimensions: tf.float32, location: tf.float32, occluded: tf.int64, rotation_y: tf.float32, truncated: tf.float32, type: tf.int64}}>, 'validation': <PrefetchDataset shapes: {image: (None, None, 3), image/file_name: (), objects: {alpha: (None,), bbox: (None, 4), dimensions: (None, 3), location: (None, 3), occluded: (None,), rotation_y: (None,), truncated: (None,), type: (None,)}}, types: {image: tf.uint8, image/file_name: tf.string, objects: {alpha: tf.float32, bbox: tf.float32, dimensions: tf.float32, location: tf.float32, occluded: tf.int64, rotation_y: tf.float32, truncated: tf.float32, type: tf.int64}}>, 'test': <PrefetchDataset shapes: {image: (None, None, 3), image/file_name: (), objects: {alpha: (None,), bbox: (None, 4), dimensions: (None, 3), location: (None, 3), occluded: (None,), rotation_y: (None,), truncated: (None,), type: (None,)}}, types: {image: tf.uint8, image/file_name: tf.string, objects: {alpha: tf.float32, bbox: tf.float32, dimensions: tf.float32, location: tf.float32, occluded: tf.int64, rotation_y: tf.float32, truncated: tf.float32, type: tf.int64}}>}

**Comment by vijayphoenix** [comment]
```
Why is image shape (None, None, 3)
```

This means that the Image shape is not defined but it will have three channels.

**Comment by Conchylicultor** [comment]
As @vijayphoenix said, each images in this dataset can have variable shape (e.g. `(256, 256, 3)`, `(123, 162, 3)`, ...).
If you want to batch them, you likely want to resize the images first.
