### ISSUE TITLE
Make cold start faster

### ISSUE THREAD

**Issue by AmitMY** [tensorflow/datasets#2959]
**Is your feature request related to a problem? Please describe.**
```python
import tensorflow_datasets as tfds
```
takes many seconds to complete

**Describe the solution you'd like**
faster import, perhaps by internally only differentially importing things when needed

**Describe alternatives you've considered**
None

**Additional context**
I'm trying to write a few datasets, and development is slow when this cold start is slow

**Comment by Conchylicultor** [comment]
+1
Import time is becoming an issue, we should try investigate to optimise them (e.g. by lazy importing dataset source code as needed).
If someone has ideas, don't hesitate to contribute.

**Comment by Conchylicultor** [comment]
I quickly profile the import time with

```sh
pip install tuna
python -X importtime -c "import tensorflow ; import tensorflow_datasets"  &> importtime.log
tuna importtime.log
```
If I read this correctly, most of the import time is taken by `import IPython` and the `import pandas.io.formats.style`. We should make both of the imports lazy which should already reduce by ~half the import time.

[importtime.log](https://github.com/tensorflow/datasets/files/5835649/importtime.log)

**Comment by Conchylicultor** [comment]
I'm gonna try a PR to remove those 2 imports. Please don't hesitate to share if this do not fix the issue.

Note: TFDS depends on TF which takes a while to import. The TF import time is unfortunately not really compressible from the TFDS side. So TFDS import time should be evaluated after importing TF:

```python
import tensorflow as tf
start = time.now()
import tensorflow_datasets as tfds
end = time.now()
print('Import time: {end-start} seconds')
```
