### ISSUE TITLE
Better `tfds.as_dataframe` ragged tensor visualization

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#2966]
Currently, datasets which contains nested sequences `Sequence(Sequence())` are not correctly displayed.

For example: Click on `Display examples...` in https://www.tensorflow.org/datasets/catalog/arc

We should investigate why nothing seems to be displayed. In theory, calling `tfds.as_dataframe(ds, ds_info)` should call `FeatureConnector.repr_html_ragged(ex)` on the ragged tensor and display its `repr`.

**Comment by jatin-code777** [comment]
Hi, I would like to work on this

**Comment by Conchylicultor** [comment]
Hey @jatin-code777, thank you for your interest !
As explained in https://www.tensorflow.org/datasets/contribute, no need to get the issue assigned. Simply send us a PR directly
