### ISSUE TITLE
How to use map function on datasets other than MNIST

### ISSUE THREAD

**Issue by LawrenceXu13467** [tensorflow/datasets#298]
I am relatively new and sorry if this question sounds silly. But what parameters shall we include in the map_func so that we can modify images, labels, and other stuff from more complex datasets?
Thanks for your time!!!!!

**Difference in _OptionsDataset shapes**
I was trying to use map function to resize the datasets I got from loading "coco2014". However, I notice a difference between the MNIST example and COCO datasets.

**MNIST**
here is mnist_train:
<_OptionsDataset shapes: ((28, 28, 1), ()), types: (tf.uint8, tf.int64)>

**COCO**
here is coco_train:
<_OptionsDataset shapes: {image: (None, None, 3), image/filename: (), objects: {bbox: (None, 4), label: (None,), is_crowd: (None,)}}, types: {image: tf.uint8, image/filename: tf.string, objects: {bbox: tf.float32, label: tf.int64, is_crowd: tf.bool}}>

**This does not work**
def scale(image, filename, objects):
    ....
    ....
    ....

train_data = coco_train.map(scale)

Above code returns an error:
TypeError: scale() missing 3 required positional arguments: 'img_name', 'objects', and 'is_crowd'

**Also Tried, not working**
train_data = (coco_train.values()).map(scale)

And this returns an error:
AttributeError: '_OptionsDataset' object has no attribute 'values'

**Environment information**
(if applicable)
* Operating System: Ubuntu 18.04.2 LTS
* Python version: 3.6
* `tensorflow-datasets` version: 1.0.1
* `tensorflow-gpu` version: 2.0.0a0

**Comment by LawrenceXu13467** [comment]
**The lambda expression seems to work**
train_data = coco_train.map(lambda x: {'image': x['image']/255, 'image/filename': x['image/filename'],'objects': x['objects']})

**But is there another solution? Like how to define it into a separate function**
**Thanks!!**

**Comment by Conchylicultor** [comment]
I'm not sure I understand, you can always create another function no ?

```
def process(x):
  x['image'] = x['image'] / 255
  return x

ds.map(process)
```

**Comment by LawrenceXu13467** [comment]
Thanks for your help! Yes, you are right. Sorry, I just realize it's a dictionary for coco dataset instead of a tuple like the mnist example, and that's why it gave me the missing positional arguments error.
