### ISSUE TITLE
Any reference on how to build multi-label classification datasets?

### ISSUE THREAD

**Issue by sakinaljana** [tensorflow/datasets#2992]
**What I need help with / What I was wondering**
Need reference or explanation on how to define the multi label class inside TFDS. AFAIK, all the datasets inside the TFDS mostly about multi-class datasets, not the multi-label ones.

Just wondering if you guys have experience on how to defining the multi-label class definition

**What I've tried so far**
- Already tried to read some datasets code, but still no luck.

**It would be nice if...**
Would be nice if there is any link/reference where i can take a look for the concrete example of creating multi-label dataset

Thanks in advance!

**Comment by Conchylicultor** [comment]
It's depend how you're planning to use the labels in your user code ?
One way is to represent as `{'label1': tf.bool,...}`. See https://www.tensorflow.org/datasets/catalog/celeb_a features for an example

**Comment by sakinaljana** [comment]
@Conchylicultor thanks for the response,

basically the label will be in `one_hot` format (e.g: [0, 1, 1, 1]),

seems boolean format make sense. thanks for the suggestion man!

**Comment by sakinaljana** [comment]
Hi @Conchylicultor,

Need your more advice for the features format. Currently, i'm trying to use tf.bool as one of the feature. However, it throw errors:
`ValueError: Feature not supported: {tf.bool}`

This is my features structure:

```python
def _features(self):
  return tfds.features.FeaturesDict({
      "text": tfds.features.Text(),
      "labels": tfds.features.Sequence({
          tf.bool
      }, length=len(self._label_names))
  })
```

Could you help to identify the cause of the error?

**Comment by Conchylicultor** [comment]
You should use either: `tfds.features.Sequence(tf.bool)` or `tfds.features.Sequence({'label': tf.bool})`. Not `tfds.features.Sequence({tf.bool})` as `set` is not a valid feature type

**Comment by sakinaljana** [comment]
Thanks, it works!
