### ISSUE TITLE
Tensorflow 2.4.1 unshardable dataset from image directory 

### ISSUE THREAD

**Issue by LastHorizon** [tensorflow/datasets#3008]
/!\ IF YOU WANT PEOPLE TO HELP YOU, PLEASE GIVE AS MUCH DETAIL AS POSSIBLE, INCLUDING THE FULL STACKTRACE AND CODE SNIPPET

**Short description**
Hi All, 

I hope this is the right section to report this under: 

I am moving from tensorflow 2.3.1 to tensorflow 2.4.1 as I have changed GPUs from 2 x RTX 2060s to 2 x RTX 3090.  I create a dataset using  tf.keras.preprocessing.image_dataset_from_directory. When I run model.fit this ran fine under TF 2.3.1 but under TF 2.4.1 I receive the error **"found an unshardable source dataset"**

If the dataset is not sharded then I do not appear to get the speed bonus from using my 2x 30XX series GPUs. 

**Environment information**
* Operating System: Ubuntu 18.04
* Python version: 3.8
* `tensorflow-datasets`/`tfds-nightly` version: 4.2.0
* `tensorflow`/`tf-nightly` version: 2.4.1

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?

**Reproduction instructions**

```
## create data set 
        train_ds = tf.keras.preprocessing.image_dataset_from_directory(
          data_dir,
          validation_split=validation_split,
          subset="training",
          seed=seed,
          image_size=(img_height, img_width),
          batch_size=batch_size,
          color_mode='grayscale'
        )

        val_ds = tf.keras.preprocessing.image_dataset_from_directory(
          data_dir,
          validation_split=validation_split,
          subset="validation",
          seed=seed,
          image_size=(img_height, img_width),
          batch_size=batch_size,
          color_mode='grayscale'
        )


## create model with mirrored strategy 
        mirrored_strategy = tf.distribute.MirroredStrategy()

        with mirrored_strategy.scope():

                model, offset = make_or_restore_model(checkpoint_dir, model_save_dir, log_dir, num_classes, dim_x, dim_y, dim_z)


## train model 

        history = model.fit(
          train_ds,
          validation_data=val_ds,
          epochs=epochs,
          initial_epoch=offset,
          callbacks=callbacks,
          steps_per_epoch=None,
          validation_steps=None
        )

```

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
Data set to automatically shard using the model.fit method as per TF 2.3.1 set up 

**Additional context**

**Comment by Conchylicultor** [comment]
This seems unrelated with TFDS (the `pip install tensorflow_datasets` package). I would suggest you to post to `tensorflow/tensorflow` instead.
