### ISSUE TITLE
AssertionError: Two examples share the same hashed key!

### ISSUE THREAD

**Issue by sumanthd17** [tensorflow/datasets#3013]
**What I need help with / What I was wondering**
I'm trying to create my own dataset for language modelling. The data files consist of language data with 1 sentence per line.
But I'm getting this error when I try to build my dataset.

`AssertionError: Two examples share the same hashed key! See logs above to view the examples.`

The stack trace shows these two examples to have the same hash

```
ERROR[tfrecords_writer.py]: 1st example: {'text': <tf.Tensor: shape=(), dtype=string, numpy=b'* * * * * *'>}                                                                                                
ERROR[tfrecords_writer.py]: 2nd example: {'text': <tf.Tensor: shape=(), dtype=string, numpy=b') * * * * *'>} 
```

**What I've tried so far**
I tried to search the dataset if there are 2 lines in the dataset with the same content, but there isn't. I deduped the dataset.
The strings are also different from each other, so not sure why this is happening. 

**It would be nice if...**
I would like to know the reason behind this and possible way to get rid of the error. Or is there a way to override this?

**Environment information**
(if applicable)
* Operating System: MacOS 11.0.1
* Python version: 3.6.12
* `tensorflow-datasets`/`tfds-nightly` version: 4.2.0+nightly
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.4.1

**Comment by summelon** [comment]
Hi, I met the same problem as yours when I tried to build my customized dataset.
How did you solve this problem?

**Comment by NikhilBartwal** [comment]
@sumanthd17 @summelon It looks like the key that is used for yielding each example in the `_generate_examples` is not unique. ( as shown [Here](https://www.tensorflow.org/datasets/add_dataset#dataset_example) )
The problem lies not in the data itself but the way each example is associated with a key. 
Please share the complete logs along with a snippet of the code used to generate the examples for more info. Thanks!

**Comment by summelon** [comment]
> @sumanthd17 @summelon It looks like the key that is used for yielding each example in the `_generate_examples` is not unique. ( as shown [Here](https://www.tensorflow.org/datasets/add_dataset#dataset_example) )
> The problem lies not in the data itself but the way each example is associated with a key.
> Please share the complete logs along with a snippet of the code used to generate the examples for more info. Thanks!

Thanks for your reply!
I have figured it out!
`tfds` need a unique id for each image file.
In my dataset, I have not such ids.
So here are my solution:
```python=
def _generate_examples(self, path):
      """Yields examples."""
      path = os.path.join(path, '*.jpg')
      img_files = glob.glob(path)
      for f in img_files:
        label_num = int(f.split('/')[-2])
        image_id = random.getrandbits(256)
        yield image_id, {
            'image': f,
            'label': label_num
        }   
```

**Comment by NikhilBartwal** [comment]
@summelon Since your dataset uses random ids, thus it is possible for two images to have same ids (however unlikely it might be) 
To resolve this, you can extract the image name from the `path` and use it as the `image_id` as each image would be having a unique name.

**Comment by sumanthd17** [comment]
Yes the error was that 2 examples shared the same hash key. You can add an enumerate in your for loop and that will give you unique numbers. That solved the issue for me
