### ISSUE TITLE
tfds.features.Audio(dtype=tf.int16) is written out as tf.train.Int64List, quadrupaling its size

### ISSUE THREAD

**Issue by lxkain** [tensorflow/datasets#3015]
**Short description**
Building datasets from raw int16 waveforms quadrupels storage requirements

**Environment information**
* Operating System: ubuntu 20.04
* Python version: 3.8.7
* `tensorflow-datasets` version: 4.2.0
* `tensorflow` version: 2.4.1

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? From the sources it appears so.

In https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/example_serializer.py:127 we have 

```
def _item_to_tf_feature(item, tensor_info):
  """Single item to a tf.train.Feature."""
  v = _item_to_np_array(item, shape=tensor_info.shape, dtype=tensor_info.dtype)

  # Convert boolean to integer (tf.train.Example does not support bool)
  if v.dtype == np.bool_:
    v = v.astype(int)

  v = v.flatten()  # Convert v into a 1-d array
  if np.issubdtype(v.dtype, np.integer):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=v))
```

but that last line is going to essentially cast a 16-bit value to a 64-bit one. Our planned workaround is to define our own feature, e.g. Audio16, which will represent our data as tf.string, so it eventually becomes a tf.train.BytesList. Is this the best approach? Is a more generic solution planned?

**Comment by Conchylicultor** [comment]
I agree with you, this is a limitation of tf.train.Example proto which only support int64. https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/core/example/feature.proto#L83

One solution would be to update the `example_serializer.py` / `example_parser.py` to store tf.Tensor as bytes, instead of int64. This would solve the issue in the general case.
The drawback is that it would makes it very hard to inspect the serialized proto. We should also make sure that the `tf.string > tf.in16` decoding do not impact the pipeline performances.

If someone wants to investigate this, don't hesitate to send a PR.

**Comment by harsh020** [comment]
@Conchylicultor Hi, I was looking into this issue.

Currently, I am thinking to change the `int64` to `byte` and pass a `ByteList` to serialize if the `dtype` is `int64` here:
https://github.com/tensorflow/datasets/blob/e821aa8e6ad05f7cebd5ccb3e0767134ec60398d/tensorflow_datasets/core/example_serializer.py#L134-L143

But, I suspect this might further break things. Could you brief me a bit. And yes, if you have certain resources to study before getting started that would be a great help!

Thank you.

**Comment by Conchylicultor** [comment]
Thank you for looking into this. To see if things break, the best is to run the `features/` unittests which test encoding/decoding features:
https://github.com/tensorflow/datasets/blob/c5cdff996e92e6b6fc586718041015abbc769947/tensorflow_datasets/testing/feature_test_case.py#L313

It will make sure that data are correctly decoded. When updating `example_serializer.py`,  `example_parser.py` should be updated too to perform the reverse operation
