### ISSUE TITLE
Checksums are overwritten 

### ISSUE THREAD

**Issue by EmanueleGhelfi** [tensorflow/datasets#305]
**Short description**
I want to implement a new dataset.
For this dataset I need to download multiple files from gcloud storage. The problem is that even if I run the `download_manager` with the flag `_register_checksums=True` the checksums are overwritten since the function `store_checksums` inside checksums opens the checksum file with the `w` option. By running the download manager with  `_register_checksums=True` I'm able to download my dataset, however when I delete it from the disk I'm not able to download it again since the checksums stored in the checksum file are only a few. 

**Environment information**
* Operating System: Arch Linux
* Python version: 3.6
* `tfds-nightly` version: 1.0.1.dev201903180105
* tf-nightly-gpu-2.0-preview==2.0.0.dev20190318

**Reproduction instructions**

```
import glob
import os

import tensorflow_datasets.public_api as tfds
import tensorflow as tf


class MyDataset(tfds.core.GeneratorBasedBuilder):
    """Short description of my dataset."""

    VERSION = tfds.core.Version("0.1.0")

    def _info(self):
        # Specifies the tfds.core.DatasetInfo object
        return tfds.core.DatasetInfo(
            builder=self,
            # This is the description that will appear on the datasets page.
            description=(
                "This is the dataset for xxx images."
            ),
            # tfds.features.FeatureConnectors
            features=tfds.features.FeaturesDict(
                {
                    "image_description": tfds.features.Text(),
                    "image_rgb": tfds.features.Image(shape=(64, 64, 3)),
                }
            ),
        )

    def _split_generators(self, dl_manager):
        # Downloads the data and defines the splits
        # dl_manager is a tfds.download.DownloadManager that can be used to
        # download and extract URLs
        all_files = tf.io.gfile.glob(
            "gs://mypath/*.png"
        )

        # set the flag to true in oder to store checksums
        dl_manager._register_checksums = True
        dl_paths = dl_manager.download(all_files)
        # extracted = dl_manager.extract(dl)
        return [
            tfds.core.SplitGenerator(
                name="train", num_shards=10, gen_kwargs={"images_dir_path": dl_paths}
            )
        ]

    def _generate_examples(self, images_dir_path):
        # Read the input data out of the source files
        for image_file in images_dir_path:
            yield {"image_description": "My dataset 64x64", "image_rgb": image_file}


if __name__ == "__main__":
    builder = tfds.builder("mydataset")
    builder.download_and_prepare()

```

**Expected behavior**
The checksum file should contain the checksum of all my downloaded files.

**Additional context**
I think the problem can be the parallel download of files or the option 'w' when opening the checksum file.

**Comment by EmanueleGhelfi** [comment]
Update: even when calling `dl_manager.download` sequentially for each file to download the checksums are overwritten since the function returning the checksums `_get_sizes_checksums(checksums_path)` is decorated with `@utils.memoize()` that caches the calls to the function. In this way the function returns always the content of the file at the moment of the first call.

**Comment by pierrot0** [comment]
I believe issue was fixed by commit 6358a39e937dd43ea7d5915cf97733ab81d65275.

**Comment by EmanueleGhelfi** [comment]
By the way I do not have these changes in my tensorflow dataset code installed from pip.

**Comment by rsepassi** [comment]
Try `pip install tfds-nightly` @EmanueleGhelfi. These changes will be in the next full release of `tensorflow-datasets`.

**Comment by EmanueleGhelfi** [comment]
I've installed the nightly version
