### ISSUE TITLE
How to generate my own dataset locally?

### ISSUE THREAD

**Issue by FreshmanLin** [tensorflow/datasets#3059]
**What I need help with / What I was wondering**
I have a task which is to complete the experiment: https://github.com/google-research/vision_transformer, and after I successfully run the train code with cifar10 and cifar100, next step I want to train the model with my own dataset.  I have already made files of tfrecords, but this dataset is not registered in tfds.list_builders(). I don't want to send pull request for my dataset, and just want to make it the format of tfds, then access it as the training data locally, how could I achieve it?
![image](https://user-images.githubusercontent.com/34671700/108996687-a7323b80-76d9-11eb-9ed9-fd1ac8713a75.png)

**What I've tried so far**
I have read the tutorial of "add_dataset", but where is the scripts file: create_new_dataset.py which should have existed in the directory tensorflow_datasets/scripts/. Or rather, should this file be created by myself?
![image](https://user-images.githubusercontent.com/34671700/108997331-6dae0000-76da-11eb-8722-3c95c7fcc414.png)

**It would be nice if...**
If there is any more detailed new_dataset generating code?

**Comment by Conchylicultor** [comment]
Which version of the doc are you reading ? I would suggest to read the english version of https://www.tensorflow.org/datasets/add_dataset.

**Comment by FreshmanLin** [comment]
> `create_new_dataset` has been deleted months ago. Which version of the doc are you reading ? I would suggest to read the english version of https://www.tensorflow.org/datasets/add_dataset.

Right, the version of doc I read is in Chinese...
