### ISSUE TITLE
Challenges

### ISSUE THREAD

**Issue by bhack** [tensorflow/datasets#306]
**Is your feature request related to a problem? Please describe.**
Can we add an issue template related to challenges?

**Describe the solution you'd like**
I think that could be useful to have an issue template or a general structure for handling challenges coverage cause challenges often could group multiple datasets
**Describe alternatives you've considered**

**Additional context**
I.e. see CVPR 2019 Long-term Visual Localization https://visuallocalization.net/datasets/ or CVPR 2018 Robust Vision http://www.robustvision.net/

**Comment by Conchylicultor** [comment]
What is the issue exactly ? Could you provide some context ?

**Comment by bhack** [comment]
To have a issue template for challenges instead of open one for every dataset. And eventually to have a challenges data structure/metadata to group datasets.

**Comment by Conchylicultor** [comment]
Why not using the template for datasets, and specify in the issue that you want all datasets related to this challenge ?
The drawback is that it makes it would make it harder to track progress on individual dataset (ex: to distribute the work).

**Comment by bhack** [comment]
I think any solution to handle this metadata could be good.

**Comment by rsepassi** [comment]
Yes, please use the dataset request template.
