### ISSUE TITLE
TFDS 'pylint' errors

### ISSUE THREAD

**Issue by NikhilBartwal** [tensorflow/datasets#3087]
**Short description**
Using `pylint` on TFDS does not generate a 10/10 code rating.

Running `pylint --rcfile=pylintrc tensorflow_datasets/audio` on windows as mentioned [here](https://www.tensorflow.org/community/contribute/code_style#pylint) only gives a 9.03/10  

**Expected behavior**
Using `pylint` should ideally give a 10/10 rating.

**Comment by NikhilBartwal** [comment]
I will be sending a PR for `tensorflow_datasets/audio` and `tensorflow_datasets/image` soon.
Anyone who wants to contribute, please feel free to comment and send a PR.

**Comment by vijayphoenix** [comment]
Similar https://github.com/tensorflow/datasets/issues/1644

**Comment by vijayphoenix** [comment]
Yeah, please reference #1644
