### ISSUE TITLE
Expose the number of example in subplit

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#309]
**Is your feature request related to a problem? Please describe.**
Currently, when using subsplit, the only way to get the number of example associated with it is to iterate over the entire dataset.

**Describe the solution you'd like**
Knowing this would require knowing the exact number os sample per shards (in stats).

Not sure what the API could looks like ? Maybe:
```
info.splits.len(tfds.Split.TRAIN.subsplit(tfds.percent[:50]))
```

**Comment by ParthS007** [comment]
@Conchylicultor I want to work on this. How should I proceed with it? Thanks for the help.

**Comment by Conchylicultor** [comment]
Closing this in favor of: https://github.com/tensorflow/datasets/issues/1403
