### ISSUE TITLE
Community Datasets (GSoC - Discussion Thread)

### ISSUE THREAD

**Issue by rushabh-v** [tensorflow/datasets#3097]
Hello everyone,

I am Rushabh Vasani, a 3rd-year IT student from India. I am interested in the `community datasets` project idea. Seems like a "DockerHub of Datasets" :)

Opening this thread to show my interest and to use it as a medium to share my thoughts. I also had a small doubt,

- Should the system store the entire datasets or the users need to host the data somewhere else and publish only the scripts to `download and prepare` the dataset (the way we do it in tfds currently)?

Thanks, Looking forward!

**Comment by vijayphoenix** [comment]
Hi @rushabh-v,

Thank you for your interest in TFDS.

> Should the system store the entire datasets or the users need to host the data somewhere else and publish only the scripts to download and prepare the dataset (the way we do it in tfds currently)?

In community datasets. users write scripts using the procedure described [here](https://www.tensorflow.org/datasets/add_dataset). The only difference is that the user can use and share this dataset script without adding it to TFDS.

For example, a user can write a dataset script and publish it on his/her GitHub repository.
This script can use any publicly available dataset. The user need not host the data on their own.

I hope this clarifies your doubt.

I am closing this issue. If you have any further questions, feel free to post them on the GitHub discussion thread https://github.com/tensorflow/datasets/discussions/3101

**Comment by rushabh-v** [comment]
Sure, thanks for the clarification @vijayphoenix.
