### ISSUE TITLE
Support TF 2.0

### ISSUE THREAD

**Issue by lc0** [tensorflow/datasets#31]
Any plans to support **TensorFlow 2**? Since **Datasets** are not released and hopefully TF2 is going to be released in the next months, would totally make sense.

What do you think? 

Currently I've got the issues with contrib part
```python
# Flatten
--> 127   flat_ds = tf.contrib.framework.nest.flatten(nested_ds)
    128   flat_np = []
```

**Comment by rsepassi** [comment]
Linked issue: tensorflow/tensorflow#25367

**Comment by rsepassi** [comment]
TFDS is now 2.0-ready. We’re testing against 2.0 in Travis.

One exception for now is that the LSUN dataset cannot be generated with TF 2.0 because of the use of `tf.contrib`. We have a plan to resolve it. See #34.
