### ISSUE TITLE
Option to turn tqdm progress bar off

### ISSUE THREAD

**Issue by sfujiwara** [tensorflow/datasets#310]
**Is your feature request related to a problem? Please describe.**

Progress bar by tqdm is useful when we run the code on local.
But, it a little bit bothering when we run the code on server or cloud.
So, I think an option to turn tqdm progress bar off is useful.

**Describe the solution you'd like**

This problem is discussed in tqdm GitHub issue, but it seems not to be resolved yet:
https://github.com/tqdm/tqdm/issues/619

I want a method as below:

```python
tfds.disable_progress_bar()
```

**Describe alternatives you've considered**

We can wait the update of tqdm, but we can't tell when the issue is resolved.

**Comment by sfujiwara** [comment]
I think this problem is important because it seems that tqdm can not be used (it occurs an error) on Google Cloud ML Engine as long as I investigated.

**Comment by Conchylicultor** [comment]
All `tqdm` instances used internally in `tfds` should use `tfds.utils.tqdm` so in theory, it would be possible to achieve this by replacing `tqdm` by a no-op class, when the user call `tfds.disable_progress_bar()`.

https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/utils/tqdm.py#L27

Some point to concider:
* Tqdm is sometimes used as context manager, sometimes as iterator.
* When used as context manager, tqdm return a pbar object with method called latter in the program (`pbar.total += n`, `pbar.refresh()`, ...)

**Comment by us** [comment]
I want to solve that problem. Please assign me.

**Comment by Conchylicultor** [comment]
It should be fixed with #376, which will be available in the next nightly.
