### ISSUE TITLE
[data request] <fashion_mnist>

### ISSUE THREAD

**Issue by prasadnemmikanti** [tensorflow/datasets#3103]
* Name of dataset: <fashion_mnist>
* URL of dataset: < https://github.com/zalandoresearch/fashion-mnist>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by vijayphoenix** [comment]
See catalog https://www.tensorflow.org/datasets/catalog/fashion_mnist
