### ISSUE TITLE
Community datasets not working on local env

### ISSUE THREAD

**Issue by NikhilBartwal** [tensorflow/datasets#3106]
For this year's GSOC, TFDS is going forward with community datasets. However, I had some queries regarding it as I would like to contribute to TFDS as part of this year's GSOC.

1. The [community datasets index](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/community-datasets.toml) currently contains only `huggingface` as part of registered namespaces. https://github.com/tensorflow/datasets/blob/fcd51122d639b6406648912f27ed9a8446986a84/tensorflow_datasets/community-datasets.toml#L4
However, when using `tfds.load('huggingface: any_dataset')` results in `Dataset not found`. So, are the community datasets not currently operational?

2. Also, I was thinking whether the community datasets scripts would be part of TFDS or they will be downloaded on runtime when the user loads it?

@Conchylicultor @vijayphoenix It would be great if the project could be discussed a bit more into detail. Thanks!

**Comment by Conchylicultor** [comment]
Have you tried with tfds-nightly ? You need to replace `any_dataset` by a valid dataset name

**Comment by NikhilBartwal** [comment]
@Conchylicultor I have been using a locally cloned TFDS repo up until now for contribution.
`pip install tfds-nightly` installs the nightly package but importing `tensorflow_datasets` in python, results in importing of the previous TFDS. How do I use the `tfds-nightly` package in that case?

**Comment by NikhilBartwal** [comment]
@Conchylicultor Commnity datasets are working successfully with `tfds-nightly` (that i tried with colab). However, I am not able to use `tfds-nightly` with the previously installed local repo. 
It would be great if you could help me out. Thanks!

**Comment by NikhilBartwal** [comment]
@Conchylicultor Community datasets seem to be working successfully with `tfds-nightly` on colab. However, the same does not work on local environment.
Both the TFDS versions were `4.2.0+nightly`

**Comment by Conchylicultor** [comment]
Make sure to update your tfds-nightly with `pip install --upgrade tfds-nightly`

**Comment by NikhilBartwal** [comment]
@Conchylicultor I'm currently using `tfds-nightly==4.2.0.dev202103160106` on my local machine and community datasets does not seem to work on it.
I have tried uninstalling TFDS completely and then reinstalling using ``pip install tfds-nightly` but it didn't work.
I have also tried installing TFDS from the freshly cloned repo as well.
DO you have any idea why this could be happending?

**Comment by NikhilBartwal** [comment]
@Conchylicultor I think that I have pinpointed the issue. Since the original question has been answered, I think I should open a new issue so as to avoid further confusion for others.
