### ISSUE TITLE
[data request] Stanford Question Answering Dataset 2.0

### ISSUE THREAD

**Issue by ParthS007** [tensorflow/datasets#317]
* Name of dataset: Stanford Question Answering Dataset 2.0
* URL of dataset: https://rajpurkar.github.io/SQuAD-explorer/explore/v2.0/dev/
* Short description of dataset and use case(s): Stanford Question Answering Dataset 2.0 is a reading comprehension dataset, consisting of questions posed by crowd workers on a set of Wikipedia articles, where the answer to every question is a segment of text, or span, from the corresponding reading passage, or the question might be unanswerable.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

I am working on this. @cyfra @Conchylicultor Please assign this to me.

**Comment by ParthS007** [comment]
@Conchylicultor I have made PR adding this dataset. Please review #323

**Comment by Conchylicultor** [comment]
Closing this as this dataset was been added in tfds-nightly.
