### ISSUE TITLE
[data request] <dataset name>

### ISSUE THREAD

**Issue by ppbt** [tensorflow/datasets#3171]
* Name of dataset: <CIFAR10>
* URL of dataset: <url>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by ccl-core** [comment]
Closing this issue as no dataset name was provided. Please re-open the issue and provide the relevant info (dataset name, dataset URL, etc) if still relevant.
