### ISSUE TITLE
Add `__all__` attribute to generated dataset files

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/datasets#3191]
**Is your feature request related to a problem? Please describe.**

When creating a new dataset via `tfds new` cli, `__init__.py` has the linting error. (`W0611 (unused-import)` for pylint, `F401 (imported but unused)` for flake8)

**Describe the solution you'd like**

https://github.com/tensorflow/datasets/blob/79720d25f16983d50e7aa302901d0db6bf107135/tensorflow_datasets/scripts/cli/new.py#L238-L255

The above function can be

```python
def _create_init(info: DatasetInfo) -> None:
  """Adds the `__init__.py` file."""
  file_path = info.path / '__init__.py'
  if info.in_tfds:
    # from tensorflow_datasets.image.my_dataset.my_dataset import MyDataset
    ds_import = f'{info.ds_import}.{info.name}'
  else:
    # from .my_dataset import MyDataset
    ds_import = f'{info.ds_import}{info.name}'
  # Could also import the BuilderConfig if it exists.
  content = textwrap.dedent(
      f'''\
      """{info.name} dataset."""

      from {ds_import} import {info.cls_name}

      __all__ = ["{info.cls_name}"] # Add this line
      '''
  )
  file_path.write_text(content)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Conchylicultor** [comment]
Or alternativelly:

```python
from {ds_import} import {info.cls_name}  # pylint: disable:unused-import
```

But first make sure you're using a recent version of pylint. I'm pretty sure unused imports inside __init__ files are valid. So this is a pylint bug in the old versions

**Comment by jeongukjae** [comment]
@Conchylicultor Oh, I checked and tested the functionality of the `__all__` attribute, and I think I misunderstood it. I will close this issue. Thank you :)
