### ISSUE TITLE
TFDS link broken for Cars196

### ISSUE THREAD

**Issue by calvuser** [tensorflow/datasets#3195]
I am trying to download Cars196 using tflite_model_maker

Code line:
train_data, validation_data, test_data = ImageClassifierDataLoader.from_tfds('cars196')

Error:
DownloadError: Failed to get url https://imagenet.stanford.edu/internal/car196/cars_test.tgz. HTTP code: 404.

It was working previously. Any ways to resolve broken link?

**Comment by NikhilBartwal** [comment]
Hey @calvuser, thank you for pointing this out!

The training and test data seems to have been shifted to another URL. I will be sending a fix soon, which you can then use after it gets merged.

**Comment by calvuser** [comment]
Thanks Nikhil. When will it be fix?

**Comment by NikhilBartwal** [comment]
Hey @calvuser, although I've sent the PR for the fix, but it still needs to be merged. 
When it is merged, you can then use the latest `tfds-nightly` in your project to use the dataset.

**Comment by calvuser** [comment]
@NikhilBartwal Oh I got it. Thank you!
