### ISSUE TITLE
Failed to Download One Billion Word Dataset

### ISSUE THREAD

**Issue by daskol** [tensorflow/datasets#3198]
Failed to fetch dataset.
```python
>>> tsds.load('lm1b')
....
DownloadError: Failed to get url http://www.statmt.org/lm-benchmark/1-billion-word-language-modeling-benchmark-r13output.tar.gz. HTTP code: 503.
```
It seems like the dataset file is unavailiable.
```bash
$ curl -I http://www.statmt.org/lm-benchmark/1-billion-word-language-modeling-benchmark-r13output.tar.gz
HTTP/1.1 503 Service Unavailable
Date: Sun, 02 May 2021 22:14:42 GMT
Server: Apache/2.4.18 (Ubuntu) SVN/1.9.3 OpenSSL/1.0.2g mod_wsgi/4.7.1 Python/3.7 mod_perl/2.0.9 Perl/v5.22.1
Connection: close
Content-Type: text/html; charset=iso-8859-1
```

**Comment by NikhilBartwal** [comment]
Hey @daskol, have you tried it again recently as the dataset seems to be successfully downloaded and generated on the latest version of TFDS and `tfds-nightly` both. It might be that the url was temporarily down.
Please let us know if the problem persists. Thanks!

**Comment by daskol** [comment]
@NikhilBartwal URL is available now. It was inaccessible for long enough time in order to report the issue. By the way, I wonder why `tensorflow-datasets` does not cache datasets in a cloud storage like GCS.

**Comment by Conchylicultor** [comment]
> @NikhilBartwal URL is available now. It was inaccessible for long enough time in order to report the issue. By the way, I wonder why `tensorflow-datasets` does not cache datasets in a cloud storage like GCS.

We would love mirror datasets to avoid depending on third_party website. Unfortunately we are not allowed to redistribute most datasets due to legal issues :'(

**Comment by daskol** [comment]
@Conchylicultor Oh, I see. This is disappointing.

Should I report issues related to unavailability of a third-party dataset next time?

**Comment by NikhilBartwal** [comment]
@daskol Yes, it would be great if you could. Many times the official dataset is shifted to a different URL or the dataset structure changed. In these cases we can update the dataset generation script accordingly.

**Comment by daskol** [comment]
Thanks!

**Comment by tinyxuyan** [comment]
Recently, the lm1b url is inaccessible again. When I run the code below:
`(ds, ds_info) = tfds.load('lm1b', data_dir='/tensorflow_datasest')`, the output error is 
`DownloadError: Failed to get url https://www.statmt.org/lm-benchmark/1-billion-word-language-modeling-benchmark-r13output.tar.gz. HTTP code: 404.`
