### ISSUE TITLE
Dataset Template Generator Script

### ISSUE THREAD

**Issue by us** [tensorflow/datasets#320]
**Is your feature request related to a problem? Please describe.**
There are some files and folders to create for each new dataset. It always takes time. 
On the other hand anyone can sometimes miss out something from the documentation and forgot some things.

**Describe the solution you'd like**
A utility script that creates common files, functions and their TODO's for each new dataset.

Sample usage:
`python -m tensorflow_datasets.scripts.generate_dataset_template --name dataset_name --type dataset_type`

You can check my pr #321 about details.

**Comment by Conchylicultor** [comment]
Closing this as some support for this has been added for this in https://github.com/tensorflow/datasets/pull/321 (thanks again for setting this up)

The script can be improved over time depending on the feedbacks
