### ISSUE TITLE
[data request] <cars196>

### ISSUE THREAD

**Issue by VikramAchuthan** [tensorflow/datasets#3203]
* Name of dataset: <cars196>
* URL of dataset: <https://ai.stanford.edu/~jkrause/cars/car_dataset.html>
* License of dataset: <http://image-net.org/download-faq>

This dataset is already a part of the collection, but I am getting a 404 error when I run this code, saying that the program is unable to get the dataset url :
* ds_train_all,ds_info = tfds.load('cars196', split='train', shuffle_files=True,with_info=True)
* Error I get:
* DownloadError: Failed to get url https://image-net.org/internal/car196/cars_test.tgz. HTTP code: 404.

I would appreciate if this could be addressed. Thank you!!

**Comment by NikhilBartwal** [comment]
Hey @VikramAchuthan. This was also mentioned in #3195 and solved with PR #3197. You can use the updated `tfds-nightly` once the PR is merged. Thanks!
