### ISSUE TITLE
Cannot import ` tensorflow_datasets.folder_dataset`

### ISSUE THREAD

**Issue by thisiscam** [tensorflow/datasets#3210]
/!\ IF YOU WANT PEOPLE TO HELP YOU, PLEASE GIVE AS MUCH DETAIL AS POSSIBLE, INCLUDING THE FULL STACKTRACE AND CODE SNIPPET

**Short description**
I get:
```shell 
>>> import tensorflow_datasets.folder_dataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow_datasets.folder_dataset'
```
when I try to import `tensorflow_datasets.folder_dataset`.

**Environment information**
* Operating System: macOS
* Python version: 2.8.8
* `tensorflow-datasets`/`tfds-nightly` version: 4.3.0
* `tensorflow`/`tf-nightly` version: 2.4.1

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
Yes

```
import tensorflow_datasets.folder_dataset
```

**Expected behavior**
I expect this to work:
```python
import tensorflow_datasets.folder_dataset as tfds_fd
print(tfds_fd.TranslateFolder)
```

**Comment by Conchylicultor** [comment]
Does the following works ?
```python
from tensorflow_datasets  import folder_dataset
```
There is no tensorflow_datasets/folder_dataset/ module. It's get added in the `__init__.py`.
More generally our API is intended to by used through
```python
import tensorflow_datasets as tfds

tfds.folder_dataset
```
Direct imports are discouraged.

**Comment by thisiscam** [comment]
```python
import tensorflow_datasets as tfds

tfds.folder_dataset
```
That works for me. Thanks!
