### ISSUE TITLE
TFDS imagenet_resized link broken

### ISSUE THREAD

**Issue by sun2000nian** [tensorflow/datasets#3257]
**Short description**
tfds returned 404 when trying to load dataset'imagenet_resized'

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
* yes

**Reproduction instructions**
```
---------------------------------------------------------------------------
DownloadError                             Traceback (most recent call last)
<ipython-input-37-157431618bfb> in <module>()
----> 1 imagenet2012_train = tfds.load('imagenet_resized/64x64')

21 frames
/usr/local/lib/python3.7/dist-packages/tensorflow_datasets/core/download/downloader.py in _assert_status(response)
    257   if response.status_code != 200:
    258     raise DownloadError('Failed to get url {}. HTTP code: {}.'.format(
--> 259         response.url, response.status_code))

DownloadError: Failed to get url https://image-net.org/image/downsample/Imagenet64_train_part1_npz.zip. HTTP code: 404.
```

**Expected behavior**
line 50 of file 'datasets/tensorflow_datasets/image_classification/imagenet_resized.py' is
```
_URL_PREFIX = 'http://www.image-net.org/image/downsample/'
```
which should be
```
_URL_PREFIX = 'http://www.image-net.org/data/downsample/'
```
I changed the url and made it load normally

**Comment by NikhilBartwal** [comment]
Thank you for pointing this out @sun2000nian! I've sent the required PR, changing the URL and re-generating the checksums.

**Comment by eliaspo** [comment]
update tensorflow-datasets version to 4.5.2 with this code:

pip install tensorflow-datasets==4.5.2
