### ISSUE TITLE
[data request] Fruits-360

### ISSUE THREAD

**Issue by BrEr** [tensorflow/datasets#326]
* Name of dataset: Fruits-360
* URL of dataset: https://github.com/Horea94/Fruit-Images-Dataset
* License of dataset: MIT
* Short description of dataset and use case(s): A high-quality, dataset of images containing fruits.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by ChanchalKumarMaji** [comment]
@BrEr , This dataset has already been added here #174. Please close the issue.

**Comment by BrEr** [comment]
Sorry, wasn't listed here:

https://github.com/tensorflow/datasets/blob/master/docs/datasets.md
