### ISSUE TITLE
[data request] Natural Questions

### ISSUE THREAD

**Issue by rsepassi** [tensorflow/datasets#33]
* Name of dataset: Natural Questions
* URL of dataset: https://ai.google.com/research/NaturalQuestions/dataset
* License of dataset: Creative Commons Share-Alike 3.0
* Short description of dataset and use case(s):
To help spur development in open-domain question answering, we have created the Natural Questions (NQ) corpus, along with a challenge website based on this data. The NQ corpus contains questions from real users, and it requires QA systems to read and comprehend an entire Wikipedia article that may or may not contain the answer to the question. The inclusion of real user questions, and the requirement that solutions should read an entire page to find the answer, cause NQ to be a more realistic and challenging task than prior QA datasets.

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by tabshaikh** [comment]
@rsepassi if anyone is not working on this, could I add this dataset ?

**Comment by Naman-Bhalla** [comment]
Hello @rsepassi  I would like to work on this issue. Thanks

**Comment by tabshaikh** [comment]
@Naman-Bhalla I think there is a pr which will close this issue

**Comment by nahidalam** [comment]
@tabshaikh which PR you are referring to.

**Comment by rsepassi** [comment]
PR #39.
