### ISSUE TITLE
Implementing highly configurable datasets

### ISSUE THREAD

**Issue by jackd** [tensorflow/datasets#332]
A lot of datasets provide some base data source which undergoes considerable pre-processing before use in machine learning algorithms. For example, I work in 3D reconstruction from images, and a lot of research is done based on rendering CAD models and trying to predict voxel grids or point clouds. In this case there are a number of ways of rendering (lighting, camera location etc) and producing labels (e.g. different voxel resolutions, point cloud densitites etc).

While some of these can be handled with builder kwargs, most have to be implemented using separate configs. Trying to support every possible config is obviously infeasible, and when it comes to combinations (e.g. having multiple voxel resolution label datasets matched against the same set of renderings) disk space usage can become significant.

# What I've tried so far
Any subclass of `DatasetBuilder` exposes a mutable `BUILDER_CONFIGS` list. Highly-configurable preprocessing can be implemented in a builder-specific config class and appended by users separate to tfds as I've done [here](https://github.com/jackd/datasets/blob/modelnet/tensorflow_datasets/volume/modelnet/modelnet.py#L55). This just seems hacky.

Alternatively, one could provide just the base implementation (i.e. just CAD models in the above example) and allow users to use `tf.data.Dataset.map` (along with possible `cache` etc.) but that
(a) means the base data source must be saved to disk in tensorflow-compatible format (this can be tricky with CAD models); and 
(b) means resulting datasets miss out on all the additional goodies offered by `DatasetBuilder`s - info, statistics etc.

# Questions:
1. Is there a standard way the tfds team would like highly configurable datasets to be implemented? Minimal base implementation only plus extensible configs? Plus a few common configs?
2. Is there any mechanism by which `DatasetBuilder`s can be built/loaded such that the resulting datasets can be used with `tf.data.Dataset.zip`? As I understand it the current shuffling behaviour during prorcessing precludes this use case.

**Comment by rsepassi** [comment]
The `BuilderConfig` for the dataset can expose all the needed options. In the `BUILDER_CONFIGS` list, only a few common/important ones should be listed. Users that want more fine-grained configuration can explicitly instantiate the `BuilderConfig` with the options they want and pass that to the `DatasetBuilder`.

**Comment by jackd** [comment]
Makes a lot of sense. This precludes it's use from `tfds.load` and other convenience wrappers, but I don't think that's a big deal (I suppose users can still append to `BUILDER_CONFIGS` list if they desperately want these conveniences).
