### ISSUE TITLE
Typo in readme for glue_stsb

### ISSUE THREAD

**Issue by jasonwei20** [tensorflow/datasets#3341]
Small typo. For [glue_stsb](https://www.tensorflow.org/datasets/catalog/glue#gluestsb), it says that the textual similarity is measured from 1-5. It is actually 0-5, if you look at the values (and it also says so in the [paper](https://aclanthology.org/S17-2001.pdf)).

**Comment by aryyan11** [comment]
@jasonwei20 I would like to fix this. Could you please tell me how to proceed ? I'm doing this for the first time

**Comment by Yash621** [comment]
@jasonwei20 I really want to do this ? could you please assign this issue to me ?
I would be really greatful.
