### ISSUE TITLE
Dedicated folder for Sequential data

### ISSUE THREAD

**Issue by mr-ubik** [tensorflow/datasets#339]
I thought it could be useful to have dedicated time_series/sequence folders for all Sequential Datasets that are neither audio nor text/translation.

i.e., somewhere to place stuff like #337

**Comment by ChanchalKumarMaji** [comment]
@mr-ubik Thanks for your suggestion. I think the team members will add more such folders as required by the datasets. There are many more datasets to add.

**Comment by Conchylicultor** [comment]
If you think a dataset do not goes into any current category, you can add create a new folder but we should first make sure that it would be for more than just one dataset.
Quickdraw exists also as png so I think it make sense to keep all quickdraw versions under `image/`.

I'm closing this for now as we shouldn't create an empty folder while we don't have datasets in it. But new folders can be created when adding new datasets
