### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by reza-ghazi** [tensorflow/datasets#3422]
Hello,
On page: [TensorFlow Datasets](https://www.tensorflow.org/datasets/overview), the following line of code under the title [```As batched tf.Tensor (batch_size=-1)```](https://www.tensorflow.org/datasets/overview#as_batched_tftensor_batch_size-1) will generate a **Deprecation Warning**.
```python
image, label = tfds.as_numpy(tfds.load(
    'mnist',
    split='test',
    batch_size=-1,
    as_supervised=True,
))

print(type(image), image.shape)
```

The warning message is:
```
WARNING:tensorflow:From e:\python39\lib\site-packages\tensorflow_datasets\core\dataset_builder.py:622: get_single_element (from tensorflow.python.data.experimental.ops.get_single_element) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.
```
Thank you,

**Comment by Conchylicultor** [comment]
Thanks for reporting. Sending a fix now
