### ISSUE TITLE
Key Error for download_and_prepare

### ISSUE THREAD

**Issue by nicolasblumenroehr** [tensorflow/datasets#3442]
**What I need help with / What I was wondering**
I am trying to load a custom data set, which actually worked out yesterday, but now I receive a KeyError, when I am calling the download_and_prepare method.

**What I've tried so far**
I called the instance for my custom dataset class to invoke the datasetBuilder method, which I have slightly modified to pass additional metadata information to the _info() function. Everything works out and I was actually able to run the download_and_prepare  method yesterday and transfer my dataset into the as_dataset() function. But now I get the following error, when I execute the download_and_prepare function: 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-73fa175ef758> in <module>
----> 1 myDataset.download_and_prepare()

/opt/anaconda3/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py in download_and_prepare(self, download_dir, download_config)
    437           # Old version of TF are not os.PathLike compatible
    438           with tf_compat.mock_gfile_pathlike():
--> 439             self._download_and_prepare(
    440                 dl_manager=dl_manager,
    441                 download_config=download_config,

/opt/anaconda3/lib/python3.8/site-packages/tensorflow_datasets/core/dataset_builder.py in _download_and_prepare(self, dl_manager, download_config)
   1132 
   1133       # Start generating data for all splits
-> 1134       path_suffix = file_adapters.ADAPTER_FOR_FORMAT[
   1135           self.info.file_format].FILE_SUFFIX
   1136 

KeyError: None

Here my custom dataset class

    class Custom_dataset(tfds.core.GeneratorBasedBuilder):
  
        VERSION = tfds.core.Version('1.0.0')
        
        RELEASE_NOTES = {
        '1.0.0': 'Initial release.',
        }
        def __init__(
            self,
            *,
            data_dir: Optional[utils.PathLike] = None,
            config: Union[None, str, tfds.core.BuilderConfig] = None,
            version: Union[None, str, utils.Version] = None,
            for_Info: {"Metadata": None, "Download Directory": None, "Extraction Directory": None, "URL_Path": None}):
            self.metadata = for_Info["Metadata"]
            self.download_directory = for_Info["Download Directory"]
            self.extraction_directory = for_Info["Extraction Directory"]
            self.url_path = for_Info["URL_Path"]
                                         
            if data_dir:
                data_dir = os.fspath(data_dir)  # Pathlib -> str
    
            self._original_state = dict(
                data_dir=data_dir, config=config, version=version)
            self._builder_config = self._create_builder_config(config)
            self._version = self._pick_version(version)
            self._data_dir_root, self._data_dir = self._build_data_dir(data_dir)
            if tf.io.gfile.exists(self._data_dir):
                self.info.read_from_directory(self._data_dir)
            else:  
                self.info.initialize_from_bucket()
             
        def _info(self) -> tfds.core.DatasetInfo:
            return tfds.core.DatasetInfo(
            builder = self,
                description = self.metadata["Data Description"],
                features = tfds.features.FeaturesDict({
                    'image': tfds.features.Image(shape = (self.metadata["Height"], self.metadata["Width"], self.metadata["Channel"])),
                    'label': tfds.features.ClassLabel(num_classes = self.metadata["Number Labels"]),
                }),
                homepage = self.metadata["Image Location"],
                license = self.metadata["License"],
                disable_shuffling=True,
                citation = self.metadata["Citation"]
            )
        
        def _split_generators(self, dl_manager=tfds.download.DownloadManager):
            extracted_path=dl_manager.download_and_extract(url_or_urls=self.url_path)
            return [
                    tfds.core.SplitGenerator(
                        name=tfds.Split.TRAIN,
                        gen_kwargs=dict(path=extracted_path,)),
                ]
        
        def _generate_examples(self, path):
            
            """Generator of examples for each split."""
            for img_path in glob.glob(path+'*.jpg'):
                # Yields (key, example)
                #one = random.randint(1, 1000)
                #two = random.randint(1, 1000)
                yield img_path, {
                    'image': img_path,
                    'label': 1
                    
              }

**It would be nice if...**
I have no idea what this refers to, as the download_and_extract function within the _generate_splits function in my custom dataset class also works out and the data is downloaded and executed. Do you have an idea, where the catch is?

**Environment information**
(if applicable)
* Operating System: macOS Big Sur 11.4
* Python version: 3.8.8
* `tensorflow-datasets`/`tfds-nightly` version: 4.4.0+nightly
* `tensorflow  version: 2.5.0

**Comment by Conchylicultor** [comment]
It seems that your dataset overwrite `__init__` without calling `super().__init__`. The base class `__init__` perform validation and transformations, so make sure to call `super()`. This should solve your issue

**Comment by Conchylicultor** [comment]
I'm not sure what `Dataset2` refer too. It doesn't seem to match your code. The following would works:

```python
builder = tfds.builder('custom_dataset')
builder.info.metadata
```

**Comment by ccl-core** [comment]
Hello @nicolasblumenroehr , is this still an issue?
If not, could you please close the issue?
