### ISSUE TITLE
AI2_ARC Dataset appears to have moved

### ISSUE THREAD

**Issue by haydenjeune** [tensorflow/datasets#3452]
**Short description**
AI2 Dataset appears to have moved.

**Environment information**
* Operating System: macOS 11.5.2
* Python version: 3.9.2
* `tfds-nightly` version: tfds-nightly-4.4.0.dev202108260107
* `tensorflow` version: tensorflow-2.6.0

**Reproduction instructions**

```
tfds build ai2_arc
```
shows a stack trace ending in

```
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://ai2-datasets.s3-us-west-2.amazonaws.com/arc/ARC-V1-Feb2018.zip. HTTP code: 404.
```

**Expected behavior**
The dataset successfully downloads

**Additional context**
The current dataset url is 
https://ai2-datasets.s3-us-west-2.amazonaws.com/arc/ARC-V1-Feb2018.zip
I have verified with a web browser that this location does not exist

The link at https://allenai.org/data/arc suggests that the dataset url is now
https://ai2-public-datasets.s3-us-west-2.amazonaws.com/arc/ARC-V1-Feb2018.zip

I'm happy to raise a PR for this

**Comment by tomvdw** [comment]
Fix seems to be working.
