### ISSUE TITLE
[data request] Smartwatch Gestures Dataset

### ISSUE THREAD

**Issue by ianzur** [tensorflow/datasets#3479]
* Name of dataset: SmartwatchGesturesDataset
* URL of dataset: https://tev.fbk.eu/resources/smartwatch
* License of dataset: research or academic purposes only
* Short description of dataset and use case(s): gesture recognition from accelerometer data

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

- [X] class definition
- [x] test
- [x] checksum

**Comment by ianzur** [comment]
Where should this dataset be located in the directory structure?

**Comment by ccl-core** [comment]
Thank you @ianzur for your contribution!
Your dataset has successfully been merged and will be available soon on tfds.

Have a great day!
