### ISSUE TITLE
Missing labels in test split

### ISSUE THREAD

**Issue by SoumyadeepJana** [tensorflow/datasets#349]
**What I need help with / What I was wondering**
There are quite a number of datasets that have been created as a part of some competition or challenge and those folks don't provide the labels to test set as the model the user develops needs to be evaluated by some evaluation server.

**What I've tried so far**
For all those types of datasets, we can assign a general string such as "test" as label

**It would be nice if...**
Is there any other elegant solution to tackle this?

**Comment by SoumyadeepJana** [comment]
@Conchylicultor @rsepassi Your views on this?

**Comment by rsepassi** [comment]
You could add a "missing" class label and all the test images would use that as the class label.

**Comment by SoumyadeepJana** [comment]
@rsepassi Okay :)

**Comment by Conchylicultor** [comment]
`ClassLabel` already allow for unknown label if you pass `-1`, so no need to add a new label.

Just:
```
yield {
    'image': img_path,
    'label': -1,
}
```

See tensorflow_datasets/core/features/class_label_feature.py line 127
