### ISSUE TITLE
Split dataset between workers

### ISSUE THREAD

**Issue by samsamoa** [tensorflow/datasets#35]
For large datasets being processed on many workers, it is useful to be able to read separate shards of the dataset on each worker.  Is this possible with the `tfds` API?

I experimented a bit with the `Split.subsplit` functionality, but it looks like it works by reading every dataset element and masking out selected elements (see [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/dataset_utils.py#L59)).  This means that every worker ends up reading the whole dataset, which can be costly.  In particular, this makes it impossible to use `tf.data.Dataset.cache`.

**Comment by danchyy** [comment]
Is there any update on this issue? Will there be some sort of multiprocess support in the future? 

If not, will there be some guides on how to utilize multiprocessing in the best way using this package?

**Comment by Conchylicultor** [comment]
The current plan is to let the user select the shards they want with: https://github.com/tensorflow/datasets/issues/121

Not sure when I'll have time to implement this in a close future though.

**Comment by Conchylicultor** [comment]
For update, the Split API has been updated to be more performant and only read required shards, rather than the whole dataset.
This should significantly increase performances.

For automatic multiprocessing, I'm closing this issue in favor of https://github.com/tensorflow/datasets/issues/1426
