### ISSUE TITLE
Is there a roadmap or release schedule?

### ISSUE THREAD

**Issue by BrEr** [tensorflow/datasets#350]
I am wondering when new releases are expected? Is there a release schedule or roadmap determined?

**Comment by SoumyadeepJana** [comment]
@BrEr I think all the datasets that will be added during GSoc will be organized and listed after GSoc

**Comment by BrEr** [comment]
If I go to https://www.tensorflow.org/datasets they show version 1.0.2 is used, while here on github the latest release is 1.0.1, what's going on?

**Comment by Conchylicultor** [comment]
Unfortunately, we don't really have a fixed release schedule. We publish updates gradually once they are ready.

See: https://github.com/tensorflow/datasets/releases for the history of release.
