### ISSUE TITLE
Dataset "definite_pronoun_resolution" cannot be loaded

### ISSUE THREAD

**Issue by YangDong2002** [tensorflow/datasets#3508]
**Short description**

The link for the dataset "definite_pronoun_resolution" does not work now.(http://www.hlt.utdallas.edu/~vince/data/emnlp12/train.c.txt). Seems like we also need to contact the dataset authors.

**Environment information**
* Operating System: Ubuntu 18.04.5 LTS (in Colab)
* Python version: 3.7
* `tfds-nightly` version: tfds-nightly-4.4.0.dev202109290107
* `tensorflow` version: 2.6.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?

Yes

**Reproduction instructions**

```python
import tensorflow_datasets as tfds
tfds.load("definite_pronoun_resolution")
```

**Link to logs**

```
ConnectionError                           Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='www.hlt.utdallas.edu', port=80): Max retries exceeded with url: /~vince/data/emnlp12/test.c.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5cfe25d550>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Expected behavior**

The dataset successfully downloads

**Comment by ccl-core** [comment]
Thanks for reporting this. Do you have a new link where this data can be downloaded? We would be happy to update the code with the new link.

**Comment by YangDong2002** [comment]
It turns out Huggingface Datasets cached this dataset on their server (https://github.com/huggingface/datasets/issues/3264). Simply changing the link in `tensorflow_datasets/text/definite_pronoun_resolution.py` as follows works for me.

`_DATA_URL_PATTERN = 'https://s3.amazonaws.com/datasets.huggingface.co/definite_pronoun_resolution/{}.c.txt'
`
