### ISSUE TITLE
Contribution Code Style

### ISSUE THREAD

**Issue by mr-ubik** [tensorflow/datasets#353]
Is there a file formally specifying the code style to use when contributing?

I guess:

- 2 Spaces Indent
- Format with Yapf

Is there anything else?

**Comment by cyfra** [comment]
TL;DR: Run pylint.

The full code style is here:
https://github.com/google/styleguide/blob/gh-pages/pyguide.md

**Comment by mr-ubik** [comment]
Mmmh, the guide says 4 space indentation but I am often seeing 2 spaces which shall we use? Is it indifferent?

**Comment by us** [comment]
@mr-ubik You should 2 spaces. Please check [tf code style guide](https://www.tensorflow.org/community/contribute/code_style)

**Comment by mr-ubik** [comment]
I think that linking that to the Contributing section would help newcomers.

**Comment by mr-ubik** [comment]
Thanks to @us I can close this :grinning:
