### ISSUE TITLE
IMDB

### ISSUE THREAD

**Issue by xingzhe1234** [tensorflow/datasets#3536]
* Name of dataset: <name>
* URL of dataset: <url>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by ccl-core** [comment]
@xingzhe1234 , note that the imdb_reviews dataset already exists in TFDS: https://www.tensorflow.org/datasets/catalog/imdb_reviews

If this solves your request, please close this issue.

If the dataset you are referring to is different than the imdb_reviews in the TFDS catalog, please add the dataset specifications above (name, URL, license, ...)
