### ISSUE TITLE
"beans" dataset download error

### ISSUE THREAD

**Issue by autapomorphy** [tensorflow/datasets#3550]
**Short description**
Cannot download 'beans' dataset.

**Environment information**
google colab
* Operating System: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
* Python version: 3.7.12
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets:4.0.1
* `tensorflow`/`tf-nightly` version: tensorflow: 2.6.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
yes

**Reproduction instructions**

```python
import tensorflow as tf
import tensorflow_datasets as tfds

ds = tfds.load('beans', split='train', shuffle_files=True)
```

**Expected behavior**

DownloadError: Failed to get url https://storage.googleapis.com/ibeans/train.zip. HTTP code: 403.

**Comment by heechul** [comment]
Cannot download 'beans' dataset. 
---
[/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/download/downloader.py](https://localhost:8080/#) in _assert_status(response)
    327   """Ensure the URL response is 200."""
    328   if response.status_code != 200:
--> 329     raise DownloadError(
    330         'Failed to get url {}. HTTP code: {}.'.format(
    331             response.url, response.status_code

DownloadError: Failed to get url https://storage.googleapis.com/ibeans/train.zip. HTTP code: 403.
---

Clicking the link to the train.zip file on the browser returns the following XML message. 
---
<Error>
<Code>UserProjectAccountProblem</Code>
<Message>The project to be billed is associated with a delinquent billing account.</Message>
<Details>The billing account for the owning project is disabled in state delinquent</Details>
</Error>
---

Solution?
