### ISSUE TITLE
The dependency on future is useless

### ISSUE THREAD

**Issue by IRDonch** [tensorflow/datasets#3586]
**Short description**
The TFDS distribution has a dependency on the [future](https://pypi.org/project/future/) distribution. However, as far as I can see, none of the functionality of future is actually used in TFDS. There are no imports of either the `future` or `past` packages anywhere (I wasn't even able to find any in the history), and removing `future` from the Python environment does not break TFDS.

**Environment information**
* Operating System: Any
* Python version: Any
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets 4.4.0
* `tensorflow`/`tf-nightly` version: Any

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? Yes

**Reproduction instructions**
N/A

**Link to logs**
N/A

**Expected behavior**
TFDS should not have a dependency on future if it isn't used.

**Additional context**
N/A

**Comment by Conchylicultor** [comment]
Thanks for reporting, sending a fix now
