### ISSUE TITLE
tfds.load(): <split> with 'all' generates AssertionError

### ISSUE THREAD

**Issue by ixig** [tensorflow/datasets#3640]
/!\ PLEASE INCLUDE THE FULL STACKTRACE AND CODE SNIPPET

**Short description**
The documentation (splits.md) states that 'all' can be used to refer to the union of all splits. But doing so gives an error: "Unknown split "all". 

**Environment information**
* Operating System: Colab
* Python version: 3.7.12
* `tensorflow-datasets`/`tfds-nightly` version: 4.4.0
* `tensorflow`/`tf-nightly` version: 2.7.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ? YES

**Reproduction instructions**

```python
splits, _ = tfds.load('rock_paper_scissors', with_info=True, as_supervised=True,
                         split = ['all'])
```

If you share a colab, make sure to update the permissions to share it.

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
Expect no error, but got:
ValueError: Unknown split "all". Should be one of ['train', 'test'].

**Additional context**

**Comment by Conchylicultor** [comment]
Could you try with `tfds-nightly` ? I'm not sure we released this feature yet in the last version

**Comment by ixig** [comment]
Ok, just checked with tf-nightly and tfds-nightly builds -- it's working. Thanks!
[](https://colab.research.google.com/drive/128CFoNVlxzRARNidxdFytTilFQJwh-sC?usp=sharing)
