### ISSUE TITLE
[data request] assin2

### ISSUE THREAD

**Issue by marcospiau** [tensorflow/datasets#3641]
* Name of dataset: assin2
* URL of dataset: https://sites.google.com/view/assin2/english
* License of dataset: Not specified
* Short description of dataset and use case(s): ASSIN2 is a Portuguese dataset with two tasks: Semantic Textual Similarity and Textual Entailment. This dataset is used as benchmark in works in Portuguese language. It is also already in [Hugging Face Hub](https://huggingface.co/datasets/assin2). 

I'm already working o this dataset and would like to have this issue assigned to me.

Thanks!

**Comment by ccl-core** [comment]
Thank you @marcospiau for opening this issue! As requested, we are assigned this to you. Feel free to send a PR for review!
