### ISSUE TITLE
More love for Time Series/Sequences

### ISSUE THREAD

**Issue by mr-ubik** [tensorflow/datasets#365]
Was not sure whether to post it as help or feature request.

It would help (and speed up development) if we could have some examples, even dummy ones of how to properly code Sequential datasets.

Example: let's say that I am importing a financial dataset, how should data be encoded? Should I use a FeatureDict or a SequenceDict?

cc: @galeone

**Comment by SoumyadeepJana** [comment]
> Was not sure whether to post it as help or feature request.
> 
> It would help (and speed up development) if we could have some examples, even dummy ones of how to properly code Sequential datasets.
> 
> Example: let's say that I am importing a financial dataset, how should data be encoded? Should I use a FeatureDict or a SequenceDict?
> 
> cc: @galeone

SequenceDict correspond to sequence of tfds.features.FeatureDict. At generation time, a list for each of the sequence element is given. The output of tf.data.Dataset will batch all the elements of the sequence together.
SequenceDict is more of a collection of FeatureDict
Coming to your example,it is more of how your dataset is organized,that it falls in which category

**Comment by ChanchalKumarMaji** [comment]
@mr-ubik What do u want ? Can u please elaborate about the structure of your dataset. Is it a tabular dataset ?

**Comment by ftakelait** [comment]
@SoumyadeepJana I want to know if this is an open problem that can be an idea for GSoC proposal or not?

**Comment by Conchylicultor** [comment]
For update `tfds.features.Sequence()` accept any arbitrary nested feature (including other `tfds.features.Sequence`).
Ex: You can have a nested sequence of int with `tfds.features.Sequence(tfds.features.Sequence(tf.int32))`. You can also use `tfds.features.Tensor(shape=(None,), dtype=tf.int32)` for sequences with a single time dimension and which don't match other more explicit features (Image, ClassLabel,...).

**Comment by PanderMusubi** [comment]
Perhaps have a look at https://github.com/MArpogaus/tensorflow_time_series_dataset
