### ISSUE TITLE
OverflowError when importing tensorflow-datasets version 4.5.0

### ISSUE THREAD

**Issue by rendicahya** [tensorflow/datasets#3709]
```
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
Input In [5], in <module>
----> 1 import tensorflow_datasets as tfds

File D:\JupyterLabNotebooks\tensorflow-course-udacity\venv\lib\site-packages\tensorflow_datasets\__init__.py:65, in <module>
     63 from tensorflow_datasets import translate
     64 from tensorflow_datasets import video
---> 65 from tensorflow_datasets import vision_language
     68 # Public API to create and generate a dataset
     69 from tensorflow_datasets.public_api import *  # pylint: disable=wildcard-import

File D:\JupyterLabNotebooks\tensorflow-course-udacity\venv\lib\site-packages\tensorflow_datasets\vision_language\__init__.py:21, in <module>
     19 from tensorflow_datasets.vision_language.grounded_scan import GroundedScan
     20 from tensorflow_datasets.vision_language.refcoco import RefCoco
---> 21 from tensorflow_datasets.vision_language.wit import Wit
     22 from tensorflow_datasets.vision_language.wit_kaggle import WitKaggle

File D:\JupyterLabNotebooks\tensorflow-course-udacity\venv\lib\site-packages\tensorflow_datasets\vision_language\wit\__init__.py:18, in <module>
      1 # coding=utf-8
      2 # Copyright 2022 The TensorFlow Datasets Authors.
      3 #
   (...)
     13 # See the License for the specific language governing permissions and
     14 # limitations under the License.
     16 """wit dataset."""
---> 18 from tensorflow_datasets.vision_language.wit.wit import Wit

File D:\JupyterLabNotebooks\tensorflow-course-udacity\venv\lib\site-packages\tensorflow_datasets\vision_language\wit\wit.py:25, in <module>
     22 import tensorflow as tf
     23 import tensorflow_datasets.public_api as tfds
---> 25 csv.field_size_limit(sys.maxsize)
     27 _DESCRIPTION = """
     28 Wikipedia-based Image Text (WIT) Dataset is a large multimodal multilingual
     29 dataset. WIT is composed of a curated set of 37.6 million entity rich image-text
   (...)
     32 learning models.
     33 """
     35 _CITATION = """
     36 @article{srinivasan2021wit,
     37   title={WIT: Wikipedia-based Image Text Dataset for Multimodal Multilingual Machine Learning},
   (...)
     41 }
     42 """

OverflowError: Python int too large to convert to C long
```

**Short description**
OverflowError occurs when importing tensorflow-datasets 4.5.0. Can be easily fixed by downgrading to 4.4.0.

**Environment information**
* Operating System: Windows
* Python version: 3.9.10
* `tensorflow-datasets`/`tfds-nightly` version: 4.5.0
* `tensorflow`/`tf-nightly` version: 2.7.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?

**Reproduction instructions**

```python
import tensorflow_datasets as tfds
```

**Comment by dacalin** [comment]
I have the same error in windows. Installing master didn't solve the problem. 

---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
Input In [1], in <module>
      1 import tensorflow as tf
----> 3 import tensorflow_datasets as tfds

File ~\AppData\Roaming\Python\Python39\site-packages\tensorflow_datasets\__init__.py:65, in <module>
     63 from tensorflow_datasets import translate
     64 from tensorflow_datasets import video
---> 65 from tensorflow_datasets import vision_language
     68 # Public API to create and generate a dataset
     69 from tensorflow_datasets.public_api import *  # pylint: disable=wildcard-import

File ~\AppData\Roaming\Python\Python39\site-packages\tensorflow_datasets\vision_language\__init__.py:21, in <module>
     19 from tensorflow_datasets.vision_language.grounded_scan import GroundedScan
     20 from tensorflow_datasets.vision_language.refcoco import RefCoco
---> 21 from tensorflow_datasets.vision_language.wit import Wit
     22 from tensorflow_datasets.vision_language.wit_kaggle import WitKaggle

File ~\AppData\Roaming\Python\Python39\site-packages\tensorflow_datasets\vision_language\wit\__init__.py:18, in <module>
      1 # coding=utf-8
      2 # Copyright 2022 The TensorFlow Datasets Authors.
      3 #
   (...)
     13 # See the License for the specific language governing permissions and
     14 # limitations under the License.
     16 """wit dataset."""
---> 18 from tensorflow_datasets.vision_language.wit.wit import Wit

File ~\AppData\Roaming\Python\Python39\site-packages\tensorflow_datasets\vision_language\wit\wit.py:25, in <module>
     22 import tensorflow_datasets.public_api as tfds
     24 # Limit to 100 MB. Value must be smaller than the C long maximum value.
---> 25 csv.field_size_limit(100 * 1024**3)
     27 _DESCRIPTION = """
     28 Wikipedia-based Image Text (WIT) Dataset is a large multimodal multilingual
     29 dataset. WIT is composed of a curated set of 37.6 million entity rich image-text
   (...)
     32 learning models.
     33 """
     35 _CITATION = """
     36 @article{srinivasan2021wit,
     37   title={WIT: Wikipedia-based Image Text Dataset for Multimodal Multilingual Machine Learning},
   (...)
     41 }
     42 """

OverflowError: Python int too large to convert to C long


**Environment information**

- OS: Windows
- Python: 3.9.9
- tensorflow: 2.7.0

**Comment by Conchylicultor** [comment]
Sorry for the breakage. We'll send a fix and update to 4.5.1 as soon as possible.

**Comment by Conchylicultor** [comment]
4.5.1 version has been released. It should have fixed the issue. Let us know if you still encounter issues after updating.

**Comment by zhiltsov-max** [comment]
Hi, we still can see this problem 
https://github.com/openvinotoolkit/datumaro/runs/5006795500?check_suite_focus=true

**Comment by Conchylicultor** [comment]
Sorry for the issue, indeed it looks like the issue appear in 2 places and we only fix one of the files. We're working on releasing 4.5.2 now (hopefully it will work now)

**Comment by Conchylicultor** [comment]
https://pypi.org/project/tensorflow-datasets/ is now at 4.5.2 and should contain the https://github.com/tensorflow/datasets/commit/68fa6da5a700f58c764c1cc9990e7a3938a1cae0 fix.
Let us know if you're still encountering the issue
