### ISSUE TITLE
Standardize some dataset variants

### ISSUE THREAD

**Issue by ageron** [tensorflow/datasets#371]
**Is your feature request related to a problem? Please describe.**
It is very common to want a small sample of a dataset, to explore it, to train a first model on your machine before you go to the cloud, and so on. Right now, you must do:

```python
tfds.load("some_large_dataset",
           download_and_prepare_kwargs=tfds.download.DownloadConfig(
                                           max_examples_per_split=1000))
```

This is buried in the documentation, and long to type. Moreover, it applies the same restriction to every split.

**Describe the solution you'd like**
It would be nice to have a shortcut argument for this in the `tfds.load()` function, like `max_examples_per_split`, as I think it's a frequent need. Moreover, it would be nice to be able to specify a ratio rather than an absolute number, for example `max_examples_per_split=0.1` would mean 10% of the original dataset. Perhaps also support `max_examples_per_split={"train": 10000, "test": 2000}`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by us** [comment]
I love it 👍

**Comment by us** [comment]
Please can you check this [link](https://www.tensorflow.org/datasets/splits#specify_a_percentage_slice). Isn't that what you're feature request about?

**Comment by ageron** [comment]
Oops, indeed, I missed that, thanks @us !
