### ISSUE TITLE
NonMatchingChecksumError while downloading DeepWeeds dataset

### ISSUE THREAD

**Issue by borjaeg** [tensorflow/datasets#3817]
```
NonMatchingChecksumError: Artifact https://drive.google.com/uc?export=download&id=1xnK3B6K6KekDI55vwJ0vnc2IGoDga9cj, downloaded to /root/tensorflow_datasets/downloads/ucexport_download_id_1xnK3B6K6KekDI55vwJ0vnc2ITDlCjLc2rcwnx4HX2m4DkEyLfA722UJqaLRkfNhB6ec.tmp.05d07fceb62945899020d3b83dba9d8b/uc, has wrong checksum:
* Expected: UrlInfo(size=468.75 MiB, checksum='0961f63c01b997bfab1559ad09e99c0e8130617fd96a8b92fdc09940e01b0ce8', filename='images.zip')
* Got: UrlInfo(size=2.15 KiB, checksum='f1a0005e24221111115ff441819e0d41bfdead1d1c9603ea8074fe86a8268073', filename='uc')
To debug, see: https://www.tensorflow.org/datasets/overview#fixing_nonmatchingchecksumerror
```

**Short description**
NonMatchingChecksumError while downloading DeepWeeds dataset

**Environment information**
* Operating System: Ubuntu 18.04.5 LTS (Bionic Beaver)
* Python version: 3.7.12
* `tensorflow-datasets` version: 4.4.0
* `tensorflow`/`tf-nightly` version: 2.8.0

**Reproduction instructions**

```python
import tensorflow_datasets as tfds

data = tfds.load("deep_weeds", split="train", as_supervised=True)
```

**Expected behavior**
That error should not appear.

**Comment by ccl-core** [comment]
Hello @borjaeg , thank you for reporting this!

This bug should be fixed in our nightly version. You should be able to successfully import the dataset with `import tfds-nightly as tfds`:)

Thank you!

**Comment by skr3178** [comment]
> import tfds-nightly as tfds

SyntaxError: invalid syntax
