### ISSUE TITLE
Lint tensorflow_datasets

### ISSUE THREAD

**Issue by rsepassi** [tensorflow/datasets#390]
**Short description**
TFDS has many lint errors according to `lint.sh` in #389. We should fix them.

**Reproduction instructions**

```
./oss_scripts/lint.sh
```

**Expected behavior**
No lint errors.

**Additional context**
This requires mostly fixing the errors. Sometimes it makes more sense to disable the linter with `pylint: disable=name-of-linter-error`.

**Comment by ParthS007** [comment]
I want to work on this. Please assign it to me.

**Comment by rsepassi** [comment]
Thanks @ParthS007!

**Comment by us** [comment]
@ParthS007 you have already a lot assign. If you want I can take this project

**Comment by ParthS007** [comment]
@rsepassi #389 has not been merged yet. Please merge it so that I can start working on this Issue. Thanks :)

**Comment by Conchylicultor** [comment]
Even if the PR is still open (not sure why it hasn't synced), it has been merged: see: https://github.com/tensorflow/datasets/blob/master/oss_scripts/lint.sh
