### ISSUE TITLE
Default data_dir creates a folder named ~ instead of in home directory.

### ISSUE THREAD

**Issue by bermeitinger-b** [tensorflow/datasets#3903]
When loading a dataset (e.g. `mnist`) without setting any data_dir (not in kwargs or env), the prepared dataset will end up in the actual literal folder `~/tensorflow_datasets/mnist` (without resolving to the users home directory).

The intermediate/final downloads are in the expected location.

Example:
```python
import tensorflow_datasets as tfds
tfds.load('mnist')
```
```
2022-04-29 20:57:35.285745: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
Downloading and preparing dataset 11.06 MiB (download: 11.06 MiB, generated: 21.00 MiB, total: 32.06 MiB) to ~/tensorflow_datasets/mnist/3.0.1...
Dl Completed...: 100%|███████████████| 4/4 [00:04<00:00,  1.03s/ file]
Dataset mnist downloaded and prepared to ~/tensorflow_datasets/mnist/3.0.1. Subsequent calls will reuse this data.
```

The folders will look like this inside the current working directory:
```
.
└── ~
    └── tensorflow_datasets
        └── mnist
            └── 3.0.1
                ├── dataset_info.json
                ├── image.image.json
                ├── mnist-test.tfrecord-00000-of-00001
                └── mnist-train.tfrecord-00000-of-00001

4 directories, 4 files
```
And this is the actual folder in my home directory:
```
/home/bernhard/tensorflow_datasets
└── downloads
    └── extracted

2 directories, 0 files
```

Python 3.10.4, tfds version: `tfds-nightly-4.5.2.dev202204290044`

I believe it's the default value here that is not resolved correctly: https://github.com/tensorflow/datasets/blob/3912a1e4e5fadd3effc46b982d113d63fa8d7e6b/tensorflow_datasets/core/constants.py#L27-L28

**Comment by anykx** [comment]
I encountered the same problem. Any solution for solving this?

**Comment by bermeitinger-b** [comment]
You could set the environment variable `TFDS_DATA_DIR` to the directory of your choice. That's what I did.

**Comment by anykx** [comment]
It works! Thanks for your reply.
