### ISSUE TITLE
[data request] LFW

### ISSUE THREAD

**Issue by SinghKislay** [tensorflow/datasets#393]
* Name of dataset: lfw
* URL of dataset: http://vis-www.cs.umass.edu/lfw/
* License of dataset: Unknown
* Short description of dataset and use case(s): lfw is a dataset of 1 or more photos of different individuals. It was used in facenet. It is a very relevant dataset for face-recognition models.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by SoumyadeepJana** [comment]
@SinghKislay  Didn't you make a PR of this issue?

**Comment by shashvatshahi1998** [comment]
I will love to work on this

**Comment by SinghKislay** [comment]
I have already got the pr reviewed and waiting for it to get merged.

**Comment by cyfra** [comment]
Fixed in #379
