### ISSUE TITLE
moist handwritten digit classification

### ISSUE THREAD

**Issue by LigolaH** [tensorflow/datasets#394]
* Name of dataset: <name>
* URL of dataset: <url>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by SoumyadeepJana** [comment]
@cfyra @Conchylicultor @rsepassi  I would like to work on this

**Comment by SoumyadeepJana** [comment]
@Conchylicultor This issue can be closed.
