### ISSUE TITLE
[data request] Malaria Cell Images Dataset

### ISSUE THREAD

**Issue by SoumyadeepJana** [tensorflow/datasets#405]
* Name of dataset: Malaria Cell Images Dataset
* URL of dataset: https://ceb.nlm.nih.gov/repositories/malaria-datasets/
* License of dataset: Unknown
* Short description of dataset and use case(s): This dataset contains images of segmented cells from the thin blood smear slide images from the Malaria Screener research activity. The dataset contains a total of 27,558 cell images with equal instances of parasitized and uninfected cells. 

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by SoumyadeepJana** [comment]
@Conchylicultor  @rsepassi @cyfra I am working on this, please assign me. :)

**Comment by cyfra** [comment]
Fixed in #826
