### ISSUE TITLE
Testing and subclasses

### ISSUE THREAD

**Issue by EmanueleGhelfi** [tensorflow/datasets#406]
**What I need help with / What I was wondering**
I'm trying to convert our internal dataset as tfds. However, I have some difficulties. 
The basic testing class: `tensorflow_datasets.testing.DatasetBuilderTestCase`  searches for the test data inside the folder "tensorflow_dataset/testing/test_data/fake_examples". Unfortunately I am not using the tfds repository but an internal repository.

My idea was to implement a subclass of `tensorflow_datasets.testing.DatasetBuilderTestCase` (let's say `InternalDatasetuilderTestCase`) in order to override the `setUp` function looking for a different folder. Doing in this way when I subclass the `InternalDatasetuilderTestCase` and I run tests I got an error since the tests run also on the `InternalDatasetuilderTestCase` that does not have a `DATASET_CLASS`. 
I can override the `setUp` method for each test dataset class, but I think it's not an elegant way.

What's the correct way to proceed?

I think it could be nice if the `tensorflow_datasets.testing.DatasetBuilderTestCase` would accept the fake example folder as parameter or if a class extending  `tensorflow_datasets.testing.DatasetBuilderTestCase` can be marked as "To not test".

Thank you for your attention.

**Comment by EmanueleGhelfi** [comment]
Fixed.
I was importing my InternalDatasetuilderTestCase as:

`from myrepo.testing.internal_datasetuilder_test_case import InternalDatasetuilderTestCase`

Doing in this way results in the class being tested.
In the same way creating a testing class importing directly DatasetBuilderTestCase:

`from tensorflow_datasets.testing import DatasetBuilderTestCase`

results in the class DatasetBuilderTestCase being tested and this causes an error.
I think this can be reported in the documentation in order to avoid errors.

**Comment by Conchylicultor** [comment]
Closing this as it seems fixed.
Note that you can also overwrite `EXAMPLE_DIR` to customize the fake data dir.

See: https://www.tensorflow.org/datasets/api_docs/python/tfds/testing/DatasetBuilderTestCase?version=nightly
