### ISSUE TITLE
TypeError: Can't instantiate abstract class MyDataset with abstract methods _split_generators

### ISSUE THREAD

**Issue by ValentinKlamka** [tensorflow/datasets#4135]
```
TypeError                                 Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_2388\2548683246.py in <module>
----> 1 ds = tfds.builder('my_dataset')
      2 

c:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\load.py in builder(name, try_gcs, **builder_kwargs)
    152   # First check whether we can find the corresponding dataset builder code
    153   try:
--> 154     cls = builder_cls(str(name))
    155   except registered.DatasetNotFoundError as e:
    156     cls = None  # Class not found

c:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\load.py in builder_cls(name)
     95             f'Cannot load {ds_name} when community datasets are disabled')
     96     else:
---> 97       cls = registered.imported_builder_cls(str(ds_name))
     98       cls = typing.cast(Type[dataset_builder.DatasetBuilder], cls)
     99     return cls

c:\Users\Me\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_datasets\core\registered.py in imported_builder_cls(name)
    121     # Will raise TypeError: Can't instantiate abstract class X with abstract
    122     # methods y, before __init__ even get called
--> 123     _ABSTRACT_DATASET_REGISTRY[name]()  # pytype: disable=not-callable
    124     # Alternativelly, could manually extract the list of non-implemented
    125     # abstract methods.


TypeError: Can't instantiate abstract class MyDataset with abstract methods _split_generators
```
**Short description**
I built my custom dataset with `tfds build` which seemed to work fine. Then I tried to execute `ds = tfds.builder('my_dataset')` in Python and got the stacktrace above

**Code**

```python
from typing import Dict, Iterator, Tuple
import tensorflow_datasets as tfds
import tensorflow as tf
import numpy as np
from pathlib import Path
def _info(self) -> tfds.core.DatasetInfo:
    ...
    ...
    ...
def _split_generators(self,blub):
    """Returns SplitGenerators."""

    path = Path('../img')
    path2= Path('../coords')

    return {
        'train': self._generate_examples(path, path2)
    }

def _generate_examples(self, path, path2) -> Iterator[Tuple[str, Dict[np.ndarray, tf.Tensor]]]:
    ...
    ...
    ...
```
I don't use `blub` in the _split_generators function, but still had to provide an argument to get the command `tfds.build` working. I don't think, that's the problem though. But how do I get rid of this TypeError?

**Environment information**
* Operating System: Windows 10
* Python version: 3.7.4
* `tensorflow-datasets` version: 4.6.0
* `tensorflow` version: 2.10.0

**Comment by Conchylicultor** [comment]
Are you sure you do not have another `class MyDataset` which do not implement the `_split_generators` function ?

In your code you pasted, you're not declaring a class anywhere ? Could you provide the real code you're using ?

Also once your dataset is generated, you do not need anymore to import your dataset code. So you would not have registration issues (TFDS will auto-detect the dataset files in the `~/tensorflow_datasets/` data_dir and load it).

**Comment by ValentinKlamka** [comment]
@Conchylicultor you pushed me to the solution already. Indeed I was using an ipynb notebook called playground to test everything and there I also had the class MyDataset defined. After restarting the kernel and just executing` ds = tfds.builder('my_dataset')` it works without error. Thanks!
