### ISSUE TITLE
Documentation: Bair robot pushing dataset

### ISSUE THREAD

**Issue by oscartackstrom** [tensorflow/datasets#415]
The documentation for the "bair_robot_pushing_dataset" seems wrong. From the dataset statistics it looks like this is the "bair robot pushing dataset" from https://sites.google.com/corp/view/sna-visual-mpc/. But the documentation mixes the description of the bair dataset with the "google robot pushing dataset" from https://sites.google.com/site/brainrobotdata/home/push-dataset.

**Comment by us** [comment]
@oscartackstrom Thank you for reporting. I fixed it #416
