### ISSUE TITLE
Change default download directoy to hidden folder

### ISSUE THREAD

**Issue by frthjf** [tensorflow/datasets#43]
Currently, the default download directory for dataset caching appears to be ``~/tensorflow_datasets``. However, since it's not a folder that is meant to be accessed through a file manager, I'd suggest to make it hidden by default, e.g. ``~/.tensorflow_datasets``.

**Comment by rsepassi** [comment]
Thanks for the suggestion! We'd be open to making it hidden, but it is sometimes useful to look in that directory. The `manual_dir` that some datasets need (e.g. ImageNet) also defaults to being in there, so that also makes us lean to not having it be hidden. I'll leave this open though so that other users can chime in.

**Comment by Conchylicultor** [comment]
Also open to discussion, but I would have some concerns about making it hidden.
The download directory may contains hundreds of GB downloaded automatically. In a hidden directory, users may have more difficulty to locate where their data are located, or even not being aware that they have a huge hidden folder consuming their diskspace.

**Comment by cyfra** [comment]
Thanks for the proposal @frthjf 

I'd second what @Conchylicultor wrote: this directory can be quite large, and making it hidden by default might be confusing to some users.
You can always select the hidden path as your data dir - if you so prefer.

I'll close this bug.

**Comment by tufei** [comment]
I have been searching and struggling to find an option to allow me setting a different default directory other than ~/tensorflow_datasets. Oftentimes there is personal convention on organizing files and directories, not having such an option is really surprising.

**Comment by Conchylicultor** [comment]
@tufei Can't you just set `data_dir` to whatever you  want ?

```
ds = tfds.load('mnist', data_dir='/my/custom/tensorflow_datasets')
```

**Comment by diego1109** [comment]
Tensor flow_dataset

数据集默认存放路径：`~/tensorflow_datasets`
数据集存放路径修改方式：以**MNIST**为例，代码如下：

```python
import tensorflow_datasets as tfds
tfds.load('mnist', data_dir='/dir/to/save/dataset/')
```

**Comment by SicariusNoctis** [comment]
Could this be put into a JSON config option? e.g. `~/.config/tensorflow_datasets.json`:

```json
{
    "data_dir": "/mnt/big_drive/.tensorflow_datasets"
}
```

**Comment by Yannik1337** [comment]
> Could this be put into a JSON config option? e.g. `~/.config/tensorflow_datasets.json`:
> 
> ```json
> {
>     "data_dir": "/mnt/big_drive/.tensorflow_datasets"
> }
> ```

As an alternative, you can set the environmental variable, `TFDS_DATA_DIR`, to a directory of your choice. Per default, this is `~/tensorflow_datasets`.

This is especially helpful for container environments, where you might want to process data within the container, but persist it to disk (to use it again another time, without processing.)
