### ISSUE TITLE
Remove any tensorflow dependency

### ISSUE THREAD

**Issue by stepelu** [tensorflow/datasets#4354]
**Is your feature request related to a problem? Please describe.**

I would like to use tensorflow_datasets, which is very convenient and well designed, but I do not use nor plan to use tensorflow.

Currently, this package requires tensorflow to be installed:

```
> tfds build mnist

***************************************************************
Failed to import TensorFlow. Please note that TensorFlow is not installed by default when you install TFDS. This allow you to choose to install either `tf-nightly` or `tensorflow`. Please install the most recent version of TensorFlow, by following instructions at https://tensorflow.org/install.
***************************************************************

Traceback (most recent call last):
  File "/home/sp/miniconda3/envs/tfds/bin/tfds", line 5, in <module>
    from tensorflow_datasets.scripts.cli.main import launch_cli
  File "/home/sp/miniconda3/envs/tfds/lib/python3.10/site-packages/tensorflow_datasets/__init__.py", line 41, in <module>
    import tensorflow_datasets.core.logging as _tfds_logging
  File "/home/sp/miniconda3/envs/tfds/lib/python3.10/site-packages/tensorflow_datasets/core/__init__.py", line 23, in <module>
    tf_compat.ensure_tf_install()
  File "/home/sp/miniconda3/envs/tfds/lib/python3.10/site-packages/tensorflow_datasets/core/tf_compat.py", line 47, in ensure_tf_install
    import tensorflow as tf  # pylint: disable=import-outside-toplevel
ModuleNotFoundError: No module named 'tensorflow'
```

When installed, tensorflow is imported at runtime which cause issues wrt other frameworks (like tensorflow reserving GPU memory for itself), and in general it is a waste of space to have to install tensorflow when it is not used.
The package is promoted for use with jax and other frameworks, it would be best to just remove any dependency on tensorflow.

**Describe the solution you'd like**

Make the tensorflow_datasets package independent of tensorflow.

**Comment by pierrot0** [comment]
Hi, we are working on this.
TF is not longer imported when TFDS is imported, but will be the first time it's needed. We are working with https://github.com/google/grain to be able to provide a dataset loading path fully free of TF.

**Comment by NeilGirdhar** [comment]
Any update on this?

**Comment by marcenacp** [comment]
@stepelu, @NeilGirdhar, TensorFlow is no longer a dependency to read datasets!

Find the full documentation here: https://www.tensorflow.org/datasets/tfless_tfds.

We're looking forward to your feedback.

**Comment by marcenacp** [comment]
It's already packaged in `tfds-nightly`! But yes, it'll come with the next release.

A few optimizations are also coming to make things run even faster, especially for PyTorch pipelines.

**Comment by NeilGirdhar** [comment]
Is tensorflow required for "mnist"?
```
import tensorflow_datasets as tfds
tfds.load(name="mnist")  # ModuleNotFoundError: No module named 'tensorflow'
```
with
```
tensorflow-datasets==4.9.3
tensorflow-metadata==1.14.0
tensorflow-probability==0.22.0
```
Am I doing something wrong?

**Comment by SkittlePox** [comment]
Echoing @NeilGirdhar I'm still getting a ModuleNotFoundError

**Comment by marcenacp** [comment]
@SkittlePox @NeilGirdhar `tfds.load` is meant to be used with tf.data, so TensorFlow is still needed.

You're probably looking for [`tfds.data_source`](https://www.tensorflow.org/datasets/api_docs/python/tfds/data_source). Please, read more about this in the documentation: https://www.tensorflow.org/datasets/tfless_tfds.

**Comment by NeilGirdhar** [comment]
@marcenacp Awesome, thanks that makes sense!  Any plans on adding `with_info` or `as_supervised` to the local interface?

**Comment by eadadi** [comment]
```
ds = tfds.data_source("mnist", split="train")    # no module named 'tensorflow'
```

with
```
tfds-nightly             4.9.7.dev202412120044
```

**Comment by marcenacp** [comment]
@eadadi TensorFlow is still needed to prepare and serialize the dataset. You can follow [the full `tfds.data_source` tutorial](https://www.tensorflow.org/datasets/data_source) to know more.

**Comment by eadadi** [comment]
@marcenacp thanks. any plans to remove the dependancy?

**Comment by eadadi** [comment]
also - is there minimal tensorflow installatio only for this capability?

**Comment by marcenacp** [comment]
> @marcenacp thanks. any plans to remove the dependancy?

Not on the dataset creation side where users typically care less about performance or used libraries or import times.

> also - is there minimal tensorflow installatio only for this capability?

The best is to follow the tutorial I linked above.

```
pip install tfds-nightly
pip install tensorflow
```
