### ISSUE TITLE
[data request] GAP data set

### ISSUE THREAD

**Issue by sklan** [tensorflow/datasets#440]
* Name of dataset: GAP
* URL of dataset: https://github.com/google-research-datasets/gap-coreference
* License of dataset: Apache License 2.0
* Short description of dataset and use case(s): GAP is a gender-balanced dataset containing 8,908 coreference-labeled pairs of (ambiguous pronoun, antecedent name), sampled from Wikipedia for the evaluation of coreference resolution in practical applications.
ArXiV Link: [https://arxiv.org/abs/1810.05201](https://arxiv.org/abs/1810.05201)
Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by sklan** [comment]
This is another data set I want to add. Can somebody please assign me?

**Comment by shashvatshahi1998** [comment]
Can I add it @sklan please I am new to it.

**Comment by sklan** [comment]
@shashvatshahi1998 I am actually mostly done already. However, you can find interesting datasets here:
[https://ai.google/tools/datasets/](https://ai.google/tools/datasets/)

**Comment by cyfra** [comment]
Merged in #460
