### ISSUE TITLE
[data request]  Downsampled ImageNet

### ISSUE THREAD

**Issue by rodrigob** [tensorflow/datasets#45]
* Name of dataset:  Downsampled ImageNet
* URL of dataset: http://image-net.org/small/download.php
* License of dataset: Same as ImageNet
* Short description of dataset and use case(s): great for prototyping and quick experimentation beyond MNIST.

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by tabshaikh** [comment]
As this is a good first issue would like to take this up 😀

**Comment by tabshaikh** [comment]
There are 2 version of this dataset 32*32 images and 64*64 images should both be done ?

**Comment by rsepassi** [comment]
That's great @tabshaikh, thank you! 

Yes, I think we should have both using ["heavy" configuration](https://www.tensorflow.org/datasets/add_dataset#dataset_configuration), but you can start with just one.

**Comment by rsepassi** [comment]
I'll assign the issue to you as soon as you accept the collaborator invite! :smiley:

**Comment by tabshaikh** [comment]
Sure thanks :)

**Comment by rsepassi** [comment]
Sounds good! Thank you!

**Comment by Anupam-tripathi** [comment]
@rsepassi I would love to collaborate with @tabshaikh and make a pull request for Downsampled ImageNet. Please assign it to me also.

**Comment by rsepassi** [comment]
Hi @Anupam-tripathi, thanks for your interest! Are you already working directly with @tabshaikh? If not, let's give him a chance to get a PR in. If he'd like the help, then please do work together to get something in!

**Comment by Anupam-tripathi** [comment]
No, I have not joined him till now but will surely contact him personally.

**Comment by tabshaikh** [comment]
@Anupam-tripathi I would love to collaborate with you but the pr is almost done with a few changes left to do and hopefully, I have added the dataset correctly @rsepassi  I would do a pr till mid next week as I will be going for an ML hackathon during the weekend, I had some question too would ask in the draft pr
Cheers :)

**Comment by rsepassi** [comment]
Sounds good. Thanks!

**Comment by Anupam-tripathi** [comment]
Ya, surely I will prove to be a good teammate.

**Comment by tabshaikh** [comment]
@rodrigob @rsepassi the link for http://image-net.org/small/download.php does not contain the whole dataset of the downsampled imagenet nor does it contain the labels. 
Further i found these links https://patrykchrabaszcz.github.io/Imagenet32/ for dataset details and this http://image-net.org/download-images which contains the whole dataset and 
I could not understand in which dev kit of imagenet the labels are present as mentioned in this link https://patrykchrabaszcz.github.io/Imagenet32/ ? 
Also the data is requires login and is present in the form of pickle file which extracts into a dictionary 
Can you help me how to proceed with this further :)

**Comment by cyfra** [comment]
@tabshaikh - Yes, this dataset has only a subset of subsampled imagenet images and does NOT have labels.

This is on purpose - as it was used for autoregressive algorithms, that were generating the output images (rather than trying to predict the class).

Please download from the official link rather than from side-ones.

**Comment by tabshaikh** [comment]
@cyfra okay cool

**Comment by rodrigob** [comment]
The idea of this ticket was to create a smaller version of imagenet that is small enough so that most people can prototype and experiment without having to worry about download time or disk-space.

I would suggest to go for 32x32 and 64x64 versions; ideally _with_ labels so that supervised training (à la MNIST and CIFAR) can also be used.

**Comment by tabshaikh** [comment]
@rodrigob okay thanks :)

**Comment by joel-shor** [comment]
Any thoughts on doing the 128x128 version while you're at it?

**Comment by rsepassi** [comment]
Joel, looks like there are only 2 versions listed, 32 and 64: http://image-net.org/small/download.php

**Comment by rsepassi** [comment]
@joel-shor

**Comment by tabshaikh** [comment]
@rsepassi no there are 4 versions actually 8x8, 16x16, 32x32, 64x64 here http://image-net.org/download-images. The link which you pointed out is incomplete as there is no labels for the same.
@joel-shor can you point me to 128x128 version :)

**Comment by joel-shor** [comment]
Sorry for the delay. The 128x128 imagenet, which is used in a number of state-of-the-art GANs (such as Self Attention GAN), can be found here: https://github.com/openai/improved-gan/blob/master/imagenet/convert_imagenet_to_records.py

If you were able to turn this in to a TFDS data set, you would be a hero!

**Comment by joel-shor** [comment]
@tabshaikh Have you moved on from this?

**Comment by Conchylicultor** [comment]
Has been added with https://github.com/tensorflow/datasets/pull/613. Closing this now
