### ISSUE TITLE
Library triggers its own warning

### ISSUE THREAD

**Issue by NeilGirdhar** [tensorflow/datasets#4612]
```python
import tensorflow_datasets as tfds
tfds.load('diamonds')
```
produces:
```
WARNING:absl:You use TensorFlow DType <dtype: 'float32'> in tfds.features This will soon be deprecated in favor of NumPy DTypes. In the meantime it was converted to float32.
```
Still broken on master.

**Comment by marcenacp** [comment]
Hi @NeilGirdhar, we are in the process of making TensorFlow optional, so all types should now be NumPy DType.

Thank you for reporting that this dataset was not fully migrated! [This commit](https://github.com/tensorflow/datasets/commit/47a2ac537cacede9872575def3679e7cf95292d5) should fix it.

**Comment by NeilGirdhar** [comment]
@marcenacp Awesome! Really looking forward to this since it will make many projects support Python 3.11.
