### ISSUE TITLE
create_new_dataset 

### ISSUE THREAD

**Issue by lc0** [tensorflow/datasets#462]
**Short description**
I have issues using dataset generator 
```
AttributeError: module 'tensorflow_datasets.core.naming' has no attribute 'snake_to_camelcase'
```

Also, colab says it's `1.0.2`, but I only can see `1.0.1` on github

**Environment information**
* Operating System: colab
* Python version: `3.6.7`
* `tensorflow-datasets`/`tfds-nightly` version: '1.0.2'
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 1.13.1

**Reproduction instructions**

```
!python tensorflow_datasets/scripts/create_new_dataset.py \
		--dataset awesome_dataset \
		--type image
```

**Comment by Conchylicultor** [comment]
The `create_new_dataset.py` script is used to generate template files when wanting to add a new dataset in tensorflow_dataset repository. It's usage is not designed for Colab.
In colab, you'll have to write the code directly in the notebook, instead of creating new files. I'm gonna update the doc to clarify this.

**Comment by lc0** [comment]
@Conchylicultor 
Yes, I actually wanted to add a new dataset. I have the same issue on my local machine. Just wanted to validate, if the issue is reproducible on colab as well, since local version is different

**Comment by sklan** [comment]
@lc0 Could you share a colab notebook with the error?

**Comment by lc0** [comment]
Interesting, now i see different versions. The code I had from the day I created the issue
![image](https://user-images.githubusercontent.com/775466/56084351-5c371400-5e32-11e9-85a4-5e5bfa0197ac.png)

And the one I can reproduce today
https://colab.research.google.com/drive/1jfgmYoy43y10qkKWVjTsyjblxw8aYtR6

**Comment by sklan** [comment]
The ```nightly``` version doesn't have this problem. Colab notebooks come with a preinstalled ```tfds-nightly``` version.  So don't do ```pip install tensorflow_datasets```.
If you want to install ```tensorflow_datasets``` for development on colab. I have shared a way in the colab notebook below. 
https://colab.research.google.com/drive/1aawcl41lCb-f2HO0vXypxK40jCQK_K-X

**Comment by lc0** [comment]
hm, good to know. This kind of means, that current public version is broken, but only until the next release

**Comment by drozzy** [comment]
What's the status on this? I still can't import tfds as I get:

```
module 'tensorflow_datasets' has no attribute 'public_api'
```

**Comment by Conchylicultor** [comment]
@drozzy which TFDS version, plateform,... are you using ?
What are you trying to import ?

`import tensorflow_datasets as tfds` should works, no matter which version you are using
