### ISSUE TITLE
Using tfds breaks tf.keras's fit(verbose=1) output.

### ISSUE THREAD

**Issue by 20zinnm** [tensorflow/datasets#470]
I suspect this is due to an issue with Keras and TQDM, which is imported by tfds. The output in a Jupyter notebook looks like:

```
286/21810 [..............................] - ETA: 18:28:59 - loss: 0.8366 - acc: 0.781 - ETA: 2:41:29 - loss: 0.8840 - acc: 0.727 - ETA: 1:35:41 - loss: 0.8536 - acc: 0.73 - ETA: 1:04:52 - loss: 0.8264 - acc: 0.73 - ETA: 49:28 - loss: 0.7828 - acc: 0.7500 - ETA: 40:13 - loss: 0.7983 - acc: 0.73 - ETA: 34:04 - loss: 0.7568 - acc: 0.75 - ETA: 29:40 - loss: 0.7582 - acc: 0.75 - ETA: 26:21 - loss: 0.7291 - acc: 0.75 - ETA: 23:47 - loss: 0.7393 - acc: 0.75 - ETA: 21:44 - loss: 0.7307 - acc: 0.76 - ETA: 20:02 - loss: 0.7366 - acc: 0.76 - ETA: 18:37 - loss: 0.7253 - acc: 0.76 - ETA: 17:26 - loss: 0.7306 - acc: 0.76 - ETA: 16:24 - loss: 0.7323 - acc: 0.76 - ETA: 15:31 - loss: 0.7262 - acc: 0.76 - ETA: 14:45 - loss: 0.7349 - acc: 0.75 - ETA: 14:04 - loss: 0.7383 - acc: 0.75 - ETA: 13:28 - loss: 0.7348 - acc: 0.76 - ETA: 12:56 - loss: 0.7326 - acc: 0.76 - ETA: 12:27 - loss: 0.7363 - acc: 0.76 - ETA: 12:01 - loss: 0.7361 - acc: 0.76 - ETA: 11:36 - loss: 0.7414 - acc: 0.75 - ETA: 11:14 - loss: 0.7454 - acc: 0.75 - ETA: 10:54 - loss: 0.7527 - acc: 0.75 - ETA: 10:35 - loss: 0.7480 - acc: 0.75 - ETA: 10:14 - loss: 0.7442 - acc: 0.75 - ETA: 9:58 - loss: 0.7439 - acc: 0.7561 - ETA: 9:47 - loss: 0.7400 - acc: 0.757 - ETA: 9:37 - loss: 0.7428 - acc: 0.756 - ETA: 9:24 - loss: 0.7437 - acc: 0.755 - ETA: 9:14 - loss: 0.7392 - acc: 0.755 - ETA: 9:04 - loss: 0.7392 - acc: 0.756 - ETA: 8:55 - loss: 0.7372 - acc: 0.757 - ETA: 8:45 - loss: 0.7399 - acc: 0.756 - ETA: 8:35 - loss: 0.7387 - acc: 0.757 - ETA: 8:26 - loss: 0.7373 - acc: 0.757 - ETA: 8:18 - loss: 0.7396 - acc: 0.757 - ETA: 8:10 - loss: 0.7396 - acc: 0.757 - ETA: 8:02 - loss: 0.7382 - acc: 0.757 - ETA: 7:55 - loss: 0.7416 - acc: 0.757 - ETA: 7:47 - loss: 0.7408 - acc: 0.757 - ETA: 7:41 - loss: 0.7399 - acc: 0.757 - ETA: 7:34 - loss: 0.7429 - acc: 0.756 - ETA: 7:28 - loss: 0.7436 - acc: 0.757 - ETA: 7:22 - loss: 0.7447 - acc: 0.757 - ETA: 7:15 - loss: 0.7415 - acc: 0.758 - ETA: 7:10 - loss: 0.7384 - acc: 0.759 - ETA: 7:04 - loss: 0.7379 - acc: 0.7592
...
```

Does anyone know of a way I can fix this? The progress bar is fine when I manually create the dataset (in a different notebook).

**Comment by SoumyadeepJana** [comment]
@20zinnm  Could you please provide the code to reproduce this

**Comment by rsepassi** [comment]
Does calling tfds.disable_progress_bar() beforehand fix the issue? This was
recently added to disable TQDM altogether if need be.

**Comment by Conchylicultor** [comment]
Tfds only uses tqdm when creating the data. It seems that your issue happen only after the data is created so I would suspect something with Keras.

Additionally, tqdm can create visual artifacts with some versions of Jupyter notebooks, which is maybe what happened here.

Closing this issue as it seems unrelated to tfds.

**Comment by 20zinnm** [comment]
Sorry for the delay. Here is a sample notebook: https://gist.github.com/20zinnm/8a2da46f59faf8ca19d83d03ec85ac7c

I will try your suggestions as soon as possible, but I have not had any issues outside of using tfds.

**Comment by 20zinnm** [comment]
@rsepassi Invoking tfds.disable_progress_bar() does not seem to fix the issue. Is tqdm still imported if the progress bar is disabled?

**Comment by 20zinnm** [comment]
@Conchylicultor 

> Tfds only uses tqdm when creating the data. It seems that your issue happen only after the data is created so I would suspect something with Keras.

I believe this issue is a result of tfds importing tqdm, not necessarily using it during training.

**Comment by Conchylicultor** [comment]
To test your hypothesis, could you try a simple keras code without all the extra code.

1) Once with Keras only (no tqdm, no tfds)
2) Once with Keras only, but add a `import tqdm` line before the call to `model.fit`
3) Once with Keras + tfds

Do you observe the same behavior in all three cases ? Does 2 and 3 create the same behavior different from 1 ?
