### ISSUE TITLE
imagenet_v2 errors due to 403 http error

### ISSUE THREAD

**Issue by banoffee-pie** [tensorflow/datasets#4842]
**Short description**
Trying to load imagenet_v2 errors out due to a 403: forbidden response when trying to download `https://s3-us-west-2.amazonaws.com/imagenetv2public/imagenetv2-matched-frequency.tar.gz`

**Environment information**
* **Operating System:** MacOS 13.3
* **Python version:** 3.8.8
* **`tensorflow-datasets`/`tfds-nightly` version:** `tensorflow-datasets` version 4.8.3
* **`tensorflow`/`tf-nightly` version:** `tensorflow` version 2.12.0

* **Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?**
A different error is raised (TypeError: Unknown resource path) when using tfds-nightly

**Reproduction instructions**

```python
import tensorflow_datasets as tfds
ds = tfds.load('imagenet_v2')
```

**Link to logs**
https://pastebin.com/RBgzpJ6E

**Expected behavior**
The dataset should be downloaded as normal.

**Comment by marcenacp** [comment]
Hello @banoffee-pie, thanks for raising this issue!

In https://github.com/modestyachts/ImageNetV2/issues/12, the author of the dataset warns that they uploaded all the resources to the Hugging Face hub. I just fixed the URLs in https://github.com/tensorflow/datasets/pull/4848.

**Comment by marcenacp** [comment]
@banoffee-pie, can you please confirm it works on your side? Thanks!

**Comment by banoffee-pie** [comment]
> @banoffee-pie, can you please confirm it works on your side? Thanks!

It's working now, thank you! 👍
