### ISSUE TITLE
Enable more flexibility on dataset read

### ISSUE THREAD

**Issue by remydubois** [tensorflow/datasets#487]
**My problem**
It is hard to have several jobs running concurrently on the same dataset because of all the optimizations TensorFlow does under the hood when reading the TFRecord files. For instance, it is almost impossible to run hyperparams optimization in parallel.

**The solutions I could think of**
Perhaps the as_dataset method could allow more flexibility on arguments such as:

 - cycle_length:
in core.dataset_utils.build_dataset 
- num_parallel_calls:
When decoding examples, and reading the TFRecord in core.dataset_utils.build_dataset 
- prefetch argument
When decoding examples in core.DatasetBuilder._as_dataset

**Considered alternatives**
Enabling cycle_length and num_parallel_calls in the as_dataset method, which would be passed to the subsequent methods.

**Additional context**
I am working on a dataset where each sample is fairly heavy (~150MB), and reading the dataset with the provided parameters sometimes even freezes my server.

**Comment by Conchylicultor** [comment]
Thanks for reporting. I agree we should provide more flexibility in the tf.data hyper-parameters pipeline. Possibly by wrapping all pipeline config parameters in some config object. Not sure about the name though (`DecodeConfig`, `PipelineConfig`, `ReadConfig` ?)

```py
builder.as_dataset(split='train', read_config=ReadConfig(
    ...
))
```

**Comment by SoumyadeepJana** [comment]
@Conchylicultor I would like to work on this,please tell me how to proceed

**Comment by remydubois** [comment]
@Conchylicultor Thanks for your answer. 
`ReadConfig` seems fairly transparent to me. 
I think such object can be pretty simple. For instance, I think it can hold only one value for `num_parallel_calls`, even if this param is involved several times in the reading/decoding process. Outside of that, it should also hold `decode_prefetch_buffer` and the `read_cycle_length`, even if I agree that the naming is non-obvious here.

I can work on a PR if that sounds relevant to you.

**Comment by Conchylicultor** [comment]
Closing this as there is now a `tfds.ReadConfig` which allow customizing the input pipeline. Please open a new bug if you need control over a specific parameter which is not exposed yet.

**Comment by remydubois** [comment]
Fantastic, 
thank you for following-up on that.
