### ISSUE TITLE
Working from Iran and not having access to some datasets 

### ISSUE THREAD

**Issue by aslansd** [tensorflow/datasets#4885]
**What I need help with / What I was wondering**
I am working from Iran and it seems due to sanctions I am not able to download some datasets directly using the following command:

dataset = tfds.load('shapes3d', split='train', shuffle_files=True, data_dir='../tensorflow_datasets')

which gives the following error:

"Failed to get url https://storage.googleapis.com/3d-shapes/3dshapes.h5. HTTP code: 403."

I was wondering if there is any solution for this.

**Comment by fylux** [comment]
I am afraid that there is no TFDS-based solution for this, since the dataset is defined based on that URL and TFDS will try to download from your own computer which might be subject to internet restriction.

**Comment by aslansd** [comment]
Ok, thanks!

**Comment by marcenacp** [comment]
Closing the issue because `wget https://storage.googleapis.com/3d-shapes/3dshapes.h5` downloads the link.
