### ISSUE TITLE
[data request] Colorectal Histology (Collection of textures in colorectal cancer histology)

### ISSUE THREAD

**Issue by tarrade** [tensorflow/datasets#49]
* Name of dataset:  Colorectal Histology (Collection of textures in colorectal cancer histology)
* URL of dataset: https://zenodo.org/record/53169#.XGL2CNFCfOR
* License of dataset: Open Access
* Short description of dataset and use case(s): 
The dataset serves as a much more interesting MNIST or CIFAR10 problem for biologists by focusing on histology tiles from patients with colorectal cancer. In particular, the data has 8 different classes of tissue (but Cancer/Not Cancer can also be an interesting problem).
https://www.kaggle.com/kmader/colorectal-histology-mnist/home
https://zenodo.org/record/53169#.XGL2CNFCfOR

Good example for people to see use case of AI for Good.

Can tried to help to do TFRecords files if needed (I am learning it)

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by cyfra** [comment]
Big thanks to @jackd for submitting this dataset.
