### ISSUE TITLE
[data request] DiscoFuse

### ISSUE THREAD

**Issue by Rohith-hacker** [tensorflow/datasets#490]
* Name of dataset: DiscoFuse
* URL of dataset: https://github.com/google-research-datasets/discofuse
* License of dataset: Creative Commons Attribution-ShareAlike 3.0 license.
* Short description of dataset and use case(s): DiscoFuse was created by applying a rule-based splitting method on two corpora - sports articles crawled from the Web, and Wikipedia
Overall, each part contains 6 data subsets:

train
train_balanced
dev
dev_balanced
test
test_balanced

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by captain-pool** [comment]
Hey @cyfra, I'ld like to work on this. Can you assign this to me?

**Comment by ChanchalKumarMaji** [comment]
Issue #437 and PR #439 . This dataset has already been added. Please close this issue. Thanks.
