### ISSUE TITLE
[Feature Request/Bug] Add identity index or original file name to celeb_a attributes 

### ISSUE THREAD

**Issue by sk1ddy** [tensorflow/datasets#4905]
Maybe I am missing something, so correct me if I am wrong, but I noticed that there is no identity attribute in the tfds 'celeb_a' dataset, despite it being mentioned in the dataset description.
I quote from [here](https://www.tensorflow.org/datasets/catalog/celeb_a):
_"CelebA has large diversities, large quantities, and rich annotations, including - **10,177 number of identities**, - 202,599 number of face images, and - 5 landmark locations, 40 binary attributes annotations per image."_

I do not know if this is intended or not, anyway I find all these tfds datasets very convenient, but I also need to use the identity label for my use case. Would it be possible to add an identity index to the current set of features? Another idea would be to directly add the original file name to the attributes (the identity can be inferred from that), as it was suggested, among other things, [here](https://github.com/tensorflow/datasets/issues/118#issuecomment-528164335) .

**Comment by pierrot0** [comment]
Hey, thanks for the request.
At the moment it's unlikely that we will get any bandwidth to work on this though. However if you wish to send a PR, we will look at it.

From a quick look at it, one would need to download the identities file from around https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/datasets/celeb_a/celeb_a_dataset_builder.py#L93, then read that file and do the stitching around https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/datasets/celeb_a/celeb_a_dataset_builder.py#L180. Then the test and checksums file would need to be updated.

**Comment by OmkarBorhade98** [comment]
Hi, @sk1ddy @pierrot0 
I was trying to work on this issue. 
I was not able to load dataset since it was not able to bypass the Google Drive warning: Google Drive can't scan this file for viruses. img_align_celeba.zip (1.3G) is too large for Google to scan for viruses.

I have raised a issue for the same: #4924

**Comment by OmkarBorhade98** [comment]
Hi, @pierrot0
I have submitted a PR #4928 which will fix this issue.

**Comment by ccl-core** [comment]
Thank you @OmkarBorhade98 for your contribution! PR #4928 is merged.

**Comment by andergalvaan** [comment]
Hello everyone,

Is there any reference code in which celeb_a dataset is used to deploy a face recognition system?

Best regards,
Ander

**Comment by sk1ddy** [comment]
Hello again! I recently updated my tensorflow-datasets package to make use of this new addition, but apparently the checksums were not updated? (I am not an expert, so it is just a guess). If I try to download the latest version of celeb_a dataset (v2.1.0), I get the following error more or less in the middle of the download:


```
NonMatchingChecksumError: Artifact https://drive.google.com/uc?export=download&id=1_ee_0u7vcNLOfNLegJRHmolfH5ICW-XS, downloaded to /home/myusername/tensorflow_datasets/downloads/ucexport_download_id_1_ee_0u7vcNLOfNLegJRHm-XS-m5PzEfg9sSrNxcG3ljG0A7D5ulnonRfaRfoicHDKdU.tmp.3d01a991ed914a75bd55d877f711d107/download, has wrong checksum:
* Expected: UrlInfo(size=3.27 MiB, checksum='c6143857c3e2630ac2da9f782e9c1232e5e59be993a9d44e8a7916c78a6158c0', filename='identity_CelebA.txt')
* Got: UrlInfo(size=1.96 KiB, checksum='532ce20ea8d6729699bb89faab7cad9810af6d15ba5770a50d5c688f5967d332', filename='download')
To debug, see: https://www.tensorflow.org/datasets/overview#fixing_nonmatchingchecksumerror
```

I guess this derives by the recent addition of the identity feature. I'll try to manually download it, for now, and see if I can make it work, but I wanted to bring this to your attention.

Thank you for your work!
