### ISSUE TITLE
Please consider using platformdirs for the data directory

### ISSUE THREAD

**Issue by NeilGirdhar** [tensorflow/datasets#4919]
The data directory defaults to `~/tensorflow_datasets`: https://github.com/tensorflow/datasets/pull/4014.  [The platformdirs project](https://github.com/platformdirs/platformdirs) gives the correct location for a data directory.  I believe [this function](https://github.com/platformdirs/platformdirs/blob/b8c42ddca4def1fba38b9815a7d94ec2ac630b29/src/platformdirs/__init__.py#L71) may be the right one to call to give the appropriate directory.

**Comment by fineguy** [comment]
Hi Neil

Thanks for bringing this to our attention! 

The directory structure that [the platformdirs project](https://github.com/platformdirs/platformdirs) helps to enforce is not applicable to Tensorflow Datasets, because it's a library and not an application. You can set your own data directory with [TFDS_DATA_DIR](https://github.com/tensorflow/datasets/blob/90b5b7d102c22be80842dc25f723fb651daf6c36/tensorflow_datasets/core/constants.py#L32) environment variable.

I'm closing this issue, but if you have a more specific problem with our directory structure, please don't hesitate to open a new issue.

Have a good day!

**Comment by NeilGirdhar** [comment]
> You can set your own data directory with [TFDS_DATA_DIR](https://github.com/tensorflow/datasets/blob/90b5b7d102c22be80842dc25f723fb651daf6c36/tensorflow_datasets/core/constants.py#L32) environment variable.

That means I would have to figure out where the data directories should be stored on each system (mac, linux, windows), which I don't know off-hand.  The whole point of the platformdirs project is that it does this for you.  And it also means adding this environment variable to each system I want to run my program on.

> The directory structure that [the platformdirs project](https://github.com/platformdirs/platformdirs) helps to enforce is not applicable to Tensorflow Datasets, because it's a library and not an application

I feel like forcing the user to configure an environment variable is signficantly inferior to using a standard directory.  What's the problem with tucking your stored files under a site directory `tensorflow`/`datasets`?

**Comment by NeilGirdhar** [comment]
FYI: Here's the [Matplotlib issue](https://github.com/matplotlib/matplotlib/issues/12549#issuecomment-1555421893) contemplating using appdirs.

**Comment by fineguy** [comment]
> That means I would have to figure out where the data directories should be stored on each system (mac, linux, windows), which I don't know off-hand. The whole point of the platformdirs project is that it does this for you. And it also means adding this environment variable to each system I want to run my program on.

> I feel like forcing the user to configure an environment variable is signficantly inferior to using a standard directory. 

Sorry, I don't understand, could you please give examples to how our current users of TFDS:
- have to figure out where the data directories should be stored on each system?
- are forced to configure an environment variable?

From what I've seen and personally used after you run `pip install tensorflow-datasets` there's nothing you need to set up. 

My understanding is that using `platformdirs` would set a different default directory, but nothing will change for our users. 

> What's the problem with tucking your stored files under a site directory tensorflow/datasets? Is there a reason why those names should be reserved for applications only?

I think there's a difference between user/lib data (e.g. configuration for running your library) and dataset data (e.g. downloaded images for MNIST). There're some conventions for storing the former, but I don't see how that's applicable to the latter. Dataset data doesn't belong to TFDS and you're free to use other tools for processing these datasets. 

I'm not particularly knowledgeable about the directory structure, but I can imagine for example that `find` on `/usr/local/share` will slow down significantly if you were to dump a few terabytes of data there. Nevertheless, I don't see a strong argument why dataset data should be stored in `/usr/local/share`.

**Comment by NeilGirdhar** [comment]
> Sorry, I don't understand, could you please give examples to how our current users of TFDS:

Sorry, what I meant to say was that they're forced to do so if they want to avoid their home directory being polluted by cached files.  Other applications, like browsers, don't pollute the home directory with their cache.  They tuch it away in an appropriate platform-dependent location.

> From what I've seen and personally used after you run `pip install tensorflow-datasets` there's nothing you need to set up.

Yeah, I'd like to believe that, but I just can't agree with you there.  The polluting of the home directory induces people to have to configure an environment variable to avoid it.  This configuration could be avoided.

> My understanding is that using `platformdirs` would set a different default directory, but nothing will change for our users.

Yes, exactly.  The main benefit would be that the default directory would be appropriate to the platform, and ideally not pollute the home directory or another visible directory.

> I think there's a difference between user/lib data (e.g. configuration for running your library) and dataset data (e.g. downloaded images for MNIST). There're some conventions for storing the former, but I don't see how that's applicable to the latter.

I think TFDS should store its cache the same way that a browser stores its cache: in a hidden directory.  Browsers don't just create folders in your home directory to store their cache.  Why should this library be any different?

> I'm not particularly knowledgeable about the directory structure, but I can imagine for example that `find` on `/usr/local/share` will slow down significantly if you were to dump a few terabytes of data there.

`find` won't be affected because it just looks at the file tables.

> Nevertheless, I don't see a strong argument why dataset data should be stored in /usr/local/share.

My argument is just that it pollutes the home directory and as someone who likes to keep everything tidy, it would be nice if it didn't do that :smile:

**Comment by NeilGirdhar** [comment]
> Just for the sake of the argument, file tables could be very large. For example https://www.tensorflow.org/datasets/catalog/laion400m has 400 million images.

Good point, but I think that that's all the more reason to store those files in a cache directory that won't be indexed and searched over the home directory, which will.

> The existing users will have to migrate to the new directory. They could have other code dependent on the current location.

Fair point, but if they didn't set the TFDS_DIR variable, then is it very likely that they're depending on the default location?

> This will pollute a different directory. Other users might also prefer a different choice. Setting your own environment variable is a compromise that provides enough flexibility.

Most libraries  just make the most logical choice.  A cache directory, for example, can't really be "polluted".

> As you mention, you might get “do you want to clear out cache locations” notifications although you fully intend to keep using the datasets.

I think that's fine, right?  That's like any other cache.  If your Chrome cache for the Youtube website is cleared, the Youtube code has to be re-downloaded, etc.

> Overall, I still don't think that the arguments are strong enough to justify the collective work (both from the team and from the users) required to update the default value.

It's up to you.  Ever other library and application does this (which is why my home directory is clean)--it's just tfds that isn't following suit.
