### ISSUE TITLE
Cars196 link doesn't working

### ISSUE THREAD

**Issue by Energy00** [tensorflow/datasets#4932]
I wanna use this dataset, but get error.

DownloadError: Failed to get url https://ai.stanford.edu/~jkrause/cars/car_devkit.tgz. HTTP code: 404.

**Comment by fylux** [comment]
Thanks for reporting. Unfortunately we don't have bandwidth to fix individual datasets, so it's unlikely we will fix this soon, but we accept contributions.
Alternatively please feel free to contact the author of the dataset https://ai.stanford.edu/~jkrause/

**Comment by The-Lama** [comment]
The dataset can be found on kaggle: [https://www.kaggle.com/datasets/jessicali9530/stanford-cars-dataset](https://www.kaggle.com/datasets/jessicali9530/stanford-cars-dataset)
