### ISSUE TITLE
TypeError: GeneratorBasedBuilder._download_and_prepare() got an unexpected keyword argument 'num_proc' add Code

### ISSUE THREAD

**Issue by shivance** [tensorflow/datasets#4946]
<details><summary>Error Stacktrace </summary>
  Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to /root/tensorflow_datasets/wikitext/wikitext-2-v1/1.0.0...
  Downloading and preparing dataset wikitext/wikitext-2-v1 (download: 4.27 MiB, generated: 12.71 MiB, post-processed: Unknown size, total: 16.97 MiB) to /root/.cache/huggingface/datasets/wikitext/wikitext-2-v1/1.0.0/a241db52902eaf2c6aa732210bead40c090019a499ceb13bcbfa3f8ab646a126...
  ---------------------------------------------------------------------------
  TypeError                                 Traceback (most recent call last)
  Cell In[21], line 5
        1 # preprocessor = keras_nlp.models.BertMaskedLMPreprocessor.from_preset(
        2 #     "bert_tiny_en_uncased"
        3 # )
        4 import tensorflow_datasets as tfds
  ----> 5 ds = tfds.load('huggingface:wikitext/wikitext-2-v1')
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py:169, in _FunctionDecorator.__call__(self, function, instance, args, kwargs)
      167 metadata = self._start_call()
      168 try:
  --> 169   return function(*args, **kwargs)
      170 except Exception:
      171   metadata.mark_error()
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/load.py:640, in load(name, split, data_dir, batch_size, shuffle_files, download, as_supervised, decoders, read_config, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
      521 """Loads the named dataset into a `tf.data.Dataset`.
      522 
      523 `tfds.load` is a convenience method that:
     (...)
      632     Split-specific information is available in `ds_info.splits`.
      633 """
      634 dbuilder = _fetch_builder(
      635     name,
      636     data_dir,
      637     builder_kwargs,
      638     try_gcs,
      639 )
  --> 640 _download_and_prepare_builder(dbuilder, download, download_and_prepare_kwargs)
      642 if as_dataset_kwargs is None:
      643   as_dataset_kwargs = {}
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/load.py:499, in _download_and_prepare_builder(dbuilder, download, download_and_prepare_kwargs)
      497 if download:
      498   download_and_prepare_kwargs = download_and_prepare_kwargs or {}
  --> 499   dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py:169, in _FunctionDecorator.__call__(self, function, instance, args, kwargs)
      167 metadata = self._start_call()
      168 try:
  --> 169   return function(*args, **kwargs)
      170 except Exception:
      171   metadata.mark_error()
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builder.py:646, in DatasetBuilder.download_and_prepare(self, download_dir, download_config, file_format)
      644   self.info.read_from_directory(self._data_dir)
      645 else:
  --> 646   self._download_and_prepare(
      647       dl_manager=dl_manager,
      648       download_config=download_config,
      649   )
      651   # NOTE: If modifying the lines below to put additional information in
      652   # DatasetInfo, you'll likely also want to update
      653   # DatasetInfo.read_from_directory to possibly restore these attributes
      654   # when reading from package data.
      655   self.info.download_size = dl_manager.downloaded_size
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builder.py:1498, in GeneratorBasedBuilder._download_and_prepare(self, dl_manager, download_config)
     1496 else:
     1497   optional_pipeline_kwargs = {}
  -> 1498 split_generators = self._split_generators(  # pylint: disable=unexpected-keyword-arg
     1499     dl_manager, **optional_pipeline_kwargs
     1500 )
     1501 # TODO(tfds): Could be removed once all datasets are migrated.
     1502 # [https://github.com/tensorflow/datasets/issues/2537](https://github.com/tensorflow/datasets/issues/2537%3C/span%3E)
     1503 # Legacy mode (eventually convert list[SplitGeneratorLegacy] -> dict)
     1504 split_generators = split_builder.normalize_legacy_split_generators(
     1505     split_generators=split_generators,
     1506     generator_fn=self._generate_examples,
     1507     is_beam=isinstance(self, BeamBasedBuilder),
     1508 )
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builders/huggingface_dataset_builder.py:361, in HuggingfaceDatasetBuilder._split_generators(***failed resolving arguments***)
      357 def _split_generators(
      358     self, dl_manager: download.DownloadManager
      359 ) -> Dict[splits_lib.Split, split_builder_lib.SplitGenerator]:
      360   del dl_manager
  --> 361   ds = self._download_and_prepare_for_hf()
      362   return {split: self._generate_examples(data) for split, data in ds.items()}
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builders/huggingface_dataset_builder.py:330, in HuggingfaceDatasetBuilder._download_and_prepare_for_hf(self)
      328 def _download_and_prepare_for_hf(self) -> Mapping[str, Any]:
      329   login_to_hf(self._hf_hub_token)
  --> 330   self._hf_builder.download_and_prepare(
      331       num_proc=self._hf_num_proc,
      332       verification_mode=self._verification_mode,
      333   )
      334   return self._hf_builder.as_dataset(
      335       verification_mode=self._verification_mode,
      336   )
  
  File /opt/conda/lib/python3.10/site-packages/datasets/builder.py:605, in DatasetBuilder.download_and_prepare(self, download_config, download_mode, ignore_verifications, try_from_hf_gcs, dl_manager, base_path, use_auth_token, **download_and_prepare_kwargs)
      603         logger.warning("HF google storage unreachable. Downloading and preparing it from source")
      604 if not downloaded_from_gcs:
  --> 605     self._download_and_prepare(
      606         dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
      607     )
      608 # Sync info
      609 self.info.dataset_size = sum(split.num_bytes for split in self.info.splits.values())
  
  TypeError: GeneratorBasedBuilder._download_and_prepare() got an unexpected keyword argument 'num_proc'Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to /root/tensorflow_datasets/wikitext/wikitext-2-v1/1.0.0...
  Downloading and preparing dataset wikitext/wikitext-2-v1 (download: 4.27 MiB, generated: 12.71 MiB, post-processed: Unknown size, total: 16.97 MiB) to /root/.cache/huggingface/datasets/wikitext/wikitext-2-v1/1.0.0/a241db52902eaf2c6aa732210bead40c090019a499ceb13bcbfa3f8ab646a126...
  ---------------------------------------------------------------------------
  TypeError                                 Traceback (most recent call last)
  Cell In[21], line 5
        1 # preprocessor = keras_nlp.models.BertMaskedLMPreprocessor.from_preset(
        2 #     "bert_tiny_en_uncased"
        3 # )
        4 import tensorflow_datasets as tfds
  ----> 5 ds = tfds.load('huggingface:wikitext/wikitext-2-v1')
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py:169, in _FunctionDecorator.__call__(self, function, instance, args, kwargs)
      167 metadata = self._start_call()
      168 try:
  --> 169   return function(*args, **kwargs)
      170 except Exception:
      171   metadata.mark_error()
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/load.py:640, in load(name, split, data_dir, batch_size, shuffle_files, download, as_supervised, decoders, read_config, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
      521 """Loads the named dataset into a `tf.data.Dataset`.
      522 
      523 `tfds.load` is a convenience method that:
     (...)
      632     Split-specific information is available in `ds_info.splits`.
      633 """
      634 dbuilder = _fetch_builder(
      635     name,
      636     data_dir,
      637     builder_kwargs,
      638     try_gcs,
      639 )
  --> 640 _download_and_prepare_builder(dbuilder, download, download_and_prepare_kwargs)
      642 if as_dataset_kwargs is None:
      643   as_dataset_kwargs = {}
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/load.py:499, in _download_and_prepare_builder(dbuilder, download, download_and_prepare_kwargs)
      497 if download:
      498   download_and_prepare_kwargs = download_and_prepare_kwargs or {}
  --> 499   dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py:169, in _FunctionDecorator.__call__(self, function, instance, args, kwargs)
      167 metadata = self._start_call()
      168 try:
  --> 169   return function(*args, **kwargs)
      170 except Exception:
      171   metadata.mark_error()
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builder.py:646, in DatasetBuilder.download_and_prepare(self, download_dir, download_config, file_format)
      644   self.info.read_from_directory(self._data_dir)
      645 else:
  --> 646   self._download_and_prepare(
      647       dl_manager=dl_manager,
      648       download_config=download_config,
      649   )
      651   # NOTE: If modifying the lines below to put additional information in
      652   # DatasetInfo, you'll likely also want to update
      653   # DatasetInfo.read_from_directory to possibly restore these attributes
      654   # when reading from package data.
      655   self.info.download_size = dl_manager.downloaded_size
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builder.py:1498, in GeneratorBasedBuilder._download_and_prepare(self, dl_manager, download_config)
     1496 else:
     1497   optional_pipeline_kwargs = {}
  -> 1498 split_generators = self._split_generators(  # pylint: disable=unexpected-keyword-arg
     1499     dl_manager, **optional_pipeline_kwargs
     1500 )
     1501 # TODO(tfds): Could be removed once all datasets are migrated.
     1502 # [https://github.com/tensorflow/datasets/issues/2537](https://github.com/tensorflow/datasets/issues/2537%3C/span%3E)
     1503 # Legacy mode (eventually convert list[SplitGeneratorLegacy] -> dict)
     1504 split_generators = split_builder.normalize_legacy_split_generators(
     1505     split_generators=split_generators,
     1506     generator_fn=self._generate_examples,
     1507     is_beam=isinstance(self, BeamBasedBuilder),
     1508 )
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builders/huggingface_dataset_builder.py:361, in HuggingfaceDatasetBuilder._split_generators(***failed resolving arguments***)
      357 def _split_generators(
      358     self, dl_manager: download.DownloadManager
      359 ) -> Dict[splits_lib.Split, split_builder_lib.SplitGenerator]:
      360   del dl_manager
  --> 361   ds = self._download_and_prepare_for_hf()
      362   return {split: self._generate_examples(data) for split, data in ds.items()}
  
  File /opt/conda/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builders/huggingface_dataset_builder.py:330, in HuggingfaceDatasetBuilder._download_and_prepare_for_hf(self)
      328 def _download_and_prepare_for_hf(self) -> Mapping[str, Any]:
      329   login_to_hf(self._hf_hub_token)
  --> 330   self._hf_builder.download_and_prepare(
      331       num_proc=self._hf_num_proc,
      332       verification_mode=self._verification_mode,
      333   )
      334   return self._hf_builder.as_dataset(
      335       verification_mode=self._verification_mode,
      336   )
  
  File /opt/conda/lib/python3.10/site-packages/datasets/builder.py:605, in DatasetBuilder.download_and_prepare(self, download_config, download_mode, ignore_verifications, try_from_hf_gcs, dl_manager, base_path, use_auth_token, **download_and_prepare_kwargs)
      603         logger.warning("HF google storage unreachable. Downloading and preparing it from source")
      604 if not downloaded_from_gcs:
  --> 605     self._download_and_prepare(
      606         dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs
      607     )
      608 # Sync info
      609 self.info.dataset_size = sum(split.num_bytes for split in self.info.splits.values())
  
  TypeError: GeneratorBasedBuilder._download_and_prepare() got an unexpected keyword argument 'num_proc'
</details>

**Short description**
TFDS throws error when downloading wikitext

**Environment information**
Kaggle latest environment
* Operating System: ubuntu
* Python version: 3.10.10
* `tensorflow-datasets` version: 4.9.2
* `tensorflow` version: 2.12.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
Yes
**Reproduction instructions**
```python
import tensorflow_datasets as tfds
ds = tfds.load('huggingface:wikitext/wikitext-2-v1')
```

If you share a colab, make sure to update the permissions to share it.

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
The dataset should download and load properly

**Additional context**

**Comment by sushant0709** [comment]
Hi Anshuman! How to resolve this issue? I am getting the same issue on kaggle notebook.
