### ISSUE TITLE
Load iris dataset failed due to 404

### ISSUE THREAD

**Issue by arti1117** [tensorflow/datasets#4956]
/!\ PLEASE INCLUDE THE FULL STACKTRACE AND CODE SNIPPET

**Description**
Running tfds.load("iris") raises:

```python
[/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/download/downloader.py](https://localhost:8080/#) in _assert_status(response)
    327   """Ensure the URL response is 200."""
    328   if response.status_code != 200:
--> 329     raise DownloadError(
    330         'Failed to get url {}. HTTP code: {}.'.format(
    331             response.url, response.status_code

DownloadError: Failed to get url https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data. HTTP code: 404.
```

**Environment information**
* Operating System: Google Colab
* Python version: 3.10.12
* `tensorflow-datasets` version: 4.9.2
* `tensorflow` version: 2.12.0

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
Yes.

**Reproduction instructions**

```python
import tensorflow_datasets as tfds
iris, iris_info = tfds.load('iris')
```

**Expected behavior**
Load iris dataset successfully.

It seems like same issue as [citrus_leaves raises 404 Error](https://github.com/tensorflow/datasets/issues/2155).

**Comment by ccl-core** [comment]
Hi @arti1117 , thank you for reporting this issue!

commit #4957 32c00bb is now merged which fixes the url in the `iris` dataset. The change will be reflected in `tfds-nightly` in a couple of days max and in `tensorflow-datasets` in the next release.
