### ISSUE TITLE
Have TFDS CLI launch Dataflow jobs per builder config in parallel instead of sequentially

### ISSUE THREAD

**Issue by carlthome** [tensorflow/datasets#4960]
**Is your feature request related to a problem? Please describe.**
We're running `tfds build` on CI to launch Dataflow jobs. When a dataset builder has a lot of builder configs we're hitting the build time limits and need to re-run the CI workflow until completion.

**Describe the solution you'd like**
Since builder configs don't actually depend on each other, it would be nice with a option to `tfds build` for launching all Dataflow jobs at once.

**Describe alternatives you've considered**
We've considered introducing a build matrix with builder configs and having multiple `tfds build` calls but that feels a bit involved. We've also considered requesting a `tfds build --async` flag to only submit but not poll for the jobs to finish, but that seems like a big change with lots of work.

**Comment by fineguy** [comment]
Hi Carl,

Thanks for the suggestion, I hope this will be useful to you https://github.com/tensorflow/datasets/pull/4986

Let me know if it covers your case.
