### ISSUE TITLE
Infering features from tf.data.Dataset

### ISSUE THREAD

**Issue by mhorlacher** [tensorflow/datasets#4993]
`tfds.dataset_builders.store_as_tfds_dataset` offer a convenient way to store a tf.data.Dataset on disk, however, it still requires one to specify the `features` argument. Is there a way to omit this step and directly infer features from the tf.data.Dataset instance?

**Comment by fineguy** [comment]
Hi Marc

Thank you for your suggestion!

It's indeed a desirable feature, but it's very tricky to implement. Unfortunately we can't prioritise it at the moment.

I'm closing this issue, but maybe https://www.tensorflow.org/tfx/data_validation/get_started could help you?
