### ISSUE TITLE
[data request] <caltech birds>

### ISSUE THREAD

**Issue by kyuhuikim** [tensorflow/datasets#4996]
* Name of dataset: <name>
* URL of dataset: <url>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by fineguy** [comment]
Hi there!

Thank you for your request, but could you please provide more details of what you need?

Does any of these datasets suit you:
- https://www.tensorflow.org/datasets/catalog/caltech_birds2010
- https://www.tensorflow.org/datasets/catalog/caltech_birds2011
?
