### ISSUE TITLE
Follow this issue to be notified of release

### ISSUE THREAD

**Issue by rsepassi** [tensorflow/datasets#5]
Hi all, thanks for your interest in `tensorflow/datasets`. We're actively working on the project and hope to release soon with a starter set of datasets. Please follow this issue to be notified of when we have an initial version on PyPI.

We have an alpha nightly release that you can try out: `pip install tfds-nightly`. Please leave feedback through Issues if you try it out. 

If you're interested in contributing a dataset implementation, please feel free to start looking through the [new dataset documentation](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md) and familiarize yourself with the codebase. [`MNIST`](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/mnist.py) might be a good starting point.

**Comment by slerman12** [comment]
This is fantastic! Thank you for building this. Any expected timeline for the release?

**Comment by rsepassi** [comment]
Thanks! We plan to have an initial release either before the holidays or just after.

**Comment by rsepassi** [comment]
You can be an early user of `tensorflow_datasets` with `pip install tfds-nightly` which is a nightly release from HEAD. If you try it out, please do open an issue to give feedback. Thank you!

**Comment by suvarnak** [comment]
Thanks for this library!.
Is there any api to process custom datasets (those which are not in the list, for ex. nonMNIST) with this library? Thanks

**Comment by rsepassi** [comment]
Yes, there is. See our doc on [adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

We also plan on having even easier versions for common dataset types like image classification or text-to-text problems. See [the `ImageLabelFolder` dataset](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/image_folder.py) for our first example for image classification.

Please note that the APIs are unstable at the moment, but we're planning on releasing soon.

**Comment by mr-ubik** [comment]
Should the `tensorflow-datasets` available on PyPi be for the moment removed or be added a warning that `tfds-nightly` is to be used instead? Also removing that indication from the README.md would be ideal since it can mislead into installing the wrong package.

**Comment by rsepassi** [comment]
Thanks @mr-ubik. I've removed the bad releases of `tensorflow-datasets` and will update the README shortly. TF 1.13 now has a [release candidate](https://www.tensorflow.org/versions/r1.13/api_docs/python/tf) and we'll be releasing a stable `tensorflow-datasets` after 1.13 is the stable TF.

**Comment by dynamicwebpaige** [comment]
@mr-ubik - socks incoming. Check your Twitter DMs! 😊

**Comment by Worthy7** [comment]
Came here after a day of struggling trying to get https://www.tensorflow.org/tutorials/images/deep_cnn working, which says to run `pip install tensorflow-datasets` :(

**Comment by rsepassi** [comment]
Yikes, sorry about that. Will release after TF 1.13 is out. You can use
tfds-nightly if you’d like to live on the edge.

**Comment by Worthy7** [comment]
Got it thanks - excited!

**Comment by rsepassi** [comment]
Hi all, `tensorflow-datasets` is now released! `v1.0.0` is now on PyPI. Thanks for waiting, and enjoy! Please leave feedback through GitHub issues, and consider adding a dataset yourself ([guide to add a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md), [current dataset requests](https://github.com/tensorflow/datasets/labels/dataset%20request)).
