### ISSUE TITLE
[data request] GLUE Datasets

### ISSUE THREAD

**Issue by HanGuo97** [tensorflow/datasets#50]
* Name of dataset: GLUE Datasets
* URL of dataset: https://gluebenchmark.com/tasks
* License of dataset:
* Short description of dataset and use case(s): The General Language Understanding Evaluation (GLUE) benchmark is a collection of resources for training, evaluating, and analyzing natural language understanding systems.

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by aayu04** [comment]
Can anybody guide me what exactly to be done here..i am intersted in this issue

**Comment by hamatake** [comment]
I suggest requesting the datasets individually. They each have different license characteristics. Note that SNLI is currently assigned (https://github.com/tensorflow/datasets/issues/20), as is MNLI (https://github.com/tensorflow/datasets/issues/342).

**Comment by Conchylicultor** [comment]
Thank you for your interest. I think glue has already been added recently.
https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/glue.py

Closing this issue as this seems solved.
