### ISSUE TITLE
[nii.gz] <lung>

### ISSUE THREAD

**Issue by wangyan1122** [tensorflow/datasets#5074]
* Name of dataset: <name>
* URL of dataset: <url>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by tomvdw** [comment]
Hey,
Thanks for the request. Could you add some more details on what dataset you'd like? It's currently not clear to me.

**Comment by tomvdw** [comment]
Please reopen the issue when you've added more details.
