### ISSUE TITLE
Best practices for hosting dataset on GCS

### ISSUE THREAD

**Issue by toby-coleman** [tensorflow/datasets#5083]
**What I need help with / What I was wondering**
I've [defined my own custom dataset](https://www.tensorflow.org/datasets/add_dataset), and [saved it to GCS](https://www.tensorflow.org/datasets/gcs) by running
```sh
tfds build my_dataset.py --data_dir gs://my-bucket/datasets
```
This works well and creates files of the form `my-bucket/datasets/my_dataset/default/0.1.0/my_dataset-train.tfrecord-xxxxx-of-yyyyy`.

What I've found is that loading the dataset locally is very slow. For example, if I run
```python
ds = tfds.load("my_dataset", split="test", data_dir="gs://my-bucket/datasets")
data = list(ds.take(1))
```
then I need to wait several minutes, while TFDS appears to download the whole (many GB) dataset from GCS.

My expectation was that calling `ds.take(1)` would only require data from a single shard, and therefore should be fast, or have I misunderstood?

**What I've tried so far**
I've tried adjusting [`ReadConfig`](https://www.tensorflow.org/datasets/api_docs/python/tfds/ReadConfig) to disable auto-cache, but found no improvement.

**It would be nice if...**
Am I doing something wrong here? Or is best practice to cache the data locally rather than reading from GCS all the time.  If so, what is the recommended way to do this for a dataset that is 10s of GB in size?

**Environment information**
* Operating System: `macOS 13.5.2`
* Python version: `3.9.18`
* `tensorflow-datasets`/`tfds-nightly` version: `tensorflow-datasets 4.9.2`
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: `tensorflow 2.12.0`

**Comment by fineguy** [comment]
Hi @toby-coleman, thanks for having an interest in TFDS.

If you want to disable downloading data, simply pass `download=False` to `tfds.load`. 

`tfds.load` is actually a convenience method that wraps multiple steps: https://www.tensorflow.org/datasets/overview#tfdsload. You could instead write:
```
builder = tfds.builder("my_dataset", data_dir="gs://my-bucket/datasets")
ds = builder.as_dataset(split="test")
data = list(ds.take(1))

```
