### ISSUE TITLE
Winogrande checksum changed

### ISSUE THREAD

**Issue by ari9dam** [tensorflow/datasets#5120]
Had to update the checksum file by the following to make it work. "https://storage.googleapis.com/ai2-mosaic/public/winogrande/winogrande_1.1.zip\t3395492\t3619ab104d8be2977b25c90ff420cb42d491707dcc75362a1e5d22bc082b7318\twinogrande_1.1.zip"

**Comment by marcenacp** [comment]
Thanks, I just sent the fix in PR https://github.com/tensorflow/datasets/pull/5123.
