### ISSUE TITLE
CycleGAN datasets not accessible

### ISSUE THREAD

**Issue by apereiroc** [tensorflow/datasets#5134]
I was trying to run the tensorflow cyclegan example, and when running this

```python
dataset, metadata = tfds.load('cycle_gan/horse2zebra',
                              with_info=True, as_supervised=True)
```

I get the following error
```python
DownloadError: Failed to get url https://people.eecs.berkeley.edu/~taesung_park/CycleGAN/datasets/horse2zebra.zip. HTTP code: 404.
```
It is pointing to the following URL, which seems to be down
[https://people.eecs.berkeley.edu/~taesung_park/CycleGAN/datasets/horse2zebra.zip](url)

**Comment by fylux** [comment]
Hi @apereiroc,

You are probably using an older version of TFDS. The broken link was fixed in 
https://github.com/tensorflow/datasets/pull/5084
