### ISSUE TITLE
[data request] <speech_commands>

### ISSUE THREAD

**Issue by Caozq2** [tensorflow/datasets#5141]
* Name of dataset: speech_commands
* URL of dataset: [<url>](https://github.com/tensorflow/datasets/tree/master/tensorflow_datasets/datasets/speech_commands)
* License of dataset: <license type>
* Short description of dataset and use case(s): This is a spoken word audio dataset. We want to train and evaluate the keyword recognition system.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by fylux** [comment]
TFDS already has a dataset named "speech_commands": https://www.tensorflow.org/datasets/catalog/speech_commands

If that's not the one you are referring to, feel free to reopen the bug adding more information about which exact dataset are you looking for.
