### ISSUE TITLE
How to use tff.simulation.datasets.ClientData no argument?

### ISSUE THREAD

**Issue by mohammed-almahi** [tensorflow/datasets#5216]
**What I need help with / What I was wondering**
Your question, or a clear description of what you're looking for help with.
this is my function not working, the error ClientData no argument `
`# Function to create the TFF ClientData object
def create_tff_client_data(client_ids, train_data, feature_columns, target_column):
    return tff.simulation.datasets.ClientData(
        client_ids=client_ids,
        create_tf_dataset_for_client_fn=lambda client_id: (
            tf.data.Dataset.from_tensor_slices(
                {
                    'features': train_data[train_data['client_id'] == client_id][feature_columns].values,
                    'label': train_data[train_data['client_id'] == client_id][target_column].values
                }
            )
        )
    )
**What I've tried so far**
A description of what you've tried so far to solve your problem.

**It would be nice if...**
Could we have done anything to make things better (documentation, etc.)?

**Environment information**
(if applicable)
* Operating System: <os>
* Python version: <version>
* `tensorflow-datasets`/`tfds-nightly` version: <package and version>
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version>

**Comment by pierrot0** [comment]
This issue seems to have nothing to do with TFDS (different than tf.data).
You may want to ask your question on https://discuss.tensorflow.org/tags/c/general-discussion/6/tfdata.

**Comment by mohammed-almahi** [comment]
Thanks to Tensorflow
I have code and two datasets about federated learning for predicting
employee performance but not working well.
I would like to send it to you.
give me permission i will send.
many thanks
