### ISSUE TITLE
[data request] <dataset name>

### ISSUE THREAD

**Issue by Moushumi9medhi** [tensorflow/datasets#5263]
* Name of dataset: NYU Depth Dataset V2

* URL of dataset: http://horatio.cs.nyu.edu/mit/silberman/nyu_depth_v2/bathrooms_part1.zip

I am not able to download this dataset now (which I could years ago). It says the site can't be reached. Any help would be appreciated. Thanks.

**Comment by fineguy** [comment]
Thanks @Moushumi9medhi for reporting this!

TFDS pulls data from a different url: https://github.com/tensorflow/datasets/blob/8f9c889869fd12236e44c04e84362c12385d2277/tensorflow_datasets/datasets/nyu_depth_v2/nyu_depth_v2_dataset_builder.py#L24, which seems to be working. 

Do you experience any problems when running `tfds.load('nyu_depth_v2', split='train')`?

**Comment by Moushumi9medhi** [comment]
Thank you so much. ☺️
