### ISSUE TITLE
mnist access fails when loaded with ArrayRecord-based data source

### ISSUE THREAD

**Issue by mmhamdy** [tensorflow/datasets#5270]
/!\ PLEASE INCLUDE THE FULL STACKTRACE AND CODE SNIPPET

**Short description**
When using `tfds.data_source` to load `mnist`, accessing the dataset fails afterward and I get this error:
```
RuntimeError: Corrupted Riegeli/records file: chunk header hash mismatch (computed 0x36030866f6df5fa8, stored 0xfff399099f0a3bbf), chunk at 19766506; at byte 19766546; Failed to read RiegeliPostscript
```
But `fashion_mnist` works fine.

**Environment information**
* Operating System: Google Colab
* Python version: Google Colab
* `tensorflow-datasets`/`tfds-nightly` version:  `tensorflow-datasets` v4.9.4
* `tensorflow`/`tf-nightly` version: tf was not used

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) ?
Yes, the issue still exists with tfds-nightly.

**Reproduction instructions**

```python
mnist_info = tfds.builder('mnist').info
mnist_ds = tfds.data_source('mnist')
mnist_ds["train"][0] # access fails
```

If you share a colab, make sure to update the permissions to share it.

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
What you expected to happen.

**Additional context**

**Comment by fineguy** [comment]
Thanks @mmhamdy for filing this report!

https://github.com/tensorflow/datasets/pull/5271 should fix this issue.

In the meanwhile you could use this code:
```python
import tensorflow_datasets as tfds
builder = tfds.image_classification.MNIST(file_format='array_record')
builder.download_and_prepare(download_config=tfds.download.DownloadConfig(try_download_gcs=False))
ds = builder.as_data_source()
ds['train'][0]
```

**Comment by mmhamdy** [comment]
Thank you so much, @fineguy
