### ISSUE TITLE
[data request] smallnorb

### ISSUE THREAD

**Issue by Noahsark** [tensorflow/datasets#5336]
Hi,

I just found that the prime source of smallnorb (https://cs.nyu.edu/~ylclab/data/norb-v1.0-small/) is no longer available. Calling builder.download_and_prepare() will cause HTTP code 403. Any idea where else it can be downloaded? 

Thanks

**Comment by ccl-core** [comment]
Hello @Noahsark and thank you for raising this issue!

It seems indeed that the dataset homepage isn't working anymore, affecting all versions hosted on different repos. I sent an email to their webmaster, will keep you posted.

**Comment by ccl-core** [comment]
Hi @Noahsark , I contacted the webmaster who just notified me that the link works again now :)

I'm closing the issue now, feel free to reopen it if you encounter any further issue.
