### ISSUE TITLE
Example serializer doesn't properly raise exception

### ISSUE THREAD

**Issue by njanne19** [tensorflow/datasets#5363]
**Short description**
When following [a tutorial for generating an RLDS dataset](https://github.com/google-research/rlds/blob/main/rlds/examples/rlds_tfds_envlogger.ipynb), I observed that `.tfrecord` files were failing to generate. Upon further investigation, I have found this is because when a `ValueError` is raised in `core.sequential_writer._serialize_example` during a type mismatch, this does not cause the main thread to crash conventionally. 

**Environment information**
* Operating System: Ubuntu 22.04
* Python version: 3.10.14
* `tensorflow-datasets`/`tfds-nightly` version: `tfds-nightly 4.9.4.dev202404120045`
* `tensorflow`/`tf-nightly` version: `tensorflow 2.15.0`

* Does the issue still exists with the last `tfds-nightly` package (`pip install --upgrade tfds-nightly`) : `yes`

**Reproduction instructions**

To reproduce this error, change `reward_info = tf.float64` to `reward_info = tf.int64` in this [RLDS/TFDS example notebook](https://github.com/google-research/rlds/blob/main/rlds/examples/rlds_tfds_envlogger.ipynb). Alternatively, run the code below in a local environment. 

When running locally, the sample code (with `reward_info = tf.float64`), a `.tfrecord` file will generate where specified. When running the same code with `reward_info = tf.int64`, the main process should exit normally and no error will be printed in the console, but you should no longer see a `.tfrecord` file generated. Upon examining with a VSCode debugger, I only then find the ValueError.

```python
import os
import rlds
import envlogger
from envlogger.backends import rlds_utils
from envlogger.backends import tfds_backend_writer
from envlogger.testing import catch_env
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds
import time
from typing import Optional, List

_METADATA_FILENAME='features.json'

def get_ds_paths(pattern: str) -> List[str]:
  """Returns the paths of tfds datasets under a (set of) directories.

  We assume that a sub-directory with features.json file contains the dataset
  files.

  Args:
    pattern: Root directory to search for dataset paths or a glob that matches
      a set of directories, e.g. /some/path or /some/path/prefix*. See
      tf.io.gfile.glob for the supported patterns.

  Returns:
    A list of paths that contain the environment logs.

  Raises:
    ValueError if the specified pattern matches a non-directory.
  """
  paths = set([])
  for root_dir in tf.io.gfile.glob(pattern):
    if not tf.io.gfile.isdir(root_dir):
      raise ValueError(f'{root_dir} is not a directory.')
    print(f'root: {root_dir}')
    for path, _, files in tf.io.gfile.walk(root_dir):
      if _METADATA_FILENAME in files:
        print(f'path: {path}')
        paths.add(path)
  return list(paths)


generate_data_dir='tmp/catch/' # @param
num_episodes= 20 # @param
max_episodes_per_shard = 100 # @param

os.makedirs(generate_data_dir, exist_ok=True)


def record_data(data_dir, num_episodes, max_episodes_per_shard):
  env = catch_env.Catch()

  def step_fn(unused_timestep, unused_action, unused_env):
    return {'timestamp_ns': time.time_ns()}

  ds_config = tfds.rlds.rlds_base.DatasetConfig(
        name='catch_example',
        observation_info=tfds.features.Tensor(
            shape=(10, 5),
            dtype=tf.float32,
            encoding=tfds.features.Encoding.ZLIB),
        action_info=tf.int64,
        reward_info=tf.int64, # CHANGE FROM FLOAT
        discount_info=tf.float64,
        step_metadata_info={'timestamp_ns': tf.int64})

  with envlogger.EnvLogger(
      env,
      backend = tfds_backend_writer.TFDSBackendWriter(
        data_directory=data_dir,
        split_name='train',
        max_episodes_per_file=max_episodes_per_shard,
        ds_config=ds_config),
      step_fn=step_fn) as env:
    print('Done wrapping environment with EnvironmentLogger.')

    print(f'Training a random agent for {num_episodes} episodes...')
    for i in range(num_episodes):
      print(f'episode {i}')
      timestep = env.reset()
      while not timestep.last():
        action = np.random.randint(low=0, high=3)
        timestep = env.step(action)
    print(f'Done training a random agent for {num_episodes} episodes.')

record_data(generate_data_dir, num_episodes, max_episodes_per_shard)
```

**Link to logs**
Here's the value error as seen in the VSCode debugger: https://gist.github.com/njanne19/c49bfcdd950ac6f0107946de32ff6d82

**Expected behavior**
Upon the ValueError, I expect some announcement in the main process to occur, or an exception to be raised. It was extremely difficult to track down this error off the bat, and a datatype mismatch between config and data seems to be a reasonably normal mistake. 

**Additional context**
The `_serialize_example` function definition does have an `except` block on `Exception` that instructs `py_utils.reraise` to be called. 
https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/sequential_writer.py#L43-L46

However, I'm much less familiar with this section of the codebase, and from what I can tell, it's not functioning properly in this scenario. This behavior I listed above could be expected in the event that I am not properly handling re-raised exceptions, although it doesn't seem like that is the case. I would love some input in case my sample code provides any evidence that I'm not handling my workflow correctly.

**Comment by fineguy** [comment]
Thanks for reporting this issue! 

I tried running the Colab and it threw an error:
<img width="851" alt="Screenshot 2024-04-17 at 10 59 32" src="https://github.com/tensorflow/datasets/assets/6347460/dff4f907-0af1-4241-b9bb-3b861ece3a77">

I also tried running your script, which also fails with an error:
<img width="1116" alt="Screenshot 2024-04-17 at 11 01 04" src="https://github.com/tensorflow/datasets/assets/6347460/1a97dfa6-efad-42b4-a47e-327001af4995">

This matches your desired behavior, so could you please provide a reproducible setup for this error?

**Comment by njanne19** [comment]
Thanks for the response. I've tried following my own re-creation instructions a few times and am no longer observing this behavior following your comment, and haven't been able to observe the same behavior. Given your similar observation I'm going to close this issue and chalk it up to something I must have missed the first time around. Apologies!
