### ISSUE TITLE
[data request] Indian Numerals Dataset (cmaterdb)

### ISSUE THREAD

**Issue by prabhuomkar** [tensorflow/datasets#540]
* Name of dataset: Indian Numerals Datasets (cmaterdb)
* URL of dataset: https://code.google.com/archive/p/cmaterdb/downloads
* License of dataset: Apache License 2.0
* Short description of dataset and use case(s): CMATERdb is the pattern recognition database repository created at the ‘Center for Microprocessor Applications for Training Education and Research’ (CMATER) research laboratory, India. They have a series of datasets released which includes Handwritten numeral+character database for Indian regional languages.
This dataset can be used for classification and has a similar scope like MNIST.
**I want to contribute to this repository with their _Handwritten Telugu, Bangla, Devanagari Numeral_ dataset.**

PS: There are lot of papers using Indian Numerals Dataset, I feel this should definitely be in this repository :)

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

**Comment by prabhuomkar** [comment]
Hey @cyfra I would like to contribute to this!

**Comment by ChanchalKumarMaji** [comment]
Kannada - MNIST
https://github.com/vinayprabhu/Kannada_MNIST
https://arxiv.org/abs/1908.01242

**Comment by cyfra** [comment]
Fixed in #562
