### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by xmak9102** [tensorflow/datasets#5414]
### Environment description
- Ubuntu 24.04 
* Python 3.10
+ `tensorflow` 2.16

I first installed the package via pip
```
pip install tensorflow-datasets
```
Also tried
```
pip install tfds-nightly
```
Same Error occur
>Building wheels for collected packages: promise
    Building wheel for promise (setup.py) ... error
    error: subprocess-exited-with-error    
    × python setup.py bdist_wheel did not run successfully.
    │ exit code: 1
    ╰─> [84 lines of output]
        running bdist_wheel

> AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]

>  note: This error originates from a subprocess, and is likely not a problem with pip.
      ERROR: Failed building wheel for promise
      Running setup.py clean for promise
    Failed to build promise
    ERROR: Could not build wheels for promise, which is required to install pyproject.toml-based projects

#### When I tried 
```
git clone https://github.com/tensorflow/datasets.git
cd datasets
pip install -e .
```
Package is already installed and same thing happened
>    File "/home/mak9102/py_env/skeleton310/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]
  
  >note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for promise
  Running setup.py clean for promise
Successfully built tensorflow-datasets
Failed to build promise
ERROR: Could not build wheels for promise, which is required to install pyproject.toml-based projects

But running `import tensorflow_datasets as tfds` is not likely to work 
> ModuleNotFoundError                       Traceback (most recent call last)
Cell In[14], line 1
----> 1 import tensorflow_datasets

>File ~/py_env/working_space/skeleton310/datasets/tensorflow_datasets/__init__.py:43
     41 _TIMESTAMP_IMPORT_STARTS = time.time()
     42 from absl import logging
---> 43 import tensorflow_datasets.core.logging as _tfds_logging
     44 from tensorflow_datasets.core.logging import call_metadata as _call_metadata
     46 _metadata = _call_metadata.CallMetadata()

>File ~/py_env/working_space/skeleton310/datasets/tensorflow_datasets/core/__init__.py:20
     16 """API to define datasets."""
     18 # Allow to use `tfds.core.Path` in dataset implementation which seems more
     19 # natural than having to import a third party module.
---> 20 from etils.epath import Path
     22 from tensorflow_datasets.core import community
     23 from tensorflow_datasets.core.dataset_builder import BeamBasedBuilder

>ModuleNotFoundError: No module named 'etils'

**Comment by pierrot0** [comment]
Hi, I am sorry but this doesn't look like a TFDS problem, more like a pip packaging error (from Ubuntu?). Maybe https://github.com/pypa/pip/issues/10857 can give you a pointer.

Things seem to work fine on my side:
```
$ python3 -m venv ~/dev/venv_5414
$ source ~/dev/venv_5414/bin/activate
(venv_5414) $ pip install tensorflow-datasets
(venv_5414) $ pip install ipython
(venv_5414) $ ipython3
Python 3.11.8 (main, Feb  7 2024, 21:52:08) [GCC 13.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.24.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import tensorflow_datasets as tfds
In [2]: tfds.__version__
Out[2]: '4.9.4'
```
