### ISSUE TITLE
etils.epy.lazy_imports not found

### ISSUE THREAD

**Issue by hhoppe** [tensorflow/datasets#5448]
When running the import of version 4.9.5,
it complains that etils.epy.lazy_imports() is not found.
My version of etils is 1.7.0.
(etils==1.9.0 would require Python 3.11 and I still have Python 3.10.)
Importing version 4.9.4 works fine --- I notice it is also the current default in Colab.

**Comment by marcenacp** [comment]
etils recently dropped support for Python 3.10 (following the [calendar for scientific packages](https://scientific-python.org/specs/spec-0000/)). Could you migrate to Python 3.11?

**Comment by hhoppe** [comment]
@marcenacp 
Is "you" referring to me or to `tensorflow-datasets` (which still only requires Python 3.10)?

From the [calendar for scientific packages](https://scientific-python.org/specs/spec-0000/):

> Support for Python versions be dropped 3 years after their initial release.

However, Python 3.10 was released less than 3 years ago: October 4, 2021.

(Note that https://colab.research.google.com/ still runs Python 3.10.)

**Comment by marcenacp** [comment]
TFDS supports 3.10, 3.11 and [very soon](https://github.com/tensorflow/datasets/commit/aa6205f6001f79f2f7045d08cf514ef2e0b4adff) 3.12. The GitHub Actions run for all versions in the CI. So it should also work.

What do you have on https://colab.research.google.com when you run:

```
!pip install --upgrade tensorflow_datasets
import etils
import tensorflow_datasets as tfds
print(etils.__version__)
print(tfds.__version__)
```

**Comment by hhoppe** [comment]
Darn, I'm unfortunately not able to reproduce the problem anymore with `tensorflow_datasets==4.9.5`.
The error was definitely `lazy_imports` not found in `epy` but I can't recreate it.
Sorry about the bother.

**Comment by marcenacp** [comment]
No worries, also we'll keep in mind that Colab still runs Python 3.10 before deprecating 3.10. Thanks!
