### ISSUE TITLE
[pubmed] <scientific_papers>

### ISSUE THREAD

**Issue by mahnoor-farhat** [tensorflow/datasets#5476]
* Name of dataset: <scientific_papers>
* URL of dataset: <https://www.tensorflow.org/datasets/catalog/scientific_papers#scientific_paperspubmed>
* License of dataset: <license type>
* Short description of dataset and use case(s): <PubMed is a free resource supporting the search and retrieval of biomedical and life sciences literature with the aim of improving health–both globally and personally.
 The PubMed database contains more than 37 million citations and abstracts of biomedical literature. It does not include full text journal articles; however, links to the full text are often present when available from other sources, such as the publisher's website or [PubMed Central (PMC)](https://www.ncbi.nlm.nih.gov/pmc/about/intro/)>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by fineguy** [comment]
@mahnoor-farhat thanks for opening this issue! 

Could you please clarify what you want TFDS to do?
