### ISSUE TITLE
Unregister Dataset for problem ValueError: Dataset with name x already registered.

### ISSUE THREAD

**Issue by NumesSanguis** [tensorflow/datasets#552]
**Is your feature request related to a problem? Please describe.**
I want to create a new dataset using `DatasetBuilder` and I'm using Jupyter Notebook to interactively write my class for `tfds.core.GeneratorBasedBuilder`. It's frustrating that if I execute the cell with that class more than 1 time, I will get the error: `ValueError: Dataset with name my_dataset already registered.` This slows down the creation of a new Dataset.

**Describe the solution you'd like**
I would like to have an `unregister_dataset()` function, which can be used like:

```
ds_name = "my_dataset"
try:
    tfds.core.unregister_dataset(ds_name)
except:
    print(f"Dataset with name '{ds_name}' not registered")
```

**Describe alternatives you've considered**
Restart kernel of the Jupyter Notebook each time and run all cells again. However, this completely removes the interactive aspect of developing with Jupyter Notebook, and therefore slowing down the development of a new Dataset.

**Additional context**
DatasetBuilder class:

```
# data access class
class MyDataset(tfds.core.GeneratorBasedBuilder):
  """TODO(my_dataset): Short description of my dataset."""

  # TODO(my_dataset): Set up version.
  VERSION = tfds.core.Version('0.1.0')

  def _info(self):
    # TODO(my_dataset): Specifies the tfds.core.DatasetInfo object
    return tfds.core.DatasetInfo(
        builder=self,
        # This is the description that will appear on the datasets page.
        description=_DESCRIPTION,
        # tfds.features.FeatureConnectors
        features=tfds.features.FeaturesDict({
            # These are the features of your dataset like images, labels ...
        }),
        # If there's a common (input, target) tuple from the features,
        # specify them here. They'll be used if as_supervised=True in
        # builder.as_dataset.
        supervised_keys=('audio', 'label'),
        # Homepage of the dataset for documentation
        urls=[],
        citation=_CITATION,
    )

  def _split_generators(self, dl_manager):
    """Returns SplitGenerators."""
    # TODO(my_dataset): Downloads the data and defines the splits
    # dl_manager is a tfds.download.DownloadManager that can be used to
    # download and extract URLs
    return [
        tfds.core.SplitGenerator(
            name=tfds.Split.TRAIN,
            # TODO(my_dataset): Tune the number of shards such that each shard
            # is < 4 GB.
            num_shards=10,
            # These kwargs will be passed to _generate_examples
            gen_kwargs={},
        ),
    ]

  def _generate_examples(self):
    """Yields examples."""
    # TODO(my_dataset): Yields examples from the dataset
    yield {}
```

Already registered error when executing the cell more than 1 time:

```
ValueError                                Traceback (most recent call last)
<ipython-input-9-a3e52fd35190> in <module>
      1 # data access class
----> 2 class MyDataset(tfds.core.GeneratorBasedBuilder):
      3   """TODO(my_dataset): Short description of my dataset."""
      4 
      5   # TODO(my_dataset): Set up version.

/usr/local/lib/python3.5/dist-packages/tensorflow_datasets/core/registered.py in __new__(mcs, cls_name, bases, class_dict)
    113 
    114     if name in _DATASET_REGISTRY:
--> 115       raise ValueError("Dataset with name %s already registered." % name)
    116     if name in _IN_DEVELOPMENT_REGISTRY:
    117       raise ValueError(

ValueError: Dataset with name my_dataset already registered.
```

**Comment by Conchylicultor** [comment]
Thanks for reporting, I agree this is an issue. We are going to work to improve the colab workflow

**Comment by rodrigob** [comment]
Any update on this front ?

**Comment by Conchylicultor** [comment]
We did not have time yet. An easy solution would be to add a SKIP_REGISTERING property to `DatasetBuilder`, and then check it in register.py ([here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/registered.py#L114)):

```
class MyDataset(tfds.core.GeneratorBasedBuilder):
  SKIP_REGISTERING = True
```
Don't hesitate to send a PR if you have time.

**Comment by dhirensr** [comment]
@Conchylicultor : I am working on this! how do I test this after adding this feature?

**Comment by Conchylicultor** [comment]
@dhirensr  Thank you for looking into this. For testing, ddd your test in https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/registered_test.py
Create a dataset with this SKIP_REGISTER property and check in a test that this dataset hasn't been added into the register _DATASET_REGISTRY.

**Comment by dhirensr** [comment]
@Conchylicultor : thank you for your reply.
I had 2 doubts : should I directly create a new instance of class tfds.core.GeneratorBasedBuilder or EmptyDatasetBuilder is doing that? and after the instance how do I call registered.RegisteredDataset class object?
I think the test does not create an instance of registered.RegisteredDataset class .

**Comment by Conchylicultor** [comment]
Just creates another `class SkipRegistering(EmptyDatasetBuilder):`. The registration is done automatically when the class is declared (using Python `__metaclass__`).

Once declared, you can the class are accessible through `load`, like in `registered.load('empty_dataset_builder')`: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/registered_test.py#L116

**Comment by dhirensr** [comment]
@Conchylicultor : I have tried to fix according to what you said but the test is failing! can you guide me by reviewing the PR https://github.com/tensorflow/datasets/pull/1049 so that I can fix it completely.
Thanks a lot.

**Comment by Conchylicultor** [comment]
Thank you all for your contributions. After discussion internally, we decided to allow register overwriting automatically when running in a colab environment.

So this should be completely transparent for the user. The same class declaration can be run twice when running on Jupyter Notebook, and will overwrite the previous dataset.

So this should solve this issue if you're running after https://github.com/tensorflow/datasets/pull/1092.

**Comment by vijayphoenix** [comment]
Fixed by PR #1092.
Can be closed.

**Comment by mac133k** [comment]
Why the solution from PR https://github.com/tensorflow/datasets/pull/1092 is only supposed to work in Jupyter Notebook? I run my interactive sessions in text environment via ipython console (IPython 8.3.0 with Python 3.10.6), so obviously this check fails:
```
In [105]: from tensorflow_datasets.core.utils import py_utils

In [106]: py_utils.is_notebook()
Out[106]: False
```
Therefore the original error still occurs.
Can there be an additional check added? If not is there a workaround for this, ie. some way to force the deregistration without the need to reload the current session?

**Comment by mac133k** [comment]
OK, I found a workaround: the registry is a dictionary, so it is possible to deregister a dataset by removing a corresponding item from the dictionary, ie.:
error:
```
ValueError: Dataset with name my_dataset already registered.
```
fix:
```
del tfds.core.registered._DATASET_REGISTRY['my_dataset']
```
