### ISSUE TITLE
caltech_birds2011 url has changed.

### ISSUE THREAD

**Issue by h-0-0** [tensorflow/datasets#5544]
Hi, the Caltech-UCSD Birds 200 (CUB-200) dataset is now stored on a different website:
https://data.caltech.edu/records/65de6-vp158

Which causes errors when trying to download when doing checksums. So the URL needs to be changed along with checksum. 

Was wondering if someone could fix? I imagine should be pretty straightforward.

**Comment by fineguy** [comment]
Thanks for letting us know! 

I updated the homepage in https://github.com/tensorflow/datasets/pull/5547

As for the errors during download – they're probably coming from the Google Drive forced warning page (for larger files it warns that they're not scanned for viruses). You can bypass it by manually downloading the data following the urls in the dataset builder code.
