### ISSUE TITLE
[data request] <dataset name>defect engineering of photocatalyst

### ISSUE THREAD

**Issue by AISEN312** [tensorflow/datasets#5681]
* Name of dataset: <name>
* URL of dataset: <url>
* License of dataset: <license type>
* Short description of dataset and use case(s): <description>

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by fineguy** [comment]
Hi @AISEN312 ! Could you please clarify what dataset you're requesting?

**Comment by AISEN312** [comment]
solar to chemical conversion rates, synthesis method, synthesis time, dopants, water splitting,photocatalytic activity,defect concentration ,all of this should be included

**Comment by fineguy** [comment]
@AISEN312 I'm not familiar with this dataset, do you have a link to its homepage?
