### ISSUE TITLE
[data request] EMNIST

### ISSUE THREAD

**Issue by alexalemi** [tensorflow/datasets#58]
* Name of dataset: EMNIST
* URL of dataset: https://www.westernsydney.edu.au/bens/home/reproducible_research/emnist
* License of dataset: Unknown, but from the same NIST sources originally as MNIST.
* Short description of dataset and use case(s): EMNIST is an extended MNIST dataset using the same processing and normalization techniques as MNIST itself on a superset of the original NIST images.  This includes six splits, including not only a larger 280k MNIST digit equivalent, but also a 814k handwritten digit and letter dataset. For more information and details see: Cohen, G., Afshar, S., Tapson, J., & van Schaik, A. (2017). EMNIST: an extension of MNIST to handwritten letters. Retrieved from http://arxiv.org/abs/1702.05373

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by ShilpaSangappa** [comment]
I would like to work on adding this dataset. 
Can you please assign this to me?

**Comment by cyfra** [comment]
Great - @ShilpaSangappa - please accept collaborator invite

**Comment by ShilpaSangappa** [comment]
Collaborator invite accepted. Thanks.

**Comment by ShilpaSangappa** [comment]
The URL for dataset, as also mentioned in the EMNIST paper is:
https://www.westernsydney.edu.au/bens/home/reproducible_research/emnist

But, here in the first comment, the URL is mentioned as:
https://www.nist.gov/srd/nist-special-database-19

I checked the mnist.py file and see that the URL and citations are for Yann LeCun, et al. and not NIST.
I assume, the same applies for EMNIST. 

Kindly clarify.

**Comment by alexalemi** [comment]
I've updated the first comment.  It appears https://www.westernsydney.edu.au/bens/home/reproducible_research/emnist is now the official link for the dataset.  The arxiv paper: https://arxiv.org/abs/1702.05373 changed the link from v1 to v2 and added the following comment to their submission: 

> The dataset is now available for download from [this https URL](https://www.westernsydney.edu.au/bens/home/reproducible_research/emnist). This link is also included in the revised article

The url in the original paper was: https://www.nist.gov/itl/iad/image-group/emnist-dataset
This url didn't have working download links a couple weeks ago but appears to be working now.

Both this dataset, the EMNIST dataset and the original MNIST dataset are processed versions of the NIST dataset: https://www.nist.gov/srd/nist-special-database-19

This request is to specifically add EMNIST, a processed version of NIST, processed in a way consistent with the original MNIST.

**Comment by ShilpaSangappa** [comment]
Thanks for the clarifications and updations.

**Comment by us** [comment]
Sorry everyone for I really couldn't see assigned.

**Comment by ShilpaSangappa** [comment]
@us , Are you working on adding EMNIST dataset?

**Comment by us** [comment]
@ShilpaSangappa yeap I added it, this pr #198

**Comment by us** [comment]
@cyfra emnist added, we can close that issue.
