### ISSUE TITLE
register_checksums with external datasets

### ISSUE THREAD

**Issue by jackd** [tensorflow/datasets#580]
It would be nice to be able to develop a dataset outside of this package but still use automatic statistics generation, pre-shuffling, sharding etc in the builder classes without having write-access to the tfds directory itself. As far as I can tell, this is currently impossible without serious hacking due to the checksum registration process. One can either choose to register checksums which requires write-access to the tfds.checksums folder, or check against previously stored values, which presumably requires write-access at some point in the past).

Would a third option be welcome? Maybe an `ignore_checksums` option in `DownloadManager`, or a customizable `checksums` directory/path?

**Comment by EternalMoment** [comment]
I have a similar issue. I have a private dataset with restricted license. I have finished all the code for setting up tfds pipeline, but got stuck on the checksum error. Could I use tfds for ETL without merging it into tfds?

**Comment by jackd** [comment]
On closer inspection, this seems to be resolved in the master branch. If you're stuck using older versions (or want to stick to the official releases), you can do the following slightly dirty hack. 

```python
def append_checksum_dir(checksum_dir):
  tfds.core.download.checksums._CHECKSUM_DIRS.append(checksum_dir)
  tfds.core.download.checksums._checksum_paths.cache_clear()
```

**Comment by pierrot0** [comment]
It would make sense to be able to setup alternative checksums directories.
There are a few possible options:
 1- Search for `url_checksums` directories next to dataset definitions (maybe too much magic involved).
 2- Have an environment variable to specify additional checksums directories.
 3- Have a method to add additional checksum directories, which each dataset can use .

3 sounds nice to me. We should also document the full process of defining datasets outside of the library.

**Comment by pierrot0** [comment]
jackd@ could you maybe re-open the issue?

**Comment by jackd** [comment]
@pierrot0 have you tried the nightly version? I haven't looked into it since I resolved it for my use case, but from what I recall when I was looking into it checksums are handled very differently compared to the stable pip version, and I'm not sure it's still an issue.

**Comment by SamuelMarks** [comment]
Surprisingly, updating the [`_sizes_checksums`](https://github.com/tensorflow/datasets/blob/v2.1.0/tensorflow_datasets/core/download/download_manager.py#L241-L243) dictionary of the [`tfds.download.DownloadManager`]( https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadManager) is sufficient here:
https://github.com/SamuelMarks/ml_prepare/blob/d81a625/ml_prepare/refuge/tfds.py#L82-L97

(not documented usage, and subject to change as it uses a `_` prefixed method)
