### ISSUE TITLE
[data request] Yelp Polarity Review

### ISSUE THREAD

**Issue by ksboy** [tensorflow/datasets#583]
* Name of dataset: Yelp Polarity Review
* URL of dataset: https://s3.amazonaws.com/fast-ai-nlp/yelp_review_polarity_csv.tgz
* License of dataset: No license specified, the work may be protected by copyright.
* Short description of dataset and use case(s): **Yelp Polarity Review** is a classical dataset for sentiment analysis, which is proposed by Xiang Zhang in Paper "Character-level Convolutional Networks for Text Classification", including a set of 560,000 highly polar yelp reviews for training, and 38,000 for testing.

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by Eshan-Agarwal** [comment]
Hey ! is this is open now for add mentioned data set ?

**Comment by Conchylicultor** [comment]
This has been merged, so can be closed.
