### ISSUE TITLE
Create a CHANGELOG to help users know of new datasets that are added

### ISSUE THREAD

**Issue by 00krishna** [tensorflow/datasets#584]
**Is your feature request related to a problem? Please describe.**

Tensorflow Datasets is a great package and very much needed. One challenge I noticed was that it is hard to determine when new datasets are added. There are a large number of dataset pull requests in various stages of approval, etc. So I expect that there will be new datasets released at any time. Right now the only way for me to find out if a new dataset has been added is to look at the Github page for the list of datasets, but I am not certain this is updated each time a new dataset is added. There is also `tfds.list_builders()` command, but that command does not indicate when new datasets were added. 

So it is just rather difficult to understand when new dataset are added to the system.
**Describe the solution you'd like**
There are a couple of different ways that this could be solved. The first idea is just a simple CHANGELOG.txt on the github page that is updated when new datasets are added. That would be really useful and a single source of dataset updates.

A CHANGELOG is such a simple solution, but I thought it might be the easiest to implement.

**Describe alternatives you've considered**
The second way might be to add additional metadata to the `tfds.list_builders()` function, so that users can sort that list by date added or other factors. You could even make the `tfds.list_builders()` output a pandas dataframe instead of a list--hopefully without too much trouble. Then that would allow users to sort based upon metadata about the datasets. 

**Additional context**
No additional context provided.

**Comment by us** [comment]
Where do you install the package pip or repo ? If you using pip version of `tensorflow-datasets`, pip couldn't install the last version of repo, it's just install the last release for example now 1.0.2 release. New datasets will be available in the next release. Please try to install from repo.

Clone repo then 
`python setup.py install`

**Comment by 00krishna** [comment]
@us So are you saying that whenever a new dataset is added to `tensorflow-datasets` that the release number is updated? In just looking at the issue list, I don't think that is accurate. Don't get me wrong, I appreciate all of the work that the `tensorflow-datasets` team is doing. This is really just a usability issue that helps users take advantage of the package. 

Here are 2 datasets that have been apparently added--since the issues are closed. Yet the README.md or list of datasets has not been updated to reflect the addition. 

Discofuse dataset
https://github.com/tensorflow/datasets/issues/490

Moist digits
https://github.com/tensorflow/datasets/issues/394

The EMNIST and KMNIST datasets were added subsequent to the initial release of the `tensorflow-datasets` package, yet there is no way to know this unless you did a `diff` on the list of datasets. That is why I am requesting some sort of changelog so that users can know what is actually available versus what is not. _As the list of datasets gets longer and longer, it is going to get harder to see which datasets were recently added, etc._ 

So this does not need to be a changelog in any formal sense. But there should be some record of when new datasets are added or changed. A dated list of changes at the bottom of the README would work too.

**Comment by us** [comment]
@00krishna No I did not want to say that. I want to say `tensorflow-datasets` thats's on the pip packages  not updated every time. It's just updated new releases. So adding datasets that are added after release, not installed until the new release with pip.

These two datasets were closed because the pull request was sent but the pr still being reviewed so not added yet. Discofuse dataset #439 pr and I think the other dataset issue closed wrongly and we'll open again.

The list of datasets generated by script and we didn't updated every time but need to updated. I will add the adding dataset guide.

Thanks for feedback.

**Comment by 00krishna** [comment]
Ahhh, so this makes a lot more sense. Thanks for the clarifications. I should clone the library and install it instead of using `pip`. So I can do that from now on. That makes a lot more sense. 

Thanks for the clarification on the other two datasets as well, Discofuse and Moist digits.

Yes, just to reiterate I think that this `tensorflow datasets` project is really excellent. Having a quick way to import common datasets is really wonderful, and I expect the project to grow very quickly. From the user perspective there were just different signals in the README versus the github issues, etc., So that was making it a bit confusing. Anything you can do to help clarify the process for adding datasets or the schedule for adding them, etc. would be helpful on the user side. 

Once again, keep up the good work. I guess we can close this issue and open new ones for specific updates to the adding datasets guide? Or let me know what you prefer.

**Comment by Conchylicultor** [comment]
I agree keeping tracks of the new features & datasets would be good.
I've started some release notes that we're going to try to keep them updated..
https://github.com/tensorflow/datasets/blob/master/docs/release_notes.md

**Comment by vijayphoenix** [comment]
This can be closed as the catalog now indicates which datasets are available only in `tfds-nightly`.

**Comment by Conchylicultor** [comment]
I still need to update the table of content to display the nightly icon on the menu. Hopefully this should be done by tomorrow.

**Comment by Conchylicultor** [comment]
Closing this. Now the future datasets added will be marked explicitly on the website.
