### ISSUE TITLE
`_make_download_manager` appends `self.name` to `manual_dir`

### ISSUE THREAD

**Issue by jackd** [tensorflow/datasets#587]
`DatasetBuilder._make_download_manager` appends `self.name` to `manual_dir`. I understand the motivation when using the default `manual_dir`, but when one is supplied in the input `download_config` this introduces an uneccessary file structure constraint on the user (directory on disk must have same name as builder).

Relevant code is [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/dataset_builder.py#L541)

```python
    manual_dir = (download_config.manual_dir or
                  os.path.join(download_dir, "manual"))
    manual_dir = os.path.join(manual_dir, self.name)
```

Could this be changed to
```python
    manual_dir = (download_config.manual_dir or
                  os.path.join(download_dir, "manual", self.name))
```

Arguably this is a design choice I disagree with rather than a bug, but I fail to see the original motivation. By implementing this change, users can keep the same file structure and smiply append `self.name` to the `DownloadConfig` they create. Modifying it would be a breaking change for existing implementations with specified `manual_dir`s, hence this issue rather than a PR.

**Comment by us** [comment]
What's the difference the `manual_dir = os.path.join(manual_dir, self.name)` and your offer ? I didn't fully understand.

**Comment by jackd** [comment]
@us that would achieve the current behaviour, so porting to the proposed new version would be straight-forward.

However, consider the situation where I have data at `/datasets/imagenet_data`. If I use `manual_dir=/datasets/imagenet_data`, `tfds` will look for files in `datasets/imagenet_data/imagenet2012` - a directory which likely doesn't exist. Sure I could create a link to the relevant folder, but that kind of defeats the purpose of a customisable `manual_dir`.

**Comment by Flamefire** [comment]
I'm also affected by that. We have a shared download of the ImageNet2012 dataset on the cluster and it is really hard to use (and impossible with currently released TF_datasets 1.3 due to #1075)

**Comment by Conchylicultor** [comment]
That would make sense to allow sharing `manual_dir` between different datasets.

If you send a PR for this, please also update the `download_and_prepare.py` script to set `manual_dir=os.path.join(FLAGS.manual_dir, builder.info.name)` for backward compatibility: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/scripts/download_and_prepare.py#L119

An alternative solution is for the user to create a symlink `<manual_dir>/<ds_name>` -> `<manual_dir>/imagenet2012 `. This won't require changes, but isn't really user friendly

**Comment by dhirensr** [comment]
@Conchylicultor  : I am working on this ,will send a PR this weekend.

**Comment by vijayphoenix** [comment]
This can be closed.
See PR https://github.com/tensorflow/datasets/pull/1599
