### ISSUE TITLE
[Question] - Would it be okay to generate tfrecords from downloaded/pre-downloaded dataset ?

### ISSUE THREAD

**Issue by ksachdeva** [tensorflow/datasets#6]
Hi,

Thanks for this package; its look really good.

I have a question regarding the optimal workflow and usage of this package for below mentioned scenario :

Let's say that there is a very large database (20+ GBs) of images (and access is password protected). In the tensorflow ecosystem it is recommended to use tfrecords to consolidate the labels and data and speed up training etc so this data needs to be converted to tfrecords.

Since it is 20+ GB and password protected I would tend to think that automatic download would not be recommended and hence this library provides a way to specify the folder.

However, since original dataset needs to be converted to tfrecords first -:

Would you suggest that the conversion (to tfrecords) is done as part of this library (sub classes) or should it be a separate step (equivalent to manual downloading of images)

Regards
Kapil

**Comment by rsepassi** [comment]
Hi Kapil,

We recommend setting up that dataset such that the user is expected to first manually download the password-protected data into a directory and then specify that directory as `manual_dir` when calling `builder.download_and_prepare`. The builder would then expect the data to be in `manual_dir` and convert it to TFRecord files.

The [`diabetic_retinopathy_detection`](https://github.com/tensorflow/datasets/blob/f2bb27c729e18fd57e40e7f90fd8c4df81cbbdef/tensorflow_datasets/image/diabetic_retinopathy_detection.py#L53) dataset is an example of a dataset that does that.

Please do open up an issue or PR if you'd like to contribute a dataset like that. Thanks!

@pierrot0 FYI
