### ISSUE TITLE
Downloader Kaggle Extension Wrong Prefix

### ISSUE THREAD

**Issue by us** [tensorflow/datasets#623]
**Short description**
`kaggle.KaggleFile.is_kaggle_url` checks the url, but it's check just a `_URL_PREFIX = "kaggle://"`. That url prefix is wrong because kaggle hasn't got any url like this. So that extension will not working with kaggle api, it downloading with `requests` lib on `dl_manager`.

**Expected behavior**
Should correctly check the kaggle url, working with kaggle api, not with `requests` lib.

**Comment by Conchylicultor** [comment]
This is a custom uri which allow to use the same API than with other urls. I agree this is badly documented, and do not seems to be used anywhere. Usage is:

```
out = dl_manager.download('kaggle://some-competition/a.csv')
```

**Comment by us** [comment]
So is it just a tag for understanding kaggle url for `dl_manager.download` and then downloading with `kaggleDownloader` ?

**Comment by Conchylicultor** [comment]
Yes, exactly. It allow to use the same API as other files, like: `dl_manager.download_and_extract('kaggle://some-competition/train.zip')`.

**Comment by us** [comment]
Okay I got it. Thanks!
