### ISSUE TITLE
ucf101 dataset load fail

### ISSUE THREAD

**Issue by huhuta** [tensorflow/datasets#625]
**Short description**
ucf101 dataset loads fail because ucf101_labels.txt not found in site-packages

code
```
import tensorflow_datasets as tfds
tfds.load(name="ucf101")
```

output
```
.../site-packages/tensorflow_datasets/video/ucf101_labels.txt; No such file or directory
```

I fixed by download labels.txt file
```
wget https://raw.githubusercontent.com/tensorflow/datasets/master/tensorflow_datasets/video/ucf101_labels.txt
```

**Environment information**
* Operating System: ubuntu18.04
* Python version: 3.6
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets==1.0.2
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow==1.13.1

**Reproduction instructions**

```
import tensorflow_datasets as tfds
tfds.load(name="ucf101")
```

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
labels.txt already exist in site-packages when pip install tensorflow-datasets

**Additional context**

**Comment by ChanchalKumarMaji** [comment]
Thanks, for reporting this. For now download this file from [here](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/video/ucf101_labels.txt) and put this in the `video` folder.

**Comment by Conchylicultor** [comment]
This should be fixed in the next nightly release thanks to Chanchal PR
