### ISSUE TITLE
Direct ondrive url (for Resisc45)

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#631]
Currently, Resisc45 require to manually download the data because TFDS do not support RAR file extraction.

By adding RAR file extraction to TFDS, it may unlock direct download for this dataset.

If so, we should use it and also update the checksum Resisc45 file.

**Comment by us** [comment]
I download `public.dm.files.1drv.com` link with wget. Please check this [link](https://public.dm.files.1drv.com/y4mSB3ExPYvRfpcX--fqdrdx5hAoKvVJ_xRjlpZlP2CAa2etDRR9N3r4xxuW_SyBSEkYvvPe2RUpr1RTvWoeOuI3ZnDT7hnaJLtxrKm88_CJ6FMK2tu1_9bOEo3T6A_AXc1TBavYfsDmwatqp8FgpK-2MOfTasSF3N5au2Q8B3cCubsA8NnMe7Lt56hW1g-Yd_SgruI-b0jFJgNQAlW6clPeg/NWPU-RESISC45.rar?access_token=EwAQA61DBAAUcSSzoTJJsy%2bXrnQXgAKO5cj4yc8AAVIgJS%2fofAeBCDnlogoBw%2f5JmopE80cn3Ag%2for5qUWNP4xth6vSxL3218uOYVHHqvnA%2fUNj454HpWQDtptU%2br8gC5A5HOHrwJvYOyTrCJoNY7OAmRUXVxASrG0IvxHlFrgV52MGlTV%2fYSKQq0JL9%2foMyn8elkafEggBm3FgAcToYwlBVNVpurpPdZAGsn7X%2bsmqmme%2bTwJLidahgRBy%2b6MZvOCxEJdX%2bOPDOJI4ISkeYFEYzHEq64zg2lMRr1fII8b9gCEHZEQKrMucIPvchnHYP3ONyxXBDJrSievrl3Kv9MSX5POhS1NZ4qTRAb98wFKIu1KYM4afbk9cArcQO5C0DZgAACJToDLytLR2P4AE4bNQFjQJEOCFjEbNsWzATf8D8aDVyV7ElqH57llZpQtSpLwy4qAwnonZQAPRHHeg%2by%2fPrpWa2PHFnlvJYumCkuLMLyF1ElbVB1STzjrBG%2bNweLhcdaal9pSoEgIicrfZzERbZRPpLanGEZZej%2bj9PxeTD%2fMW%2bv9Eix1z4q57Q6P9RBn8eSNkPX9lTlmy6cvSM6OwLsrN30SmxXkMbo68z0FkQoUTgJ0XaVOgUR02H6lxwY0G%2fFldJuO5YK7Stsc1xTb%2f8d3ocXlKNz%2fLy1PCmuZEWMcE2Vdzs7Niw56ho6%2bEJHzirexVlONftNAJYhgOm7%2fk951wEo1Iv1WaZs3DOwkVE7nFHKHRwwVfEfbLBMc8zDK%2fjSAS2RrY5G68Y3srPP9ZBfb4z3Q2quos19h6%2fsTYGDy6eF0IO%2fCf3CgJOA%2fiB3gimWF%2bSZIauHlYCoKYXEf6mTAk9kkcZi0h1LLAP3neDJCtYHkoGhohqdiCpf2oFlo%2b6TpvjNF6moOsMWTHJFmIPBrsyC25gZyhVqCnyvxYFR5OwbAfNUmRXxlqQqdKTkXRV15WnGTG%2fpAFt6sRgQFsnL1lIjC6r9Vlde%2fm%2f%2fX9gEJ4gnqwhnPJt3KA3Dv7mNhP70%2bIACkCK660y%2bNENAg%3d%3d). 
Is this the solution you're looking for?

**Comment by Conchylicultor** [comment]
I get `This public.dm.files.1drv.com page can’t be found` when clicking on [your link](https://public.dm.files.1drv.com/y4mSB3ExPYvRfpcX--fqdrdx5hAoKvVJ_xRjlpZlP2CAa2etDRR9N3r4xxuW_SyBSEkYvvPe2RUpr1RTvWoeOuI3ZnDT7hnaJLtxrKm88_CJ6FMK2tu1_9bOEo3T6A_AXc1TBavYfsDmwatqp8FgpK-2MOfTasSF3N5au2Q8B3cCubsA8NnMe7Lt56hW1g-Yd_SgruI-b0jFJgNQAlW6clPeg/NWPU-RESISC45.rar?access_token=EwAQA61DBAAUcSSzoTJJsy%2bXrnQXgAKO5cj4yc8AAVIgJS%2fofAeBCDnlogoBw%2f5JmopE80cn3Ag%2for5qUWNP4xth6vSxL3218uOYVHHqvnA%2fUNj454HpWQDtptU%2br8gC5A5HOHrwJvYOyTrCJoNY7OAmRUXVxASrG0IvxHlFrgV52MGlTV%2fYSKQq0JL9%2foMyn8elkafEggBm3FgAcToYwlBVNVpurpPdZAGsn7X%2bsmqmme%2bTwJLidahgRBy%2b6MZvOCxEJdX%2bOPDOJI4ISkeYFEYzHEq64zg2lMRr1fII8b9gCEHZEQKrMucIPvchnHYP3ONyxXBDJrSievrl3Kv9MSX5POhS1NZ4qTRAb98wFKIu1KYM4afbk9cArcQO5C0DZgAACJToDLytLR2P4AE4bNQFjQJEOCFjEbNsWzATf8D8aDVyV7ElqH57llZpQtSpLwy4qAwnonZQAPRHHeg%2by%2fPrpWa2PHFnlvJYumCkuLMLyF1ElbVB1STzjrBG%2bNweLhcdaal9pSoEgIicrfZzERbZRPpLanGEZZej%2bj9PxeTD%2fMW%2bv9Eix1z4q57Q6P9RBn8eSNkPX9lTlmy6cvSM6OwLsrN30SmxXkMbo68z0FkQoUTgJ0XaVOgUR02H6lxwY0G%2fFldJuO5YK7Stsc1xTb%2f8d3ocXlKNz%2fLy1PCmuZEWMcE2Vdzs7Niw56ho6%2bEJHzirexVlONftNAJYhgOm7%2fk951wEo1Iv1WaZs3DOwkVE7nFHKHRwwVfEfbLBMc8zDK%2fjSAS2RrY5G68Y3srPP9ZBfb4z3Q2quos19h6%2fsTYGDy6eF0IO%2fCf3CgJOA%2fiB3gimWF%2bSZIauHlYCoKYXEf6mTAk9kkcZi0h1LLAP3neDJCtYHkoGhohqdiCpf2oFlo%2b6TpvjNF6moOsMWTHJFmIPBrsyC25gZyhVqCnyvxYFR5OwbAfNUmRXxlqQqdKTkXRV15WnGTG%2fpAFt6sRgQFsnL1lIjC6r9Vlde%2fm%2f%2fX9gEJ4gnqwhnPJt3KA3Dv7mNhP70%2bIACkCK660y%2bNENAg%3d%3d).
Is it expected ?

**Comment by dhirensr** [comment]
@Conchylicultor : are you looking for this link https://1drv.ms/u/s!AmgKYzARBl5ca3HNaHIlzp_IXjs ?

**Comment by Conchylicultor** [comment]
@dhirensr It seems this is the link already pointed in: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/resisc45.py#L72

Does this works if you replace the manual dir by `dl_manager.download_and_exatract()`, and generate the dataset with `--register_checksums` ?
If so, don't hesitate to update [the dataset](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/resisc45.py) and send a PR.

**Comment by dhirensr** [comment]
@Conchylicultor : thank you for your reply.
The links surely works but then it downloads and creates a folder with the same as link name and then it cannot extract because the method automatically detects that filename is not a tar or something.
should i send an intermediate PR for review for better understanding?

**Comment by Conchylicultor** [comment]
Thanks for the update. If the file is correctly downloaded, but the extension isn't detected, you can manually set the archive type with:

```
dl_path = dl_manager.download_and_extract(tfds.download.Resource(
    url=_URL,
    extract_method=tfds.download.ExtractMethod.ZIP,
))
```

With extract_method being one of: https://www.tensorflow.org/datasets/api_docs/python/tfds/download/ExtractMethod

Let us know if this works.

**Comment by dhirensr** [comment]
@Conchylicultor : i tried that but the problem is none of the extract method is working because it's a .RAR file and according to the code https://github.com/tensorflow/datasets/blob/9dd9d66e889d9f9c4b94cb1c51dcaadee882dcac/tensorflow_datasets/core/download/resource.py#L59 none of the methods fit for .Rar

is there any method for extracting .rar files with tfds ?

**Comment by Conchylicultor** [comment]
@dhirensr thanks for the update. This is the reason why it requires manual download. Solving this would require updating TFDS to support rar file extraction.

**Comment by dhirensr** [comment]
@Conchylicultor : so I don't need to update anything in this dataset right?

**Comment by Conchylicultor** [comment]
@dhirensr Yes, the issue is that RAR license is too restrictive, so we cannot include this at Google.

I'm gonna close this as there is no straightforward answer and it only affect a single dataset. We might reconsider this if we encounter other datasets using RAR.
