### ISSUE TITLE
[data request] KITTI dataset

### ISSUE THREAD

**Issue by SuperElectric** [tensorflow/datasets#638]
* Name of dataset: KITTI dataset
* URL of dataset: http://www.cvlibs.net/datasets/kitti/
* License of dataset: CC-BY-NC-SA 3.0
* Short description of dataset and use case(s): Real-world stereo imagery recorded from a car, with pixelwise labels for stereo, flow, sceneflow, depth, and frame-wise labels for odometry, object bounding boxes (bird-eye 2D, first-person 2D, and first-person 3D),  and raw data.

Used for SLAM research, as well as vision research in inferring the above labels.

**Comment by pierrot0** [comment]
Implemented in image/kitti.py

**Comment by lgeiger** [comment]
Thanks for adding KITTI.

@pierrot0 @rsepassi Are there any plans for adding the [KITTI depth estimation dataset](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction) dataset as well?

**Comment by pierrot0** [comment]
Hi Lukas,

At the moment we don't have such plans.
Could you maybe create a new github issue for KITTI depth estimation dataset?
I don't think we will have time soon for that dataset, but at least it's tracked and a contributor might decide to tackle it.

Thanks

**Comment by lgeiger** [comment]
Thanks for the info. I added a new issue: #840
