### ISSUE TITLE
Enable overlapping splits to build cross-validation datasets.

### ISSUE THREAD

**Issue by remydubois** [tensorflow/datasets#664]
**Is your feature request related to a problem? Please describe.**

As of now, one is not allowed to build cross-validation datasets (i.e compose several train/val folds from an initial TRAIN split), because it is impossible to merge (or add) subsplits taken from a given split. 
The core issue is that one can not build a split with a "hole" in it, and building a subsplit by "taking everything except a previously-defined subsplit" is not documented.

**Describe the solution you'd like**

I do not know how deep in the code such feature would take root, but authorizing overlapping subsplits would allow to compose several train/val folds like this:

```
# Build 80/20 train/val folds:
k = 5
# Identify the subsplits
FOLDS = tfds.Split.TRAIN.subsplit(k=k)

# Go through all the possible folds
for i in range(k):
    those_folds = list(FOLDS)
    valid_split = those_folds.pop(i)
    train_split = reduce(lambda split0, split1: split0 + split1, those_folds)

    # build this fold's train
    train = dataset.as_dataset(as_supervised=True,
                               shuffle_files=False,
                               split=train_split)
    # build this fold's valid
    valid = dataset.as_dataset(as_supervised=True,
                               shuffle_files=False,
                               split=valid_split)

    # fit on this fold's and get results
    model.fit(train, validation_data=valid)
```

**Describe alternatives you've considered**

A first alternative would be to 'hard-code' the subsplits in the `_split_generator`method and save already-split datasets: instead of saving a 'train' and a 'test' set in the `_split_generators` method, save `train_subsplit_0`, ..., `train_subsplit_k`, `test`, and then merge the desired subsplits to circumvent the overlapping-splits issue.

Another alternative would be to allow building subsplits with "hole" in it, i.e. building a subsplit in this fashion: "from 0% to 20%, and from 40% to 100% of the hole TRAIN split"

Another alternative would be to allow building subsplits by taking everything except a previously defined subsplit: "this fold's valid is from 20% to 40%, and this fold's train is the hole TRAIN except valid"

**Comment by Conchylicultor** [comment]
@pierrot0 is currently working on improving the API to allow this feature.

**Comment by remydubois** [comment]
Awesome, any idea when this would be released ?

**Comment by pierrot0** [comment]
This is being progressively rolled-out (S3 experiment).
As soon as the dataset you are interested in has a version with S3, you should be able to use it.

My estimation is that by the end of the week we should have almost all image datasets except the ones using beam (https://github.com/tensorflow/datasets/pull/683). Other datasets and documentation will follow in upcoming weeks.

Example of usage:
https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/tfrecords_reader_test.py#L328

**Comment by remydubois** [comment]
Thank you very much for your detailed answered and your work, 
I will definitely keep an eye out on the doc until this is completely rolled out.

**Comment by pierrot0** [comment]
Closing, you can follow rollout of new api on issue #737.
