### ISSUE TITLE
when I used tensorflow 2.0 I download the datasets but it can't work

### ISSUE THREAD

**Issue by mjwise-hyx** [tensorflow/datasets#671]
**Short description**
Description of the bug.

**Environment information**
* Operating System: <os>
* Python version: <version>
* `tensorflow-datasets`/`tfds-nightly` version: <package and version>
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version>

**Reproduction instructions**
![image](https://user-images.githubusercontent.com/42193551/59431512-ad09bf80-8e17-11e9-86f6-c746a3b00d3f.png)

```
<put a code snippet or link to a gist here>
```

**Link to logs**
If applicable, <link to gist with logs, stack trace>

**Expected behavior**
What you expected to happen.

**Additional context**

**Comment by Conchylicultor** [comment]
Could you copy the full stacktrace as text or in a gist ? Also please complete the environment information to help us debug

**Comment by Conchylicultor** [comment]
Closing this as the issue seems inactive. Please reopen the issue with the complete gist and code snippet used if it's not fixed.
