### ISSUE TITLE
Better Sequence display in documentation

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#689]
Currently, the documentation pack the Sequence on a single line:

```
FeaturesDict({
    'bobjects': Sequence({'bbox': TensorInfo(shape=(None, 4), dtype=tf.float32), 'source': TensorInfo(shape=(None,), dtype=tf.int64), 'is_group_of': TensorInfo(shape=(None,), dtype=tf.int8), 'is_inside': TensorInfo(shape=(None,), dtype=tf.int8), 'is_depiction': TensorInfo(shape=(None,), dtype=tf.int8), 'is_truncated': TensorInfo(shape=(None,), dtype=tf.int8), 'label': TensorInfo(shape=(None,), dtype=tf.int64), 'is_occluded': TensorInfo(shape=(None,), dtype=tf.int8)}),
    'image': Image(shape=(None, None, 3), dtype=tf.uint8),
    'image/filename': Text(shape=(), dtype=tf.string, encoder=None),
    'objects': Sequence({'source': TensorInfo(shape=(None,), dtype=tf.int64), 'confidence': TensorInfo(shape=(None,), dtype=tf.int32), 'label': TensorInfo(shape=(None,), dtype=tf.int64)}),
    'objects_trainable': Sequence({'source': TensorInfo(shape=(None,), dtype=tf.int64), 'confidence': TensorInfo(shape=(None,), dtype=tf.int32), 'label': TensorInfo(shape=(None,), dtype=tf.int64)}),
})
```

It would be nice that the sequence gets expanded, for better readability. Additionally, the `Sequence` should display the `FeatureConnector`, instead of the `TensorInfo`:

```
FeaturesDict({
    'bobjects': Sequence({
        'bbox': BBox(shape=(4), dtype=tf.float32),
        'source': ClassLabel(shape=(None,), dtype=tf.int64),
        ...
    }),
    'image': Image(shape=(None, None, 3), dtype=tf.uint8),
    'image/filename': Text(shape=(), dtype=tf.string, encoder=None),
    'objects': Sequence({
        'source': ClassLabel(shape=(), dtype=tf.int64),
        'confidence': Tensor(shape=(None,), dtype=tf.int32), 
        ...
    }),
})
```

The solution may simply be to add a `__repr__` to `Sequence`, and remove the  `_additional_repr_info(self)` which seem never called.

**Comment by us** [comment]
I want to work on this, you can assign me.

**Comment by Conchylicultor** [comment]
Thank you @us

**Comment by Conchylicultor** [comment]
@us Currently, the formatting is done with `_pprint_features_dict` https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/scripts/document_datasets.py#L312

**Comment by us** [comment]
Thank you ! I will check it.

**Comment by us** [comment]
Feature dict completely came on single line like that. Is that what you're talking about?


![Screen Shot 2019-06-18 at 7 59 02 PM](https://user-images.githubusercontent.com/22618852/59703953-b1611e80-9203-11e9-92f7-729eaf3e74ec.png)

**Comment by Conchylicultor** [comment]
If you print(FeaturesDict), yes, however when you generate the doc, the `_pprint_features_dict` that I linked above will apply some special formating.

Maybe it's better to have this special indentation formatting directly inside `FeaturesDict.__repr__`. as it would make user `print()` more user friendly too.

**Comment by Conchylicultor** [comment]
Fixed. Thanks for implementing this
