### ISSUE TITLE
'cityhash' for tfds-nightly fails to build on windows 64 

### ISSUE THREAD

**Issue by vidyabhandary** [tensorflow/datasets#690]
**Short description**
'cityhash' for tfds-nightly fails to build on windows 64 - with the following ERROR
Command line error D8021 : invalid numeric argument '/Wno-unused-value'

**Environment information**
* Operating System: Windows 10 64 bit Home edition with NVidia GPU
* Python version: 3.6.8
* `tensorflow-datasets`/`tfds-nightly` version: tfds_nightly=1.0.2.dev201906170105
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 
tf-nightly-gpu-2.0-preview=tf_nightly_gpu_2.0_preview-2.0.0.dev20190607
AND
tensorflow-gpu==2.0.0-beta1

**Reproduction instructions**
Install tensorflow-gpu or tf-nightly-gpu-2.0-preview on windows 64 machine with GPU enabled for tensorflow 

```
Running setup.py install for cityhash: finished with status 'error'
    ERROR: Complete output from command 'D:\Data\Study\4hml\handson-ml2\env\Scripts\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\Vidya\\AppData\\Local\\Temp\\pip-install-58_3chbe\\cityhash\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Vidya\AppData\Local\Temp\pip-record-j9m6li9e\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Data\Study\4hml\handson-ml2\env\include\site\python3.6\cityhash':
    ERROR: running install
    running build
    running build_ext
    building 'cityhash' extension
    creating build
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\src
    D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Iinclude -ID:\Data\Study\4hml\include -ID:\Data\Study\4hml\include "-ID:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\ATLMFC\include" "-ID:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include" "-ID:\Windows Kits\10\include\10.0.17763.0\ucrt" "-ID:\Windows Kits\10\include\10.0.17763.0\shared" "-ID:\Windows Kits\10\include\10.0.17763.0\um" "-ID:\Windows Kits\10\include\10.0.17763.0\winrt" "-ID:\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpsrc/city.cc /Fobuild\temp.win-amd64-3.6\Release\src/city.obj -O3 -Wno-unused-value -Wno-unused-function
    cl : Command line error D8021 : invalid numeric argument '/Wno-unused-value'
    error: command 'D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

**Comment by us** [comment]
You have encountered such a problem because the new s3 update on the tfds. This bug will be fixed as soon as possible. 
You can continue to use by going old commit on git.

Please try that:
```
git checkout 389eeb60
python setup.py install 
```

**Comment by vidyabhandary** [comment]
Thanks @us. Unfortunately that did not work. I tried the checkout before that too - That too gave me the same error. 

I added the following to my requirements.txt and ran the pip install

#tensorflow-datasets
#tfds-nightly
#git+https://github.com/tensorflow/datasets.git@389eeb6
git+https://github.com/tensorflow/datasets.git@cae2527

**Comment by us** [comment]
If you checkout this commit, you shouldn't got error, because on this commit cityhash package is not using. Please check git logs and checkout 389eeb60b634aa86e5a83dddcede2f08254f007d.
I got same error and I checkout this commit so problem is solved.
```
| commit 389eeb60b634aa86e5a83dddcede2f08254f007d (HEAD)
| Author: Etienne Pot <epot@google.com>
| Date:   Tue Jun 11 14:24:41 2019 -0700
|
|     Update doc
|
|     PiperOrigin-RevId: 252698370```

**Comment by vidyabhandary** [comment]
@us 
It is puzzling why that checkout is working for you. Browsing through the git repo at that checkout - shows 'cityhash' as a required package.

https://github.com/tensorflow/datasets/blob/389eeb60b634aa86e5a83dddcede2f08254f007d/setup.py#L44

I commented out cityhash and did that install. Admittedly it is a hack but I can see the tensorflow datasets in my site-packages.

**Comment by us** [comment]
Because cityhash has just been added and it worked when I returned to the old code that haven't got cityhash package. But yes yours is an alternative tricky solution. I'm glad you solved the problem. This bug will be fixed as soon as possible.

**Comment by pierrot0** [comment]
Thank you for reporting Vdy!

We are looking at alternatives for cityhash to resolve this problem.

Would you mind trying to install the following libraries on your system and tell us if installation was successful?

1) pip install csiphash
2) pip install siphashc
3) pip install siphash

It would be nice if you could try the installation on py2 and py3 if you have both on your system.
To check the installation worked fine, in a python prompt:
```
import struct
import csiphash
res = csiphash.siphash24(b'\0' * 16, b'foo')
struct.unpack('<Q', res)[0]  # Should print 15988776847138518036

import siphashc
siphashc.siphash(b'\0'*16, b'foo')  # Should print 15988776847138518036

import siphash
siphash.SipHash24(b'\0' * 16, b'foo').hash()  # Should print 15988776847138518036
```

Library (3) should work since it's a pure python implementation, but it doesn't hurt to check.
The solution we are looking it would be to swap cityhash library for a combination of two of those libraries: (1) or (2) and (3) as a backup (slower).

Thanks for your help!
Pierre

**Comment by vidyabhandary** [comment]
Hi pierrot0,

I installed all three libraries and checked if the installation was fine using your instructions.
I get the correct hash for all three libraries.  I ran this in python 3. I do not have python 2 on my machine !

Cheers !

**Comment by pierrot0** [comment]
Thank you!
