### ISSUE TITLE
tfds.features.text.SubwordTextEncoder unexpected behavior on 0

### ISSUE THREAD

**Issue by jkamalu** [tensorflow/datasets#702]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 18.04
- **TensorFlow installed from (source or binary)**: source 
- **TensorFlow version (use command below)**: 2.0.0-dev20190601
- **Python version**: 3.6
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**:

```
import tensorflow_datasets as tfds
tokenizer = tfds.features.text.SubwordTextEncoder("wazzaaaaaaappppp")
tokenizer.decode([0])    # passes (expected)
tokenizer.decode([1])    # passes (expected)
try:
    tokenizer.decode([-1])   # breaks (expected)
except ValueError as v:
    print("[-1]: ", str(v).lower())
try:
    tokenizer.decode([0, 1]) # breaks (NOT expected)
except ValueError as v:
    print("[0, 1]: ", str(v).lower())
```

### Describe the problem

self-explanatory -- the tokenizer should either never be able to handle `0` or always handle `0` or throw an error message which accounts for cases where `0` does or does not work. As it stands, the error message is false and the behavior inconsistent.

### Logs
```
~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_datasets/core/features/text/subword_text_encoder.py in decode(***failed resolving arguments***)
    110 
    111     for subword_id in subword_ids:
--> 112       subword = self._id_to_subword(subword_id)
    113       if isinstance(subword, six.binary_type):
    114         # Byte-encoded

~/anaconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_datasets/core/features/text/subword_text_encoder.py in _id_to_subword(self, subword_id)
    176     if subword_id < 0 or subword_id >= (self.vocab_size - 1):
    177       raise ValueError("Received id %d which is invalid. Ids must be within "
--> 178                        "[0, %d)." % (subword_id + 1, self.vocab_size))
    179 
    180     if 0 <= subword_id < len(self._subwords):
```

**Comment by Conchylicultor** [comment]
Sorry for the confusion. I agree that the error message is confusing. Don't hesitate to send a PR to improve the reporting

**Comment by Disciple7** [comment]
Is there any one still handle this? Cause I come up with the same confusion

**Comment by Disciple7** [comment]
Is there any one still handling this? Cause I come up with the same confusion

**Comment by Conchylicultor** [comment]
Note that TFDS subwords encoders should be considered deprecated. Please use tensorflow_text instead which is better supported and tested and don't have some of the bugs from here.
https://www.tensorflow.org/tutorials/tensorflow_text/intro

**Comment by CoaLee** [comment]
I think line number 176~178 of code still need to be corrected, though this part is deprecated.
```
    176     if subword_id < 0 or subword_id >= (self.vocab_size - 1):
    177       raise ValueError("Received id %d which is invalid. Ids must be within "
--> 178                        "[0, %d)." % (subword_id + 1, self.vocab_size))
```
It yields incorrect error message when `subword_id < 0`. For example, if `subword_id` is `-1`, it passes the condition and raises error saying `'Received id 0 ...'`

So I suggest changing `subword_id + 1` of line 178 to `subword_id`.

**Comment by vijayphoenix** [comment]
API deprecated

**Comment by lopeselio** [comment]
use tfds.deprecated.text.SubWordTextEncoder

as the aPI is deprecated
