### ISSUE TITLE
`TokenTextEncoder.decode()` has wrong results when using pre-padding.

### ISSUE THREAD

**Issue by HanGuo97** [tensorflow/datasets#719]
The error is caused by the `pad_decr()` at [this line](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/features/text/text_encoder.py#L281). To reproduce the results:

```python
pad_decr([0, 0, 1, 2, 0, 3, 0, 0])
>>> [-1, -1, 0, 1, -1, 2]
```

Even though the correct outputs should have been `[0, 1, 2]`

**Comment by vijayphoenix** [comment]
TFDS text encoders are deprecated.
Please use tensorflow_text instead which is better supported and tested and doesn't have some of the bugs from here.
https://www.tensorflow.org/tutorials/tensorflow_text/intro
