### ISSUE TITLE
Dataset Versioning

### ISSUE THREAD

**Issue by EmanueleGhelfi** [tensorflow/datasets#721]
**What I need help with / What I was wondering**
How can I version a dataset?
tfds supports the version parameter `version=x.y.z` inside `tfds.core.DatasetInfo` but from the documentation it is not clear how to version a dataset.

I have a custom dataset, with the number of images gradually increasing. I have trained some models on a dataset version V1. After some time some images have been added to the dataset. What I want is to create another version of the dataset, let's say the version V2. 

How can I manage the new version? Should I add custom code inside my dataset class that changes the download URL based on the version?

Is there a way to do it using tfds api?

I think that the versioning part of tfds is not well documented, can you provide some examples on how to version a dataset?

**Comment by ChanchalKumarMaji** [comment]
You can use `BuilderConfig`.

**Comment by EmanueleGhelfi** [comment]
Hi @ChanchalKumarMaji , How can I use BuilderConfig? Do I need to use it when I instantiate my dataset? 
How can I manage versioning inside my dataset?

**Comment by us** [comment]
Hey @EmanueleGhelfi you can check `DiabeticRetinopathyDetectionConfig`. For example on this dataset have different resolution versions and with `BuilderConfig` he set. You can separate versions of dataset by looking at it.

**Comment by EmanueleGhelfi** [comment]
Hi @us , thank you! This is a smart way to manage versions. I think a similar examples could be added to the README or to the API doc.

**Comment by us** [comment]
Yep @EmanueleGhelfi we think so and will add and if you want you can help us to docs. Thanks again :)

**Comment by EmanueleGhelfi** [comment]
Hi @us . I'm following your example. However, The unique config that is loaded in my dataset is the first.

```python
class MyDatasetConfig(tfds.core.BuilderConfig):
    """
    Builder config for a generic dataset
    """

    def __init__(self, url=None, **kwargs):
        """
        Builder config for a generic dataset
        Args:
            url: url from which to download
            **kwargs: kwargs to forward to super
        """
        super(MyDatasetConfig, self).__init__(**kwargs)
        self._url = url

    @property
    def url(self):
        return self._url

```

My dataset uses the builder config in this way:

```python
class MyDataset(tfds.core.GeneratorBasedBuilder):
        BUILDER_CONFIGS = [
                MyDatasetConfig(
                    name="0.2.0",
                    version="0.2.0",
                    description="Dataset at 01-07-2019",
                    url="url1",
                 ),
                MyDatasetConfig(
                    name="0.1.0",
                    version="0.1.0",
                    description="Initial dataset",
                    url="url2",
                 ),
          ]
```

When I load my dataset in this way:

```python
x = tfds.load(
        "my_dataset",
        split=tfds.Split.TRAIN,
        builder_kwargs={"version": "0.1.0"},
    )
```

results in an `AssertionError` since the version loaded in the config is only the version specified in the first BuilderConfig. Do I need to specify the supported versions for each BuilderConfig?

**Comment by ChanchalKumarMaji** [comment]
By default when you use `tfds.load(my_dataset, ...)` it refers to the first BuilderConfig. To get others you have to do `tfds.load(my_dataset/config_name, ...)`

**Comment by EmanueleGhelfi** [comment]
Thank you   @ChanchalKumarMaji . Can you explain the difference between config and version? A config can have multiple versions?

**Comment by ChanchalKumarMaji** [comment]
`config` is used when the structure of different datasets are similar. Instead of rewriting similar codes over and over again we use BuilderConfigs. 
Since, your dataset structures are similar, instead one contains more images than the other, so you can safely use config instead of writing similar codes for different versions.

**Comment by pierrot0** [comment]
Configs are here to define different "flavors" of a same dataset (for example: different picture sizes). But two configs of the same builder should return the same conceptual dataset.

In this case, it would be preferable to create a new Builder (it can inherit from the one you already have, to re-use code). We have for example OpenImagesV4. We might eventually have OpenImagesV5, ...

The documentation for versioning is coming soon (PR to be sent within next day or two).

**Comment by EmanueleGhelfi** [comment]
Hi @pierrot0, in my understanding a new builder means a new dataset. Am I wrong? In this case I need to take care manually of versioning and in the case of multiple version I will end up with multiple datasets. I think that builder configs are an easier way. In my case the dataset is conceptually the same, the only thing that change is the number of images. In my case the version2 contains all the images of version1.

**Comment by pierrot0** [comment]
Documentation available: https://github.com/tensorflow/datasets/blob/master/docs/datasets_versioning.md

You can use inheritance, and should be able to re-use most of the code.
Then I guess the question becomes: how many versions do you plan to have?

If you decide to use different builder configs, it might make it harder to introduce variations of those datasets. For example v1_with_size_z_y, ...

If the only different is the number of images, then maybe it would make sense to introduce more splits. For example: train1, train2, ... And in your paper, specify you are using (train1) or (train1, train2) or whatever other combinations...

**Comment by EmanueleGhelfi** [comment]
I think we can close the issue. Thanks for the help!
