### ISSUE TITLE
Trying to run the code and get an error message

### ISSUE THREAD

**Issue by yupliu** [tensorflow/datasets#733]
**Short description**
Description of the bug.

**Environment information**
* Operating System: <os>
* Python version: <version>
* `tensorflow-datasets`/`tfds-nightly` version: <package and version>
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: <package and version>

**Reproduction instructions**

```
<put a code snippet or link to a gist here>
```
mnist_example, = mnist_train.take(1)
image, label = mnist_example["image"], mnist_example["label"]

plt.imshow(image.numpy()[:, :, 0].astype(np.float32), cmap=plt.get_cmap("gray"))
print("Label: %d" % label.numpy())
**Link to logs**

ValueError                                Traceback (most recent call last)
<ipython-input-11-11d2fd750bf8> in <module>()
----> 1 mnist_example, = mnist_train.take(1)
      2 image, label = mnist_example["image"], mnist_example["label"]
      3 
      4 plt.imshow(image.numpy()[:, :, 0].astype(np.float32), cmap=plt.get_cmap("gray"))
      5 print("Label: %d" % label.numpy())

ValueError: too many values to unpack (expected 1)
**Expected behavior**
What you expected to happen.

**Additional context**

**Comment by cyfra** [comment]
It might be TF related. Which tensorflow version are you using ?

> print(tf.__version__)


You can also verify the code in the colab (that runs 1.14):
https://colab.research.google.com/github/tensorflow/datasets/blob/master/docs/overview.ipynb

**Comment by yupliu** [comment]
Hi -,

Thanks! Actually, I got the error message while I was running the notebook in the colab. 

![2019-07-04_053550_1](https://user-images.githubusercontent.com/29743569/60657136-c3a3a500-9e1e-11e9-9f2e-aa8b61f28028.png)

**Comment by ChanchalKumarMaji** [comment]
@yupliu I just checked but didn't find any errors.

**Comment by yupliu** [comment]
I don't know what happened but I tried several times in the Colab and got the same error message all the time.

**Comment by yupliu** [comment]
I think the error message is caused by this line tf.enable_eager_execution(). Yesterday, when I ran it, I failed and got some wierd error. 

I just tried again and it worked.  As long as tf.enable_eager_execution() is executed sucessfully the error message go away.

**Comment by ChanchalKumarMaji** [comment]
`tf.enable_eager_execution()` must be executed at the start of the program. 
Yes, I saw that if u do not execute `tf.enable_eager_execution()` you get the exact same error. Try restarting runtime and run again.

**Comment by us** [comment]
Hey @yupliu,
Please check this [link](https://www.tensorflow.org/guide/eager) about eager execution. 

If your problem is solved you can close this issue :)

**Comment by yupliu** [comment]
Thanks!
