### ISSUE TITLE
S3 roll-out

### ISSUE THREAD

**Issue by pierrot0** [tensorflow/datasets#737]
This is about rolling out the S3 (new sharding shuffling slicing mechanism).

Currently, the hash function being used is siphash, with csiphash library, which causes tests to crash on kokoro with py3 and tf13. We don't understand why at this point, and consider switching to md5 (slower - but faster than pure python implementation of siphash - but hey, at least it's guaranteed to work everywhere).

**Comment by pierrot0** [comment]
Recep, Chanchal, if you have time, please do not hesitate to make new versions with S3 support for DatasetBuilder classes which don't have that already. It should be doable for all builders, and beam ones once #677 is fixed.

**Comment by Conchylicultor** [comment]
Closing this now S3 has been rolled out. 
https://github.com/tensorflow/datasets/issues/1519 to track cleanup legacy code.
