### ISSUE TITLE
Support for use image_label_folder for GCS buckets

### ISSUE THREAD

**Issue by captain-pool** [tensorflow/datasets#741]
**Is your feature request related to a problem? Please describe.**
TFDS have this wonderful property where a dataset can be stored in a cloud bucket and loaded directly. However, `image_label_folder` cannot be loaded directly from GCS buckets. It says, `manual_dir` is missing certain files.

**Describe the solution you'd like**
manual_dir parameter of Download Config should support cloud buckets. it would be much easier to train from an image_label_folder dataset on cloud TPUs. (Cloud TPUs needs the data to be in a gcs bucket).

**Additional context**
```python3
import tensorflow_datasets as tfds
dataset_name = "name of dataset to load"
ds  =tfds,load("image_label_folder/dataset_name=%s" % dataset_name,
               split="split_name",
               download_and_prepare_kwargs={
                   "download_config": tfds.download.DownloadConfig(
                                                  manual_dir="gs://bucket/path")})
```
something similar to this would be really helpful.

**Comment by vijayphoenix** [comment]
Hi @captain-pool,
Please try out the new [tfds.ImageFolder](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/custom_dataset/image_folder.py) API. It should be available in tfds-nightly soon.

Let us know if you are still facing the problem.

**Comment by Conchylicultor** [comment]
@vijayphoenix tfds.ImageFolder should fix this issue.
