### ISSUE TITLE
[data request] binary-mnist

### ISSUE THREAD

**Issue by pierrot0** [tensorflow/datasets#758]
* Name of dataset: binary-mnist
* URL of dataset: https://github.com/yburda/iwae/blob/master/datasets/BinaryMNIST/README
* License of dataset: MIT
* Short description of dataset and use case(s): Starting with the MNIST dataset, a train-test-valid split was introduced, values were scaled to [0, 1], and pixels were then sampled as Bernoulli random variables from those values to produce this official dataset. The dataset was first used in Salakhutdinov and Murray (2008) and since used in papers such as NADE, DARN, and Variational Autoencoders.

Label information is not included, so the relevant tasks are unsupervised learning and generation.

**Comment by us** [comment]
@Conchylicultor @cyfra I think it can be closed.
