### ISSUE TITLE
two files of same name but different capitalization

### ISSUE THREAD

**Issue by MareoRaft** [tensorflow/datasets#8]
You have a file called `Text.md` and one called `text.md` in the same directory `datasets/docs/api_docs/python/tfds/features/`.

This is causing an issue in filesystems that ignore capitalization in filenames.  (My filesystem overwrote one of the files with the other, and now git shows unstaged changes/modification.)

Could you resolve the conflict between the two files?

**Comment by rsepassi** [comment]
Thanks for reporting. We'll see if we can rename one of them. We develop on Linux (which generally has case-sensitive filesystems) so that's why we didn't spot it before.

**Comment by rsepassi** [comment]
Are you using Windows? Have you otherwise found Windows usage to be working well?

**Comment by rsepassi** [comment]
Great, thank you for clarifying. Confirmed that this is an issue on MacOS
as well.

**Comment by Conchylicultor** [comment]
This should be fixed by: https://github.com/tensorflow/datasets/commit/ba1bec65eb310b86a68234d3d80f1d0d95dbeb69

Please re-open if you still get the issue
