### ISSUE TITLE
Can't download IMDB dataset from Microsoft Windows

### ISSUE THREAD

**Issue by textninja** [tensorflow/datasets#800]
**Short description**
Attempts to download the IMDB dataset from a Windows 7 machine result in "unmatched parenthesis" errors and a failed download.

**Environment information**
* Operating System: Windows 7
* Python version: 3.6.2
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow_datasets-1.0.2
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow-gpu 2.0.0-beta1

**Reproduction instructions**
* First, delete your `%USERPROFILE%/tensorflow_datasets` directory to ensure the download isn't bypassed by cached data
* Next, run the following code (adapted from the official Tensorflow 2.0 text classification tutorial) which attempts to download the IMDB dataset: https://gist.github.com/textninja/835f57b66ada0fe2cdfba18bc1486532
* An error similar to the one shown in the logs below should be triggered

**Link to logs**
https://gist.github.com/textninja/c4af0c75dab2cd00d1f0a0a50994ac9a

**Expected behavior**
I expect the IMDB dataset to be downloaded silently, without error.

**Additional context**
The problem, essentially, is due to incompatibility with Windows path separators and regular expression escape sequences. Some additional background and a proposed solution / patch is provided in this StackOverflow post: https://stackoverflow.com/questions/56421669/how-should-i-deal-with-error-unbalanced-parenthesis-at-position-32/57152491#57152491

**Comment by us** [comment]
Thanks for reporting ! 

I will check it as soon as possible.

**Comment by Conchylicultor** [comment]
I think this was fixed with https://github.com/tensorflow/datasets/commit/4d0e1447a8d1727c3cb6f9de491b3f648e885397#diff-87c0e6b8597b399f0fd68dc0ab44a07d

I've just updated tfds to 1.1.0, try a pip upgrade and it should works.

**Comment by textninja** [comment]
You're absolutely right, my mistake - this issue is only present in my outdated version of tensorflow_datasets, which I've since updated. Thanks for responding so quickly.

**Comment by 20zinnm** [comment]
Can this issue be closed? @textninja
