### ISSUE TITLE
EMNIST/MNIST images are transposed

### ISSUE THREAD

**Issue by 183amir** [tensorflow/datasets#812]
**Short description**
Looks like the images in the emnist dataset are transposed.

**Environment information**
* Operating System: Linux
* Python version: 3.6
* `tensorflow-datasets`/`tfds-nightly` version: tensorflow-datasets 1.0.2
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: tensorflow-gpu 1.14.0

**Reproduction instructions**
Please see images:
![emnist_1](https://user-images.githubusercontent.com/5738695/61873999-86937580-aee7-11e9-8c9f-a182278430b9.png)
![emnist_2](https://user-images.githubusercontent.com/5738695/61874000-86937580-aee7-11e9-82f8-57621b156106.png)

**Expected behavior**
I expect the emnist images to be of correct rotation.

**Additional context**
None.

**Comment by Conchylicultor** [comment]
Our EMNIST processing use the exact same code as for Mnist (inherit from Mnist and reuse `_generate_examples`). https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/mnist.py#L265
Is it possible that the original data is transposed ? Are all digit like this or only a few ? Are the other emnist/configs transposed ?

**Comment by 183amir** [comment]
> Are all digit like this or only a few ?

They are all like this.

> Are the other emnist/configs transposed ?

I did not check.

**Comment by Conchylicultor** [comment]
By searching on the internet, it seems that this is how the data is provided: https://stackoverflow.com/questions/48532761/letters-in-emnist-training-dataset-are-rotated-and-little-vague

We try to provide the data as the original datasets author provided it, and let users apply the post processing they want. So I don't think we want to fix this unless emnist provide a new version.
You could use https://www.tensorflow.org/api_docs/python/tf/image/rot90 with `ds = ds.map` in your input pipeline to convert the "natural" order.

**Comment by 183amir** [comment]
Maybe we can document it to avoid the confusion?

**Comment by Conchylicultor** [comment]
Added a clarification in https://github.com/tensorflow/datasets/commit/76553955ca0d56a50170374c3e28f1a4b9720601
