### ISSUE TITLE
Unit testing does not work on Windows

### ISSUE THREAD

**Issue by 20zinnm** [tensorflow/datasets#817]
**Short description**
Windows does not have a method `os.chown` but the unit tests set the side effect of attributes without checking whether they exist. See: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/testing/dataset_builder_testing.py#L156

This results in an error like:
```
Traceback (most recent call last):
  File "C:\Users\meyer\PycharmProjects\datasets\tensorflow_datasets\testing\dataset_builder_testing.py", line 144, in setUp
    self._mock_out_forbidden_os_functions()
  File "C:\Users\meyer\PycharmProjects\datasets\tensorflow_datasets\testing\dataset_builder_testing.py", line 156, in _mock_out_forbidden_os_functions
    getattr(mock_os, fop).side_effect = err
  File "C:\Users\meyer\Anaconda3\envs\cleantfds\lib\unittest\mock.py", line 582, in __getattr__
    raise AttributeError("Mock object has no attribute %r" % name)
AttributeError: Mock object has no attribute 'chown'
```

**Environment information**
* Operating System: **Windows 10**
* Python version: 3.6.8
* `tensorflow-datasets`/`tfds-nightly` version: n/a (development version)
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: `1.13.1`, `2.0.0-beta1`

**Reproduction instructions**

Try to run any unit tests (incl. MNIST) on Windows.

**Expected behavior**
The function that checks for file system access should do a sanity check to ensure it is not trying to mock non-existent `os` functionality.

I can submit a PR for this in a few minutes.

**Comment by 20zinnm** [comment]
I solved this issue but more keep popping up--seems like unit testing is a mess on Windows and I'm not too familiar with abseil. If somebody else wouldn't mind looking into this, that'd be appreciated.

**Comment by 20zinnm** [comment]
For now, I'm using a Docker container to do unit testing. I'm going to leave this issue open since ideally unit tests should work regardless of platform.

One possible solution would be to only inject the side-effect for functions present in the `os` package on the local machine, since by definition a call to `chown` from Windows will err anyways. It makes sense to me to only permit functions that work cross-platform (hence the use of `tf.io`), so this does not unnecessarily restrict file I/O.

**Comment by us** [comment]
Thanks for reporting! We'll look.

We need to add windows to kokoro. If you know any windows script, you can help us to add  equivalent windows .bat files for these: 
```
./oss_scripts/oss_pip_install.sh
./oss_scripts/oss_tests.sh 
```

**Comment by 20zinnm** [comment]
@us I don't know Windows batch scripts, but could we not just install Cygwin on Kokoro to run the Bash scripts?
