### ISSUE TITLE
CLEVR dataset is missing the questions

### ISSUE THREAD

**Issue by bionicles** [tensorflow/datasets#827]
**Short description**
CLEVR is a Visual Question Answering dataset but the questions are missing, so user needs to jump through a bunch of hoops to download and parse them

**Environment information**
* Operating System: linux
* Python version: 3.6.8
* `tensorflow-datasets`/`tfds-nightly` version: 1.1
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: gpu 2b1

**Reproduction instructions**

```
ds_test, ds_train, ds_validation = tfds.load(name="clevr", split=['test', 'train', 'validation'])
for element in ds_train:
    tf.print(element)
```

**Link to logs**
```
 [[115 114 114]
  [117 116 114]
  [115 114 113]
  ...
  [156 153 147]
  [156 153 147]
  [156 153 148]]],
 'objects': {'3d_coords': [[0.438755214 -2.79463482 0.7]
 [2.59563708 1.5761956 0.35]
 [-2.9369 2.04038 0.35]
 ...
 [2.28646755 2.97107983 0.7]
 [-1.16437554 2.7382021 0.7]
 [2.27009153 0.293746442 0.7]],
             'color': [1 6 0 ... 3 2 2],
             'material': [0 0 1 ... 0 0 0],
             'pixel_coords': [[141 187 9.35730934]
 [383 166 10.7077045]
```

**Expected behavior**
i expected a visual question answering dataset to have questions to answer

**Additional context**

**Comment by bionicles** [comment]
https://cs.stanford.edu/people/jcjohns/clevr/

**Comment by Conchylicultor** [comment]
I confirm only images are present currently. It should probably be easy to add a `'question': tfds.features.Text()` field in: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/clevr.py

**Comment by dhirensr** [comment]
@Conchylicultor : I can work on this issue! but for testing would it download the complete dataset of around 20GB? or how can I test this after implementing?

**Comment by Conchylicultor** [comment]
@dhirensr Thanks for looking into this. For testing, you should generate the completely dataset at least once to ensure it is generated properly. The tests.py however just try the generation on fake data (less than 5 examples). See the doc for more details : https://www.tensorflow.org/datasets/add_dataset#testing_mydataset

**Comment by divij30bajaj** [comment]
Hello! I would like to work on this issue. This will be my first contribution. Kindly guide me on this. Thanks.

**Comment by Conchylicultor** [comment]
Thanks.
The dataset is implemented in https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/clevr.py
Have a look at our guide to understand the code: https://www.tensorflow.org/datasets/add_dataset

**Comment by WilliamHYZhang** [comment]
@divij30bajaj are you still working on this issue?

**Comment by LexusH** [comment]
Hey @divij30bajaj if you are no longer working on this issue I would love to take a look at it

**Comment by vijayphoenix** [comment]
@Conchylicultor please review #1583.
Thank you
