### ISSUE TITLE
STL10

### ISSUE THREAD

**Issue by guillaumelorre28** [tensorflow/datasets#831]
* Name of dataset: STL10
* URL of dataset: https://cs.stanford.edu/~acoates/stl10/
* License of dataset: <license type>
* Short description of dataset and use case(s):
Dataset used for unsupervised or semi-supervised learning on images.
96x96 images with 10 classes (airplane, bird, car, cat, deer, dog, horse, monkey, ship, truck)

500 training images (10 pre-defined folds), 800 test images per class
100000 unlabeled images for unsupervised learning

Folks who would also like to see this dataset in `tensorflow/datasets`, please thumbs-up so the developers can know which requests to prioritize.

And if you'd like to contribute the dataset (thank you!), see our [guide to adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md).

**Comment by dhirensr** [comment]
working on it! will send a PR in a week

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as STL10 is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image_classification/stl10.py and https://www.tensorflow.org/datasets/catalog/stl10 for more info.
Thank you for your contribution
