### ISSUE TITLE
Enhance supervised keys. 

### ISSUE THREAD

**Issue by npuichigo** [tensorflow/datasets#849]
I found that supervised_keys is required to be a tuple of (input_key, target_key) when used, but in common case, we have several inputs and maybe several outputs, where supervised_keys cannot be used. 

In addition, if we leave supervised_keys=False, then use the output dataset with tf.estimator is not natural because estimator requires model_fn to have features and labels as parameters, but labels are None in that case.

So can we enhance supervised keys to hold multiple values, or use something else to split features and labels when loading data?

**Comment by Conchylicultor** [comment]
You do not have to provide label with tf.estimator. Why not directly return the dict ?

```
def input_fn():
  ds = tfds.load(...)
  return ds, None

def model_fn(features):
  input1 = features['input1']
  input2 = features['input2']
  label = features['label']
  ...
```

**Comment by npuichigo** [comment]
It's okay that we simply unpack the returned dict and get the labels we want, but I think it doesn't fit estimator's signature well, in which case it's better to separate the raw dict into a feature and a label dict. 

Although we can construct the model_fn like what you provide,  I think it's dataset's duty to prepare the inputs and outputs set.

**Comment by Conchylicultor** [comment]
This seems reasonable. For which tfds dataset would you need this ? And what would be the input/output keys ?
Currently, the user can always customize any input/output he wants by using `ds.map`:

```
ds = tfds.load(...)
ds = ds.map(lambda ex: ex['input'], ex['output'])
```

**Comment by npuichigo** [comment]
If we have several inputs and outputs, maybe using ds.map would be like this.
```python
ds = ds.map(lambda ex: {'input1': ex['input1'], 'input2': ex['input2'], 'input3': ex['input3'], .....}, {'output1': ex['output1'], 'output2': ex['output2'], ....})
```
In addition, now that tensorflow datasets is responsible for feeding data for users and it already uses DatasetInfo to describe the signature of data pipeline, maybe it's not suitable for users to determine the signature again (namely split the inputs and outputs manually).

Ideally, it's natural to have codes like this:
```python
class MyDataset(tfds.core.GeneratorBasedBuilder):

  def _info(self):
    return tfds.core.DatasetInfo(
        builder=self,
        # This is the description that will appear on the datasets page.
        description=("My dataset."),
        # tfds.features.FeatureConnectors
        features=tfds.features.FeaturesDict({
            "input1": tfds.features.Tensor(...),
            "input2": tfds.features.Tensor(...),
            "input3": tfds.features.Tensor(...),
            "output1": tfds.features.Tensor(...),
            "output2": tfds.features.Tensor(...)
        }),
        supervised_keys=(("input1", "input2", "input3"), ("output1", "output2")),
    )

ds = tfds.load(...)
print(ds)
 <DatasetV1Adapter shapes: ({input1: (), input2: (), input3: ()}, {output1: (), output2: ()})>
```

**Comment by rodrigob** [comment]
I am not sure what is the problem with using `ds.map`.
You example would look like:
```
inputs = [ "input1", "input2"]
ouputs = ["output1", "output2"]
ds = ds.map(lambda ex: ({i: ex[i] for in inputs}, {o: ex[o] for o in outputs}))
```
I understand `supervised_keys` is there to make the easy cases easy, and the rest can be handled with `ds.map` over the features dictionary. Not sure it serves well to overload the `supervised_keys` use cases.

In my opinions APIs should "make the easy things easy, and the hard things possible".

**Comment by Conchylicultor** [comment]
I'll be in favour of waiting having a concrete usage within tfds, before adding this into core. The current workaround seems good enough for now even if we may want to improve this in the future.

**Comment by Conchylicultor** [comment]
Closing this for now. We might revisit this if we have a usage in tfds. In the meantime, either `ds.map` or returning `dict` should works fine.
