### ISSUE TITLE
Chexpert not in dataset list

### ISSUE THREAD

**Issue by andrewk1** [tensorflow/datasets#87]
**Short description**
The DatasetBuilder for CheXpert was recently merged into master, but it currently does not appear in the [datasets list](https://github.com/tensorflow/datasets/blob/master/docs/datasets.md). I was just wondering if this should have been generated automatically. Thanks!

**Environment information**
* Operating System: Not applicable
* Python version: Not applicable
* `tensorflow-datasets`/`tfds-nightly` version: Not applicable
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: Not applicable

**Reproduction instructions**
Open the [datasets list](https://github.com/tensorflow/datasets/blob/master/docs/datasets.md), look for `Chexpert`.

**Expected behavior**
See Chexpert under `image` sublist.

**Comment by cyfra** [comment]
Hey @andrewk1 ,

The dataset list is not generated automatically - we usually update it every couple days with a script.

**Comment by rsepassi** [comment]
And see the note on #100.
