### ISSUE TITLE
Broken link in Readme.md

### ISSUE THREAD

**Issue by keshan** [tensorflow/datasets#883]
**Short description**
Link to List of datasets gives a 404 because the file https://github.com/tensorflow/datasets/tree/master/docs/datasets.md doesn't exist.

**Reproduction instructions**
Go to datasets main repo click on the [List of datasets](https://github.com/tensorflow/datasets/tree/master/docs/datasets.md) link in the readme

**Comment by Conchylicultor** [comment]
The list is now at https://github.com/tensorflow/datasets/tree/master/docs/catalog.
Thanks for reporting. Will be fixed soon

**Comment by efischer19** [comment]
#888 fixed docs/README.md, but It's also broken on the main README

https://github.com/tensorflow/datasets/blame/master/README.md#L8

**Comment by fvisin** [comment]
https://github.com/tensorflow/datasets/tree/master/docs/catalog is broken as well....

**Comment by rodrigob** [comment]
In the meantime you can consult the list here:
https://www.tensorflow.org/datasets/catalog/overview

and/or via `tfds.list_builders()`.

**Comment by Conchylicultor** [comment]
The links should be fixed. Closing this.
