### ISSUE TITLE
TFDS fails on windows when writing tfrecords files.

### ISSUE THREAD

**Issue by RameezI** [tensorflow/datasets#896]
**Short description**
Hello, I have tried to load food101 dataset and it fails when writing the tfrecord files on Windows platform. I also tried writing my own dataset class, derived from GeneratorBasedBuilder,  and it fails too with the same error. However, If I generate a subset of examples, a few thousand only, it works as expected. The dataset builds fine on Linux though.

I did some digging and I think something is wrong with the shuffle method. I suspect that the packing/unpacking of bytes in the method is not platform-independent which is causing this issue. Any help or pointer in this regard will be highly appreciated.

**Environment information**
* Operating System: Windows10, 64-bit
* Python version: 3.6.7, MSC v.1900 64 bit (AMD64)
* `tfds-nightly` version: 1.1.0.dev201908100105
* `tensorflow-gpu` version: 2.0.0b1

**Reproduction instructions**

```
import tensorflow_datasets.public_api as tfds
tfds.load(name='food101:1.*.*', split=tfds.Split.TRAIN)
```

**Log/Stack trace**
<https://gist.github.com/RameezI/88ab3b34a24f179150bce60a26c7e0c2>

**Comment by pierrot0** [comment]
Thank you for the detailed report Rameez!
Could you please try with changes in https://github.com/tensorflow/datasets/pull/901/files?

**Comment by RameezI** [comment]
@pierrot0  Yes, this resolved the issue. I could successfully build the dataset after applying your changes. Thanks a lot.
