### ISSUE TITLE
[data request] Amazon product data

### ISSUE THREAD

**Issue by cyfra** [tensorflow/datasets#9]
* Name of dataset: Amazon product data
* URL of dataset: http://jmcauley.ucsd.edu/data/amazon/
* Short description of dataset and use case(s): Dataset contains product reviews and metadata from Amazon.

Folks who would also like to see this dataset in `tensorflow/datasets`, please +1/thumbs-up so the developers can know which requests to prioritize.

**Comment by rsepassi** [comment]
I think we should instead use https://s3.amazonaws.com/amazon-reviews-pds/readme.html
It doesn't require contacting the data provider.

**Comment by kaustumbh7** [comment]
@rsepassi I would like to work on this. This dataset would fall under the category of `datasets/tensorflow_datasets/structured/`, right?

**Comment by ChanchalKumarMaji** [comment]
@rsepassi @cyfra @Conchylicultor I have created a pull request (#265). Please Check.

**Comment by ChanchalKumarMaji** [comment]
The dataset contains 2 parts as described [here](https://s3.amazonaws.com/amazon-reviews-pds/tsv/index.txt). 

- The first part contains different products reviews from US marketplace only. BuilderConfig for different product items.
   -- US REVIEWS DATASET #265 

- The second part contains different product reviews from different marketplaces. BuilderConfig for different marketplaces.
   -- MULTILINGUAL REVIEWS DATASET #270 

@rsepassi @cyfra @Conchylicultor , Please Check.
