### ISSUE TITLE
Preparing dataset with S3 support creates large number of open tmp files, crashes

### ISSUE THREAD

**Issue by jackd** [tensorflow/datasets#907]
**Short description**
After changing a previously-working externally developed `GeneratorBasedBuilder` to support S3 by adding a key to each generated example, `download_and_prepare` creates a large number of open temporary files part-way through the process (> 900), exceeding the OS limit and raising an error.

**Environment information**
* Operating System: ubuntu 16.04
* Python version: 3.6.9
* `tensorflow-datasets`/`tfds-nightly` version: 1.1.0 (also in nightly tfds-nightly-1.1.0.dev201908120105)
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version:
tensorflow-gpu 1.14.0

**Reproduction instructions**
Builder is [here](https://github.com/jackd/shape-tfds/blob/master/shape_tfds/shape/modelnet/pointnet2.py#L112). Note the number of files does not increase per iteration, but suddently jumps (from 0 to ~980) after ~5000 examples have been processed. Open files at time of crash are all `.tmp` files in `incomplete` subdirectories, e.g. `DATA_DIR/0.0.1.incomplete995TMB/bucket_4f7c9d92-dc3e-4199-a4de-5d67cad36326_957.tmp`
```bash
git clone https://github.com/jackd/shape-tfds.git
pip install -e shape-tfds
cd shape-tfds/example
python pointnet.py
```

**Comment by pierrot0** [comment]
Thanks for reporting.
Yes, during the preparation of a dataset, the number of open files can grow up to 1K.
However, 1K is usually fine...

Jack, what does `cat /proc/sys/fs/file-max` returns on your machine?
Or do you store your datasets on some specific file system?

Thanks,
Pierre

**Comment by jackd** [comment]
Apologies, I forgot about this PR and changed the github repo to use the old interface, so the bug wasn't exhibited. I've just re-run it with latest nightly build and it all seems fine now... so... really not sure what went on.

In answer to your questions though: `cat /proc/sys/fs/file-max` returns 1608328 which indeed sounds sufficiently large. File system is regular hard drive.
