### ISSUE TITLE
Add a tfds.features.LabeledImage() feature connector

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/datasets#910]
For some use cases, it could be good to have a `LabelImage` or `LabeledImage` (name to define) which combines `ClassLabel` with `Image`. This could be used for per-instance pixel-masks.

API ideally should combine the two class kwargs and methods.
```python
features = {
    'mask': tfds.features.LabelImage(
        names=['background', 'people', 'road'], shape=(256, 256, 1))
}

info.features['mask'].num_classes  # 3
info.features['mask'].int2str(1)  # "people"
info.features['mask'].str2int('people')  # 1
info.features['mask'].encode_example('/path/to/img.png')

info.features['mask'].shape # (256, 256, 1)
info.features['mask'].dtype # tf.int64
```

* shape: (h,, w, 1)
* dtype: np.uint16

`Image(shape=(h,, w, 1), dtype=np.uint16)`

During `_generate_examples`:
```python
yield {
   'mask': '/path/to/image.png',  # Or np.array
}
```

Image could be stored as 1 channel int16 png, and converted to tf.int64 at decode time.
Implementation wise, not sure yet what would be the best option to reuse both Image and ClassLabel code.

**Comment by rodrigob** [comment]
> This could be used for per-instance pixel-masks.
Note that it is important to distinguish between semantic labelling (e.g. Pascal VOC12), instance segmentation (e.g. COC 2017), and panoptic annotations case (e.g. Cityscapes).

One possible approach could be to have two channels int16 png.
One channel with the classes, another with the instance id (and just use by convention that instance id 0 is used for classes that are not supposed to have multiple instances).

**Comment by Conchylicultor** [comment]
@rodrigob In case of instance segmentation, maybe it would make more sense to keep two separate image rather than trying to merge two semantic information in a single tensor (the user can still concatenate the two values).

```
features={
    'mask_label': tfds.features.LabelImage(names=['dog', 'cat']),
    'instance_id_mask': tfds.features.Image(dtype=tf.int16),
}
```

**Comment by rodrigob** [comment]
Agreed. Then LabeImage focuses solely on the semantic labelling part of things, which is better.

**Comment by rodrigob** [comment]
Toying with this feature, I noticed that I am unsure what is the recommended strategy to handle "empty features" for the test set.
I guess for class labels, the labels list is left empty. Unclear for `LabelImage` what is recommended way to express "no label ground truth available for this image".

**Comment by Conchylicultor** [comment]
@rodrigob Sorry for the late answer, but this is a very good question. As first step, an easy solution would be to have an image filled with `-1`. This is sub-obtimal for decoding but shouldn't take more space due to png encoding. For decoding, users can still pass `tfds.decoder.SkipDecoding`
