### ISSUE TITLE
[data request] recommendation datasets like Movielens

### ISSUE THREAD

**Issue by marcromeyn** [tensorflow/datasets#931]
I think it would be valuable if some of the most  popular recommendation datasets would be included, like:

- Movielens 1M & 20M
- Criteo ads dataset
- Spotify 1M playlist dataset
...

If there’s more interest in this, I am happy to help implement it.

**Comment by ChanchalKumarMaji** [comment]
Can u please add the dataset details, for eg: description, citation, dataset_url, etc...

**Comment by marcromeyn** [comment]
**MovieLens Dataset**
MovieLens 20M movie ratings. Stable benchmark dataset. 20 million ratings and 465,000 tag applications applied to 27,000 movies by 138,000 users. Includes tag genome data with 12 million relevance scores across 1,100 tags. There are also smaller MovieLens datasets available with 1M & 100K reviews.

[Movielens 1M & 20M](https://grouplens.org/datasets/movielens/) [F. Maxwell Harper and Joseph A. Konstan. 2015. The MovieLens Datasets: History and Context. ACM Transactions on Interactive Intelligent Systems (TiiS) 5, 4, Article 19 (December 2015), 19 pages. DOI=http://dx.doi.org/10.1145/2827872]

**Criteo ads dataset (1TB)**
Criteo is pleased to announce the release of a new dataset which is an extended version of our Kaggle click prediction  dataset. With over 4 billion lines and over 1TB in size, this is the largest public machine learning dataset ever released.

As large-scale problems become more prevalent, we believe it is important to make such a dataset available to the academic community and we hope this will serve as a useful benchmark for distributed learning algorithms. Dataset can be found [here](https://labs.criteo.com/2013/12/download-terabyte-click-logs/).

**Spotify 1M playlist dataset**
As part of this challenge, Spotify has released the Million Playlist Dataset. It comprises a set of 1,000,000 playlists that have been created by Spotify users, and includes playlist titles, track listings and other metadata. Dataset can be found [here](https://labs.spotify.com/2018/05/30/introducing-the-million-playlist-dataset-and-recsys-challenge-2018/).

**Comment by us** [comment]
Hey @marcromeyn,
Thanks for recommendations! These datasets look good. If you want to implement these, it would be great. 
You can start with [add dataset guide](https://www.tensorflow.org/datasets/add_dataset).

**Comment by marcromeyn** [comment]
Sweet, let me do a first pass next week.

**Comment by 20zinnm** [comment]
It seems like the terms for the Spotify challenge prohibit sharing the Million Playlists dataset, and the link provided does not directly allow you to download the data (you need to sign in to the competition, which is already over).

**Comment by us** [comment]
You can skip the downloading and use the `manual_dir`. Check for [details](https://www.tensorflow.org/datasets/api_docs/python/tfds/download/DownloadManager).

**Comment by TonyWZ** [comment]
Hi, I am working on adding MovieLens to tfds. I plan to first add MovieLens 25M and MovieLens latest small (100k) first.

**Comment by adiagarwalgoogle** [comment]
This issue is being closed as Movie lens is now part of TensorFlow datasets package.
Please refer to https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/structured/movielens.py and https://www.tensorflow.org/datasets/catalog/movie_lens for more info.
Thank you for your contribution
