### ISSUE TITLE
Dataset documentation should clearly mark which ones require manual download

### ISSUE THREAD

**Issue by cyfra** [tensorflow/datasets#936]
Some of the datasets require manual downloading of files. This should be clearly marked in the dataset documentation.

Preferably it should be detected 'automatically' - by seeing which datasets depend on manual_dir.

**Comment by ShambhaviCodes** [comment]
> Some of the datasets require manual downloading of files. This should be clearly marked in the dataset documentation.
> 
> Preferably it should be detected 'automatically' - by seeing which datasets depend on manual_dir.

I want to work on this issue. Can you please guide how to go ahead with it?

**Comment by Conchylicultor** [comment]
@ShambhaviCodes Thanks for looking into this.

manual dir is accessed through: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/download/download_manager.py#L372
After download_and_prepare, the dataset builder should looks if this field has been called, indicating that the dataset is using manual data: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/dataset_builder.py#L285
Then this information should be saved inside dataset_info (is some new field `self.info.use_manual_data`), so the DatasetInfo class should be updated: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/core/dataset_info.py
Note that you also want to update the associated proto: https://github.com/tensorflow/datasets/tree/master/tensorflow_datasets/core/proto
Finally, the dataset template should be updated to use this new `builder.info.use_manual_data` field: https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/scripts/templates/dataset.mako.md

Let me know if you encounter any issues.

**Comment by ShambhaviCodes** [comment]
I have downloaded/cloned the .zip file.
Extracted it and trying to run it on a virtual environment.
I am facing errors in doing so. I have checked the requirements etc. Can you please guide for the same, if I am facing any version difference or is it something else?
![Issue](https://user-images.githubusercontent.com/42893001/66043536-07e93300-e53d-11e9-93f3-146d2ff3930e.JPG)

**Comment by ShambhaviCodes** [comment]
I was trying to re-create this issue. I have successfully managed to clone, extract and run the code to reproduce the (mnist) dataset. Can you suggest a dataset that requires manual downloading of files?

**Comment by Conchylicultor** [comment]
You can find which datasets are using manual_dir by searching on the code: https://github.com/tensorflow/datasets/search?p=2&q=dl_manager.manual_dir&unscoped_q=dl_manager.manual_dir

For instance: `abstract_reasoning`, `chexpert`, `xsum`,...

**Comment by ShambhaviCodes** [comment]
Hello!
This is my first PR and first contribution to OpenSource. 
I am much excited but scared at the same time.

Can you please approve if I am going correct or not.

def download_and_prepare(self, download_dir=None, download_config=None):
 
   download_and_prepare.has_been_called = True
     pass
  download_and_prepare.has_been_called = False
   
  
  download_and_prepare()
  if not download_and_prepare.has_been_called:
      print('Requires Manual Download')

**Comment by cyfra** [comment]
Fixed in #1227
