### ISSUE TITLE
Do not set experimental_deterministic

### ISSUE THREAD

**Issue by pierrot0** [tensorflow/datasets#951]
[from Marvin]
The shuffle_files arguments on as_dataset also sets options for the tf.data.Dataset. Options cannot be overwritten later. If I want to have a non-deterministic dataset I have to allow shuffling files.

I think setting tf.data.Options should be left the the user and not be done by TFDS.

Also note that I would always shuffle files but sometimes choose to set a random seed. This is currently not possible.

**Comment by Conchylicultor** [comment]
`experimental_deterministic` can now be customized through the `tfds.ReadConfig()` argument, so closing this.
