### ISSUE TITLE
Can't download celeba

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/datasets#965]
**What I need help with / What I was wondering**
Your question, or a clear description of what you're looking for help with.

When I download celeb with tfds in China I get the following error. 

> Dl Completed...: 0 url [00:00, ? url/s]
> 
> Dl Size...: 0 MiB [00:00, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:00, ? file/s][A[A
> Dl Completed...:   0%|          | 0/1 [00:00<?, ? url/s]
> 
> Dl Size...: 0 MiB [00:00, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:00, ? file/s][A[A
> Dl Completed...:   0%|          | 0/2 [00:00<?, ? url/s]
> 
> Dl Size...: 0 MiB [00:00, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:00, ? file/s][A[A
> Dl Completed...:   0%|          | 0/3 [00:00<?, ? url/s]
> 
> Dl Size...: 0 MiB [00:00, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:00, ? file/s][A[A
> Dl Completed...:   0%|          | 0/4 [00:00<?, ? url/s]
> 
> Dl Size...: 0 MiB [00:00, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:00, ? file/s][A[A/home/xieyi/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /home/xieyi/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /home/xieyi/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /home/xieyi/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /home/xieyi/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /home/xieyi/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /home/xieyi/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> /home/xieyi/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:851: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> 
> Dl Completed...:   0%|          | 0/4 [00:01<?, ? url/s]
> 
> Dl Size...: 0 MiB [00:01, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:01, ? file/s][A[A
> Dl Completed...:  25%|██▌       | 1/4 [00:01<00:03,  1.05s/ url]
> Dl Completed...:  25%|██▌       | 1/4 [00:01<00:03,  1.05s/ url]
> 
> Dl Size...: 0 MiB [00:01, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:01, ? file/s][A[A
> Dl Completed...:  25%|██▌       | 1/4 [00:01<00:03,  1.05s/ url]
> 
> Dl Size...: 0 MiB [00:01, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:01, ? file/s][A[A
> Dl Completed...:  25%|██▌       | 1/4 [00:01<00:03,  1.05s/ url]
> 
> Dl Size...: 0 MiB [00:01, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:01, ? file/s][A[A
> Dl Completed...:  50%|█████     | 2/4 [00:01<00:02,  1.05s/ url]
> 
> Dl Size...: 0 MiB [00:01, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:01, ? file/s][A[A
> Dl Completed...:  75%|███████▌  | 3/4 [00:01<00:01,  1.05s/ url]
> 
> Dl Size...: 0 MiB [00:01, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:01, ? file/s][A[A
> Dl Completed...:  75%|███████▌  | 3/4 [00:01<00:01,  1.05s/ url]
> 
> Dl Size...: 0 MiB [00:01, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:01, ? file/s][A[A
> Dl Completed...: 100%|██████████| 4/4 [00:01<00:00,  1.28 url/s]
> Dl Completed...: 100%|██████████| 4/4 [00:01<00:00,  1.28 url/s]
> 
> Dl Size...: 0 MiB [00:01, ? MiB/s][A
> 
> 
> Extraction completed...: 0 file [00:01, ? file/s][A[A
> Extraction completed...: 0 file [00:01, ? file/s]
> 
> Dl Size...: 0 MiB [00:01, ? MiB/s]
> 
> Dl Completed...: 100%|██████████| 4/4 [00:01<00:00,  2.60 url/s]
> Traceback (most recent call last):
>   File "create_celeba_datasets.py", line 18, in <module>
>     main();
>   File "create_celeba_datasets.py", line 10, in main
>     celeba_builder.download_and_prepare();
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
>     return fn(*args, **kwargs)
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_builder.py", line 287, in download_and_prepare
>     download_config=download_config)
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_builder.py", line 937, in _download_and_prepare
>     max_examples_per_split=download_config.max_examples_per_split,
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_builder.py", line 793, in _download_and_prepare
>     for split_generator in self._split_generators(dl_manager):
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/image/celeba.py", line 132, in _split_generators
>     "landmarks_celeba": LANDMARKS_DATA,
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py", line 359, in download_and_extract
>     return _map_promise(self._download_extract, url_or_urls)
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py", line 395, in _map_promise
>     res = utils.map_nested(_wait_on_promise, all_promises)
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 129, in map_nested
>     for k, v in data_struct.items()
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 129, in <dictcomp>
>     for k, v in data_struct.items()
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/utils/py_utils.py", line 143, in map_nested
>     return function(data_struct)
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py", line 379, in _wait_on_promise
>     return p.get()
>   File "/home/xieyi/.local/lib/python3.6/site-packages/promise/promise.py", line 510, in get
>     return self._target_settled_value(_raise=True)
>   File "/home/xieyi/.local/lib/python3.6/site-packages/promise/promise.py", line 514, in _target_settled_value
>     return self._target()._settled_value(_raise)
>   File "/home/xieyi/.local/lib/python3.6/site-packages/promise/promise.py", line 224, in _settled_value
>     reraise(type(raise_val), raise_val, self._traceback)
>   File "/home/xieyi/.local/lib/python3.6/site-packages/six.py", line 693, in reraise
>     raise value
>   File "/home/xieyi/.local/lib/python3.6/site-packages/promise/promise.py", line 85, in try_catch
>     return (handler(*args, **kwargs), None)
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py", line 246, in callback
>     resource, download_dir_path, checksum, dl_size)
>   File "/home/xieyi/.local/lib/python3.6/site-packages/tensorflow_datasets/core/download/download_manager.py", line 207, in _handle_download_result
>     raise NonMatchingChecksumError(resource.url, tmp_path)
> tensorflow_datasets.core.download.download_manager.NonMatchingChecksumError: Artifact https://drive.google.com/uc?export=download&id=0B7EVK8r0v71pZjFTYXZWM3FlRnM, downloaded to /home/xieyi/tensorflow_datasets/downloads/ucexport_download_id_0B7EVK8r0v71pZjFTYXZWM3FlDDaXUAQO8EGH_a7VqGNLRtW52mva1LzDrb-V723OQN8.tmp.3d1c735fd8a9427b8cba7107a1e811a4/uc, has wrong checksum.

I dont know wether it is an internal error of tfds or a problem or a network problem.

**What I've tried so far**
A description of what you've tried so far to solve your problem.

I tried the following code on different machines in China.
```python
  celeba_builder = tfds.builder("celeb_a");
  celeba_builder.download_and_prepare();
```
the problem occurs. I tried downloading mnist with tfds and succeeded. It seems an exclusive problem of celeba.

**It would be nice if...**
Could we have done anything to make things better (documentation, etc.)?

sorry I dont know how.

**Environment information**
(if applicable)
* Operating System: ubuntu 18.04
* Python version: 3.6.8
* `tensorflow-datasets`/`tfds-nightly` version: 1.2.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.0.0-dev20190731

**Comment by Qoyyuum** [comment]
Have you tried with a VPN?

**Comment by breadbread1984** [comment]
yeah, HK's vps

**Comment by Qoyyuum** [comment]
> 
> 
> yeah, HK's vps

Could you try a VPS outside of China?

**Comment by breadbread1984** [comment]
OK if that is the only solution.

**Comment by faajabbari** [comment]
I have exactly the same problem. Have you found any solution?

**Comment by breadbread1984** [comment]
no solution yet

**Comment by Conchylicultor** [comment]
For wrong checksums issues: See: https://github.com/tensorflow/datasets/issues/1482

**Comment by elfelround** [comment]
@Conchylicultor ?? the checksum doesnt add up cause the file simply didnt download so sums to 0

**Comment by elfelround** [comment]
tried setting FORCE_REDOWNLOAD and register_checksums=True with no success

**Comment by Eshan-Agarwal** [comment]
@elfelround  Can you try it with `tfds-nightly` or cloning tfds repo ?

**Comment by elfelround** [comment]
so i basically went onto tensorflow_datasets and deleted everything, then i run the code which errored again, went to the created folders, opened a .cc file that was created and found this

Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.
© 2020 Google - Help - Privacy & Terms

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  can we add this dataset to `gs://tfds-data/datasets` .

**Comment by Conchylicultor** [comment]
@Eshan-Agarwal we would love to add celebA to our public GCS, but we need to check first with the authors and internally if this would be ok.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor So should I contact them? As I also solve this same error on [stackoverflow](https://stackoverflow.com/questions/60992196/notmachingchecksumerror-in-tensorflow-datasets/60999603#60999603) and when I was trying I also face same error as mentioned by @elfelround  but after some time later it works fine. But it not works now, [colab](https://colab.research.google.com/drive/1cZhmt5CcJdWqfKjYLzQbs9hEibUrq9BE). So I think this is good to include it on tfds GCS.

**Comment by Conchylicultor** [comment]
@Eshan-Agarwal, before contacting them, I need to make sure is is ok internally.

**Comment by javigd17** [comment]
Same problem here.

Any update?

Thanks!

**Comment by elfelround** [comment]
please yes, upload it to an external cloud, ive tried many times, i check in a while every so many days and no luck, i even change my ip etc... the problem is celeba is 2-3 GB so i understand that the cdn collapses

**Comment by elfelround** [comment]
I advise uploading this dataset to kaggle.com
