### ISSUE TITLE
PCam dataset

### ISSUE THREAD

**Issue by shenjikai** [tensorflow/datasets#979]
Name of dataset: PatchCamelyon (PCam)
URL of dataset: https://github.com/basveeling/pcam
License of dataset: The data is provided under the CC0 License, following the license of Camelyon16. The rest of this repository is under the MIT License.
Short description of dataset and use case(s): The PatchCamelyon benchmark is a new and challenging image classification dataset. It consists of 327.680 color images (96 x 96px) extracted from histopathologic scans of lymph node sections. Each image is annoted with a binary label indicating presence of metastatic tissue. PCam provides a new benchmark for machine learning models: bigger than CIFAR10, smaller than imagenet, trainable on a single GPU.
I want to use this dataset to build a CNN and deal with the pathological recognition from these images.

**Comment by ChanchalKumarMaji** [comment]
This dataset is already present - https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image/patch_camelyon.py. Please close this issue.
