### ISSUE TITLE
NumPy usage variables in README not consistent

### ISSUE THREAD

**Issue by EduardoDixo** [tensorflow/datasets#99]
**Short description**
Readme.md line 136 creates variable numpy_data, line 137 uses undefined variable numpy_dataset

**Expected behavior**
line 137 should read:
numpy_images, numpy_labels = numpy_data["image"], numpy_data["label"]

**Comment by Conchylicultor** [comment]
Thanks for noticing. Sending a fix

**Comment by Conchylicultor** [comment]
Closed with https://github.com/tensorflow/datasets/pull/101
